from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[2]
CF=ROOT/'cloudflare-worker'

def replace_exact(path,old,new,count=1):
    text=path.read_text(encoding='utf-8')
    got=text.count(old)
    if got!=count:
        raise SystemExit(f'{path}: expected {count} match(es), got {got}: {old[:180]}')
    path.write_text(text.replace(old,new,count),encoding='utf-8')

def replace_regex(path,pattern,new,count=1):
    text=path.read_text(encoding='utf-8')
    out,n=re.subn(pattern,new,text,count=count,flags=re.S)
    if n!=count:
        raise SystemExit(f'{path}: expected {count} regex match(es), got {n}: {pattern[:180]}')
    path.write_text(out,encoding='utf-8')

# 1) New entries must never be created from REST fallback/stale microstructure.
strategy=CF/'bybit-symbol-strategy.js'
old="function profileGate(s={},p={}){if(!p?.enabled)return {ok:false,reason:'SYMBOL_PROFILE_DISABLED'};if(s.regime==='HIGH_VOL_SHOCK'&&!p.allowHighVolShockNewRisk)return {ok:false,reason:'PROFILE_HIGH_VOL_SHOCK_NO_NEW_RISK'};const spread=num(s.book?.spreadBps);if(spread>num(p.maxSpreadBps||8))return {ok:false,reason:'PROFILE_SPREAD_TOO_WIDE',spreadBps:spread,maxSpreadBps:p.maxSpreadBps};const turnover=num(s.turnover24h);if(turnover>0&&turnover<num(p.minTurnoverUsd||0))return {ok:false,reason:'PROFILE_LIQUIDITY_TOO_LOW',turnover24h:turnover,minTurnoverUsd:p.minTurnoverUsd};if(Array.isArray(p.preferredRegimes)&&p.preferredRegimes.length&&!p.preferredRegimes.includes(String(s.regime)))return {ok:false,reason:'PROFILE_REGIME_NOT_PREFERRED'};return {ok:true};}"
new="function profileGate(s={},p={}){if(!p?.enabled)return {ok:false,reason:'SYMBOL_PROFILE_DISABLED'};if(s.regime==='HIGH_VOL_SHOCK'&&!p.allowHighVolShockNewRisk)return {ok:false,reason:'PROFILE_HIGH_VOL_SHOCK_NO_NEW_RISK'};const spread=num(s.book?.spreadBps),maxSpread=num(p.maxSpreadBps||8);if(spread>maxSpread)return {ok:false,reason:'PROFILE_SPREAD_TOO_WIDE',spreadBps:spread,maxSpreadBps:maxSpread};const turnover=num(s.turnover24h),baseMin=Math.max(0,num(p.minTurnoverUsd||0)),q=s.quality||{},liveWs=String(s.microstructureSource)==='VPS_BYBIT_WS'&&q.freshBook===true&&q.freshTrades===true&&q.spreadOk!==false,tightSpread=liveWs&&spread<=maxSpread*.50,liquidityMult=liveWs?(tightSpread?.40:.65):1,effectiveMin=baseMin*liquidityMult;if(turnover>0&&turnover<effectiveMin)return {ok:false,reason:'PROFILE_LIQUIDITY_TOO_LOW',turnover24h:turnover,minTurnoverUsd:baseMin,effectiveMinTurnoverUsd:effectiveMin,liquidityMult,liveWs,tightSpread};if(Array.isArray(p.preferredRegimes)&&p.preferredRegimes.length&&!p.preferredRegimes.includes(String(s.regime)))return {ok:false,reason:'PROFILE_REGIME_NOT_PREFERRED'};return {ok:true,effectiveMinTurnoverUsd:effectiveMin,liquidityMult,liveWs,tightSpread};}"
replace_exact(strategy,old,new)

old="qualityMin=.23*Math.max(.85,num(p.qualityThresholdMult)||1),flowMult=Math.max(.8,num(p.flowThresholdMult)||1),bookTol=Math.max(.8,num(p.bookToleranceMult)||1),threshold=(p.style==='MOMENTUM' ? .060:p.style==='BURST' ? .058:p.style==='TREND' ? .064:p.style==='RANGE' ? .052:.060)*flowMult,votes=[flow3>.045*flowMult,flow5>.055*flowMult,flow15>.045*flowMult,pressure>.035*flowMult,impulse>.04*flowMult,book>-.035*bookTol,micro>-.10*bookTol,pulseScore>.025].filter(Boolean).length;if(q<qualityMin||abs<threshold||votes<5)return {ok:false,reason:'PROFILE_EDGE_NOT_CONFIRMED',diagnostic:{q,qualityMin,score,threshold,votes,style:p.style}};"
new="qualityMin=.23*Math.max(.85,num(p.qualityThresholdMult)||1),flowMult=Math.max(.8,num(p.flowThresholdMult)||1),bookTol=Math.max(.8,num(p.bookToleranceMult)||1),threshold=(p.style==='MOMENTUM' ? .060:p.style==='BURST' ? .058:p.style==='TREND' ? .064:p.style==='RANGE' ? .052:.060)*flowMult,votes=[flow3>.045*flowMult,flow5>.055*flowMult,flow15>.045*flowMult,pressure>.035*flowMult,impulse>.04*flowMult,book>-.035*bookTol,micro>-.10*bookTol,pulseScore>.025].filter(Boolean).length,strongConsensus=abs>=threshold*1.75&&q>=qualityMin*1.10,minVotes=strongConsensus?4:5;if(q<qualityMin||abs<threshold||votes<minVotes)return {ok:false,reason:'PROFILE_EDGE_NOT_CONFIRMED',diagnostic:{q,qualityMin,score,threshold,votes,minVotes,strongConsensus,style:p.style}};"
replace_exact(strategy,old,new)

old="export function selectBybitSymbolSetup(s={}){const symbol=normalizeBybitSymbol(s.symbol||'BTCUSDT'),p=coinProfileForSymbol(symbol);if(!p)return {ok:false,reason:'SYMBOL_NOT_IN_MAJOR_CAP_UNIVERSE',symbol};const gate=profileGate(s,p);if(!gate.ok)return {...gate,symbol,profile:p};const base=selectBaseSetup({...s,symbol});if(base?.ok)return adaptBase(base,s,p);return specializedSetup(s,p);}"
new="export function selectBybitSymbolSetup(s={}){const symbol=normalizeBybitSymbol(s.symbol||'BTCUSDT'),p=coinProfileForSymbol(symbol);if(!p)return {ok:false,reason:'SYMBOL_NOT_IN_MAJOR_CAP_UNIVERSE',symbol};const q=s?.quality||{},freshWs=String(s.microstructureSource)==='VPS_BYBIT_WS'&&q.freshBook===true&&q.freshTrades===true&&q.spreadOk!==false;if(!freshWs)return {ok:false,reason:'PROFILE_MICROSTRUCTURE_STALE_OR_FALLBACK_ONLY',symbol,profile:p,source:s.microstructureSource||null,freshBook:q.freshBook??null,freshTrades:q.freshTrades??null,spreadOk:q.spreadOk??null};const gate=profileGate(s,p);if(!gate.ok)return {...gate,symbol,profile:p};const base=selectBaseSetup({...s,symbol});if(base?.ok)return adaptBase(base,s,p);return specializedSetup(s,p);}"
replace_exact(strategy,old,new)
replace_exact(strategy,"export const BYBIT_SYMBOL_STRATEGY_VERSION='BYBIT_SYMBOL_COGNITION_V2_PROFIT_SCALE_STATEFLOW';","export const BYBIT_SYMBOL_STRATEGY_VERSION='BYBIT_SYMBOL_COGNITION_V3_FRESHNESS_ADAPTIVE_CONSENSUS';")

# 2) Existing positions: if WS microstructure is stale, keep native protection but do not cut/rewrite TP/SL from fallback data.
engine=CF/'bybit-symbol-engine.js'
needle="for(const x of t)state=updateTrancheProtection(state,x.id,currentStop);state.aggregateStop=currentStop;state.lastProtectionAt=iso();events.push({symbol:SYMBOL,managed:true,verdict:\"TIGHTEN\",phase:\"EMERGENCY_PROTECT\",previousSl:0,nextSl:currentStop,r:0,peakR:0});}\n  const baseSl="
insert="for(const x of t)state=updateTrancheProtection(state,x.id,currentStop);state.aggregateStop=currentStop;state.lastProtectionAt=iso();events.push({symbol:SYMBOL,managed:true,verdict:\"TIGHTEN\",phase:\"EMERGENCY_PROTECT\",previousSl:0,nextSl:currentStop,r:0,peakR:0});}\n  const dynamicDataHealthy=String(market.microstructureSource)==='VPS_BYBIT_WS'&&market?.quality?.freshBook===true&&market?.quality?.freshTrades===true&&market?.quality?.spreadOk!==false;if(!dynamicDataHealthy){state.holdLogicVersion='NATIVE_PROTECTION_STALE_DATA_HOLD_V1';state.lastPositionStability={at:iso(),side,decision:'HOLD',reason:'MICROSTRUCTURE_STALE_NATIVE_PROTECTION_ONLY',source:market.microstructureSource||null,freshBook:market?.quality?.freshBook??null,freshTrades:market?.quality?.freshTrades??null,spreadOk:market?.quality?.spreadOk??null};return {state,events,position,cut:false};}\n  const baseSl="
replace_exact(engine,needle,insert)
replace_exact(engine,'BYBIT-MULTI-ASSET-ENGINE-4.3-OBJECTIVE-PROFIT-EFFICIENCY','BYBIT-MULTI-ASSET-ENGINE-4.3.1-FRESHNESS-FAIR-ENTRY',3)

# 3) Portfolio controller: protected stops are zero active risk; rank all scanned candidates before consuming the one-entry event slot; rotate deep coverage.
controller=CF/'bybit-multi-asset-controller.js'
old="function positionRisk(x={}){const q=Math.abs(num(x.size)),e=num(x.avgPrice),sl=num(x.stopLoss),m=Math.max(0,num(x.positionIM));return sl>0&&e>0?q*Math.abs(e-sl):m*.60;}"
new="function positionRisk(x={}){const q=Math.abs(num(x.size)),e=num(x.avgPrice),sl=num(x.stopLoss),m=Math.max(0,num(x.positionIM)),side=String(x.side||'');if(sl>0&&e>0){if(side==='Buy'&&sl>=e)return 0;if(side==='Sell'&&sl<=e)return 0;return q*Math.abs(e-sl);}return m*.60;}"
replace_exact(controller,old,new)

old="function groupCount(positions,group){return positions.filter(x=>coinProfileForSymbol(sym(x))?.correlationGroup===group).length;}\nfunction entryBlockFor"
new="function groupCount(positions,group){return positions.filter(x=>coinProfileForSymbol(sym(x))?.correlationGroup===group).length;}\nfunction rotatingDeepSymbols(ranked=[],count=6,cursor=0){const eligible=ranked.filter(x=>x.eligible),n=Math.max(1,Math.min(eligible.length,Math.floor(num(count)||1)));if(eligible.length<=n)return {symbols:eligible.map(x=>x.symbol),nextCursor:0};const headCount=Math.max(1,Math.min(n,Math.max(2,n-2))),head=eligible.slice(0,headCount),tail=eligible.slice(headCount),rotateCount=Math.max(0,n-head.length),out=[...head];for(let i=0;i<rotateCount&&tail.length;i++)out.push(tail[(Math.floor(num(cursor))+i)%tail.length]);return {symbols:[...new Set(out.map(x=>x.symbol))],nextCursor:tail.length?(Math.floor(num(cursor))+rotateCount)%tail.length:0};}\nfunction setupRank(r={}){const s=r?.scan?.best;if(!s)return null;const strength=String(s.strength||'NORMAL')==='A_PLUS'?3:String(s.strength||'NORMAL')==='STRONG'?2:1,tier=String(s.entryTier||'CONFIRM')==='FULL'?3:String(s.entryTier||'CONFIRM')==='CONFIRM'?2:1,e=s.evidence||{},profile=coinProfileForSymbol(s.symbol||r?.market?.symbol||''),edge=Math.abs(num(e.score)),quality=num(e.quality),netRR=num(s.cost?.netRewardRisk),priority=num(profile?.priority),rankScore=strength*100+tier*30+clamp(edge,0,1)*20+clamp(quality,0,1)*15+clamp(netRR,0,6)*2+priority/100;return {symbol:normalizeBybitSymbol(s.symbol||r?.market?.symbol||''),rankScore,strength:String(s.strength||'NORMAL'),entryTier:String(s.entryTier||'CONFIRM'),edgeScore:edge,quality,netRR,priority,setup:String(s.setup||'PROFILE_EDGE')};}\nfunction entryBlockFor"
replace_exact(controller,old,new)

new_function=r'''export async function runBybitMultiAssetControlled(env,opts={}){const mode=bybitExecutionMode(env),api=bybitV5(env),balance=await reconcileBtcAccountBalance(env),equity=num(balance?.snapshot?.equityUsd)||num(balance?.state?.lastEquityUsd);let positions=openPos(await api.positions()),ranked=rankUniverse(tickerRows(await api.tickers())),eventSymbol=normalizeBybitSymbol(opts.symbol||'BTCUSDT');if(!isSupportedTradeSymbol(eventSymbol))eventSymbol='BTCUSDT';const unmanaged=positions.filter(x=>!isSupportedTradeSymbol(sym(x))),previous=await get(env,CONTROL_KEY,{});const openSymbols=[...new Set(positions.filter(x=>isSupportedTradeSymbol(sym(x))).map(sym))],rotation=rotatingDeepSymbols(ranked,Math.max(1,num(BYBIT_PORTFOLIO_POLICY.deepScanCount)||6),num(previous.deepScanCursor)),targets=[...new Set([...openSymbols,eventSymbol,...rotation.symbols])],results=[],scanRows=[];let newEntryDone=false;if(unmanaged.length){const ctl={executionMode:mode,multiAsset:true,lastCycleAt:iso(),lastCycleReason:'UNMANAGED_SYMBOL_POSITION_PRESENT',unmanagedPositions:unmanaged.map(x=>({symbol:x.symbol,side:x.side,size:num(x.size)})),universe:BYBIT_TRADE_UNIVERSE,runtimeRevision:String(env.RUNTIME_REVISION||'UNKNOWN')};await put(env,CONTROL_KEY,ctl);return {ok:false,mode,reason:'UNMANAGED_SYMBOL_POSITION_PRESENT',unmanagedPositions:unmanaged,controller:ctl,results:[]};}
for(const symbol of targets){const hardBlock=entryBlockFor({symbol,positions,equity,newEntryDone:false,ranked}),ctx=portfolioContext(positions,symbol,balance),r=await runBybitSymbolEngine(env,{symbol,entryBlockReason:hardBlock||'EVENT_CANDIDATE_RANK_ONLY',portfolioContext:ctx});results.push(r);await sendLifecycle(env,r);const rank=setupRank(r);if(rank)scanRows.push({...rank,scanBlock:hardBlock||null});if(r?.reason==='SMART_CUT'||(r?.lifecycles||[]).some(x=>x?.cutExecuted))positions=openPos(await api.positions());}
positions=openPos(await api.positions());const queue=scanRows.sort((a,b)=>b.rankScore-a.rankScore||b.priority-a.priority);for(const candidate of queue){if(newEntryDone)break;const symbol=candidate.symbol,block=entryBlockFor({symbol,positions,equity,newEntryDone:false,ranked});if(block)continue;const ctx=portfolioContext(positions,symbol,balance),r=await runBybitSymbolEngine(env,{symbol,entryBlockReason:null,portfolioContext:ctx});results.push(r);await sendEntry(env,r);await sendLifecycle(env,r);if(r?.executed){newEntryDone=true;positions=openPos(await api.positions());break;}if(r?.reason==='SMART_CUT'||(r?.lifecycles||[]).some(x=>x?.cutExecuted))positions=openPos(await api.positions());}
const active=positions.map(x=>({symbol:x.symbol,side:x.side,size:num(x.size),avgPrice:num(x.avgPrice),markPrice:num(x.markPrice),unrealisedPnl:num(x.unrealisedPnl),stopLoss:num(x.stopLoss),takeProfit:num(x.takeProfit),leverage:num(x.leverage),positionIM:num(x.positionIM),activeRiskUsd:positionRisk(x)})),best=ranked.find(x=>x.eligible)||null,last=results.at(-1)||{},ctl={...previous,executionMode:mode,requestedLive:String(env.BYBIT_AUTO_LIVE||'').toLowerCase()==='true',btcLiveAck:String(env.BYBIT_BTC_LIVE_ACK||'').toLowerCase()==='true',liveAuthority:mode==='LIVE'?'MULTI_ASSET_MAJOR_CAP':'PAPER',multiAsset:true,legacyMultiCoinDisabled:false,eventDriven:true,timeGate:false,sessionGate:false,cooldownGate:false,unlimitedDailyEntries:true,maxNewEntriesPerEvent:1,decisionAuthority:'VPS_WS_MARKET_STATE_CHANGE',profileAuthority:'PER_SYMBOL_COGNITION_V1',portfolioAuthority:BYBIT_PORTFOLIO_POLICY.authority,entrySelectionAuthority:'OBJECTIVE_SCAN_THEN_RANK_FRESH_RECHECK',deepScanAuthority:'TOP_LIQUIDITY_PLUS_ROTATING_COVERAGE',deepScanCursor:rotation.nextCursor,universe:BYBIT_TRADE_UNIVERSE,lastEventSymbol:eventSymbol,activePositions:active,activePositionCount:active.length,maxConcurrent:maxConcurrentForEquity(equity),rankedUniverse:ranked.slice(0,8).map(x=>({symbol:x.symbol,eligible:x.eligible,score:Number(x.score.toFixed(4)),spreadBps:Number(x.spreadBps.toFixed(3)),turnover24h:x.turnover,style:x.profile.style})),objectiveCandidateRanking:queue.slice(0,8),bestUniverseSymbol:best?.symbol||null,equityUsd:equity,walletBalanceUsd:num(balance?.snapshot?.walletBalanceUsd),availableUsd:num(balance?.snapshot?.availableUsd),lastCycleAt:iso(),lastCycleReason:String(last?.reason||'MULTI_ASSET_CYCLE_COMPLETE'),lastCycleExecuted:results.some(x=>x?.executed),lastSymbolResults:results.slice(-8).map(x=>({symbol:x?.market?.symbol||x?.plan?.symbol||null,reason:x?.reason||null,executed:!!x?.executed,regime:x?.market?.regime||null,setup:x?.scan?.best?.setup||null,entryTier:x?.scan?.best?.entryTier||null})),runtimeRevision:String(env.RUNTIME_REVISION||'UNKNOWN')};await put(env,CONTROL_KEY,ctl);return {ok:true,mode,multiAsset:true,eventSymbol,equity,universe:BYBIT_TRADE_UNIVERSE,ranked:ctl.rankedUniverse,objectiveCandidateRanking:ctl.objectiveCandidateRanking,activePositions:active,results,controller:ctl};}'''
replace_regex(controller,r"export async function runBybitMultiAssetControlled\(env,opts=\{\}\)\{.*?\}\nexport async function getMultiAssetControllerState",new_function+"\nexport async function getMultiAssetControllerState")
replace_exact(controller,"export const BYBIT_MULTI_ASSET_CONTROLLER_VERSION='BYBIT_MULTI_ASSET_CONTROLLER_V1_EVENT_DRIVEN';","export const BYBIT_MULTI_ASSET_CONTROLLER_VERSION='BYBIT_MULTI_ASSET_CONTROLLER_V2_OBJECTIVE_RANKED_ROTATING';")

# 4) Runtime identity/contract advertises the actual safeguards and selection authority.
runtime=CF/'bybit-runtime-contract.js'
replace_exact(runtime,"BYBIT_MULTI_ASSET_RUNTIME_V16_OBJECTIVE_PROFIT_EFFICIENCY","BYBIT_MULTI_ASSET_RUNTIME_V17_FRESHNESS_FAIR_ENTRY")
replace_exact(runtime,"BYBIT-MULTI-STATEFLOW-4.3","BYBIT-MULTI-STATEFLOW-4.3.1")
replace_exact(runtime,"marketScanAuthority:'EVENT_DRIVEN_RANK_THEN_DEEP_SCAN'","marketScanAuthority:'EVENT_DRIVEN_OBJECTIVE_SCAN_RANK_ROTATING_DEEP_SCAN'")
replace_exact(runtime,"profileNormalizedQuality:true,peakNetProfitRetention:true,shortMomentumAloneCanExit:false","profileNormalizedQuality:true,peakNetProfitRetention:true,freshWsRequiredForNewRisk:true,staleDataNativeProtectionHold:true,adaptiveProfileVoteThreshold:true,executionQualityAdaptiveLiquidityGate:true,objectiveCandidateRanking:true,rotatingDeepCoverage:true,protectedStopZeroActiveRisk:true,shortMomentumAloneCanExit:false")

config=CF/'bybit-auto-config.js'
replace_exact(config,"// BYBIT-MULTI-STATEFLOW-4.3 OBJECTIVE-PROFIT-EFFICIENCY configuration.","// BYBIT-MULTI-STATEFLOW-4.3.1 FRESHNESS + OBJECTIVE-ENTRY configuration.")

print('BYBIT_V4_3_1_PATCH_OK')
