from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
p=ROOT/'cloudflare-worker/bybit-control-plane.js';s=p.read_text()
marker="async function publicUniverse(env){"
helper="""async function synchronizeCapitalMetadata(env,b={}){\n  const st=b.state||{},snap=b.snapshot||{},equity=Number(snap.equityUsd||0),wallet=Number(snap.walletBalanceUsd||0),available=Number(snap.availableUsd||0),continuous=Math.max(0,Math.min(equity,Number(st.continuousCapitalUsd||equity)||equity)),highWater=Math.max(equity,Number(st.highWaterUsd||equity)||equity),capitalIntelligence={authority:st.continuousScaleAuthority||null,stateVersion:Number(st.capitalStateVersion||0),highWaterUsd:highWater,protectedEquityUsd:Number(st.protectedEquityUsd||wallet),lastExternalCashFlow:st.lastExternalCashFlow||null,recognition:st.capitalRecognition||null,transactionLogPages:Number(st.transactionLogPages||0),transactionLogRows:Number(st.transactionLogRows||0)};\n  const controller=await getMultiAssetControllerState(env),nextController={...controller,equityUsd:equity,continuousCapacityCapitalUsd:continuous,walletBalanceUsd:wallet,availableUsd:available,capitalIntelligence,capitalMetadataSyncedAt:new Date().toISOString(),capitalMetadataSyncAuthority:'READ_ONLY_CAPITAL_RECONCILIATION_NO_STRATEGY_EXECUTION'};\n  const btc=await getBybitSymbolState(env,'BTCUSDT'),nextBtc={...btc,highWaterUsd:highWater,lastEquityUsd:equity,lastWalletBalanceUsd:wallet,lastAvailableUsd:available,lastContinuousCapitalUsd:continuous,lastCapitalBaseUsd:continuous,capitalAuthority:st.continuousScaleAuthority||null,capitalMetadataSyncedAt:new Date().toISOString()};\n  if(env.TRADING_STATE){await Promise.all([env.TRADING_STATE.put('bybit:auto:v1:controller',JSON.stringify(nextController)),env.TRADING_STATE.put('bybit:btc:hyperscale:v2:state',JSON.stringify(nextBtc))]);}\n  return {controller:{equityUsd:nextController.equityUsd,continuousCapacityCapitalUsd:nextController.continuousCapacityCapitalUsd,walletBalanceUsd:nextController.walletBalanceUsd,availableUsd:nextController.availableUsd,capitalIntelligence:nextController.capitalIntelligence,capitalMetadataSyncedAt:nextController.capitalMetadataSyncedAt},btc:{highWaterUsd:nextBtc.highWaterUsd,lastEquityUsd:nextBtc.lastEquityUsd,lastWalletBalanceUsd:nextBtc.lastWalletBalanceUsd,lastAvailableUsd:nextBtc.lastAvailableUsd,lastContinuousCapitalUsd:nextBtc.lastContinuousCapitalUsd,lastCapitalBaseUsd:nextBtc.lastCapitalBaseUsd,capitalAuthority:nextBtc.capitalAuthority,capitalMetadataSyncedAt:nextBtc.capitalMetadataSyncedAt}};\n}\n\n"""
if 'async function synchronizeCapitalMetadata' not in s:
    if marker not in s:raise SystemExit('CAPITAL_METADATA_HELPER_INSERT_MARKER_MISSING')
    s=s.replace(marker,helper+marker,1)
old="""if(u.pathname==='/bybit/capital/sync'&&req.method==='GET'){if(!authState(req,env).ok)return unauthorized(req,env);try{const b=await reconcileBtcAccountBalance(env),st=b.state||{},snap=b.snapshot||{};return json({ok:b.ok!==false,readOnlyExecution:true,tradingExecuted:false,reason:b.reason||null,netExternalCashFlowUsd:Number(b.netExternalCashFlowUsd||0),account:{equityUsd:Number(snap.equityUsd||0),walletBalanceUsd:Number(snap.walletBalanceUsd||0),availableUsd:Number(snap.availableUsd||0)},capital:{stateVersion:Number(st.capitalStateVersion||0),continuousCapitalUsd:Number(st.continuousCapitalUsd||0),highWaterUsd:Number(st.highWaterUsd||0),protectedEquityUsd:Number(st.protectedEquityUsd||0),authority:st.continuousScaleAuthority||null,recognition:st.capitalRecognition||null,lastExternalCashFlow:st.lastExternalCashFlow||null,transactionLogPages:Number(st.transactionLogPages||0),transactionLogRows:Number(st.transactionLogRows||0)},checkedAt:new Date().toISOString()})}catch(e){return json({ok:false,readOnlyExecution:true,tradingExecuted:false,reason:'CAPITAL_SYNC_FAILED',error:String(e?.message||e)},502)}}"""
new="""if(u.pathname==='/bybit/capital/sync'&&req.method==='GET'){if(!authState(req,env).ok)return unauthorized(req,env);try{const b=await reconcileBtcAccountBalance(env),st=b.state||{},snap=b.snapshot||{},synced=await synchronizeCapitalMetadata(env,b);return json({ok:b.ok!==false,readOnlyExecution:true,tradingExecuted:false,strategyExecuted:false,ordersCreated:false,positionsChanged:false,reason:b.reason||null,netExternalCashFlowUsd:Number(b.netExternalCashFlowUsd||0),account:{equityUsd:Number(snap.equityUsd||0),walletBalanceUsd:Number(snap.walletBalanceUsd||0),availableUsd:Number(snap.availableUsd||0)},capital:{stateVersion:Number(st.capitalStateVersion||0),continuousCapitalUsd:Number(st.continuousCapitalUsd||0),highWaterUsd:Number(st.highWaterUsd||0),protectedEquityUsd:Number(st.protectedEquityUsd||0),authority:st.continuousScaleAuthority||null,recognition:st.capitalRecognition||null,lastExternalCashFlow:st.lastExternalCashFlow||null,transactionLogPages:Number(st.transactionLogPages||0),transactionLogRows:Number(st.transactionLogRows||0)},metadataSync:synced,checkedAt:new Date().toISOString()})}catch(e){return json({ok:false,readOnlyExecution:true,tradingExecuted:false,strategyExecuted:false,ordersCreated:false,positionsChanged:false,reason:'CAPITAL_SYNC_FAILED',error:String(e?.message||e)},502)}}"""
if old not in s:
    if new not in s:raise SystemExit('CAPITAL_SYNC_ROUTE_PATTERN_MISSING')
else:s=s.replace(old,new,1)
p.write_text(s)
print('BYBIT_V480_CAPITAL_METADATA_SYNC_PATCHED')
