from pathlib import Path
import re

ROOT=Path('cloudflare-worker')

def rw(name):
    p=ROOT/name
    return p,p.read_text()

def save(p,s):
    p.write_text(s)

def rep(s,old,new,label):
    if old not in s:
        raise SystemExit(f'MISSING:{label}')
    return s.replace(old,new,1)

def sub(s,pattern,new,label):
    out,n=re.subn(pattern,new,s,count=1,flags=re.S)
    if n!=1:
        raise SystemExit(f'REGEX_MISSING:{label}:{n}')
    return out

# 1) Scalp-first config: profit comes from sizing + turnover, never by stretching a scalp into a swing.
p,s=rw('bybit-auto-config.js')
s=rep(s,"authority:'OBJECTIVE_PROFIT_FLOOR_EDGE_PERSISTENCE_FLOOR_LOCK'","authority:'SCALP_FIRST_REALISTIC_TARGET_FAST_TURNOVER_PROFIT_LOCK'",'scalp authority')
s=rep(s,"minPlannedNetProfitUsd:.40,\n    preferredRunnerNetProfitUsd:1.50,\n    minPlannedNetProfitPct:.55,","minPlannedNetProfitUsd:.30,\n    preferredRunnerNetProfitUsd:1.00,\n    minPlannedNetProfitPct:.35,\n    minViableNetProfitUsd:.18,\n    allowFloorRelaxationForFastScalp:true,",'profit objectives')
s=rep(s,"{equityUsd:0,minNetUsd:.40},{equityUsd:50,minNetUsd:.55},{equityUsd:75,minNetUsd:.75},\n      {equityUsd:100,minNetUsd:1.00},{equityUsd:150,minNetUsd:1.40},{equityUsd:250,minNetUsd:2.00},\n      {equityUsd:500,minNetUsd:4.00},{equityUsd:1000,minNetUsd:8.00},{equityUsd:2500,minNetUsd:18.00},\n      {equityUsd:5000,minNetUsd:40.00},{equityUsd:10000,minNetUsd:80.00}","{equityUsd:0,minNetUsd:.25},{equityUsd:50,minNetUsd:.35},{equityUsd:75,minNetUsd:.45},\n      {equityUsd:100,minNetUsd:.55},{equityUsd:150,minNetUsd:.75},{equityUsd:250,minNetUsd:1.10},\n      {equityUsd:500,minNetUsd:2.00},{equityUsd:1000,minNetUsd:3.50},{equityUsd:2500,minNetUsd:8.00},\n      {equityUsd:5000,minNetUsd:16.00},{equityUsd:10000,minNetUsd:32.00}",'profit ladder')
s=rep(s,"profitPeakRetentionPct:.78,\n    profitLockR:.55,\n    trailStartR:1.10,\n    trailRange5Pct:.22,\n    trailPricePct:.00170,","profitPeakRetentionPct:.72,\n    profitLockR:.45,\n    trailStartR:.82,\n    trailRange5Pct:.16,\n    trailPricePct:.00110,",'faster protection')
s=sub(s,r"adaptiveProtection:\{\n      enabled:true,\n      authority:'EDGE_PERSISTENCE_NATIVE_TP_SL_SINGLE_WRITER',.*?\n      timeGate:false\n    \}","adaptiveProtection:{\n      enabled:true,\n      authority:'SCALP_FIRST_NATIVE_TP_SL_SINGLE_WRITER',\n      probeBaseTargetR:1.25,\n      confirmBaseTargetR:1.50,\n      fullBaseTargetR:1.75,\n      minTargetR:.75,\n      maxTargetR:2.20,\n      strongExtensionR:.28,\n      weakCompressionR:.32,\n      minTargetMoveR:.10,\n      minLiveGapR:.12,\n      peakGivebackActivationR:.65,\n      peakGivebackR:.30,\n      neverLoosenStop:true,\n      combineNativeTpSlWrite:true,\n      timeGate:false\n    }",'adaptive protection')
s=rep(s,"profitableMarketExit:false,\n    profitHarvestExit:true,\n    profitHarvestMinEvidence:3,\n    earlyHarvestMinNetUsd:.30,\n    earlyHarvestMinPeakR:.65,\n    earlyHarvestMinEvidence:2,\n    earlyHarvestConfirmEvents:2,\n    earlyHarvestGivebackR:.30,\n    profitHarvestConfirmEvents:2,\n    profitHarvestPeakGivebackR:.35,","profitableMarketExit:true,\n    profitHarvestExit:true,\n    profitHarvestMinEvidence:2,\n    earlyHarvestMinNetUsd:.18,\n    earlyHarvestMinPeakR:.42,\n    earlyHarvestMinEvidence:2,\n    earlyHarvestConfirmEvents:1,\n    earlyHarvestGivebackR:.18,\n    profitHarvestConfirmEvents:1,\n    profitHarvestPeakGivebackR:.24,",'harvest speed')
s=rep(s,"decelerationLockMinR:.55,\n    decelerationPeakMinR:.80,","decelerationLockMinR:.38,\n    decelerationPeakMinR:.55,",'deceleration')
s=s.replace('BYBIT-MULTI-STATEFLOW-4.8.0','BYBIT-MULTI-STATEFLOW-4.9.0')
save(p,s)

# 2) Profiles + portfolio: normalize every core/dynamic coin to scalp horizons and let risk/margin be the real admission authority.
p,s=rw('bybit-coin-profiles.js')
s=rep(s,"authority:'DYNAMIC_BYBIT_SCALP_PORTFOLIO_V8_CAPITAL_INTELLIGENCE_FAST_SCALE',\n  maxNewEntriesPerEvent:1,\n  deepScanCount:16,promotionScanCount:0,","authority:'DYNAMIC_BYBIT_SCALP_PORTFOLIO_V9_MULTI_ENTRY_CAPACITY',\n  maxNewEntriesPerEvent:null,\n  deepScanCount:28,promotionScanCount:0,",'portfolio policy')
s=rep(s,"concurrentByEquity:[{equityUsd:0,max:2.35},{equityUsd:50,max:2.70},{equityUsd:100,max:3.10},{equityUsd:250,max:4.00},{equityUsd:500,max:5.00},{equityUsd:1000,max:6.00},{equityUsd:2500,max:7.00},{equityUsd:5000,max:8.00}],","concurrentByEquity:[{equityUsd:0,max:4.5},{equityUsd:50,max:5.5},{equityUsd:100,max:6.5},{equityUsd:250,max:8.0},{equityUsd:500,max:10.0},{equityUsd:1000,max:12.0},{equityUsd:2500,max:14.0},{equityUsd:5000,max:16.0}],",'concurrency')
s=rep(s,"const DYNAMIC_PROFILE_BASE=freeze({...base,marketCapClass:'DYNAMIC',riskMult:.55,targetMult:1.10,stopMult:1.06,signalGain:.96,flowThresholdMult:1.04,qualityThresholdMult:1.10,bookToleranceMult:.94,leverageMult:.82,maxSpreadBps:20.0,minTurnoverUsd:500_000,runnerMaxR:4.5,holdMult:1.08,minNetProfitMult:1.00,profitGivebackMult:.92,reverseExitEvidenceMult:1.08,style:'BALANCED',correlationGroup:'DYNAMIC_ALT',priority:35,dynamicProfile:true});\nconst DYNAMIC_PROFILE_CACHE=new Map();","const DYNAMIC_PROFILE_BASE=freeze({...base,marketCapClass:'DYNAMIC',riskMult:.55,targetMult:.98,stopMult:.96,signalGain:.98,flowThresholdMult:1.02,qualityThresholdMult:1.06,bookToleranceMult:.96,leverageMult:.82,maxSpreadBps:12.0,minTurnoverUsd:750_000,runnerMaxR:2.15,holdMult:.90,minNetProfitMult:.96,profitGivebackMult:.88,reverseExitEvidenceMult:.96,style:'BALANCED',correlationGroup:'DYNAMIC_ALT',priority:35,dynamicProfile:true});\nconst DYNAMIC_PROFILE_CACHE=new Map();\nconst CORE_SCALP_PROFILE_CACHE=new Map();\nfunction scalpNormalizedCoreProfile(x){return freeze({...x,targetMult:Math.min(1.03,Number(x.targetMult)||1),stopMult:Math.min(1.02,Number(x.stopMult)||1),runnerMaxR:Math.min(2.25,Number(x.runnerMaxR)||2.25),holdMult:Math.min(1.03,Number(x.holdMult)||1),profitGivebackMult:Math.min(1.00,Number(x.profitGivebackMult)||1),reverseExitEvidenceMult:Math.min(1.05,Number(x.reverseExitEvidenceMult)||1)});}", 'dynamic/core scalp profile')
s=rep(s,"const s=normalizeBybitSymbol(symbol),core=BYBIT_COIN_PROFILES[s];if(core)return core;","const s=normalizeBybitSymbol(symbol),core=BYBIT_COIN_PROFILES[s];if(core){if(!CORE_SCALP_PROFILE_CACHE.has(s))CORE_SCALP_PROFILE_CACHE.set(s,scalpNormalizedCoreProfile(core));return CORE_SCALP_PROFILE_CACHE.get(s);}",'core normalization')
s=rep(s,"return Math.min(10,last.max+Math.log1p(Math.max(0,e-last.equityUsd)/Math.max(1,last.equityUsd))*1.25);","return Math.min(20,last.max+Math.log1p(Math.max(0,e-last.equityUsd)/Math.max(1,last.equityUsd))*1.50);",'tail concurrency')
s=rep(s,"export function correlationCapForEquity(equityUsd=0){const e=Math.max(0,Number(equityUsd)||0);return Math.min(3,1.20+Math.log1p(e/150)*.55);}","export function correlationCapForEquity(equityUsd=0){const e=Math.max(0,Number(equityUsd)||0);return Math.min(5,2.20+Math.log1p(e/100)*.80);}",'correlation capacity')
save(p,s)

# 3) BTC geometry: every setup is a scalp; structural stops cannot silently turn pullbacks into day trades.
p,s=rw('bybit-btc-strategy.js')
s=rep(s,"function distFloor(s={}){const px=Math.max(1,num(s.price)),r5=Math.max(0,num(s.range5?.width)),r15=Math.max(0,num(s.range15?.width));return Math.max(px*.00095,r5*.085,r15*.025);}","function distFloor(s={}){const px=Math.max(1,num(s.price)),r5=Math.max(0,num(s.range5?.width)),r15=Math.max(0,num(s.range15?.width));return Math.max(px*.00080,r5*.075,r15*.020);}",'btc floor')
s=sub(s,r"function geometry\(side,s=\{\},setup='',entryTier='CONFIRM'\)\{.*?\}\nfunction evidence","function geometry(side,s={},setup='',entryTier='CONFIRM'){const e=num(s.price),floor=distFloor(s),st=s.structure15||{},sw=s.sweep5||{};let sl=0;if(side==='Buy')sl=Math.min(num(sw.priorLow)||e-floor,num(st.recentLow)||e-floor,e-floor);else sl=Math.max(num(sw.priorHigh)||e+floor,num(st.recentHigh)||e+floor,e+floor);let risk=Math.max(floor,Math.abs(e-sl)),r5=Math.max(0,num(s.range5?.width)),r15=Math.max(0,num(s.range15?.width)),cap=Math.max(floor*1.35,Math.min(e*.00160,Math.max(floor,r5*.22,r15*.055)));risk=clamp(risk,floor,cap);sl=side==='Buy'?e-risk:e+risk;let runner=entryTier==='PROBE'?1.55:entryTier==='CONFIRM'?1.72:1.90;if(setup.includes('BREAKOUT'))runner=entryTier==='FULL'?2.05:1.82;if(setup.includes('RANGE'))runner=entryTier==='PROBE'?1.48:1.62;if(setup.includes('LIQUIDATION'))runner=1.65;if(setup.includes('PULLBACK'))runner=1.72;const tp=side==='Buy'?e+risk*runner:e-risk*runner;return {entry:e,sl,tp,rr:runner,stopDistance:risk,scalpOnly:true};}\nfunction evidence",'btc geometry')
s=rep(s,"minNetBps=Math.max(tier==='PROBE'?4.5:5.5,totalCostBps*(tier==='PROBE'?.40:.48)),minNetRR=tier==='PROBE'?.48:.58;","minNetBps=Math.max(tier==='PROBE'?3.0:4.0,totalCostBps*(tier==='PROBE'?.28:.36)),minNetRR=tier==='PROBE'?.30:.38;",'btc cost gate')
s=s.replace("BTC_STATE_FIRST_MICROSTRUCTURE_V8_PROBE_CONFIRM_FULL","BTC_STATE_FIRST_MICROSTRUCTURE_V9_SCALP_ONLY_FAST_TURNOVER")
save(p,s)

# 4) Per-symbol strategy: shorter target R, tighter stop cap, still net-positive after costs.
p,s=rw('bybit-symbol-strategy.js')
s=sub(s,r"function targetRFor\(p=\{\},regime='TRANSITION',tier='CONFIRM'\)\{.*?\}\nfunction geometry","function targetRFor(p={},regime='TRANSITION',tier='CONFIRM'){const style=String(p.style||'BALANCED'),base=tier==='PROBE'?1.50:tier==='FULL'?1.90:1.70,regimeMult=/BREAKOUT/.test(regime)?1.08:/TREND/.test(regime)?1.04:regime==='SQUEEZE'?1.02:regime==='RANGE'?.92:regime==='REVERSAL'?.96:1,styleMult=style==='MOMENTUM'?1.04:style==='TREND'?1.02:style==='BURST'?1.03:style==='RANGE'?.94:1;return clamp(base*regimeMult*styleMult*num(p.targetMult||1),1.30,Math.min(2.25,num(p.runnerMaxR)||2.25));}\nfunction geometry",'symbol targetR')
s=sub(s,r"function geometry\(side,s=\{\},p=\{\},tier='CONFIRM'\)\{.*?\}\nfunction momentumFootprint","function geometry(side,s={},p={},tier='CONFIRM'){const e=Math.max(0,num(s.price)),r5=Math.max(0,num(s.range5?.width)),r15=Math.max(0,num(s.range15?.width)),floor=Math.max(e*.00078,r5*.07,r15*.018)*Math.max(.78,num(p.stopMult)||1),st=s.structure15||{},sw=s.sweep5||{};let sl=side==='Buy'?Math.min(num(sw.priorLow)||e-floor,num(st.recentLow)||e-floor,e-floor):Math.max(num(sw.priorHigh)||e+floor,num(st.recentHigh)||e+floor,e+floor);let d=Math.max(floor,Math.abs(e-sl));const cap=Math.max(floor*1.35,Math.min(e*.00175,Math.max(floor,r5*.24,r15*.06)));d=Math.min(d,cap);sl=side==='Buy'?e-d:e+d;const rr=targetRFor(p,String(s.regime||'TRANSITION'),tier),tp=side==='Buy'?e+d*rr:e-d*rr;return {entry:e,sl,tp,rr,stopDistance:d,scalpOnly:true};}\nfunction momentumFootprint",'symbol geometry')
s=rep(s,"minNet=Math.max(4.5,total*.42)*Math.max(.92,num(profile.qualityThresholdMult)||1);return {ok:net>=minNet&&rr>=.48","minNet=Math.max(3.5,total*.32)*Math.max(.92,num(profile.qualityThresholdMult)||1);return {ok:net>=minNet&&rr>=.35",'symbol cost gate')
s=s.replace("BYBIT_SYMBOL_COGNITION_V5_DIRECTION_COHERENCE_LONG_RUN_FREEZE","BYBIT_SYMBOL_COGNITION_V6_SCALP_VELOCITY_TARGET_CAP")
save(p,s)

# 5) Engine: cap adaptive targets, relax dollar floor rather than stretching TP, manage legacy positions into scalp geometry.
p,s=rw('bybit-symbol-engine.js')
s=rep(s,"function extendTarget(side,current,candidate){if(!(candidate>0))return current;if(!(current>0))return candidate;return side===\"Buy\"?Math.max(current,candidate):Math.min(current,candidate);}","function extendTarget(side,current,candidate){if(!(candidate>0))return current;if(!(current>0))return candidate;return side===\"Buy\"?Math.max(current,candidate):Math.min(current,candidate);}\nfunction nearerTarget(side,current,candidate){if(!(candidate>0))return current;if(!(current>0))return candidate;return side===\"Buy\"?Math.min(current,candidate):Math.max(current,candidate);}",'nearer target')
s=sub(s,r"function expandSetupToProfitFloor\(setup=\{\},sized=\{\},floorUsd=1,cfg=\{\}\)\{.*?\}\nfunction positionRisk","function expandSetupToProfitFloor(setup={},sized={},floorUsd=1,cfg={}){const entry=num(setup.entry),sl=num(setup.sl),qty=Math.abs(num(sized.qty)),d=Math.abs(entry-sl),cost=Math.max(0,num(sized.costReserveUsd));if(!(entry>0&&d>0&&qty>0))return {ok:false,reason:'PROFIT_FLOOR_GEOMETRY_INVALID'};const buffer=Math.max(1,num(cfg?.scalp?.profitFloorBufferMult)||1.05),requestedNetUsd=Math.max(.12,num(floorUsd))*buffer,requiredGross=requestedNetUsd+cost,requiredDist=requiredGross/qty,requiredR=requiredDist/d,currentR=Math.abs(num(setup.tp)-entry)/d,apMax=Math.max(.8,num(cfg?.scalp?.adaptiveProtection?.maxTargetR)||2.2),profileMax=Math.max(.8,num(setup?.coinProfile?.runnerMaxR)||apMax),maxRunnerR=Math.min(apMax,profileMax),targetR=Math.max(currentR,requiredR);if(targetR>maxRunnerR+1e-9){const boundedR=Math.max(currentR,maxRunnerR),tp=String(setup.side)==='Buy'?entry+d*boundedR:entry-d*boundedR,achievableGross=Math.abs(tp-entry)*qty,achievableNet=Math.max(0,achievableGross-cost),minViable=Math.max(.12,num(cfg?.scalp?.minViableNetProfitUsd)||.18);if(cfg?.scalp?.allowFloorRelaxationForFastScalp!==false&&achievableNet+1e-9>=minViable)return {ok:true,requiredNetUsd:minViable,requestedNetUsd,requiredR,maxRunnerR,targetR:boundedR,floorRelaxedForFastScalp:true,achievableNetUsd:achievableNet,setup:{...setup,tp,rr:boundedR,profitFloorAdjusted:boundedR>currentR+1e-9,profitFloorUsd:floorUsd,requestedNetProfitUsd:requestedNetUsd,requiredNetProfitUsd:minViable,scalpFloorRelaxed:true}};return {ok:false,reason:'SCALP_TARGET_CAP_CANNOT_CLEAR_MIN_VIABLE_NET',requestedNetUsd,requiredNetUsd:minViable,requiredR,maxRunnerR,achievableNetUsd:achievableNet};}const tp=String(setup.side)==='Buy'?entry+d*targetR:entry-d*targetR;return {ok:true,requiredNetUsd:requestedNetUsd,requestedNetUsd,requiredR,targetR,maxRunnerR,setup:{...setup,tp,rr:targetR,profitFloorAdjusted:targetR>currentR+1e-9,profitFloorUsd:floorUsd,requiredNetProfitUsd:requestedNetUsd}};}\nfunction positionRisk",'profit floor cap')
s=sub(s,r"function adaptiveTargetPlan\(side,latest,mark,market,stability,cfg,d,tick,r\)\{.*?\}\nasync function manageCluster","function adaptiveTargetPlan(side,latest,mark,market,stability,cfg,d,tick,r){const ap=cfg?.scalp?.adaptiveProtection||{},tier=String(latest?.entryTier||'CONFIRM'),cp=latest?.coinProfile||{},targetMult=clamp(num(cp.targetMult)||1,.80,1.08),base=(tier==='PROBE'?num(ap.probeBaseTargetR)||1.25:tier==='FULL'?num(ap.fullBaseTargetR)||1.75:num(ap.confirmBaseTargetR)||1.50)*targetMult,minR=Math.max(.55,num(ap.minTargetR)||.75),maxR=Math.min(Math.max(minR,num(ap.maxTargetR)||2.20),Math.max(minR,num(cp.runnerMaxR)||num(ap.maxTargetR)||2.20)),support=positionSupport(side,market),strong=Math.max(0,support),weak=Math.max(0,-support),extend=Math.max(0,num(ap.strongExtensionR)||.28),compress=Math.max(0,num(ap.weakCompressionR)||.32),degradeConfirmed=stability.evidenceCount>=2&&(stability.structureAgainst||stability.mediumAgainst)&&(stability.bookAgainst||stability.pulseAgainst||stability.fastAgainst||stability.shockAgainst),weakApplied=degradeConfirmed?weak:0;let targetR=clamp(base+strong*extend-weakApplied*compress,minR,maxR);const entry=num(latest?.entry),r5=Math.max(0,num(market?.range5?.width)),r15=Math.max(0,num(market?.range15?.width)),rawScalpCap=Math.max(entry*.00135,r5*.32,r15*.085,tick*12),absoluteScalpCap=Math.max(entry*.00155,Math.min(entry*.00320,rawScalpCap)),scalpCapR=d>0?absoluteScalpCap/d:maxR;targetR=Math.min(targetR,Math.max(.55,scalpCapR));const gap=Math.max(tick*8,d*Math.max(.04,num(ap.minLiveGapR)||.12)),scalpCapTarget=side==='Buy'?entry+absoluteScalpCap:entry-absoluteScalpCap;let target=side==='Buy'?entry+d*targetR:entry-d*targetR;if(side==='Buy')target=Math.max(target,mark+gap);else target=Math.min(target,mark-gap);return {target:roundTick(target,tick),targetR,support,supportPct:Math.round(clamp(50+support*50,0,100)),baseTargetR:base,minR,maxR,degradeConfirmed,scalpCapR,scalpCapDistance:absoluteScalpCap,scalpCapTarget:roundTick(scalpCapTarget,tick),scalpOnly:true,shortMomentumAloneCanCompressTp:false};}\nasync function manageCluster",'adaptive scalp target')
s=rep(s,"desiredTarget=!profitReady&&enforceFloorTarget?extendTarget(side,rawDesiredTarget,floorTarget):rawDesiredTarget","boundedFloorTarget=adaptive?.scalpCapTarget?(side==='Buy'?Math.min(floorTarget,adaptive.scalpCapTarget):Math.max(floorTarget,adaptive.scalpCapTarget)):floorTarget,desiredTarget=!profitReady&&enforceFloorTarget?extendTarget(side,rawDesiredTarget,boundedFloorTarget):rawDesiredTarget",'floor bounded target')
s=rep(s,"harvestMinEvidence=Math.max(3,Math.round((num(cfg?.positionControl?.profitHarvestMinEvidence)||3)*reverseExitEvidenceMult)),harvestConfirm=Math.max(2,Math.round((num(cfg?.positionControl?.profitHarvestConfirmEvents)||2)*reverseExitEvidenceMult))","harvestMinEvidence=Math.max(2,Math.round((num(cfg?.positionControl?.profitHarvestMinEvidence)||2)*reverseExitEvidenceMult)),harvestConfirm=Math.max(1,Math.round((num(cfg?.positionControl?.profitHarvestConfirmEvents)||1)*reverseExitEvidenceMult))",'harvest confirmation')
s=rep(s,"earlyMinPeakR=Math.max(.30,num(cfg?.positionControl?.earlyHarvestMinPeakR)||.55)","earlyMinPeakR=Math.max(.20,num(cfg?.positionControl?.earlyHarvestMinPeakR)||.42)",'early peak')
s=rep(s,"earlyGiveback=Math.max(.15,num(cfg?.positionControl?.earlyHarvestGivebackR)||.25)","earlyGiveback=Math.max(.10,num(cfg?.positionControl?.earlyHarvestGivebackR)||.18)",'early giveback')
s=rep(s,"effectiveTarget=extendTarget(setup.side,existingTarget,candidateTarget)","effectiveTarget=nearerTarget(setup.side,existingTarget,candidateTarget)",'pyramid target merge')
s=s.replace('4.8.0-CAPITAL-INTELLIGENCE-FAST-SCALE','4.9.0-SCALP-FIRST-FAST-TURNOVER')
save(p,s)

# 6) Controller: rank by short-horizon velocity and admit multiple independent entries until actual risk/margin/slot capacity is exhausted.
p,s=rw('bybit-multi-asset-controller.js')
s=sub(s,r"function setupRank\(r=\{\}\)\{.*?\}\nfunction marketBreadth","function setupRank(r={}){const s=r?.scan?.best;if(!s)return null;const strength=String(s.strength||'NORMAL')==='A_PLUS'?3:String(s.strength||'NORMAL')==='STRONG'?2:1,tier=String(s.entryTier||'CONFIRM')==='FULL'?3:String(s.entryTier||'CONFIRM')==='CONFIRM'?2:1,e=s.evidence||{},profile=coinProfileForSymbol(s.symbol||r?.market?.symbol||''),edge=Math.abs(num(e.score)),quality=num(e.quality),netRR=num(s.cost?.netRewardRisk),priority=num(profile?.priority),t=r?.market?.trades||{},v1=Math.abs(num(t.priceChange1sBps||t.window1s?.priceChangeBps)),v3=Math.abs(num(t.priceChange3sBps||t.window3s?.priceChangeBps)),v5=Math.abs(num(t.priceChange5sBps||t.window5s?.priceChangeBps)),velocityBps=.20*v1+.45*v3+.35*v5,velocityScore=clamp(velocityBps/10,0,1),rankScore=strength*100+tier*30+clamp(edge,0,1)*20+clamp(quality,0,1)*15+clamp(netRR,0,4)*2+velocityScore*18+priority/100;return {symbol:normalizeBybitSymbol(s.symbol||r?.market?.symbol||''),side:String(s.side||''),regime:String(s.regime||''),rankScore,strength:String(s.strength||'NORMAL'),entryTier:String(s.entryTier||'CONFIRM'),edgeScore:edge,quality,netRR,scalpVelocityBps:Number(velocityBps.toFixed(3)),velocityScore:Number(velocityScore.toFixed(3)),priority,setup:String(s.setup||'PROFILE_EDGE'),localCounterTrend:!!e.localCounterTrend,reversalValidated:!!e.reversalValidated,marketContrarianQualified:!!e.marketContrarianQualified};}\nfunction marketBreadth",'velocity ranking')
s=sub(s,r"function entryBlockFor\(\{symbol,positions,equity,newEntryDone,ranked\}\)\{.*?\}\nfunction compact","function entryBlockFor({symbol,positions,equity,ranked}){const p=coinProfileForSymbol(symbol),existing=positions.find(x=>sym(x)===symbol);if(!p)return 'SYMBOL_NOT_IN_MAJOR_CAP_UNIVERSE';if(existing)return null;const row=ranked.find(x=>x.symbol===symbol);if(!row)return 'SYMBOL_NOT_IN_DYNAMIC_MARKET_UNIVERSE';if(!row.eligible)return 'DYNAMIC_UNIVERSE_WATCH_ONLY';const baseMax=maxConcurrentForEquity(equity),hardMax=baseMax+Math.max(0,Math.floor(num(BYBIT_PORTFOLIO_POLICY.physicalPositionBuffer)||0));if(positions.length>=hardMax)return 'PORTFOLIO_PHYSICAL_POSITION_HARD_CAP';const pendingEntrySlot=1;if(slotUsage(positions,equity)+pendingEntrySlot>baseMax+1e-9)return 'PORTFOLIO_RISK_SLOT_CAP';if(groupSlotUsage(positions,p.correlationGroup,equity)+pendingEntrySlot>correlationCapForEquity(equity)+1e-9)return 'PORTFOLIO_CORRELATION_RISK_SLOT_CAP';return null;}\nfunction compact",'entry capacity')
s=rep(s,"export async function runBybitMultiAssetControlled(env,opts={}){const mode=bybitExecutionMode(env)","export async function runBybitMultiAssetControlled(env,opts={}){const managementOnly=opts.managementOnly===true,mode=bybitExecutionMode(env)",'management mode')
s=rep(s,"targets=[...new Set([...openSymbols,eventSymbol,...rotation.symbols,...promotionRotation.symbols])],results=[],scanRows=[],promotionObservations=[],candidateDecisions=[];let newEntryDone=false;","targets=managementOnly?[...new Set(openSymbols)]:[...new Set([...openSymbols,eventSymbol,...rotation.symbols,...promotionRotation.symbols])],results=[],scanRows=[],promotionObservations=[],candidateDecisions=[];let entriesExecuted=0;",'targets/multi entry')
s=rep(s,"for(const candidate of queue){if(newEntryDone)break;","if(!managementOnly)for(const candidate of queue){",'multi entry loop')
s=rep(s,"if(r?.executed){newEntryDone=true;positions=openPos(await api.positions());break;}","if(r?.executed){entriesExecuted++;positions=openPos(await api.positions());continue;}",'continue entries')
s=rep(s,"maxNewEntriesPerEvent:1,decisionAuthority:","maxNewEntriesPerEvent:'DYNAMIC_UNTIL_RISK_MARGIN_CAPACITY',entriesExecutedThisEvent:entriesExecuted,managementOnly,decisionAuthority:",'controller metadata')
s=rep(s,"lastCycleReason:String(last?.reason||'MULTI_ASSET_CYCLE_COMPLETE')","lastCycleReason:managementOnly?'MANAGEMENT_ONLY_SCALP_REBASE':String(last?.reason||'MULTI_ASSET_CYCLE_COMPLETE')",'management reason')
s=s.replace("BYBIT_MULTI_ASSET_CONTROLLER_V6_CAPITAL_INTELLIGENCE_FAST_SCALE","BYBIT_MULTI_ASSET_CONTROLLER_V7_SCALP_FIRST_MULTI_ENTRY")
save(p,s)

# 7) Control-plane management-only trigger: used only to rebase existing positions without creating new risk.
p,s=rw('bybit-control-plane.js')
s=rep(s,"const symbol=normalizeBybitSymbol(req.headers.get('x-bybit-symbol')||'BTCUSDT');try{return json({exchange:'BYBIT',triggerSource:a.source,eventDriven:true,...(await runBybitMultiAssetControlled(env,{symbol}))})","const symbol=normalizeBybitSymbol(req.headers.get('x-bybit-symbol')||'BTCUSDT'),managementOnly=String(req.headers.get('x-bybit-management-only')||'').toLowerCase()==='true';try{return json({exchange:'BYBIT',triggerSource:a.source,eventDriven:true,managementOnly,...(await runBybitMultiAssetControlled(env,{symbol,managementOnly}))})",'control management')
save(p,s)

# 8) Runtime contract and validator.
p,s=rw('bybit-runtime-contract.js')
s=s.replace('BYBIT_MULTI_ASSET_RUNTIME_V26_CAPITAL_INTELLIGENCE_FAST_SCALE','BYBIT_MULTI_ASSET_RUNTIME_V27_SCALP_FIRST_MULTI_ENTRY')
s=s.replace('BYBIT-MULTI-STATEFLOW-4.8.0','BYBIT-MULTI-STATEFLOW-4.9.0')
s=rep(s,"fastScaleControlled:true,adaptiveLeverageExpanded:true","fastScaleControlled:true,scalpOnly:true,scalpTargetDistanceCapped:true,profitFloorNeverForcesSwingTarget:true,existingPositionScalpRebase:true,multiEntryUntilCapacity:true,scalpVelocityCandidateRanking:true,adaptiveLeverageExpanded:true",'runtime flags')
save(p,s)

p,s=rw('validate-btc-hyperscale.mjs')
s=s.replace('BYBIT-MULTI-STATEFLOW-4.8.0','BYBIT-MULTI-STATEFLOW-4.9.0')
s=s.replace('BYBIT_MULTI_ASSET_RUNTIME_V26_CAPITAL_INTELLIGENCE_FAST_SCALE','BYBIT_MULTI_ASSET_RUNTIME_V27_SCALP_FIRST_MULTI_ENTRY')
s=s.replace('4.8.0-CAPITAL-INTELLIGENCE-FAST-SCALE','4.9.0-SCALP-FIRST-FAST-TURNOVER')
s=rep(s,"'adaptiveLeverageExpanded','freshWsRequiredForNewRisk'","'scalpOnly','scalpTargetDistanceCapped','profitFloorNeverForcesSwingTarget','existingPositionScalpRebase','multiEntryUntilCapacity','scalpVelocityCandidateRanking','adaptiveLeverageExpanded','freshWsRequiredForNewRisk'",'validator runtime flags')
s=rep(s,"assert.ok(BYBIT_PORTFOLIO_POLICY.deepScanCount>=12);","assert.ok(BYBIT_PORTFOLIO_POLICY.deepScanCount>=24);assert.ok(maxConcurrentForEquity(60)>=5);assert.equal(BYBIT_PORTFOLIO_POLICY.maxNewEntriesPerEvent,null);",'validator portfolio')
s=rep(s,"for(const x of ['continuousCapacityCapitalUsd','capitalIntelligence','CROSS_MARKET_DIRECTION_CONFLICT','buildBybitPerformanceGovernor','performanceRiskMult'])","for(const x of ['continuousCapacityCapitalUsd','capitalIntelligence','CROSS_MARKET_DIRECTION_CONFLICT','buildBybitPerformanceGovernor','performanceRiskMult','scalpVelocityBps','entriesExecutedThisEvent','MANAGEMENT_ONLY_SCALP_REBASE'])",'validator controller')
s=rep(s,"for(const x of ['4.9.0-SCALP-FIRST-FAST-TURNOVER','positiveLockReady','exchangeMaxLeverage','lastContinuousCapitalUsd','performanceRiskMult','reduceOnly:true'])","for(const x of ['4.9.0-SCALP-FIRST-FAST-TURNOVER','positiveLockReady','exchangeMaxLeverage','lastContinuousCapitalUsd','performanceRiskMult','reduceOnly:true','nearerTarget','scalpCapTarget','floorRelaxedForFastScalp'])",'validator engine')
save(p,s)

print('BYBIT_V490_SCALP_FIRST_PATCH=APPLIED')
