import fs from "node:fs";
const PAPER="/var/lib/meme-alpha/data/paper/state.json", OUT="/var/lib/meme-alpha/data/paper/validation.json";
const s=JSON.parse(fs.readFileSync(PAPER,"utf8")); const trades=s.trades||[], open=s.openPositions||[];
const buys=trades.filter(x=>x.type==="PAPER_BUY_PROBE"), sells=trades.filter(x=>x.type==="PAPER_SELL");
const byId=new Map();
for(const b of buys){if(!b.positionId) continue; byId.set(b.positionId,{positionId:b.positionId,mint:b.mint,symbol:b.symbol,openedAt:b.timestamp,buyEvents:1,sellEvents:0,realizedPnlSol:0});}
for(const x of sells){if(!x.positionId) continue; const r=byId.get(x.positionId)||{positionId:x.positionId,mint:x.mint,symbol:x.symbol,buyEvents:0,sellEvents:0,realizedPnlSol:0}; r.sellEvents++; r.realizedPnlSol+=Number(x.pnlSol||0); r.lastSellAt=x.timestamp; byId.set(x.positionId,r);}
const openIds=new Set(open.map(p=>p.id).filter(Boolean)); const lifecycles=[...byId.values()].map(r=>({...r,closed:!openIds.has(r.positionId)&&r.buyEvents>0,realizedPnlSol:Number(r.realizedPnlSol.toFixed(10))}));
const completed=lifecycles.filter(x=>x.closed); const pnls=completed.map(x=>x.realizedPnlSol); const wins=pnls.filter(x=>x>0), losses=pnls.filter(x=>x<0); const sum=a=>a.reduce((x,y)=>x+y,0); const gp=sum(wins), gl=Math.abs(sum(losses));
const equity=Number(s.equitySol||0), start=Number(s.startingEquitySol||1), high=Number(s.highWaterEquitySol||equity); const ret=start>0?(equity/start-1)*100:0, dd=high>0?(1-equity/high)*100:0;
const result={version:"1.1",timestamp:new Date().toISOString(),startingEquitySol:start,equitySol:equity,equityReturnPct:Number(ret.toFixed(4)),highWaterEquitySol:high,currentDrawdownPct:Number(dd.toFixed(4)),openPositions:open.length,probeEntries:buys.length,realizedSellEvents:sells.length,lifecycleTrades:lifecycles.length,completedLifecycleTrades:completed.length,winningLifecycleTrades:wins.length,losingLifecycleTrades:losses.length,winRatePct:completed.length?Number((wins.length/completed.length*100).toFixed(2)):0,grossProfitSol:Number(gp.toFixed(8)),grossLossSol:Number(gl.toFixed(8)),profitFactor:gl>0?Number((gp/gl).toFixed(4)):(gp>0?"INF_NO_LOSS_YET":0),expectancyPerLifecycleSol:completed.length?Number((sum(pnls)/completed.length).toFixed(8)):0,legacyBuyEventsWithoutPositionId:buys.filter(x=>!x.positionId).length,legacySellEventsWithoutPositionId:sells.filter(x=>!x.positionId).length,realizedPnlSol:Number(s.realizedPnlSol||0),unrealizedPnlSol:Number(s.unrealizedPnlSol||0),lifecycles};
const tmp=OUT+`.tmp-${process.pid}`; fs.writeFileSync(tmp,JSON.stringify(result,null,2)); fs.renameSync(tmp,OUT);
console.log("=== MEME ALPHA VALIDATION v1.1 LIFECYCLE ==="); console.log(`CompletedLifecycles=${completed.length}`); console.log(`SellEvents=${sells.length}`); console.log(`WinRateLifecycle=${result.winRatePct}%`); console.log(`ExpectancyLifecycle=${result.expectancyPerLifecycleSol} SOL`); console.log(`LegacySells=${result.legacySellEventsWithoutPositionId}`); console.log("LIVE_EXECUTION=DISABLED"); console.log("VALIDATION_STATUS=PASS");
