import v10 from './hub-v10-unified-entry.js';
import {telegramApiRequest} from './providers/telegram-client.js';
import {getV11Accepted,getV11History,getV11Funnel} from './v11/store.js';
import {scanMarketV11,scheduledNativeV11} from './v11/native-runtime.js';
const json=(x,s=200)=>new Response(JSON.stringify(x,null,2),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
const kb=()=>({inline_keyboard:[[{text:'📚 LỆNH ĐANG CHẠY',callback_data:'v11:live'}],[{text:'💱 FOREX',callback_data:'v11:market:forex'},{text:'🪙 CRYPTO',callback_data:'v11:market:crypto'}],[{text:'🥇 METAL',callback_data:'v11:market:metal'},{text:'📊 INDEX',callback_data:'v11:market:index'}],[{text:'🔥 V11 CHÍNH THỨC',callback_data:'v11:official'},{text:'🕘 LỊCH SỬ',callback_data:'v11:history'}],[{text:'📈 THỐNG KÊ',callback_data:'v11:stats'},{text:'🧠 3 AI ĐÁNH GIÁ',callback_data:'v11:ai:review'}],[{text:'🟨 BINANCE AUTO',callback_data:'binance'}]]});
const marketKb=m=>({inline_keyboard:[[{text:'🔍 QUÉT NGAY',callback_data:`v11:scan:${m}`},{text:'📚 LIVE',callback_data:`v11:market:${m}`}],[{text:'🔥 V11',callback_data:'v11:official'},{text:'🧠 3 AI',callback_data:'v11:ai:review'}],[{text:'🏠 HUB',callback_data:'menu'}]]});
const fmt=v=>Number.isFinite(Number(v))?Number(v).toPrecision(7):'—';
const line=x=>{const c=x.candidate||{};return `${c.side==='LONG'?'🟢 BUY':'🔴 SELL'} ${x.symbol}\n📍 ${fmt(c.entry)} • SL ${fmt(c.sl)} • TP ${fmt(c.tp)} • RR ${Number(c.rr||0).toFixed(2)}\n🧭 ${c.setup||'—'} • ${x.lifecycleStatus||'OPEN'}`};
async function send(env,id,text,markup=kb()){return telegramApiRequest(env,'sendMessage',{chat_id:id||env.TELEGRAM_CHAT_ID,text,reply_markup:markup,disable_web_page_preview:true});}
async function textFor(env,kind,market){const a=await getV11Accepted(env,market),h=await getV11History(env,market),f=await getV11Funnel(env);if(kind==='live'||kind==='official')return [`🔥 V11 ${market?market.toUpperCase(): 'CHÍNH THỨC'} • ${a.length} ACTIVE`,...a.slice(0,12).map(line)].join('\n\n');if(kind==='history')return [`🕘 V11 LỊCH SỬ • ${h.length}`,...h.slice(0,15).map(x=>`${x.outcome==='WIN'?'✅':x.outcome==='LOSS'?'❌':'⚪'} ${x.symbol} • ${x.outcome} • close ${fmt(x.closePrice)}`)].join('\n');if(kind==='stats'){const wins=h.filter(x=>x.outcome==='WIN').length,loss=h.filter(x=>x.outcome==='LOSS').length,n=wins+loss;return `📈 V11 THỐNG KÊ\nClosed: ${n} • WIN ${wins} • LOSS ${loss}\nWR: ${n?(wins/n*100).toFixed(1):'—'}%\nChỉ tính outcome thực tế.`;}if(kind==='ai')return `🧠 3 AI ĐÁNH GIÁ — THEO YÊU CẦU\n━━━━━━━━━━━━\nKhông nằm trong pipeline Signal. Chỉ chạy khi bạn bấm nút này.\nDeepSeek = critic/edge/risk\nClaude = context/regime\nCodex/ChatGPT = logic/toán/consistency\n\nSignal V11 tự động không chờ AI và không bị AI chặn. AI review không có execution authority.`;return `🚀 UNIFIED TRADING HUB • SIGNAL V11\n━━━━━━━━━━━━\n☁️ Cloudflare = runtime/scheduler/state\n📡 Twelve Data + venue feeds = market data\n🧬 Profile riêng từng instrument\n🎯 Structure SL • forward-liquidity TP\n🔍 Signal tự quét không cần AI\n🧠 3 AI chỉ chạy khi bấm nút\n🟨 Binance Auto tách execution authority.`;}
function auth(u,env){const got=String(u?.callback_query?.from?.id??u?.message?.from?.id??''),want=String(env.TELEGRAM_ALLOWED_USER_ID||env.TELEGRAM_CHAT_ID||'');return !want||got===want;}
export default {async fetch(req,env,ctx){const url=new URL(req.url);if(url.pathname==='/v11/status')return json({ok:true,version:'V11',telegram:true,runtime:'CLOUDFLARE_NATIVE',scheduler:'V11_NATIVE',signalAiRequired:false,manualThreeAiReview:true,compatibility:'V10_FETCH_ONLY'});if(url.pathname==='/v11/scan'&&req.method==='POST'){const body=await req.json().catch(()=>({})),market=String(body.market||'');if(!['crypto','forex','metal','index'].includes(market))return json({ok:false,error:'INVALID_MARKET'},400);return json(await scanMarketV11(env,market));}if(url.pathname==='/telegram/webhook'&&req.method==='POST'){let u;try{u=await req.clone().json()}catch{return json({ok:false},400)}if(!auth(u,env))return json({ok:false},403);const cb=String(u?.callback_query?.data||''),msg=String(u?.message?.text||'');if(cb.startsWith('v11:')||msg==='/start'||msg==='/v11'||cb==='menu'){const id=u?.callback_query?.message?.chat?.id??u?.message?.chat?.id??env.TELEGRAM_CHAT_ID;let kind='menu',market=null;if(cb.startsWith('v11:scan:')){market=cb.split(':')[2];await send(env,id,`⏳ V11 đang quét ${market.toUpperCase()} bằng profile riêng từng sản phẩm…`,marketKb(market));const r=await scanMarketV11(env,market);await send(env,id,`🔍 V11 ${market.toUpperCase()}\nApproved: ${r.approved||0}\nWatch: ${r.watch||0}\nRejected: ${r.rejected||0}\n${r.status}`,marketKb(market));return json({ok:true,owner:'V11',scan:r});}if(cb.startsWith('v11:market:')){market=cb.split(':')[2];kind='live';}else if(cb==='v11:live')kind='live';else if(cb==='v11:official')kind='official';else if(cb==='v11:history')kind='history';else if(cb==='v11:stats')kind='stats';else if(cb==='v11:ai:review')kind='ai';await send(env,id,await textFor(env,kind,market),market?marketKb(market):kb());return json({ok:true,owner:'V11'});}}return v10.fetch(req,env,ctx);},async scheduled(event,env,ctx){return scheduledNativeV11(event,env,ctx);}};
