import legacyHub from "./hub-v77171.js";
import baseEngine from "./engine-v77168.js";
import {telegramApiRequest} from "./providers/telegram-client.js";
import {recordSignalV10Candidates,getSignalV10Accepted,getSignalV10CouncilState,handleSignalV10Api,refreshSignalV10Lifecycle} from "./signal-v10-council.js";
import {getSignalV10Stats,formatMarketStats,refreshSignalV10Learning} from "./signal-v10-learning.js";

const VERSION="V10";
const SERVICE="Trading Signal Only V10 • 3-AI Lifecycle Intelligence";
const SCHEDULE_KEY="v10:signal:schedule";
const GROUPS=["crypto","forex","metal","index"];
const INTERVAL_MS={crypto:5*60e3,forex:10*60e3,metal:10*60e3,index:15*60e3};
const json=(body,status=200)=>new Response(JSON.stringify(body,null,2),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
async function tg(env,method,payload){return telegramApiRequest(env,method,payload);}
async function send(env,chatId,text,kb){return tg(env,"sendMessage",{chat_id:chatId||env.TELEGRAM_CHAT_ID,text,reply_markup:kb,disable_web_page_preview:true});}
function verifyTelegram(req,env){return !env.TELEGRAM_WEBHOOK_SECRET||req.headers.get("x-telegram-bot-api-secret-token")===env.TELEGRAM_WEBHOOK_SECRET;}
function authorized(u,env){const got=String(u?.callback_query?.from?.id??u?.message?.from?.id??"");const want=String(env.TELEGRAM_ALLOWED_USER_ID||env.TELEGRAM_CHAT_ID||"");return !want||got===want;}
const name=g=>g==="forex"?"💱 FOREX":g==="crypto"?"🪙 CRYPTO":g==="metal"?"🥇 METAL":"📊 INDEX";
const fmt=v=>{const n=Number(v);if(!Number.isFinite(n))return "—";if(Math.abs(n)>=1000)return n.toFixed(2);if(Math.abs(n)>=10)return n.toFixed(4);if(Math.abs(n)>=1)return n.toFixed(5);return n.toPrecision(6);};
const mainKb=()=>({inline_keyboard:[[{text:"📡 SIGNAL V10",callback_data:"signal"}],[{text:"💱 Forex",callback_data:"market:forex"},{text:"🪙 Crypto",callback_data:"market:crypto"}],[{text:"🥇 Metal",callback_data:"market:metal"},{text:"📊 Index",callback_data:"market:index"}],[{text:"📈 Win-rate",callback_data:"v10:stats"},{text:"🧠 3 AI",callback_data:"v10:council"}],[{text:"🟨 BINANCE AUTO",callback_data:"binance"}],[{text:"••• Evidence",callback_data:"hub:more"}]]});
const signalKb=()=>({inline_keyboard:[[{text:"💱 Forex",callback_data:"market:forex"},{text:"🪙 Crypto",callback_data:"market:crypto"}],[{text:"🥇 Metal",callback_data:"market:metal"},{text:"📊 Index",callback_data:"market:index"}],[{text:"🔥 V10 Signals",callback_data:"signal:top"}],[{text:"📈 Win-rate",callback_data:"v10:stats"},{text:"🧠 3 AI",callback_data:"v10:council"}],[{text:"⬅️ Hub",callback_data:"menu"}]]});
const marketKb=g=>({inline_keyboard:[[{text:"🔍 Quét mới",callback_data:`signal:scan:${g}`},{text:"📚 V10 Live",callback_data:`live:${g}`}],[{text:"📈 Stats",callback_data:`v10:stats:${g}`},{text:"🎯 Từng Symbol",callback_data:`symbols:${g}:0`}],[{text:"⬅️ Signal",callback_data:"signal"},{text:"🏠 Hub",callback_data:"menu"}]]});
const backKb=g=>({inline_keyboard:[[{text:"🔄 Quét lại",callback_data:`signal:scan:${g}`},{text:"📚 V10 Live",callback_data:`live:${g}`}],[{text:"📈 Stats",callback_data:`v10:stats:${g}`}],[{text:"⬅️ Market",callback_data:`market:${g}`},{text:"🏠 Hub",callback_data:"menu"}]]});
async function engine(path,env){const r=await baseEngine.fetch(new Request(`https://internal${path}`,{method:"GET"}),env);try{return await r.json();}catch{return null;}}
async function lifecycleQuote(symbol,_market,env){const a=await engine(`/analyze?symbol=${encodeURIComponent(symbol)}`,env);const price=Number(a?.analysisQuote?.price??a?.quote?.price??a?.currentPrice);if(!(price>0))throw new Error(`V10 quote unavailable ${symbol}`);return {price,source:a?.analysisQuote?.source||a?.quote?.source||a?.source||"compatibility-engine",fresh:a?.analysisQuote?.fresh!==false&&a?.quote?.fresh!==false};}
function candidateText(g,r,added=[]){if(r?.status==="BUSY")return `${name(g)} • V10\n━━━━━━━━━━━━\n⏳ Scanner đang bận vòng khác. V10 không dùng snapshot cũ; lượt này sẽ được thử lại.`;if(r?.status==="RATE_BUDGET_WAIT")return `${name(g)} • V10\n━━━━━━━━━━━━\n⏱ Data quota đang hồi. Không phát signal từ dữ liệu cũ.`;const L=[`${name(g)} • V10 SCAN`,`━━━━━━━━━━━━`,`🔍 Coverage ${r?.broadOk||0}/${r?.requested||0} • Deep ${r?.deepOk||0}/${r?.deepRequested||0}`];if(!added.length)L.push("","⚪ Chưa có candidate vượt V10 pre-gate.");for(const x of added.slice(0,3)){const c=x.candidate,L2=x.preGate?.pass?"🧠 đang chờ 3 AI":"⛔ pre-gate reject";L.push("",`${c.side==="LONG"?"🟢 BUY":"🔴 SELL"} ${c.symbol} • ${L2}`,`📍 ${fmt(c.entry)} • SL ${fmt(c.sl)} • TP ${fmt(c.tp)}`,`⭐ Quality ${c.qualityScore}/100${c.rr?` • RR ${Number(c.rr).toFixed(2)}`:""}`,c.symbolStats?.n?`📈 WR V10 ${c.symbolStats.observedWinRatePct}% • n=${c.symbolStats.n}`:"📈 WR V10: chưa đủ mẫu");if(!x.preGate?.pass)L.push(`🚧 ${x.preGate?.reasons?.join(", ")}`);}L.push("","Candidate chưa phải signal chính thức cho tới khi 3 AI review xong.");return L.join("\n");}
function acceptedText(rows,g=null){const L=[`🔥 V10 SIGNAL${g?` • ${name(g)}`:"S"}`,"━━━━━━━━━━━━"];if(!rows.length)L.push("⚪ Chưa có signal 3-AI còn hiệu lực.");for(const x of rows.slice(0,8)){const c=x.candidate,s=x.consensus,st=c.symbolStats||{};L.push("",`${c.side==="LONG"?"🟢 BUY":"🔴 SELL"} ${c.symbol} • ${c.market.toUpperCase()}`,`📍 ${fmt(c.entry)} • SL ${fmt(c.sl)} • TP ${fmt(c.tp)}`,`⭐ Q ${c.qualityScore} • 🧠 ${s.same}/3 • Conf ${s.directionalConfidence}%`,st.n?`📈 WR V10 ${st.observedWinRatePct}% • n=${st.n}${st.avgR==null?"":` • AvgR ${st.avgR}`}`:"📈 WR V10: chưa đủ mẫu",`🔄 Lifecycle: ${x.lifecycleStatus||"OPEN"}${x.lastPrice?` • px ${fmt(x.lastPrice)}`:""}`);}L.push("","Signal-only • không execution authority.");return L.join("\n");}
function councilText(s){const h=s.workerHealth||{},age=h.reportedAt?Math.max(0,Math.round((Date.now()-Number(h.reportedAt))/1000)):null,L=["🧠 V10 • THREE-AI COUNCIL","━━━━━━━━━━━━",`⏳ Pending: ${s.pending||0}`,`✅ Accepted live: ${s.accepted||0}`,`🖥 VPS worker: ${h.status||"UNKNOWN"}${age!=null?` • age ${age}s`:""}`];if(h.providers){for(const n of ["claude","deepseek","codex"]){const p=h.providers[n]||{};L.push(`${String(p.status||"UNKNOWN")==="OK"?"🟢":"🟠"} ${n}: ${p.status||"UNKNOWN"}${p.latencySeconds!=null?` • ${p.latencySeconds}s`:""}`);}}L.push("");for(const r of s.recent||[]){const x=r.consensus||{};L.push(`${r.candidate?.symbol||"—"} • ${x.pass?"✅ PASS":"⚪ WAIT"} • ${x.reason||"—"} • ${x.directionalConfidence??0}%`);}L.push("","Claude = context/regime • DeepSeek = adversarial edge • Codex = math/execution.","2/3 cùng hướng + không có AI đối hướng; cả 3 phải trả lời OK.");return L.join("\n");}
async function statsText(env,g=null){const s=await getSignalV10Stats(env,{market:g});if(!g)return formatMarketStats(s);const x=s.markets?.[g]||{},top=(s.topSymbols||[]).filter(z=>z.n>=3).slice(0,5),L=[`📈 V10 • ${name(g)} STATS`,`━━━━━━━━━━━━`,`Closed samples: ${x.n||0}`,`Observed WR: ${x.observedWinRatePct==null?"—":x.observedWinRatePct+"%"}`,`Bayesian WR: ${x.bayesianWinRatePct==null?"—":x.bayesianWinRatePct+"%"}`,`LB80: ${x.wilsonLowerPct==null?"—":x.wilsonLowerPct+"%"}`,`AvgR: ${x.avgR??"—"}`,`Maturity: ${x.label||"LOW_SAMPLE"}`];if(top.length){L.push("","🎯 Symbol V10 nhiều mẫu:");for(const z of top)L.push(`• ${z.symbol} • WR ${z.observedWinRatePct}% • n=${z.n} • AvgR ${z.avgR??"—"}`);}L.push("","Nguồn chỉ gồm Signal V10 đã đóng; không trộn V77/V78.","Không phải xác suất thắng tương lai.");return L.join("\n");}

async function handleTelegramV10(req,env){if(!verifyTelegram(req,env))return json({ok:false,error:"invalid telegram secret"},403);let u;try{u=await req.clone().json();}catch{return null;}const cb=String(u?.callback_query?.data||""),text=String(u?.message?.text||"").trim(),chatId=u?.callback_query?.message?.chat?.id??u?.message?.chat?.id??env.TELEGRAM_CHAT_ID;if(!authorized(u,env))return null;const v10=cb==="menu"||cb==="signal"||cb==="signal:top"||cb.startsWith("market:")||cb.startsWith("signal:scan:")||cb.startsWith("live:")||cb.startsWith("v10:")||text==="/signal10"||text==="/start"||text==="/menu";if(!v10)return null;if(u?.callback_query?.id)tg(env,"answerCallbackQuery",{callback_query_id:u.callback_query.id,text:"V10"}).catch(()=>{});
  if(cb==="menu"||text==="/start"||text==="/menu"){await send(env,chatId,["◈ TRADING HUB • V10","━━━━━━━━━━━━","📡 SIGNAL ONLY + 3-AI LIFECYCLE","🟨 Binance Auto là project riêng","","V10 chỉ phát signal sau pre-gate + hội đồng 3 AI."].join("\n"),mainKb());return json({ok:true,version:VERSION});}
  if(cb==="signal"||text==="/signal10"){await send(env,chatId,["📡 SIGNAL ONLY • V10","━━━━━━━━━━━━","Market scan → Quality Gate → 3 AI → Signal → TP/SL → Learning.","","Nhiều candidate có thể được quét; Telegram chỉ phát những signal vượt toàn bộ V10 gate."].join("\n"),signalKb());return json({ok:true});}
  if(cb==="signal:top"){await send(env,chatId,acceptedText(await getSignalV10Accepted(env,{limit:12})),signalKb());return json({ok:true});}
  if(cb==="v10:stats"){await send(env,chatId,await statsText(env),signalKb());return json({ok:true});}
  if(cb.startsWith("v10:stats:")){const g=cb.split(":")[2];await send(env,chatId,await statsText(env,g),marketKb(g));return json({ok:true});}
  if(cb==="v10:council"){await send(env,chatId,councilText(await getSignalV10CouncilState(env)),signalKb());return json({ok:true});}
  if(cb.startsWith("market:")){const g=cb.split(":")[1];await send(env,chatId,[`${name(g)} • V10`,`━━━━━━━━━━━━`,`🔍 Quét candidate`,"🧠 3 AI review",`📈 Learning riêng cho ${g}`,"📚 Chỉ hiển thị signal V10 còn hiệu lực"].join("\n"),marketKb(g));return json({ok:true});}
  if(cb.startsWith("signal:scan:")){const g=cb.split(":")[2];await send(env,chatId,`⏳ ${name(g)} • V10 đang quét…`);const r=await engine(`/run-now?group=${g}`,env),added=r?.ok?await recordSignalV10Candidates(env,g,r?.analyses||[],{scanId:r?.scanId,trigger:"HUB_MANUAL_V10"}):[];await send(env,chatId,candidateText(g,r,added),backKb(g));return json({ok:true,group:g,added:added.length,status:r?.status||null});}
  if(cb.startsWith("live:")){const g=cb.split(":")[1];await send(env,chatId,acceptedText(await getSignalV10Accepted(env,{market:g,limit:12}),g),marketKb(g));return json({ok:true});}
  return null;
}

async function runDueScan(env,scheduledTime){const state=await env.TRADING_STATE?.get(SCHEDULE_KEY,"json")||{last:{}},t=Number(scheduledTime||Date.now());let pick=null,over=-Infinity;for(const g of GROUPS){const last=Number(state.last?.[g]||0),due=t-last-INTERVAL_MS[g];if(due>=0&&due>over){pick=g;over=due;}}if(!pick)return {status:"NO_DUE_SCAN"};const r=await engine(`/run-now?group=${pick}`,env);if(!r?.ok||["BUSY","RATE_BUDGET_WAIT"].includes(String(r?.status||"")))return {status:r?.status||"SCAN_FAILED",group:pick,added:0};const added=await recordSignalV10Candidates(env,pick,r?.analyses||[],{scanId:r?.scanId,trigger:"AUTO_CRON_V10"});state.last={...(state.last||{}),[pick]:t};state.updatedAt=Date.now();await env.TRADING_STATE?.put(SCHEDULE_KEY,JSON.stringify(state));return {status:"SCANNED",group:pick,added:added.length};}
function silentLifecycleEnv(env){return {...env,TELEGRAM_BOT_TOKEN:"",TELEGRAM_CHAT_ID:""};}

export default {
  async fetch(req,env,ctx){const api=await handleSignalV10Api(req,env);if(api)return api;const tgResp=new URL(req.url).pathname==="/telegram/webhook"?await handleTelegramV10(req,env):null;if(tgResp)return tgResp;const r=await legacyHub.fetch(req,env,ctx);if(new URL(req.url).pathname!=="/status")return r;let b;try{b=await r.clone().json();}catch{return r;}const council=await getSignalV10CouncilState(env);return json({...b,version:VERSION,service:SERVICE,signalOnlyV10:true,threeAiCouncil:true,vpsCouncilStatus:council.workerHealth?.status||"UNKNOWN",learningLifecycle:true,learningSource:"V10_ONLY_HISTORY",winRateSemantics:"OBSERVED_CLOSED_SIGNAL_STATS_NOT_PREDICTIVE_PROBABILITY",legacyEngineRole:"DATA_SCANNER_COMPATIBILITY_ONLY"},r.status);},
  async scheduled(event,env,ctx){ctx.waitUntil((async()=>{await refreshSignalV10Lifecycle(env,(symbol,market)=>lifecycleQuote(symbol,market,env));await refreshSignalV10Learning(env);const d=new Date(Number(event?.scheduledTime||Date.now()));const lifecycleTime=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),d.getUTCHours(),3,0);baseEngine.scheduled?.({scheduledTime:lifecycleTime},silentLifecycleEnv(env),ctx);await runDueScan(env,event?.scheduledTime||Date.now());})().catch(e=>console.error("V10_CRON",e)));}
};
