import baseEngine from "./engine-v77168.js";

const VERSION="V77.18.20";
const SERVICE="Trading V77.18.20 ChatGPT Primary + Claude Reviewer Hub";
const HYRO_PROFILE_KEY="v7717:hyro:profile",HYRO_DRAFT_KEY="v77171:hyro:draft";
const json=(body,status=200)=>new Response(JSON.stringify(body,null,2),{status,headers:{"content-type":"application/json; charset=utf-8"}});
async function telegram(env,method,payload){if(!env.TELEGRAM_BOT_TOKEN)throw new Error("TELEGRAM_BOT_TOKEN missing");const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),p=await r.json();if(!p.ok)throw new Error(p.description||"Telegram error");return p;}
const sendText=(env,text,chatId,reply_markup)=>telegram(env,"sendMessage",{chat_id:chatId,text,reply_markup,disable_web_page_preview:true});
function baseKeyboard(){return {inline_keyboard:[[{text:"📡 Signal",callback_data:"signal"},{text:"🏦 Prop",callback_data:"prop"}],[{text:"👤 Cá nhân",callback_data:"personal"},{text:"🔎 Symbol",callback_data:"symbols"}],[{text:"📊 Status",callback_data:"status"},{text:"📚 Orders",callback_data:"books"}],[{text:"🧠 Claude Reviewer",callback_data:"claude:status"}]]};}
function propKeyboard(configured=false){return {inline_keyboard:[[{text:configured?"📊 Hyro":"⚙️ Thiết lập",callback_data:configured?"prop:hyro":"prop:setup"},{text:"🛡 Risk",callback_data:"prop:risk"}],[{text:"📚 Lệnh",callback_data:"prop:orders"},{text:"🔌 API",callback_data:"prop:connect"}],[{text:"⚙️ Cấu hình",callback_data:"prop:setup"},{text:"⬅️ Menu",callback_data:"menu"}]]};}
const phaseKeyboard=()=>({inline_keyboard:[[{text:"🎯 Challenge",callback_data:"prop:wiz:phase:CHALLENGE"},{text:"💰 Funded",callback_data:"prop:wiz:phase:FUNDED"}],[{text:"⬅️ Prop",callback_data:"prop"}]]});
const drawdownKeyboard=()=>({inline_keyboard:[[{text:"📉 Standard / Trailing",callback_data:"prop:wiz:dd:STANDARD_TRAILING"},{text:"🛟 Swing / Static",callback_data:"prop:wiz:dd:SWING_STATIC"}],[{text:"⬅️ Phase",callback_data:"prop:setup"}]]});
const stepKeyboard=()=>({inline_keyboard:[[{text:"1️⃣ One-Step",callback_data:"prop:wiz:step:ONE_STEP"},{text:"2️⃣ Two-Step",callback_data:"prop:wiz:step:TWO_STEP"}],[{text:"⬅️ DD",callback_data:"prop:wiz:back:dd"}]]});
function verifyTelegram(req,env){return !env.TELEGRAM_WEBHOOK_SECRET||req.headers.get("x-telegram-bot-api-secret-token")===env.TELEGRAM_WEBHOOK_SECRET;}
async function getHyroProfile(env){try{return await env.TRADING_STATE?.get(HYRO_PROFILE_KEY,"json");}catch{return null;}}
async function getDraft(env){try{return await env.TRADING_STATE?.get(HYRO_DRAFT_KEY,"json")||{};}catch{return {};}}
async function saveDraft(env,d){await env.TRADING_STATE?.put(HYRO_DRAFT_KEY,JSON.stringify({...d,updatedAt:Date.now()}),{expirationTtl:1800});}
async function clearDraft(env){try{await env.TRADING_STATE?.delete(HYRO_DRAFT_KEY);}catch{}}
function buildHyroProfile({phase,drawdownType,program},referenceSize=5000){const size=Math.max(1,Number(referenceSize)||5000),isOne=program!=="TWO_STEP",dailyPct=isOne?4:5,maxLossPct=isOne?6:10,official={dailyDrawdownPct:dailyPct,dailyDrawdownUsd:size*dailyPct/100,maxLossPct,maxLossUsd:size*maxLossPct/100,maxRealizedLossPerTradePct:3,maxRealizedLossPerTradeUsd:size*.03},internal={dailyCautionUsd:Math.round(size*.022),dailyDefenseUsd:Math.round(size*.027),dailyHardStopUsd:Math.round(size*.029),maxSingleWorstLossUsd:Math.round(size*.02),maxCombinedOpenRiskUsd:Math.round(size*(phase==="FUNDED"?.02:.024)),normalRiskUsd:Math.round(size*(phase==="FUNDED"?.007:.008)),aPlusRiskUsd:Math.round(size*(phase==="FUNDED"?.010:.011)),givebackGuard:true,slRequiredByBot:true},challenge=phase==="CHALLENGE"?{profitTargetPhase1Pct:10,profitTargetPhase1Usd:size*.10,profitTargetPhase2Pct:isOne?null:5,profitTargetPhase2Usd:isOne?null:size*.05,minTradingDays:5,profitDistributionMaxDayPct:40}:null,funded=phase==="FUNDED"?{profitDistributionRule:false,maxMarginExposurePct:25,maxMarginExposureUsd:size*.25,maxNotionalMultiple:2,maxNotionalUsd:size*2,internalMarginCapUsd:size*.225,internalNotionalCapUsd:size*1.8}:null;return {provider:"HYROTRADER",phase,accountSize:size,capitalMode:"LIVE_EQUITY_DYNAMIC",program:isOne?"ONE_STEP":"TWO_STEP",drawdownType,official,internal,challenge,funded,configuredAt:Date.now(),connected:false,autoTrade:false};}
async function commitProfile(env,d){const old=await getHyroProfile(env),p=buildHyroProfile(d,old?.accountSize||5000);await env.TRADING_STATE?.put(HYRO_PROFILE_KEY,JSON.stringify(p));await clearDraft(env);return p;}
const phaseName=p=>p?.phase==="FUNDED"?"FUNDED":"CHALLENGE",ddName=p=>p?.drawdownType==="SWING_STATIC"?"Swing/Static":"Standard/Trailing",programName=p=>p?.program==="TWO_STEP"?"Two-Step":"One-Step";
function overviewText(p){return !p?"🏦 HyroTrader\nChưa cấu hình.":`🏦 HyroTrader • ${phaseName(p)}\n${programName(p)} • ${ddName(p)}\n💰 Vốn: tự đọc từ API\n🛡 Risk: tự scale theo equity`;}
function riskText(p){return !p?"🛡 Hyro Risk\nChưa cấu hình.":`🛡 Hyro • ${phaseName(p)}\nVốn/risk/caps: tự scale theo equity\nSL bắt buộc • telemetry fail = khóa lệnh`;}
async function handleWizard(cb,env,chatId){let d=await getDraft(env);if(cb==="prop:setup"){d={};await saveDraft(env,d);await sendText(env,"⚙️ Hyro 1/3 • Chọn giai đoạn",chatId,phaseKeyboard());return true;}if(cb?.startsWith("prop:wiz:phase:")){d={phase:cb.split(":").at(-1)};await saveDraft(env,d);await sendText(env,"⚙️ Hyro 2/3 • Chọn drawdown",chatId,drawdownKeyboard());return true;}if(cb?.startsWith("prop:wiz:dd:")){d={...d,drawdownType:cb.split(":").at(-1)};await saveDraft(env,d);if(d.phase==="FUNDED"){const old=await getHyroProfile(env),p=await commitProfile(env,{...d,program:old?.program||"ONE_STEP"});await sendText(env,"✅ Đã lưu\n"+overviewText(p),chatId,propKeyboard(true));}else await sendText(env,"⚙️ Hyro 3/3 • Chọn chương trình",chatId,stepKeyboard());return true;}if(cb?.startsWith("prop:wiz:step:")){const p=await commitProfile(env,{...d,program:cb.split(":").at(-1)});await sendText(env,"✅ Đã lưu\n"+overviewText(p),chatId,propKeyboard(true));return true;}if(cb==="prop:wiz:back:dd"){await sendText(env,"⚙️ Chọn lại drawdown",chatId,drawdownKeyboard());return true;}return false;}
async function handleHyroTelegram(req,env){if(!verifyTelegram(req,env))return json({ok:false,error:"invalid telegram secret"},403);let u;try{u=await req.clone().json();}catch{return null;}const chatId=u?.callback_query?.message?.chat?.id??u?.message?.chat?.id??env.TELEGRAM_CHAT_ID,cb=u?.callback_query?.data,text=String(u?.message?.text||""),handled=cb==="prop"||cb==="prop:setup"||cb==="prop:hyro"||cb==="prop:orders"||cb==="prop:risk"||cb==="prop:connect"||cb?.startsWith("prop:wiz:")||cb==="menu"||text==="/start"||text==="/menu";if(!handled)return null;if(u?.callback_query?.id)telegram(env,"answerCallbackQuery",{callback_query_id:u.callback_query.id}).catch(()=>{});if(cb==="menu"||text==="/start"||text==="/menu"){await sendText(env,"🏠 Trading Hub",chatId,baseKeyboard());return json({ok:true,version:VERSION});}if(await handleWizard(cb,env,chatId))return json({ok:true,version:VERSION,wizard:true});const p=await getHyroProfile(env);if(cb==="prop"||cb==="prop:hyro")await sendText(env,overviewText(p),chatId,propKeyboard(!!p));else if(cb==="prop:risk")await sendText(env,riskText(p),chatId,propKeyboard(!!p));else if(cb==="prop:orders")await sendText(env,"📚 Hyro Orders\nXem vị thế thật tại PROP → Vị thế.",chatId,propKeyboard(!!p));else if(cb==="prop:connect")await sendText(env,"🔌 Hyro API\nCredentials chỉ đặt ở Cloudflare Secret.\nRuntime tự reconnect/refresh.",chatId,propKeyboard(!!p));return json({ok:true,version:VERSION,hyroConfigured:!!p});}
async function patchedStatus(req,env){const r=await baseEngine.fetch(req,env);let p;try{p=await r.clone().json();}catch{return r;}const hp=await getHyroProfile(env);return json({...p,version:VERSION,service:SERVICE,prop:{provider:"HYROTRADER",phase:hp?.phase||null,program:hp?.program||null,capitalMode:"LIVE_EQUITY_DYNAMIC",drawdownType:hp?.drawdownType||null,riskShell:hp?"ACTIVE":"AWAITING_WIZARD"}},r.status);}
export default {async fetch(req,env,ctx){const u=new URL(req.url),path=u.pathname.replace(/\/$/,"")||"/";if(path==="/status")return patchedStatus(req,env);if(path==="/prop/hyro/profile")return json({ok:true,version:VERSION,configured:!!(await getHyroProfile(env)),profile:await getHyroProfile(env)});if(path==="/telegram/menu"){await sendText(env,`🤖 Trading Hub ${VERSION}`,env.TELEGRAM_CHAT_ID,baseKeyboard());return json({ok:true,version:VERSION});}if(path==="/telegram/webhook"&&req.method==="POST"){const handled=await handleHyroTelegram(req,env);if(handled)return handled;}return baseEngine.fetch(req,env,ctx);},async scheduled(controller,env,ctx){return baseEngine.scheduled(controller,env,ctx);}};
