import v10 from './hub-v10-unified-entry.js';
import {telegramApiRequest} from './providers/telegram-client.js';
import {getV11Accepted,getV11History,getV11Funnel} from './v11/store.js';
const json=(x,s=200)=>new Response(JSON.stringify(x,null,2),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
const kb=()=>({inline_keyboard:[[{text:'📚 LỆNH ĐANG CHẠY',callback_data:'v11:live'}],[{text:'💱 FOREX',callback_data:'v11:market:forex'},{text:'🪙 CRYPTO',callback_data:'v11:market:crypto'}],[{text:'🥇 METAL',callback_data:'v11:market:metal'},{text:'📊 INDEX',callback_data:'v11:market:index'}],[{text:'🔥 V11 CHÍNH THỨC',callback_data:'v11:official'},{text:'🕘 LỊCH SỬ',callback_data:'v11:history'}],[{text:'📈 THỐNG KÊ',callback_data:'v11:stats'},{text:'🧠 3 AI ĐÁNH GIÁ',callback_data:'v11:ai:review'}],[{text:'🟨 BINANCE AUTO',callback_data:'binance'}]]});
const fmt=v=>Number.isFinite(Number(v))?Number(v).toPrecision(7):'—';
const line=x=>{const c=x.candidate||{};return `${c.side==='LONG'?'🟢 BUY':'🔴 SELL'} ${x.symbol}\n📍 ${fmt(c.entry)} • SL ${fmt(c.sl)} • TP ${fmt(c.tp)} • RR ${Number(c.rr||0).toFixed(2)}\n🧭 ${c.setup||'—'} • ${x.lifecycleStatus||'OPEN'}`};
async function send(env,id,text){return telegramApiRequest(env,'sendMessage',{chat_id:id||env.TELEGRAM_CHAT_ID,text,reply_markup:kb(),disable_web_page_preview:true});}
async function textFor(env,kind,market){const a=await getV11Accepted(env,market),h=await getV11History(env,market),f=await getV11Funnel(env);if(kind==='live'||kind==='official')return [`🔥 V11 ${market?market.toUpperCase(): 'CHÍNH THỨC'} • ${a.length} ACTIVE`,...a.slice(0,12).map(line)].join('\n\n');if(kind==='history')return [`🕘 V11 LỊCH SỬ • ${h.length}`,...h.slice(0,15).map(x=>`${x.outcome==='WIN'?'✅':x.outcome==='LOSS'?'❌':'⚪'} ${x.symbol} • ${x.outcome} • close ${fmt(x.closePrice)}`)].join('\n');if(kind==='stats'){const wins=h.filter(x=>x.outcome==='WIN').length,loss=h.filter(x=>x.outcome==='LOSS').length,n=wins+loss;return `📈 V11 THỐNG KÊ\nClosed: ${n} • WIN ${wins} • LOSS ${loss}\nWR: ${n?(wins/n*100).toFixed(1):'—'}%\nChỉ tính outcome thực tế.`;}if(kind==='ai')return `🧠 3 AI ĐÁNH GIÁ — THỦ CÔNG\n━━━━━━━━━━━━\nNút này KHÔNG nằm trong luồng Signal tự động.\n\nKhi bấm, hệ thống tạo một yêu cầu đánh giá toàn thị trường độc lập cho:\n• DeepSeek — phản biện/edge/risk\n• Claude — context/regime\n• Codex/ChatGPT — logic/toán/consistency\n\nSignal V11 bình thường vẫn tự quét bằng data + instrument profile + Entry/SL/TP + hard gates và KHÔNG chờ AI.\n\nTrạng thái runtime hiện tại:\n• DeepSeek API: có thể gọi tự động\n• Claude Max / ChatGPT Plus: cần bridge/phiên tương tác tương ứng; không giả là API nền.\n\nYêu cầu 3-AI không được tự sửa source và không được thay đổi signal đã phát.`;return `🚀 UNIFIED TRADING HUB • SIGNAL V11\n━━━━━━━━━━━━\nSignal tự động = data + profile từng sản phẩm + Entry/SL/TP + hard safety.\n🧠 3 AI = công cụ đánh giá toàn thị trường theo yêu cầu, tách khỏi signal pipeline.\nCloudflare runtime • Twelve Data Grow 55.`;}
function auth(u,env){const got=String(u?.callback_query?.from?.id??u?.message?.from?.id??''),want=String(env.TELEGRAM_ALLOWED_USER_ID||env.TELEGRAM_CHAT_ID||'');return !want||got===want;}
export default {async fetch(req,env,ctx){const url=new URL(req.url);if(url.pathname==='/v11/status')return json({ok:true,version:'V11',telegram:true,runtime:'CLOUDFLARE',signalAiRequired:false,manualThreeAiReview:true,compatibility:'V10_LEGACY_TRACKING'});if(url.pathname==='/telegram/webhook'&&req.method==='POST'){let u;try{u=await req.clone().json()}catch{return json({ok:false},400)}if(!auth(u,env))return json({ok:false},403);const cb=String(u?.callback_query?.data||''),msg=String(u?.message?.text||'');if(cb.startsWith('v11:')||msg==='/start'||msg==='/v11'||cb==='menu'){const id=u?.callback_query?.message?.chat?.id??u?.message?.chat?.id??env.TELEGRAM_CHAT_ID;let kind='menu',market=null;if(cb.startsWith('v11:market:')){market=cb.split(':')[2];kind='live';}else if(cb==='v11:live')kind='live';else if(cb==='v11:official')kind='official';else if(cb==='v11:history')kind='history';else if(cb==='v11:stats')kind='stats';else if(cb==='v11:ai:review')kind='ai';await send(env,id,await textFor(env,kind,market));return json({ok:true,owner:'V11'});}}return v10.fetch(req,env,ctx);},async scheduled(event,env,ctx){return v10.scheduled(event,env,ctx);}};
