import baseEngine from "./engine-v77168.js";
import {loadHubUxTuning,getHubUxState} from "./hub-ux-tuning.js";
import {telegramApiRequest} from "./providers/telegram-client.js";
import {getSignalDecisionEvidence} from "./providers/decision-evidence.js";
import {buildEntryIntelligenceShadow,getEntryIntelligenceShadow} from "./providers/entry-intelligence.js";
import {isClaudeApiEnabled} from "./providers/anthropic-client.js";

const VERSION="V78.027",UI_REV="HUB-R14-SIGNAL-ONLY",SERVICE="Trading Signal Hub • Entry Intelligence";
const json=(body,status=200)=>new Response(JSON.stringify(body,null,2),{status,headers:{"content-type":"application/json; charset=utf-8"}});

async function telegram(env,method,payload){if(!env.TELEGRAM_BOT_TOKEN)throw new Error("TELEGRAM_BOT_TOKEN missing");const p=await telegramApiRequest(env,method,payload);if(!p.ok)throw new Error(p.description||"Telegram error");return p;}
const sendText=(env,text,chatId,reply_markup)=>telegram(env,"sendMessage",{chat_id:chatId,text,reply_markup,disable_web_page_preview:true});
function verifyTelegram(req,env){return !env.TELEGRAM_WEBHOOK_SECRET||req.headers.get("x-telegram-bot-api-secret-token")===env.TELEGRAM_WEBHOOK_SECRET;}

function mainKeyboard(){return {inline_keyboard:[[{text:"📡 SIGNAL CENTER",callback_data:"signal"}],[{text:"💱 Forex",callback_data:"market:forex"},{text:"🪙 Crypto",callback_data:"market:crypto"}],[{text:"🥇 Metal",callback_data:"market:metal"},{text:"📊 Index Cash",callback_data:"market:index"}],[{text:"🧭 Entry Intel",callback_data:"intel"},{text:"📊 Coverage",callback_data:"intel:coverage"}],[{text:"••• Hệ thống",callback_data:"hub:more"}]]};}
const moreKeyboard=()=>({inline_keyboard:[[{text:"🩺 Hệ thống",callback_data:"status"},{text:"📋 Evidence",callback_data:"evidence"}],[{text:"🧭 Entry Intel",callback_data:"intel"},{text:"📊 Coverage",callback_data:"intel:coverage"}],[{text:"⬅️ Hub",callback_data:"menu"}]]});
const signalKeyboard=()=>({inline_keyboard:[[{text:"💱 Forex",callback_data:"market:forex"},{text:"🪙 Crypto",callback_data:"market:crypto"}],[{text:"🥇 Metal",callback_data:"market:metal"},{text:"📊 Index Cash",callback_data:"market:index"}],[{text:"🧭 Entry Intel",callback_data:"intel"},{text:"🔥 Top setups",callback_data:"signal:top"}],[{text:"⬅️ Hub",callback_data:"menu"}]]});
const marketKeyboard=g=>({inline_keyboard:[[{text:"🔍 Quét mới",callback_data:`signal:scan:${g}`},{text:"📚 Live",callback_data:`live:${g}`}],[{text:"🎯 Từng Symbol",callback_data:`symbols:${g}:0`}],[{text:"⬅️ Signal",callback_data:"signal"},{text:"🏠 Hub",callback_data:"menu"}]]});
const scanKeyboard=g=>({inline_keyboard:[[{text:"🔄 Quét lại",callback_data:`signal:scan:${g}`},{text:"📚 Live",callback_data:`live:${g}`}],[{text:"🎯 Symbol",callback_data:`symbols:${g}:0`}],[{text:"⬅️ Market",callback_data:`market:${g}`},{text:"🏠 Hub",callback_data:"menu"}]]});
const liveGroupKeyboard=g=>({inline_keyboard:[[{text:"🔄 Refresh",callback_data:`live:${g}`},{text:"📡 Quét",callback_data:`signal:scan:${g}`}],[{text:"🎯 Symbol",callback_data:`symbols:${g}:0`}],[{text:"⬅️ Market",callback_data:`market:${g}`},{text:"🏠 Hub",callback_data:"menu"}]]});

const fmt=v=>{const n=Number(v);if(!Number.isFinite(n))return "—";if(Math.abs(n)>=1000)return n.toFixed(2);if(Math.abs(n)>=10)return n.toFixed(4);if(Math.abs(n)>=1)return n.toFixed(5);return n.toPrecision(6);};
const side=s=>s==="LONG"?"🟢 BUY":s==="SHORT"?"🔴 SELL":"⚪ WAIT";
const groupName=g=>g==="forex"?"💱 FOREX":g==="crypto"?"🪙 CRYPTO":g==="metal"?"🥇 METAL":"📊 INDEX CASH";

async function hubText(env){const style=await loadHubUxTuning(env);return {text:[style.showVersion?`◈ TRADING HUB • ${VERSION}`:"◈ TRADING HUB",`UX ${UI_REV} • ${style.preset}`,"━━━━━━━━━━━━","📡 SIGNAL-ONLY","Không auto-trade • không execution account","","Chọn thị trường hoặc mở Entry Intelligence:"].join("\n"),kb:mainKeyboard()};}

async function evidenceText(env){const sig=await getSignalDecisionEvidence(env,30),latest=sig[0]||null,live=sig.filter(x=>x?.dataIntegrity?.overallFreshness==="LIVE").length,stale=sig.filter(x=>x?.dataIntegrity?.overallFreshness==="STALE").length,missing=sig.filter(x=>["MISSING","UNKNOWN"].includes(x?.dataIntegrity?.overallFreshness)).length,blocked=sig.reduce((n,x)=>n+(x?.gates||[]).filter(g=>g?.state==="BLOCK").length,0),api=isClaudeApiEnabled(env)?"🟢 ENABLED":"⏸ PAUSED";return ["📋 SIGNAL EVIDENCE","━━━━━━━━━━━━",`🧠 Claude API: ${api}`,`📡 Evidence: ${sig.length} • LIVE ${live} • STALE ${stale} • UNKNOWN ${missing}`,`🚧 Gate blocks: ${blocked}`,latest?`🎯 Last: ${latest.symbol} • ${latest.action} • ${latest.decision?.reason||"—"}`:"🎯 Last: chưa có evidence","","Signal-only • read-only evidence • không execution authority."].join("\n");}

async function entryIntelText(env){const rows=await getEntryIntelligenceShadow(env,12),x=rows[0]||null;if(!x)return "🧭 ENTRY INTELLIGENCE\n━━━━━━━━━━━━\n⚪ Chưa có reasoning. Quét một thị trường để tạo dữ liệu.";const c=x.integrity?.core||{},m=x.integrity?.marketSpecific||{},blocks=x.integrity?.hardBlocks||[],r=x.reasoning||{},q=x.quality||{},pr=x.promotion||{};return ["🧭 ENTRY INTELLIGENCE • SIGNAL ADVISORY","━━━━━━━━━━━━",`${x.symbol||"—"} • ${String(x.market||"unknown").toUpperCase()} • ${x.existingDecision?.status||"UNKNOWN"}`,`⭐ Quality: ${q.grade||"?"} • ${q.score??"—"}/100 • ${pr.allowed===false?"⛔ SIGNAL BLOCK":"✅ SIGNAL OK"}`,`📡 Freshness: ${x.quote?.freshness||"UNKNOWN"} • ${x.quote?.source||"—"}`,`🧩 Core: ${c.known||0}/${c.total||0} • Context: ${m.known||0}/${m.total||0}`,`⏱ WHY NOW: ${r.whyNow||"UNKNOWN"}`,`📍 WHY PRICE: ${r.whyPrice||"UNKNOWN"}`,`🛑 WHY SL: ${r.whySl||"UNKNOWN"}`,`🏁 WHY TP/RR: ${r.whyTp||"UNKNOWN"}`,`❌ Invalidates: ${r.invalidates||"UNKNOWN"}`,blocks.length?`🚧 Required blocks: ${blocks.join(", ")}`:"✅ No REQUIRED evidence block","","REQUIRED có thể block • QUALITY chỉ rank • OPTIONAL không tự block.","Execution authority: NONE"].join("\n");}

async function entryCoverageText(env){const rows=await getEntryIntelligenceShadow(env,120);if(!rows.length)return "📊 ENTRY INTELLIGENCE COVERAGE\n━━━━━━━━━━━━\n⚪ Chưa có dữ liệu. Quét từng thị trường để tạo evidence.";const markets=["forex","crypto","metal","index"],L=["📊 ENTRY INTELLIGENCE • COVERAGE","━━━━━━━━━━━━"];for(const market of markets){const all=rows.filter(x=>String(x?.market||"").toLowerCase()===market),xs=all.slice(0,15);if(!xs.length){L.push(`⚪ ${market.toUpperCase()}: 0 mẫu`);continue;}const live=xs.filter(x=>x?.quote?.freshness==="LIVE").length,blocked=xs.filter(x=>x?.promotion?.allowed===false).length,avg=Math.round(xs.reduce((n,x)=>n+Number(x?.quality?.score||0),0)/xs.length),missing={};for(const x of xs)for(const k of x?.integrity?.missingCore||[])missing[k]=(missing[k]||0)+1;const topMissing=Object.entries(missing).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k,v])=>`${k}:${v}`).join(", ")||"none";L.push(`• ${market.toUpperCase()}: n=${xs.length} • LIVE ${live}/${xs.length} • Q~${avg} • BLOCK ${blocked} • Missing ${topMissing}`);}L.push("","Mỗi market tối đa 15 mẫu gần nhất để tránh Forex/Crypto lấn coverage.","Signal-only • read-only.");return L.join("\n");}

async function engineJson(path,req,env){const u=new URL(req.url);const r=await baseEngine.fetch(new Request(u.origin+path,{method:"GET"}),env);try{return await r.json();}catch{return null;}}

function setupCard(a,i=0){if(!a)return null;const p=a.planned||a,mode=a.status==="MARKET_SIGNAL"||a.status==="MARKET"||a.status==="MARKET_PLAN"?"MARKET":a.status==="LIMIT"||a.status==="LIMIT_PLAN"?"LIMIT":"WATCH",rr=Number(p?.targetRR||0),score=Number(a.score||0),q=buildEntryIntelligenceShadow(a)?.quality||null;let L=[`${i?i+". ":""}${mode==="MARKET"?"⚡":mode==="LIMIT"?"🎯":"👀"} ${a.symbol} • ${side(a.side)}`,`   ${mode} • Score ${score}/100${rr?` • RR ${rr.toFixed(2)}`:""}`];if(p?.entry)L.push(`   📍 Entry ${fmt(p.entry)}`);if(p?.sl)L.push(`   🛑 SL ${fmt(p.sl)}   🏁 TP ${fmt(p.tp2||p.tp1||p.tp)}`);if(a.method?.profile)L.push(`   🧠 ${a.method.profile}${a.method?.activeMode?` • ${a.method.activeMode}`:""}`);if(q)L.push(`   ⭐ Quality ${q.grade||"?"} ${q.score??"—"}/100`);return L.join("\n");}

function symbolResultText(g,a){const q=a?.analysisQuote||a?.quote||{},price=Number(q?.price??a?.currentPrice??a?.entry),age=Number(q?.quoteAgeSec),src=q?.source||a?.source||"—",fresh=q?.fresh===false?"🔴 STALE":"🟢 FRESH",L=[`${groupName(g)} • ${a?.symbol||"—"}`,"━━━━━━━━━━━━",`💵 Giá: ${fmt(price)}`,`📡 ${src} • ${fresh}${Number.isFinite(age)?` • ${Math.round(age)}s`:""}`,""];L.push(setupCard(a)||`⚪ ${a?.reason||"Chưa có setup"}`);return L.join("\n");}

function scanText(g,r){if(!r)return `${groupName(g)}\n━━━━━━━━━━━━\n❌ Không đọc được kết quả.`;if(r.status==="BUSY")return `${groupName(g)} • ĐANG BẬN\n━━━━━━━━━━━━\n⏳ Một lượt quét khác đang chạy.\nKhông dùng setup cũ.`;if(r.status==="RATE_BUDGET_WAIT")return `${groupName(g)} • CHỜ DATA\n━━━━━━━━━━━━\n⏱ Quota đang hồi. Thử lại sau ~${r.retryAfterSec||60}s.\nKhông dùng setup cũ.`;const arr=(r.analyses||[]).slice(0,3),L=[`${groupName(g)} • QUÉT MỚI`,`━━━━━━━━━━━━`,`🔍 Coverage ${r.broadOk||0}/${r.requested||0} • Deep ${r.deepOk||0}/${r.deepRequested||0}`,`✨ Setup mới: ${arr.length}`,""];if(!arr.length)L.push("⚪ Chưa có setup đủ đẹp lúc này.");else arr.forEach((a,i)=>{L.push(setupCard(a,i+1),"");});L.push(`🕒 ${r.scannedAt||"—"}`,"ℹ️ Score = độ hoàn thiện setup, không phải % thắng.");return L.join("\n");}

function booksText(b,g){const L=[`📚 ${groupName(g)} • SIGNAL LIVE`,`━━━━━━━━━━━━`],x=b?.[g]||{},rows=[...(x.marketActive||[]),...(x.signalActive||[]),...(x.limitActive||[]),...(x.limitPending||[])];let n=0,a=0,w=0;for(const p of rows){n++;const pending=p.status==="PENDING",pct=Number(p.pnlPct),usd=Number(p.pnlUsd),icon=pending?"🟡":Number.isFinite(pct)&&pct>0?"🟢":Number.isFinite(pct)&&pct<0?"🔴":"⚪",kind=p.signalOnly?"MARKET SIGNAL":pending?"LIMIT CHỜ":p.origin==="LIMIT"?"LIMIT KHỚP":"MARKET";pending?w++:a++;L.push("",`${icon} ${p.symbol} • ${side(p.side)} • ${kind}`,`📍 ${fmt(p.entry)}${p.currentPrice?` → ${fmt(p.currentPrice)}`:""}`,pending?"⏳ Chưa khớp • chưa tính P/L":`💵 ${p.signalOnly?"Theo dõi":"P/L"} ${Number.isFinite(pct)?(pct>=0?"+":"")+pct.toFixed(2)+"%":"—"}${Number.isFinite(usd)?` • ~${usd>=0?"+":""}${usd.toFixed(2)}`:""}${p.signalOnly?" • SIGNAL-ONLY":""}`,`🛑 SL ${fmt(p.sl)} • 🏁 TP ${fmt(p.tp)}`);}if(!n)L.push("","⚪ Thị trường này hiện chưa có signal live.");L.push("","━━━━━━━━━━━━",`Active ${a} • Pending ${w} • Tổng ${n}`,`🕒 ${b?.liveRefreshedAt?new Date(b.liveRefreshedAt).toISOString():"chưa refresh"}`);return L.join("\n");}

function symbolPageKeyboard(g,symbols,page=0){const per=12,total=Math.max(1,Math.ceil(symbols.length/per)),pg=Math.max(0,Math.min(total-1,Number(page)||0)),slice=symbols.slice(pg*per,(pg+1)*per),rows=[];for(let i=0;i<slice.length;i+=2)rows.push(slice.slice(i,i+2).map(x=>({text:x,callback_data:`symbol:${g}:${x}`})));const nav=[];if(pg>0)nav.push({text:"◀️",callback_data:`symbols:${g}:${pg-1}`});nav.push({text:`${pg+1}/${total}`,callback_data:`symbols:${g}:${pg}`});if(pg<total-1)nav.push({text:"▶️",callback_data:`symbols:${g}:${pg+1}`});rows.push(nav,[{text:"⬅️ Market",callback_data:`market:${g}`},{text:"🏠 Hub",callback_data:"menu"}]);return {inline_keyboard:rows};}

async function handleTelegram(req,env){if(!verifyTelegram(req,env))return json({ok:false,error:"invalid telegram secret"},403);let u;try{u=await req.clone().json();}catch{return null;}const chatId=u?.callback_query?.message?.chat?.id??u?.message?.chat?.id??env.TELEGRAM_CHAT_ID,cb=u?.callback_query?.data,text=String(u?.message?.text||""),handled=["menu","hub:more","signal","signal:top","status","evidence","intel","intel:coverage"].includes(cb)||cb?.startsWith("market:")||cb?.startsWith("signal:scan:")||cb?.startsWith("live:")||cb?.startsWith("symbols:")||cb?.startsWith("symbol:")||text==="/start"||text==="/menu";if(!handled)return null;if(u?.callback_query?.id)telegram(env,"answerCallbackQuery",{callback_query_id:u.callback_query.id}).catch(()=>{});
  if(cb==="menu"||text==="/start"||text==="/menu"){const x=await hubText(env);await sendText(env,x.text,chatId,x.kb);return json({ok:true,version:VERSION,ui:UI_REV});}
  if(cb==="hub:more"){await sendText(env,"••• HỆ THỐNG SIGNAL\n━━━━━━━━━━━━\nChỉ còn Signal + Entry Intelligence.",chatId,moreKeyboard());return json({ok:true});}
  if(cb==="signal"){await sendText(env,"📡 SIGNAL CENTER\n━━━━━━━━━━━━\nQuét riêng từng thị trường.\nƯu tiên setup có giá fresh + cấu trúc + RR hợp lệ.",chatId,signalKeyboard());return json({ok:true,ui:UI_REV});}
  if(cb==="signal:top"){const h=await engineJson("/hub",req,env),top=(h?.top||[]).slice(0,5),L=["🔥 TOP SETUPS","━━━━━━━━━━━━"];if(!top.length)L.push("⚪ Chưa có setup nổi bật.");else top.forEach((a,i)=>L.push(setupCard(a,i+1),""));await sendText(env,L.join("\n"),chatId,signalKeyboard());return json({ok:true});}
  if(cb?.startsWith("market:")){const g=cb.split(":").at(-1);await sendText(env,`${groupName(g)} • TRUNG TÂM\n━━━━━━━━━━━━\nQuét • Live • Symbol riêng.`,chatId,marketKeyboard(g));return json({ok:true,group:g});}
  if(cb?.startsWith("signal:scan:")){const g=cb.split(":").at(-1);await sendText(env,`⏳ ${groupName(g)} • đang quét dữ liệu mới…`,chatId);const r=await engineJson(`/run-now?group=${g}`,req,env);await sendText(env,scanText(g,r),chatId,scanKeyboard(g));return json({ok:true,group:g});}
  if(cb?.startsWith("live:")){const g=cb.split(":").at(-1);const b=await engineJson(`/books?group=${g}`,req,env);await sendText(env,booksText(b,g),chatId,liveGroupKeyboard(g));return json({ok:true,group:g});}
  if(cb?.startsWith("symbols:")){const parts=cb.split(":"),g=parts[1],page=Number(parts[2]||0),d=await engineJson(`/symbols?group=${g}`,req,env),symbols=Array.isArray(d?.symbols)?d.symbols:[];await sendText(env,`🎯 ${groupName(g)} • SYMBOL\n━━━━━━━━━━━━\nChọn mã để lấy giá mới và phân tích riêng.`,chatId,symbolPageKeyboard(g,symbols,page));return json({ok:true,group:g,page});}
  if(cb?.startsWith("symbol:")){const parts=cb.split(":"),g=parts[1],sym=parts[2];await sendText(env,`⏳ ${sym} • đang lấy giá mới + phân tích…`,chatId);const a=await engineJson(`/analyze?symbol=${encodeURIComponent(sym)}`,req,env);await sendText(env,symbolResultText(g,a),chatId,{inline_keyboard:[[{text:"🔄 Quét lại",callback_data:`symbol:${g}:${sym}`},{text:"📚 Live",callback_data:`live:${g}`}],[{text:"⬅️ Symbol",callback_data:`symbols:${g}:0`},{text:"🏠 Hub",callback_data:"menu"}]]});return json({ok:true,group:g,symbol:sym});}
  if(cb==="evidence"){await sendText(env,await evidenceText(env),chatId,{inline_keyboard:[[{text:"🔄 Refresh",callback_data:"evidence"},{text:"🧭 Entry Intel",callback_data:"intel"}],[{text:"🏠 Hub",callback_data:"menu"}]]});return json({ok:true,view:"signal-evidence"});}
  if(cb==="intel"){await sendText(env,await entryIntelText(env),chatId,{inline_keyboard:[[{text:"🔄 Refresh",callback_data:"intel"},{text:"📊 Coverage",callback_data:"intel:coverage"}],[{text:"📋 Evidence",callback_data:"evidence"},{text:"🏠 Hub",callback_data:"menu"}]]});return json({ok:true,view:"entry-intelligence",executionAuthority:"NONE"});}
  if(cb==="intel:coverage"){await sendText(env,await entryCoverageText(env),chatId,{inline_keyboard:[[{text:"🔄 Refresh",callback_data:"intel:coverage"},{text:"🧭 Entry Intel",callback_data:"intel"}],[{text:"🏠 Hub",callback_data:"menu"}]]});return json({ok:true,view:"entry-intelligence-coverage",readOnly:true});}
  if(cb==="status"){const s=await engineJson("/status",req,env);await sendText(env,["🩺 SIGNAL SYSTEM","━━━━━━━━━━━━",`${s?.kv?"🟢":"🔴"} KV State`,`${s?.twelveData?"🟢":"🔴"} Twelve Data`,`${s?.massive?"🟢":"🔴"} Index Cash Data`,`${s?.telegram?"🟢":"🔴"} Telegram`,`📡 Engine ${s?.version||"—"}`,`🎨 UX ${UI_REV}`,"","Execution authority: SIGNAL_ONLY"].join("\n"),chatId,{inline_keyboard:[[{text:"💱 Forex",callback_data:"market:forex"},{text:"🪙 Crypto",callback_data:"market:crypto"}],[{text:"🥇 Metal",callback_data:"market:metal"},{text:"📊 Index",callback_data:"market:index"}],[{text:"🏠 Hub",callback_data:"menu"}]]});return json({ok:true});}
  return null;
}

async function patchedStatus(req,env){const r=await baseEngine.fetch(req,env);let p;try{p=await r.clone().json();}catch{return r;}return json({...p,version:VERSION,service:SERVICE,hubUx:{revision:UI_REV,tuning:await getHubUxState(env)},executionAuthority:"SIGNAL_ONLY",hyroRemoved:true},r.status);}

export default {
  async fetch(req,env,ctx){const u=new URL(req.url),path=u.pathname.replace(/\/$/,"")||"/";if(path==="/status")return patchedStatus(req,env);if(path==="/hub/ux")return json({ok:true,version:VERSION,ui:UI_REV,tuning:await getHubUxState(env),executionAuthority:"SIGNAL_ONLY"});if(path==="/telegram/menu"){const x=await hubText(env);await sendText(env,x.text,env.TELEGRAM_CHAT_ID,x.kb);return json({ok:true,version:VERSION,ui:UI_REV});}if(path==="/telegram/webhook"&&req.method==="POST"){const handled=await handleTelegram(req,env);if(handled)return handled;}if(path.startsWith("/prop/")||path.startsWith("/hyro/"))return json({ok:false,error:"REMOVED",message:"Hyro auto-trade/runtime removed. Signal-only system."},410);return baseEngine.fetch(req,env,ctx);},
  async scheduled(controller,env,ctx){return baseEngine.scheduled(controller,env,ctx);}
};
