const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null;};
async function bj(path,params={}){const q=new URLSearchParams(params),r=await fetch(`https://api.bybit.com${path}?${q}`),p=await r.json().catch(()=>null);if(!r.ok||Number(p?.retCode)!==0)throw new Error(p?.retMsg||`Bybit HTTP ${r.status}`);return p;}
function candles(p){return (p?.result?.list||[]).map(x=>({ts:Number(x[0]),o:Number(x[1]),h:Number(x[2]),l:Number(x[3]),c:Number(x[4]),v:Number(x[5]),turn:Number(x[6])})).filter(x=>[x.o,x.h,x.l,x.c].every(Number.isFinite)).sort((a,b)=>a.ts-b.ts).slice(0,-1);}
function ema(a,len){if(!a.length)return null;const k=2/(len+1);let e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e;}
function atr(c,len=14){if(c.length<len+1)return null;const tr=[];for(let i=1;i<c.length;i++)tr.push(Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c)));return tr.slice(-len).reduce((a,b)=>a+b,0)/len;}
function rsi(c,len=14){if(c.length<len+1)return 50;let g=0,l=0;for(let i=c.length-len;i<c.length;i++){const d=c[i].c-c[i-1].c;if(d>0)g+=d;else l-=d;}if(l===0)return 100;const rs=(g/len)/(l/len);return 100-100/(1+rs);}
function swing(c,side,bars){const a=c.slice(-bars);return side==="BUY"?Math.min(...a.map(x=>x.l)):Math.max(...a.map(x=>x.h));}
function targetSwing(c,side,bars){const a=c.slice(-bars);return side==="BUY"?Math.max(...a.map(x=>x.h)):Math.min(...a.map(x=>x.l));}
function breakout(c,side,bars=20){const a=c.slice(-(bars+1),-1);return side==="BUY"?Math.max(...a.map(x=>x.h)):Math.min(...a.map(x=>x.l));}
function regime(c,fast=20,slow=50){const closes=c.map(x=>x.c),ef=ema(closes.slice(-Math.max(80,fast*4)),fast),es=ema(closes.slice(-Math.max(120,slow*3)),slow),last=closes.at(-1);if(last>ef&&ef>es)return "UPTREND";if(last<ef&&ef<es)return "DOWNTREND";return "RANGE";}
function h(s){let x=2166136261;for(const ch of s){x^=ch.charCodeAt(0);x=Math.imul(x,16777619);}return x>>>0;}
const MAJOR={
 BTCUSDT:{family:"TREND_PULLBACK",fast:21,slow:55,rsiBuy:50,rsiSell:50,dist:.42,slAtr:.18,swingBars:28,targetBars:72,minRR:1.8,tp1R:1,tp2R:1.8,tp3R:2.8,btcFilter:false},
 ETHUSDT:{family:"BREAKOUT_RETEST",fast:20,slow:50,rsiBuy:51,rsiSell:49,dist:.38,slAtr:.20,swingBars:24,targetBars:64,minRR:1.8,tp1R:1,tp2R:2,tp3R:3,btcFilter:true},
 SOLUSDT:{family:"MOMENTUM_BREAKOUT",fast:18,slow:45,rsiBuy:54,rsiSell:46,dist:.55,slAtr:.28,swingBars:20,targetBars:56,minRR:1.9,tp1R:1,tp2R:2,tp3R:3.2,btcFilter:true},
 XRPUSDT:{family:"LIQUIDITY_RECLAIM",fast:24,slow:60,rsiBuy:49,rsiSell:51,dist:.30,slAtr:.16,swingBars:32,targetBars:80,minRR:1.8,tp1R:.9,tp2R:1.8,tp3R:2.7,btcFilter:false},
 BNBUSDT:{family:"RANGE_BREAK",fast:20,slow:50,rsiBuy:52,rsiSell:48,dist:.35,slAtr:.18,swingBars:26,targetBars:70,minRR:1.8,tp1R:1,tp2R:1.9,tp3R:2.8,btcFilter:true},
 DOGEUSDT:{family:"MOMENTUM_BREAKOUT",fast:16,slow:42,rsiBuy:55,rsiSell:45,dist:.60,slAtr:.30,swingBars:18,targetBars:52,minRR:2,tp1R:1,tp2R:2.1,tp3R:3.4,btcFilter:true},
 ADAUSDT:{family:"TREND_PULLBACK",fast:23,slow:58,rsiBuy:50,rsiSell:50,dist:.36,slAtr:.20,swingBars:28,targetBars:74,minRR:1.8,tp1R:1,tp2R:1.9,tp3R:2.9,btcFilter:true},
 AVAXUSDT:{family:"VOL_BREAK",fast:19,slow:47,rsiBuy:53,rsiSell:47,dist:.50,slAtr:.26,swingBars:22,targetBars:60,minRR:1.9,tp1R:1,tp2R:2,tp3R:3.1,btcFilter:true},
 LINKUSDT:{family:"TREND_CONTINUATION",fast:21,slow:52,rsiBuy:52,rsiSell:48,dist:.40,slAtr:.20,swingBars:24,targetBars:68,minRR:1.85,tp1R:1,tp2R:1.9,tp3R:3,btcFilter:true},
 SUIUSDT:{family:"BREAKOUT_RETEST",fast:17,slow:44,rsiBuy:54,rsiSell:46,dist:.52,slAtr:.28,swingBars:20,targetBars:58,minRR:2,tp1R:1,tp2R:2,tp3R:3.3,btcFilter:true},
 AAVEUSDT:{family:"LIQUIDITY_RECLAIM",fast:25,slow:62,rsiBuy:49,rsiSell:51,dist:.34,slAtr:.18,swingBars:30,targetBars:78,minRR:1.9,tp1R:1,tp2R:2,tp3R:3,btcFilter:true},
 ALGOUSDT:{family:"RANGE_BREAK",fast:22,slow:56,rsiBuy:52,rsiSell:48,dist:.32,slAtr:.19,swingBars:28,targetBars:76,minRR:1.9,tp1R:1,tp2R:2,tp3R:3,btcFilter:true}
};
const FAMILIES=["TREND_PULLBACK","BREAKOUT_RETEST","MOMENTUM_BREAKOUT","LIQUIDITY_RECLAIM","RANGE_BREAK","VOL_BREAK","TREND_CONTINUATION"];
function profileFor(symbol){if(MAJOR[symbol])return {id:`${symbol}:${MAJOR[symbol].family}`,symbol,...MAJOR[symbol]};const z=h(symbol),family=FAMILIES[z%FAMILIES.length],j=(z%17)/100;return {id:`${symbol}:${family}:${z%1000}`,symbol,family,fast:18+(z%8),slow:46+(z%18),rsiBuy:50+(z%5),rsiSell:50-(z%5),dist:.32+((z>>3)%20)/100,slAtr:.17+((z>>5)%12)/100,swingBars:20+((z>>7)%14),targetBars:58+((z>>9)%28),minRR:1.8+((z>>11)%3)/10,tp1R:.9+j,tp2R:1.8+j,tp3R:2.8+j*2,btcFilter:(z%4)!==0};}
function sideFrom(h1,m15,p){const a=regime(h1,p.fast,p.slow),b=regime(m15,p.fast,p.slow);if(a==="UPTREND"&&b==="UPTREND")return "BUY";if(a==="DOWNTREND"&&b==="DOWNTREND")return "SELL";return null;}
function fundingView(ticker,side){const rate=n(ticker.fundingRate)||0,next=n(ticker.nextFundingTime)||0,mins=next>0?(next-Date.now())/60000:null,pays=(side==="BUY"&&rate>0)||(side==="SELL"&&rate<0),adverse=pays?Math.abs(rate):0,block=pays&&mins!=null&&mins>=0&&mins<=30&&adverse>=.0005,penalty=pays&&mins!=null&&mins>=0&&mins<=60?Math.min(.25,adverse*250):0;return {rate,nextFundingTime:next,minutesToFunding:mins,paysFunding:pays,adverseRate:adverse,block,rrPenalty:penalty};}
function levels(entry,sl,side,p){const r=Math.abs(entry-sl);const at=k=>side==="BUY"?entry+r*k:entry-r*k;return {tp1:at(p.tp1R),tp2:at(p.tp2R),tp3:at(p.tp3R)};}
function familyTrigger(p,side,last,e5,e15,r5,m5,relax=0){const br=breakout(m5,side,20),near=Math.abs(last-e15)/(atr(m5)||1),rb=p.rsiBuy-relax,rs=p.rsiSell+relax;if(p.family==="MOMENTUM_BREAKOUT"||p.family==="VOL_BREAK")return side==="BUY"?(last>br*(1-relax*.0008)&&r5>=rb):(last<br*(1+relax*.0008)&&r5<=rs);if(p.family==="BREAKOUT_RETEST"||p.family==="RANGE_BREAK")return side==="BUY"?(last>=e5*(1-relax*.0005)&&last>=e15*(1-relax*.0005)&&r5>=rb):(last<=e5*(1+relax*.0005)&&last<=e15*(1+relax*.0005)&&r5<=rs);if(p.family==="LIQUIDITY_RECLAIM")return side==="BUY"?(last>=e5*(1-relax*.0005)&&r5>=rb&&near<=p.dist*(.9+relax*.08)):(last<=e5*(1+relax*.0005)&&r5<=rs&&near<=p.dist*(.9+relax*.08));return side==="BUY"?(last>=e5*(1-relax*.0005)&&r5>=rb):(last<=e5*(1+relax*.0005)&&r5<=rs);}
function basePlan(symbol,ticker,h1,m15,m5,btcCtx){const p=profileFor(symbol),side=sideFrom(h1,m15,p),last=m5.at(-1)?.c;if(!side||!last)return {symbol,status:"WATCH",tier:"C",reason:"PROFILE_HTF_ALIGNMENT_REQUIRED",profile:p.id,strategy:p.family};const a15=atr(m15),e15=ema(m15.map(x=>x.c).slice(-100),p.fast),e5=ema(m5.map(x=>x.c).slice(-100),Math.max(8,p.fast-6)),r5=rsi(m5),slBase=swing(m15,side,p.swingBars),rawSl=side==="BUY"?slBase-a15*p.slAtr:slBase+a15*p.slAtr,target=targetSwing(h1,side,p.targetBars),risk=Math.abs(last-rawSl),structReward=side==="BUY"?target-last:last-target,structRR=risk>0?structReward/risk:0,dist=Math.abs(last-e15)/(a15||1),btcAgree=!p.btcFilter||!btcCtx?.side||btcCtx.side===side,fund=fundingView(ticker,side),trigger=familyTrigger(p,side,last,e5,e15,r5,m5,0),nearTrigger=familyTrigger(p,side,last,e5,e15,r5,m5,2),lv=levels(last,rawSl,side,p),effectiveRR=Math.min(structRR,p.tp3R)-fund.rrPenalty,common={symbol,side,entry:last,sl:rawSl,tp:lv.tp3,tp1:lv.tp1,tp2:lv.tp2,tp3:lv.tp3,profile:p.id,strategy:p.family,management:{tp1Pct:.40,tp2Pct:.35,runnerPct:.25,moveSlToBEAfterTp1:true,moveSlToTp1AfterTp2:true,trailingAfterTp2Atr:.8},context:{funding:fund,turnover24h:n(ticker.turnover24h),openInterestValue:n(ticker.openInterestValue),btcAgree,rsi5:r5,distAtr:dist}};
 if(!fund.block&&trigger&&dist<=p.dist&&btcAgree&&effectiveRR>=p.minRR)return {...common,status:"MARKET_PLAN",action:"MARKET_PLAN",tier:"A",riskMultiplier:1,rr:effectiveRR,reason:`${p.family}_MARKET_A`};
 const nearRR=Math.max(1.4,p.minRR-.35);if(!fund.block&&nearTrigger&&dist<=p.dist*1.35&&btcAgree&&effectiveRR>=nearRR)return {...common,status:"NEAR_MARKET_PLAN",action:"MARKET_PLAN",tier:"B",riskMultiplier:.45,rr:effectiveRR,reason:`${p.family}_NEAR_MARKET_B`};
 const limit=e15,lr=Math.abs(limit-rawSl),lreward=side==="BUY"?target-limit:limit-target,lrr=lr>0?lreward/lr:0,lvl=levels(limit,rawSl,side,p),correct=side==="BUY"?limit<last:limit>last,limitDist=Math.abs(last-limit)/(a15||1);if(!fund.block&&correct&&lrr-fund.rrPenalty>=Math.max(1.4,p.minRR-.2)&&limitDist>=.06&&limitDist<=Math.max(1.0,p.dist*2.2)&&btcAgree)return {symbol,status:"LIMIT_PLAN",action:"LIMIT_PLAN",tier:"C",riskMultiplier:.75,side,entry:limit,sl:rawSl,tp:lvl.tp3,tp1:lvl.tp1,tp2:lvl.tp2,tp3:lvl.tp3,rr:lrr-fund.rrPenalty,profile:p.id,strategy:p.family,management:common.management,reason:`${p.family}_LIMIT_C`,context:{...common.context,limitDistATR:limitDist}};
 return {symbol,status:"WATCH",tier:"C",side,reason:fund.block?"ADVERSE_FUNDING_NEAR_SETTLEMENT":"PROFILE_TRIGGER_OR_RR_REQUIRED",rr:Math.max(effectiveRR,lrr||0),profile:p.id,strategy:p.family,context:{funding:fund,btcAgree,rsi5:r5,distAtr:dist}};}
async function bundle(symbol){const [h1,m15,m5]=await Promise.all([bj("/v5/market/kline",{category:"linear",symbol,interval:"60",limit:"180"}),bj("/v5/market/kline",{category:"linear",symbol,interval:"15",limit:"180"}),bj("/v5/market/kline",{category:"linear",symbol,interval:"5",limit:"180"})]);return [candles(h1),candles(m15),candles(m5)];}
function btcContext(tickers){const t=tickers.find(x=>x.symbol==="BTCUSDT"),pct=n(t?.price24hPcnt);return {side:pct>.005?"BUY":pct<-.005?"SELL":null,pct24h:pct};}
export function hyroStrategyProfile(symbol){return profileFor(String(symbol||"").toUpperCase());}
export async function hyroDynamicScan({maxBroad=80,maxDeep=8,minTurnover=10000000}={}){const p=await bj("/v5/market/tickers",{category:"linear"}),all=(p?.result?.list||[]).filter(x=>String(x.symbol).endsWith("USDT")).map(x=>({...x,_turn:n(x.turnover24h)||0,_move:Math.abs(n(x.price24hPcnt)||0)})).filter(x=>x._turn>=minTurnover).sort((a,b)=>b._turn-a._turn).slice(0,maxBroad),ctx=btcContext(all),short=[...all].sort((a,b)=>(b._move*Math.log10(b._turn+10))-(a._move*Math.log10(a._turn+10))).slice(0,maxDeep),results=[];for(const t of short){try{const [h1,m15,m5]=await bundle(t.symbol);if(h1.length<60||m15.length<60||m5.length<60){results.push({symbol:t.symbol,status:"WATCH",tier:"C",reason:"PROFILE_DATA_SHORT",profile:profileFor(t.symbol).id});continue;}results.push(basePlan(t.symbol,t,h1,m15,m5,ctx));}catch(e){results.push({symbol:t.symbol,status:"DATA_BLOCK",tier:"C",reason:String(e?.message||e),profile:profileFor(t.symbol).id});}}const rank={MARKET_PLAN:4,NEAR_MARKET_PLAN:3,LIMIT_PLAN:2,WATCH:1,DATA_BLOCK:0};results.sort((a,b)=>(rank[b.status]??-1)-(rank[a.status]??-1)||(b.rr||0)-(a.rr||0));const tiers={A:results.filter(x=>x.tier==="A").length,B:results.filter(x=>x.tier==="B").length,C:results.filter(x=>x.tier==="C").length};return {ok:true,source:"Bybit V5 public",profile:"PER_SYMBOL_ABC_REGISTRY",broadCount:all.length,deepCount:results.length,tiers,btcContext:ctx,results};}
