const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null;};
async function bj(path,params={}){const q=new URLSearchParams(params),r=await fetch(`https://api.bybit.com${path}?${q}`),p=await r.json().catch(()=>null);if(!r.ok||Number(p?.retCode)!==0)throw new Error(p?.retMsg||`Bybit HTTP ${r.status}`);return p;}
function candles(p){return (p?.result?.list||[]).map(x=>({ts:Number(x[0]),o:Number(x[1]),h:Number(x[2]),l:Number(x[3]),c:Number(x[4]),v:Number(x[5]),turn:Number(x[6])})).filter(x=>[x.o,x.h,x.l,x.c].every(Number.isFinite)).sort((a,b)=>a.ts-b.ts).slice(0,-1);}
function ema(a,len){if(!a.length)return null;const k=2/(len+1);let e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e;}
function atr(c,len=14){if(c.length<len+1)return null;const tr=[];for(let i=1;i<c.length;i++)tr.push(Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c)));return tr.slice(-len).reduce((a,b)=>a+b,0)/len;}
function rsi(c,len=14){if(c.length<len+1)return 50;let g=0,l=0;for(let i=c.length-len;i<c.length;i++){const d=c[i].c-c[i-1].c;if(d>0)g+=d;else l-=d;}if(l===0)return 100;const rs=(g/len)/(l/len);return 100-100/(1+rs);}
function swing(c,side,nBars=24){const a=c.slice(-nBars);return side==="BUY"?Math.min(...a.map(x=>x.l)):Math.max(...a.map(x=>x.h));}
function targetSwing(c,side,nBars=60){const a=c.slice(-nBars);return side==="BUY"?Math.max(...a.map(x=>x.h)):Math.min(...a.map(x=>x.l));}
function regime(c){const closes=c.map(x=>x.c),e20=ema(closes.slice(-80),20),e50=ema(closes.slice(-120),50),last=closes.at(-1);if(last>e20&&e20>e50)return "UPTREND";if(last<e20&&e20<e50)return "DOWNTREND";return "RANGE";}
function sideFrom(h1,m15){const a=regime(h1),b=regime(m15);if(a==="UPTREND"&&b==="UPTREND")return "BUY";if(a==="DOWNTREND"&&b==="DOWNTREND")return "SELL";return null;}
function plan(symbol,ticker,h1,m15,m5,btcCtx){const side=sideFrom(h1,m15),last=m5.at(-1)?.c;if(!side||!last)return {symbol,status:"WATCH",reason:"GENERIC_HTF_ALIGNMENT_REQUIRED",profile:"GENERIC_DYNAMIC"};const a15=atr(m15),e15=ema(m15.map(x=>x.c).slice(-80),20),e5=ema(m5.map(x=>x.c).slice(-80),20),r5=rsi(m5),slBase=swing(m15,side),rawSl=side==="BUY"?slBase-a15*.15:slBase+a15*.15,target=targetSwing(h1,side),risk=Math.abs(last-rawSl),reward=side==="BUY"?target-last:last-target,rr=risk>0?reward/risk:0,dist=Math.abs(last-e15)/(a15||1),m5Aligned=side==="BUY"?(last>=e5&&r5>=48):(last<=e5&&r5<=52),btcAgree=!btcCtx?.side||btcCtx.side===side;if(rr>=1.7&&dist<=.35&&m5Aligned&&btcAgree)return {symbol,status:"MARKET_PLAN",action:"MARKET_PLAN",side,entry:last,sl:rawSl,tp:target,rr,profile:"GENERIC_DYNAMIC",reason:"DYNAMIC_TREND_TRIGGER",context:{fundingRate:n(ticker.fundingRate),openInterestValue:n(ticker.openInterestValue),turnover24h:n(ticker.turnover24h),btcAgree}};const limit=e15,lr=Math.abs(limit-rawSl),lreward=side==="BUY"?target-limit:limit-target,lrr=lr>0?lreward/lr:0,correctSide=side==="BUY"?limit<last:limit>last,limitDist=Math.abs(last-limit)/(a15||1);if(correctSide&&lrr>=1.7&&limitDist>=.08&&limitDist<=.9&&btcAgree)return {symbol,status:"LIMIT_PLAN",action:"LIMIT_PLAN",side,entry:limit,sl:rawSl,tp:target,rr:lrr,profile:"GENERIC_DYNAMIC",reason:"DYNAMIC_STRUCTURAL_PULLBACK",context:{fundingRate:n(ticker.fundingRate),openInterestValue:n(ticker.openInterestValue),turnover24h:n(ticker.turnover24h),btcAgree,limitDistATR:limitDist}};return {symbol,status:"WATCH",side,reason:"DYNAMIC_STRUCTURE_RR_REQUIRED",rr:Math.max(rr,lrr||0),profile:"GENERIC_DYNAMIC"};}
async function bundle(symbol){const [h1,m15,m5]=await Promise.all([bj("/v5/market/kline",{category:"linear",symbol,interval:"60",limit:"160"}),bj("/v5/market/kline",{category:"linear",symbol,interval:"15",limit:"160"}),bj("/v5/market/kline",{category:"linear",symbol,interval:"5",limit:"160"})]);return [candles(h1),candles(m15),candles(m5)];}
function btcContext(tickers){const t=tickers.find(x=>x.symbol==="BTCUSDT"),pct=n(t?.price24hPcnt);return {side:pct>0.005?"BUY":pct<-.005?"SELL":null,pct24h:pct};}
export async function hyroDynamicScan({maxBroad=80,maxDeep=8,minTurnover=10000000}={}){const p=await bj("/v5/market/tickers",{category:"linear"}),all=(p?.result?.list||[]).filter(x=>String(x.symbol).endsWith("USDT")).map(x=>({...x,_turn:n(x.turnover24h)||0,_move:Math.abs(n(x.price24hPcnt)||0)})).filter(x=>x._turn>=minTurnover).sort((a,b)=>b._turn-a._turn).slice(0,maxBroad),ctx=btcContext(all),short=[...all].sort((a,b)=>(b._move*Math.log10(b._turn+10))-(a._move*Math.log10(a._turn+10))).slice(0,maxDeep),results=[];for(const t of short){try{const [h1,m15,m5]=await bundle(t.symbol);if(h1.length<60||m15.length<60||m5.length<60){results.push({symbol:t.symbol,status:"WATCH",reason:"DYNAMIC_DATA_SHORT"});continue;}results.push(plan(t.symbol,t,h1,m15,m5,ctx));}catch(e){results.push({symbol:t.symbol,status:"DATA_BLOCK",reason:String(e?.message||e)});}}const rank={MARKET_PLAN:3,LIMIT_PLAN:2,WATCH:1,DATA_BLOCK:0};results.sort((a,b)=>(rank[b.status]??-1)-(rank[a.status]??-1)||(b.rr||0)-(a.rr||0));return {ok:true,source:"Bybit V5 public",profile:"GENERIC_DYNAMIC_FALLBACK",broadCount:all.length,deepCount:results.length,btcContext:ctx,results};}
