import signalHub from "./hub-v77171.js";
import {getHyroProfile,getHyroControl,setHyroPaused,getHyroTelemetry,getHyroDiagnostics,reconcileHyro,cancelHyroPending,hyroExecutionConfig,hyroDynamicRiskView} from "./hyro-execution.js";
import {runHyroAutoCycle,getHyroRuntime} from "./hyro-runtime.js";
import {runHyroDemoExecutionTest,runHyroDemoFullCycleTest,getHyroDemoTestState} from "./hyro-demo-test.js";

const VERSION="V77.18.13",SERVICE="Trading V77.18.13 Per-Symbol Microstructure Runtime";
const PROP_NOTIFY_PREFIX="v7718:hyro:notify:",PROP_NOTIFY_SNAPSHOT_KEY="v7718:hyro:notify:snapshot";
const json=(body,status=200)=>new Response(JSON.stringify(body,null,2),{status,headers:{"content-type":"application/json; charset=utf-8"}});
const money=v=>{const x=Number(v||0),sign=x>0?"+":"";return sign+"$"+x.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});},cash=v=>"$"+Number(v||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
const ago=ts=>{if(!ts)return "—";const s=Math.max(0,Math.round((Date.now()-Number(ts))/1000));if(s<60)return `${s}s`;const m=Math.round(s/60);return m<60?`${m}m`:`${Math.round(m/60)}h`;};
async function kvGet(env,key,fallback=null){try{return await env.TRADING_STATE?.get(key,"json")??fallback;}catch{return fallback;}}
async function kvPut(env,key,value,ttl){if(env.TRADING_STATE)await env.TRADING_STATE.put(key,JSON.stringify(value),ttl?{expirationTtl:ttl}:undefined);}
async function tg(env,method,payload){const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),p=await r.json();if(!p.ok)throw new Error(p.description||"Telegram error");return p;}
const send=(env,chatId,text,reply_markup)=>tg(env,"sendMessage",{chat_id:chatId,text,reply_markup,disable_web_page_preview:true});
const verify=(req,env)=>!env.TELEGRAM_WEBHOOK_SECRET||req.headers.get("x-telegram-bot-api-secret-token")===env.TELEGRAM_WEBHOOK_SECRET;
const phaseName=p=>p?.phase==="FUNDED"?"FUNDED":"CHALLENGE",programName=p=>p?.program==="TWO_STEP"?"Two-Step":"One-Step";
async function propEnv(env){const p=await getHyroProfile(env);return p?.phase==="CHALLENGE"?new Proxy(env,{get(t,k){if(k==="HYRO_BYBIT_MODE")return "DEMO";return t[k];}}):env;}
async function refreshPropConnection(env){try{return await getHyroTelemetry(await propEnv(env));}catch{return null;}}
function propKeyboard(paused=false,mode="DEMO"){const rows=[[{text:"📊 Tổng quan",callback_data:"prop:dashboard"},{text:"📈 Vị thế",callback_data:"prop:positions"}],[{text:"🛡 Risk",callback_data:"prop:risklive"},{text:"🔌 Kết nối",callback_data:"prop:connectlive"}],[{text:"🔎 Quét",callback_data:"prop:quickscan"},{text:paused?"▶ Auto":"⛔ Auto",callback_data:paused?"prop:resume":"prop:pause"}]];if(String(mode).toUpperCase()==="DEMO")rows.push([{text:"🧪 Order",callback_data:"prop:demotest"},{text:"🧪 Cycle",callback_data:"prop:fullcycletest"}]);rows.push([{text:"⚙️ Cấu hình",callback_data:"prop:setup"},{text:"⬅️ Menu",callback_data:"menu"}]);return {inline_keyboard:rows};}
function posLine(p,i){const side=p.side==="Buy"?"BUY":"SELL";return `${i+1}. ${p.symbol} ${side} | P/L ${money(p.unrealisedPnl)}\nEntry ${p.avgPrice} | SL ${p.stopLoss||"—"} | TP ${p.takeProfit||"—"}`;}
const usd2=v=>`$${Math.abs(Number(v||0)).toFixed(2)}`;
function orderUsdLevels(o){const q=Number(o?.qty||0),e=Number(o?.entry||0),sl=Number(o?.sl||0),tp=Number(o?.tp||0);return {slUsd:q&&e&&sl?Math.abs(e-sl)*q:Number(o?.riskBudget||0),tpUsd:q&&e&&tp?Math.abs(tp-e)*q:Number(o?.riskBudget||0)*Number(o?.rr||0)};}
async function notifyPropEntry(env,cycle){if(!cycle?.executed||cycle?.reason!=="ORDER_SUBMITTED"||!cycle?.execution)return;const o=cycle.execution,id=String(o.orderId||o.orderLinkId||o.id||`${o.symbol}:${o.createdAt}`),key=`${PROP_NOTIFY_PREFIX}entry:${id}`;if(await kvGet(env,key,null))return;const u=orderUsdLevels(o),side=String(o.side||"").toUpperCase(),tier=cycle.selectedTier||"A",micro=cycle.selectedMicroScore!=null?` | Micro ${Number(cycle.selectedMicroScore).toFixed(2)}`:"";await send(env,env.TELEGRAM_CHAT_ID,["PROP - HyroTrader",`${o.symbol} ${side} [${tier}]${micro}`,`SL ${o.sl} (~${usd2(u.slUsd)}) | TP ${o.tp} (~${usd2(u.tpUsd)})`].join("\n"));await kvPut(env,key,{sentAt:Date.now(),orderId:o.orderId||null,symbol:o.symbol},604800);}
function positionSnapshot(t){const m={};for(const p of t?.positions||[])m[p.symbol]={symbol:p.symbol,side:p.side,size:p.size,avgPrice:p.avgPrice};return m;}
async function notifyPropClosures(env){const t=await reconcileHyro(env);if(!t?.connected)return;const cur={at:Date.now(),positions:positionSnapshot(t),closedTradeCount:Number(t.closedTradeCount||0),closedNetPnlUsd:Number(t.closedNetPnlUsd||0)},prev=await kvGet(env,PROP_NOTIFY_SNAPSHOT_KEY,null);if(!prev){await kvPut(env,PROP_NOTIFY_SNAPSHOT_KEY,cur);return;}const closed=Object.keys(prev.positions||{}).filter(s=>!cur.positions[s]),delta=cur.closedNetPnlUsd-Number(prev.closedNetPnlUsd||0);if(closed.length){const key=`${PROP_NOTIFY_PREFIX}close:${closed.join("-")}:${cur.closedTradeCount}:${Math.round(cur.closedNetPnlUsd*100)}`;if(!(await kvGet(env,key,null))){await send(env,env.TELEGRAM_CHAT_ID,["PROP - HyroTrader",`${delta>0?"✅ TP/PROFIT":"❌ SL/LOSS"} ${closed.join(", ")}`,`P/L ${money(delta)}`].join("\n"));await kvPut(env,key,{at:Date.now()},604800);}}await kvPut(env,PROP_NOTIFY_SNAPSHOT_KEY,cur);}
function previewLine(x){if(!x)return null;const micro=x.microScore!=null?` M${Number(x.microScore).toFixed(2)}`:"";return `${x.tier||"C"} ${x.symbol} ${x.side||"—"} RR${Number(x.rr||0).toFixed(2)}${micro} ${x.strategy||""}`.trim();}
function quickScanText(r){const s=r?.scanSummary||{},t=s.tiers||{},pv=(r?.preview||[]).map(previewLine).filter(Boolean);if(r?.executed)return [`🔎 PROP • ĐÃ VÀO ${r.selectedTier||"A"}`,`${r.execution?.symbol||"—"} ${String(r.execution?.side||"").toUpperCase()}`,`Vốn ${cash(r.dynamicRisk?.capitalBasis)} | A/B/C ${t.A||0}/${t.B||0}/${t.C||0}`].join("\n");const map={NO_ABC_MARKET_ENTRY:"Chưa có A/B; tiếp tục chờ.",NO_ELIGIBLE_CANDIDATE:"Chưa có setup.",CANDIDATES_BLOCKED:"Setup chưa qua risk.",EXECUTION_REJECTED:"Execution bị từ chối.",MAX_ACTIVE_SLOTS_REACHED:"Đã đủ vị thế.",MANUAL_PAUSED:"AUTO đang dừng.",AUTO_EXECUTION_DISABLED:"AUTO OFF.",DAILY_PROFIT_TARGET_REACHED:"Đã đạt target ngày.",DAILY_HARD_STOP:"Đã chạm hard stop.",CYCLE_ERROR:"Quét lỗi — fail closed."};return [`🔎 PROP • ${map[r?.reason]||r?.reason||"WAIT"}`,`Vốn ${cash(r.dynamicRisk?.capitalBasis)} | Quét ${s.broadCount??"—"}/${s.deepCount??"—"} | A/B/C ${t.A||0}/${t.B||0}/${t.C||0}`,...pv.slice(0,3),`⏱ ${Number(r?.elapsedMs||0)}ms`].join("\n");}
async function dashboard(env){env=await propEnv(env);const p=await getHyroProfile(env),c=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env),kb=propKeyboard(c.manualPaused,cfg.mode);if(!p)return {text:"🏦 Hyro • Chưa cấu hình",kb};if(!t.connected)return {text:`🏦 Hyro • ${phaseName(p)}\nAPI lỗi: ${t.reason||"OFF"}`,kb};const d=t.day||{},r=hyroDynamicRiskView(p,t);return {text:[`🏦 Hyro • ${phaseName(p)} • ${programName(p)}`,`💰 ${cash(r.capitalBasis)} | P/L ${money(d.pnlFromDayStart||0)} | DD ${cash(d.drawdownFromPeak||0)}`,`Pos ${t.positions.length} | Pending ${t.openOrders.length} | Risk ${cash(t.openRiskUsd||0)}`,`AUTO ${c.manualPaused?"⛔ PAUSE":cfg.autoExecutionRequested?"▶ ON":"OFF"}`].join("\n"),kb};}
async function positionsText(env){env=await propEnv(env);const c=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env),kb=propKeyboard(c.manualPaused,cfg.mode);return {text:t.connected?`📈 Hyro Positions\n${t.positions.length?t.positions.map(posLine).join("\n\n"):"Không có vị thế."}`:`📈 Hyro • Telemetry ${t.reason||"OFF"}`,kb};}
async function riskText(env){env=await propEnv(env);const p=await getHyroProfile(env),c=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env),kb=propKeyboard(c.manualPaused,cfg.mode);if(!p||!t.connected)return {text:"🛡 Hyro Risk • unavailable",kb};const r=hyroDynamicRiskView(p,t);return {text:["🛡 Hyro Risk",`Vốn ${cash(r.capitalBasis)} | A ${cash(r.aPlusRiskUsd)} | B ${cash(r.aPlusRiskUsd*.5)}`,`Single ${cash(r.maxSingleWorstLossUsd)} | Combined ${cash(r.maxCombinedOpenRiskUsd)}`,`Hard ${cash(r.dailyHardStopUsd)} | Target ${cash(r.targetUsd)}`].join("\n"),kb};}
function endpointLine(x){return x.ok?`✅ ${x.name} ${x.elapsedMs}ms`:`❌ ${x.name} ${x.retCode??""} ${x.retMsg||"FAIL"}`.trim();}
async function connectText(env){env=await propEnv(env);const p=await getHyroProfile(env),c=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env),rt=await getHyroRuntime(env),kb=propKeyboard(c.manualPaused,cfg.mode),r=t.connected&&p?hyroDynamicRiskView(p,t):null;return {text:[`🔌 Hyro • ${cfg.mode} • ${t.connected?"CONNECTED":"OFF"}`,r?`Vốn ${cash(r.capitalBasis)}`:"",...(t.diagnostics?.endpoints||[]).map(endpointLine),`Engine ${rt?.reason||"—"} ${ago(rt?.finishedAt||rt?.startedAt)}`].filter(Boolean).join("\n"),kb};}
const demoTestText=r=>r?.ok?`🧪 Order ✅ ${r.symbol} | SL/TP ${r.nativeSlTpVerified?"✅":"⚠️"}`:`🧪 Order ❌ ${r?.error||"FAIL"}`;
const fullCycleText=r=>r?.ok?`🧪 Cycle ✅ ${r.symbol} | P/L ${r.closedPnl??"—"}`:`🧪 Cycle ❌ ${r?.error||"FAIL"}`;
async function handlePropTelegram(req,env){if(!verify(req,env))return json({ok:false,error:"invalid telegram secret"},403);let u;try{u=await req.clone().json();}catch{return null;}const cb=u?.callback_query?.data,allowed=["prop","prop:hyro","prop:dashboard","prop:positions","prop:risklive","prop:connectlive","prop:quickscan","prop:demotest","prop:fullcycletest","prop:pause","prop:resume"];if(!allowed.includes(cb))return null;if(u?.callback_query?.id)tg(env,"answerCallbackQuery",{callback_query_id:u.callback_query.id}).catch(()=>{});const chatId=u?.callback_query?.message?.chat?.id??env.TELEGRAM_CHAT_ID;env=await propEnv(env);const cfg=hyroExecutionConfig(env);if((cb==="prop:demotest"||cb==="prop:fullcycletest")&&cfg.mode!=="DEMO")return json({ok:false,blocked:"NON_DEMO_MODE"},409);if(cb==="prop:pause"){const c=await setHyroPaused(env,true);await cancelHyroPending(env).catch(()=>{});await send(env,chatId,"⛔ Hyro AUTO dừng",propKeyboard(c.manualPaused,cfg.mode));return json({ok:true});}if(cb==="prop:resume"){const c=await setHyroPaused(env,false);await send(env,chatId,"▶ Hyro AUTO bật",propKeyboard(c.manualPaused,cfg.mode));return json({ok:true});}if(cb==="prop:quickscan"){const cycle=await runHyroAutoCycle(env,{marketOnly:true});await notifyPropEntry(env,cycle).catch(()=>{});await notifyPropClosures(env).catch(()=>{});const c=await getHyroControl(env);await send(env,chatId,quickScanText(cycle),propKeyboard(c.manualPaused,cfg.mode));return json({ok:cycle.ok,result:cycle});}if(cb==="prop:demotest"){const r=await runHyroDemoExecutionTest(env),c=await getHyroControl(env);await send(env,chatId,demoTestText(r),propKeyboard(c.manualPaused,cfg.mode));return json({ok:r.ok,result:r});}if(cb==="prop:fullcycletest"){const r=await runHyroDemoFullCycleTest(env),c=await getHyroControl(env);await send(env,chatId,fullCycleText(r),propKeyboard(c.manualPaused,cfg.mode));return json({ok:r.ok,result:r});}const x=cb==="prop:positions"?await positionsText(env):cb==="prop:risklive"?await riskText(env):cb==="prop:connectlive"?await connectText(env):await dashboard(env);await send(env,chatId,x.text,x.kb);return json({ok:true,version:VERSION});}
async function patchedStatus(req,env){const r=await signalHub.fetch(req,env);let p;try{p=await r.clone().json();}catch{return r;}const pe=await propEnv(env),cfg=hyroExecutionConfig(pe),control=await getHyroControl(pe),runtime=await getHyroRuntime(pe);return json({...p,version:VERSION,service:SERVICE,architecture:{signal:"INDEPENDENT",prop:"INDEPENDENT",personal:"INDEPENDENT"},hyro:{...cfg,manualPaused:control.manualPaused,quickMarketScan:"ABC_MICRO",microstructure:["OPEN_INTEREST","LONG_SHORT_RATIO","ORDERBOOK","SPREAD"],autoReconnect:true,dynamicEquitySizing:true,lastRuntime:runtime}},r.status);}
export default {async fetch(req,env,ctx){ctx?.waitUntil?.(refreshPropConnection(env));const path=new URL(req.url).pathname;if(path.startsWith("/prop/hyro/")){const pe=await propEnv(env);if(path==="/prop/hyro/telemetry")return json(await getHyroTelemetry(pe));if(path==="/prop/hyro/diagnostics")return json(await getHyroDiagnostics(pe));if(path==="/prop/hyro/reconcile")return json(await reconcileHyro(pe));if(path==="/prop/hyro/runtime")return json({ok:true,version:VERSION,runtime:await getHyroRuntime(pe)});if(path==="/prop/hyro/demo-test-state")return json({ok:true,version:VERSION,state:await getHyroDemoTestState(pe)});}if(path==="/telegram/webhook"&&req.method==="POST"){const handled=await handlePropTelegram(req,env);if(handled)return handled;}if(path==="/status")return patchedStatus(req,env);return signalHub.fetch(req,env,ctx);},async scheduled(event,env,ctx){ctx.waitUntil((async()=>{const pe=await propEnv(env);await getHyroTelemetry(pe).catch(()=>null);const cycle=await runHyroAutoCycle(pe);await notifyPropEntry(pe,cycle).catch(()=>{});await notifyPropClosures(pe).catch(()=>{});})().catch(()=>{}));return signalHub.scheduled?.(event,env,ctx);}};
