import signalHub from "./hub-v77171.js";
import {getHyroProfile,getHyroControl,setHyroPaused,getHyroTelemetry,getHyroDiagnostics,reconcileHyro,cancelHyroPending,hyroExecutionConfig} from "./hyro-execution.js";
import {runHyroAutoCycle,getHyroRuntime} from "./hyro-runtime.js";
import {runHyroDemoExecutionTest,runHyroDemoFullCycleTest,getHyroDemoTestState} from "./hyro-demo-test.js";

const VERSION="V77.18.6";
const SERVICE="Trading V77.18.6 Independent Signal-Prop-Personal Runtime";
const json=(body,status=200)=>new Response(JSON.stringify(body,null,2),{status,headers:{"content-type":"application/json; charset=utf-8"}});
const money=v=>{const x=Number(v||0),sign=x>0?"+":"";return sign+"$"+x.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});};
const cash=v=>"$"+Number(v||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
const ago=ts=>{if(!ts)return "—";const s=Math.max(0,Math.round((Date.now()-Number(ts))/1000));if(s<60)return `${s}s trước`;const m=Math.round(s/60);if(m<60)return `${m}m trước`;return `${Math.round(m/60)}h trước`;};
async function tg(env,method,payload){const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),p=await r.json();if(!p.ok)throw new Error(p.description||"Telegram error");return p;}
async function send(env,chatId,text,reply_markup){return tg(env,"sendMessage",{chat_id:chatId,text,reply_markup,disable_web_page_preview:true});}
function verify(req,env){return !env.TELEGRAM_WEBHOOK_SECRET||req.headers.get("x-telegram-bot-api-secret-token")===env.TELEGRAM_WEBHOOK_SECRET;}
function phaseName(p){return p?.phase==="FUNDED"?"FUNDED":"CHALLENGE";}
function programName(p){return p?.program==="TWO_STEP"?"Two-Step":"One-Step";}
function ddName(p){return p?.drawdownType==="SWING_STATIC"?"Swing / Static":"Standard / Trailing";}
function propKeyboard(paused=false,mode="DEMO"){
  const rows=[
    [{text:"📊 TỔNG QUAN TÀI KHOẢN",callback_data:"prop:dashboard"}],
    [{text:"📈 VỊ THẾ ĐANG CHẠY",callback_data:"prop:positions"},{text:"🛡️ RISK / DD",callback_data:"prop:risklive"}],
    [{text:"🔌 KẾT NỐI",callback_data:"prop:connectlive"}]
  ];
  if(mode==="DEMO"){rows.push([{text:"🧪 TEST ORDER DEMO",callback_data:"prop:demotest"}]);rows.push([{text:"🧪 TEST FULL CYCLE DEMO",callback_data:"prop:fullcycletest"}]);}
  rows.push([{text:paused?"▶️ TIẾP TỤC AUTO":"⛔ NGỪNG AUTO",callback_data:paused?"prop:resume":"prop:pause"}]);
  rows.push([{text:"⚙️ ĐỔI CẤU HÌNH",callback_data:"prop:setup"}]);
  rows.push([{text:"⬅️ MENU CHÍNH",callback_data:"menu"}]);
  return {inline_keyboard:rows};
}
function posLine(p,i){const icon=(p.unrealisedPnl||0)>=0?"🟢":"🔴",side=p.side==="Buy"?"BUY":"SELL";return `${i+1}. ${icon} ${p.symbol} ${side}\n   Entry ${p.avgPrice} → Mark ${p.markPrice}\n   P/L ${money(p.unrealisedPnl)} | Size ${p.size}\n   SL ${p.stopLoss||"—"} | TP ${p.takeProfit||"—"}`;}
async function dashboard(env){const profile=await getHyroProfile(env),control=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env),kb=propKeyboard(control.manualPaused,cfg.mode);if(!profile)return {text:"🏦 PROP • HYROTRADER\n\nChưa cấu hình tài khoản.",kb};if(!t.connected)return {text:`🏦 HYROTRADER • ${phaseName(profile)}\n\nMode: ${cfg.mode}\nAPI: CHƯA ĐỦ TELEMETRY (${t.reason||"UNKNOWN"})\nAUTO: ${control.manualPaused?"PAUSED":cfg.autoExecutionRequested?"ARMED - FAIL CLOSED":"OFF"}`,kb};const d=t.day||{},target=Number(profile.accountSize||0)*.05,remain=Math.max(0,target-Number(d.pnlFromDayStart||0));return {text:[`🏦 HYROTRADER • ${phaseName(profile)}`,"",`${programName(profile)} • ${ddName(profile)}`,`Mode: ${cfg.mode}`,`Equity: ${cash(t.equity)}`,`Wallet: ${cash(t.walletBalance)}`,`Available: ${cash(t.available)}`,"",`📅 P/L equity hôm nay: ${money(d.pnlFromDayStart||0)}`,`🧾 Net đã chốt: ${money(d.netRealized||0)}`,`💹 Floating: ${money(t.totalUnrealised||0)}`,`🔢 Lệnh đã đóng: ${Number(d.closedTrades||0)}`,"",`📈 Peak equity: ${cash(d.peakEquity)}`,`📉 DD từ peak: -${cash(d.drawdownFromPeak||0)}`,`🎯 Target ngày +5%: ${cash(target)}`,`Còn tới target: ${cash(remain)}`,"",`Positions: ${t.positions.length} | Pending: ${t.openOrders.length}`,`Open-risk: ${cash(t.openRiskUsd||0)}`,`AUTO: ${control.manualPaused?"⛔ PAUSED":cfg.autoExecutionRequested?"▶️ ON":"OFF"}`].join("\n"),kb};}
async function positionsText(env){const t=await getHyroTelemetry(env),c=await getHyroControl(env),cfg=hyroExecutionConfig(env),kb=propKeyboard(c.manualPaused,cfg.mode);if(!t.connected)return {text:`📈 VỊ THẾ HYRO\n\nTelemetry chưa đủ: ${t.reason||"NOT_CONNECTED"}.\nExecution đang fail-closed.`,kb};return {text:`📈 VỊ THẾ HYRO ĐANG CHẠY\n\n${t.positions.length?t.positions.map(posLine).join("\n\n"):"Không có vị thế đang mở."}\n\nFloating tổng: ${money(t.totalUnrealised||0)}\nOpen-risk: ${cash(t.openRiskUsd||0)}`,kb};}
async function riskText(env){const p=await getHyroProfile(env),t=await getHyroTelemetry(env),c=await getHyroControl(env),cfg=hyroExecutionConfig(env),kb=propKeyboard(c.manualPaused,cfg.mode);if(!p)return {text:"🛡️ RISK HYRO\n\nChưa cấu hình account.",kb};if(!t.connected)return {text:`🛡️ RISK HYRO • ${phaseName(p)}\n\n⚠️ RISK/DD LIVE: UNAVAILABLE\nBot fail-closed.`,kb};const i=p.internal||{},o=p.official||{},d=t.day||{};return {text:[`🛡️ RISK HYRO • ${phaseName(p)}`,"",`Official daily DD: ${o.dailyDrawdownPct??"—"}% = ${cash(o.dailyDrawdownUsd)}`,`Official max loss: ${o.maxLossPct??"—"}% = ${cash(o.maxLossUsd)}`,`Bot hard stop ngày: ${cash(i.dailyHardStopUsd)}`,`Single worst-loss cap: ${cash(i.maxSingleWorstLossUsd)}`,`Combined open-risk cap: ${cash(i.maxCombinedOpenRiskUsd)}`,"",`DD hiện tại từ peak: ${cash(d.drawdownFromPeak||0)}`,`P/L equity hôm nay: ${money(d.pnlFromDayStart||0)}`,`Open-risk hiện tại: ${cash(t.openRiskUsd||0)}`,`Manual control: ${c.manualPaused?"PAUSED":"READY"}`].join("\n"),kb};}
function endpointLine(x){if(x.ok)return `✅ ${x.name}: PASS (${x.elapsedMs}ms)`;return `❌ ${x.name}: ${x.retCode!=null?`${x.retCode} ${x.retMsg||""}`:(x.retMsg||"FAIL")}`;}
function runtimeLabel(rt,cfg,t){if(!rt)return "WAITING_FIRST_CYCLE";if(rt.mode&&rt.mode!==cfg.mode)return "WAITING_FIRST_"+cfg.mode+"_CYCLE";if(t.connected&&rt.reason==="TELEMETRY_ERROR")return "WAITING_NEXT_CYCLE";return rt.reason||(rt.executed?"ORDER_SUBMITTED":"IDLE");}
async function connectText(env){const p=await getHyroProfile(env),c=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env),rt=await getHyroRuntime(env),dt=cfg.mode==="DEMO"?await getHyroDemoTestState(env):null,ep=t.diagnostics?.endpoints||[],runtimeState=runtimeLabel(rt,cfg,t),runtimeAt=rt?.finishedAt||rt?.startedAt||rt?.at||null,kb=propKeyboard(c.manualPaused,cfg.mode);return {text:["🔌 HYROTRADER CONNECTION","",`Profile: ${p?phaseName(p)+" • "+programName(p)+" • "+ddName(p):"CHƯA CẤU HÌNH"}`,`Mode: ${cfg.mode}`,`Credentials: ${cfg.credentialsReady?"OK":"MISSING"}`,`Fresh telemetry: ${t.connected?"CONNECTED":"NOT CONNECTED"}`,`Auto execution secret: ${cfg.autoExecutionRequested?"ON":"OFF"}`,`Manual pause: ${c.manualPaused?"ON":"OFF"}`,"",...ep.map(endpointLine),"",`Auto engine: ${runtimeState}${runtimeAt?` (${ago(runtimeAt)})`:""}`,rt?.candidateCount!=null?`Cycle candidates: ${rt.candidateCount}`:null,rt?.error?`Cycle error: ${String(rt.error).slice(0,160)}`:null,dt?`Last DEMO test: ${dt.ok?"PASS":"FAIL"}${dt.finishedAt?` (${ago(dt.finishedAt)})`:""}`:null,"",cfg.mode==="LIVE"?"🔴 LIVE execution: chỉ scanner PROP độc lập + Risk Firewall mới được phép gửi lệnh thật.":"🧪 DEMO mode: test controls available."].filter(Boolean).join("\n"),kb};}
function demoTestText(r){if(!r?.ok)return ["🧪 HYRO DEMO ORDER TEST","","❌ TEST FAIL",`Lỗi: ${r?.error||"UNKNOWN"}`].join("\n");return ["🧪 HYRO DEMO ORDER TEST","","✅ CREATE ORDER: PASS","✅ VERIFY ORDER: PASS",`Native SL/TP: ${r.nativeSlTpVerified?"✅ VERIFIED":"⚠️ NOT VERIFIED"}`,`Cancel: ${r.cancelled?"✅ PASS":"❌ FAIL"}`,"",`Symbol: ${r.symbol}`,`Qty: ${r.qty}`,`Limit: ${r.limitPrice}`,`SL: ${r.stopLoss}`,`TP: ${r.takeProfit}`,"","Đây là order thật trên Bybit DEMO, không phải LIVE."].join("\n");}
function fullCycleText(r){if(!r?.ok)return ["🧪 HYRO FULL CYCLE DEMO","","❌ TEST FAIL",`Lỗi: ${r?.error||"UNKNOWN"}`].join("\n");return ["🧪 HYRO FULL CYCLE DEMO","","✅ MARKET OPEN: PASS","✅ POSITION VISIBLE: PASS",`Native SL/TP: ${r.nativeSlTpVerified?"✅ VERIFIED":"❌ FAIL"}`,"✅ MARKET CLOSE: PASS","✅ POSITION FLAT: PASS",`Closed PnL history: ${r.closedPnlVerified?"✅ VERIFIED":"⚠️ PENDING/NOT FOUND"}`,"",`Symbol: ${r.symbol}`,`Qty: ${r.qty}`,`Entry: ${r.entryPrice||"—"}`,`SL: ${r.stopLoss||"—"}`,`TP: ${r.takeProfit||"—"}`,`Closed PnL: ${r.closedPnl??"—"}`,`Exit: ${r.avgExitPrice??"—"}`,`Elapsed: ${r.elapsedMs}ms`].join("\n");}
async function handlePropTelegram(req,env){if(!verify(req,env))return json({ok:false,error:"invalid telegram secret"},403);let u;try{u=await req.clone().json();}catch{return null;}const cb=u?.callback_query?.data;if(!["prop","prop:hyro","prop:dashboard","prop:positions","prop:risklive","prop:connectlive","prop:demotest","prop:fullcycletest","prop:pause","prop:resume"].includes(cb))return null;if(u?.callback_query?.id)tg(env,"answerCallbackQuery",{callback_query_id:u.callback_query.id}).catch(()=>{});const chatId=u?.callback_query?.message?.chat?.id??env.TELEGRAM_CHAT_ID,cfg=hyroExecutionConfig(env);if((cb==="prop:demotest"||cb==="prop:fullcycletest")&&cfg.mode!=="DEMO"){const c=await getHyroControl(env);await send(env,chatId,"⛔ DEMO TEST BỊ KHÓA\n\nWorker đang ở LIVE. Không có test order nào được phép chạy trên tài khoản Challenge.",propKeyboard(c.manualPaused,cfg.mode));return json({ok:false,blocked:true,reason:"DEMO_TEST_BLOCKED_IN_LIVE"});}if(cb==="prop:pause"){const c=await setHyroPaused(env,true);await cancelHyroPending(env).catch(()=>{});await send(env,chatId,"⛔ HYRO AUTO ĐÃ DỪNG\n\nChặn lệnh PROP mới; monitoring và bảo vệ vị thế hiện có vẫn hoạt động.",propKeyboard(c.manualPaused,cfg.mode));return json({ok:true});}if(cb==="prop:resume"){const c=await setHyroPaused(env,false);await send(env,chatId,"▶️ HYRO AUTO ĐÃ CHO PHÉP HOẠT ĐỘNG\n\nLệnh chỉ được gửi khi telemetry + scanner + Risk Firewall đều PASS.",propKeyboard(c.manualPaused,cfg.mode));return json({ok:true});}if(cb==="prop:demotest"){const r=await runHyroDemoExecutionTest(env),c=await getHyroControl(env);await send(env,chatId,demoTestText(r),propKeyboard(c.manualPaused,cfg.mode));return json({ok:r.ok,result:r});}if(cb==="prop:fullcycletest"){const r=await runHyroDemoFullCycleTest(env),c=await getHyroControl(env);await send(env,chatId,fullCycleText(r),propKeyboard(c.manualPaused,cfg.mode));return json({ok:r.ok,result:r});}let x;if(cb==="prop:positions")x=await positionsText(env);else if(cb==="prop:risklive")x=await riskText(env);else if(cb==="prop:connectlive")x=await connectText(env);else x=await dashboard(env);await send(env,chatId,x.text,x.kb);return json({ok:true,version:VERSION});}
async function patchedStatus(req,env){const r=await signalHub.fetch(req,env);let p;try{p=await r.clone().json();}catch{return r;}const cfg=hyroExecutionConfig(env),control=await getHyroControl(env),runtime=await getHyroRuntime(env),demoTest=cfg.mode==="DEMO"?await getHyroDemoTestState(env):null;return json({...p,version:VERSION,service:SERVICE,architecture:{signal:"INDEPENDENT_TELEGRAM_SIGNAL_ONLY",prop:"INDEPENDENT_HYRO_SILENT_AUTO_ACCOUNT_DASHBOARD",personal:"INDEPENDENT_RESERVED_RUNTIME"},hyro:{...cfg,manualPaused:control.manualPaused,silentTelegram:true,lastRuntime:runtime,lastDemoTest:demoTest}},r.status);}
export default {async fetch(req,env,ctx){const url=new URL(req.url),path=url.pathname;if(path==="/prop/hyro/telemetry")return json(await getHyroTelemetry(env));if(path==="/prop/hyro/diagnostics")return json(await getHyroDiagnostics(env));if(path==="/prop/hyro/reconcile")return json(await reconcileHyro(env));if(path==="/prop/hyro/runtime")return json({ok:true,version:VERSION,runtime:await getHyroRuntime(env)});if(path==="/prop/hyro/demo-test-state")return json({ok:true,version:VERSION,state:await getHyroDemoTestState(env)});if(path==="/telegram/webhook"&&req.method==="POST"){const handled=await handlePropTelegram(req,env);if(handled)return handled;}if(path==="/status")return patchedStatus(req,env);return signalHub.fetch(req,env,ctx);},async scheduled(event,env,ctx){ctx.waitUntil(runHyroAutoCycle(env).catch(()=>{}));return signalHub.scheduled?.(event,env,ctx);}};
