import signalHub from "./hub-v77171.js";
import {getHyroProfile,getHyroControl,setHyroPaused,getHyroTelemetry,reconcileHyro,cancelHyroPending,hyroExecutionConfig} from "./hyro-execution.js";
import {runHyroAutoCycle,getHyroRuntime} from "./hyro-runtime.js";
import {hyroDynamicScan} from "./hyro-scanner.js";

const VERSION="V77.18.0";
const SERVICE="Trading V77.18.0 Independent Signal-Prop-Personal Runtime";
const json=(body,status=200)=>new Response(JSON.stringify(body,null,2),{status,headers:{"content-type":"application/json; charset=utf-8"}});
const money=v=>{const x=Number(v||0),sign=x>0?"+":"";return sign+"$"+x.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});};
async function tg(env,method,payload){const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),p=await r.json();if(!p.ok)throw new Error(p.description||"Telegram error");return p;}
async function send(env,chatId,text,reply_markup){return tg(env,"sendMessage",{chat_id:chatId,text,reply_markup,disable_web_page_preview:true});}
function verify(req,env){return !env.TELEGRAM_WEBHOOK_SECRET||req.headers.get("x-telegram-bot-api-secret-token")===env.TELEGRAM_WEBHOOK_SECRET;}
function phaseName(p){return p?.phase==="FUNDED"?"FUNDED":"CHALLENGE";}
function programName(p){return p?.program==="TWO_STEP"?"Two-Step":"One-Step";}
function ddName(p){return p?.drawdownType==="SWING_STATIC"?"Swing / Static":"Standard / Trailing";}
function propKeyboard(paused=false){return {inline_keyboard:[[{text:"📊 TỔNG QUAN TÀI KHOẢN",callback_data:"prop:dashboard"}],[{text:"📈 VỊ THẾ ĐANG CHẠY",callback_data:"prop:positions"},{text:"🛡️ RISK / DD",callback_data:"prop:risklive"}],[{text:"🪙 AUTO UNIVERSE",callback_data:"prop:universe"},{text:"🔌 KẾT NỐI",callback_data:"prop:connectlive"}],[{text:paused?"▶️ TIẾP TỤC AUTO":"⛔ NGỪNG AUTO",callback_data:paused?"prop:resume":"prop:pause"}],[{text:"⚙️ ĐỔI CẤU HÌNH",callback_data:"prop:setup"}],[{text:"⬅️ MENU CHÍNH",callback_data:"menu"}]]};}
function posLine(p,i){const icon=(p.unrealisedPnl||0)>=0?"🟢":"🔴",side=p.side==="Buy"?"BUY":"SELL";return `${i+1}. ${icon} ${p.symbol} ${side}\n   Entry ${p.avgPrice} → Mark ${p.markPrice}\n   P/L ${money(p.unrealisedPnl)} | Size ${p.size}\n   SL ${p.stopLoss||"—"} | TP ${p.takeProfit||"—"}`;}
async function dashboard(env){const profile=await getHyroProfile(env),control=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env);if(!profile)return {text:"🏦 PROP • HYROTRADER\n\nChưa cấu hình tài khoản. Bấm ⚙️ ĐỔI CẤU HÌNH để bắt đầu.",kb:propKeyboard(control.manualPaused)};if(!t.connected)return {text:[`🏦 HYROTRADER • ${phaseName(profile)}`,"",`${money(profile.accountSize).replace("+$", "$" )} • ${programName(profile)} • ${ddName(profile)}`,`API: CHƯA KẾT NỐI (${t.reason||"UNKNOWN"})`,`AUTO: ${control.manualPaused?"PAUSED":cfg.autoExecutionRequested?"ARMED - WAIT API":"OFF"}`,"","PROP hoàn toàn độc lập với SIGNAL và CÁ NHÂN."].join("\n"),kb:propKeyboard(control.manualPaused)};const d=t.day||{},target=Number(profile.accountSize||0)*.05,dayPnl=Number(d.pnlFromDayStart||0),remain=Math.max(0,target-dayPnl);return {text:[`🏦 HYROTRADER • ${phaseName(profile)}`,"",`${programName(profile)} • ${ddName(profile)}`,`Equity: ${money(t.equity)}`,`Wallet: ${money(t.walletBalance)}`,`Available: ${money(t.available)}`,"",`📅 P/L hôm nay: ${money(dayPnl)}`,`📈 Peak equity: ${money(d.peakEquity)}`,`📉 DD từ peak: -$${Number(d.drawdownFromPeak||0).toFixed(2)}`,`🎯 Target ngày +5%: ${money(target)}`,`Còn tới target: ${money(remain)}`,"",`Positions: ${t.positions.length} | Pending: ${t.openOrders.length}`,`Floating tổng: ${money(t.totalUnrealised)}`,`Open-risk ước tính: $${Number(t.openRiskUsd||0).toFixed(2)}`,`AUTO: ${control.manualPaused?"⛔ PAUSED":cfg.autoExecutionRequested?"▶️ ON":"OFF"}`,"",`Telegram PROP chỉ theo dõi tài khoản. Auto entry không được gửi lên Telegram.`].join("\n"),kb:propKeyboard(control.manualPaused)};}
async function positionsText(env){const t=await getHyroTelemetry(env),c=await getHyroControl(env);if(!t.connected)return {text:`📈 VỊ THẾ HYRO\n\nChưa đọc được tài khoản: ${t.reason||"NOT_CONNECTED"}`,kb:propKeyboard(c.manualPaused)};const body=t.positions.length?t.positions.map(posLine).join("\n\n"):"Không có vị thế đang mở.";return {text:`📈 VỊ THẾ HYRO ĐANG CHẠY\n\n${body}\n\nFloating tổng: ${money(t.totalUnrealised)}\nP/L hôm nay: ${money(t.day?.pnlFromDayStart||0)}`,kb:propKeyboard(c.manualPaused)};}
async function riskText(env){const p=await getHyroProfile(env),t=await getHyroTelemetry(env),c=await getHyroControl(env);if(!p)return {text:"🛡️ RISK HYRO\n\nChưa cấu hình account.",kb:propKeyboard(c.manualPaused)};const i=p.internal||{},o=p.official||{};return {text:[`🛡️ RISK HYRO • ${phaseName(p)}`,"",`Official daily DD: ${o.dailyDrawdownPct??"—"}% = $${Number(o.dailyDrawdownUsd||0).toFixed(0)}`,`Official max loss: ${o.maxLossPct??"—"}% = $${Number(o.maxLossUsd||0).toFixed(0)}`,`Bot hard stop ngày: $${Number(i.dailyHardStopUsd||0).toFixed(0)} (<3%)`,`Single worst-loss cap: $${Number(i.maxSingleWorstLossUsd||0).toFixed(0)}`,`Combined open-risk cap: $${Number(i.maxCombinedOpenRiskUsd||0).toFixed(0)}`,"",`DD hiện tại từ peak: $${Number(t.day?.drawdownFromPeak||0).toFixed(2)}`,`P/L hôm nay: ${money(t.day?.pnlFromDayStart||0)}`,`Manual control: ${c.manualPaused?"PAUSED":"READY"}`].join("\n"),kb:propKeyboard(c.manualPaused)};}
async function universeText(env){const c=await getHyroControl(env);try{const s=await hyroDynamicScan({maxBroad:100,maxDeep:10,minTurnover:10000000}),rows=(s.results||[]).slice(0,10).map((x,i)=>`${i+1}. ${x.symbol} • ${x.status}${x.side?" • "+x.side:""}${x.rr?" • RR "+x.rr.toFixed(2):""}`);return {text:["🪙 HYRO AUTO UNIVERSE","",`Broad eligible: ${s.broadCount}`,`Deep independent scan: ${s.deepCount}`,"Nguồn lệnh: HYRO scanner riêng, KHÔNG lấy từ SIGNAL.","",...(rows.length?rows:["Chưa có candidate."])].join("\n"),kb:propKeyboard(c.manualPaused)};}catch(e){return {text:`🪙 HYRO AUTO UNIVERSE\n\nLỗi scan: ${String(e?.message||e)}`,kb:propKeyboard(c.manualPaused)};}}
async function connectText(env){const p=await getHyroProfile(env),c=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env),rt=await getHyroRuntime(env);return {text:["🔌 HYROTRADER CONNECTION","",`Profile: ${p?phaseName(p)+" • "+programName(p)+" • "+ddName(p):"CHƯA CẤU HÌNH"}`,`Mode: ${cfg.mode}`,`Credentials: ${cfg.credentialsReady?"OK":"MISSING"}`,`Telemetry: ${t.connected?"CONNECTED":"NOT CONNECTED"}`,`Auto execution secret: ${cfg.autoExecutionRequested?"ON":"OFF"}`,`Manual pause: ${c.manualPaused?"ON":"OFF"}`,`Last auto cycle: ${rt?.reason||rt?.execution?.symbol||"—"}`,"","API Secret chỉ đặt ở Cloudflare Secret. Telegram không nhận/hiển thị API key."].join("\n"),kb:propKeyboard(c.manualPaused)};}
async function handlePropTelegram(req,env){if(!verify(req,env))return json({ok:false,error:"invalid telegram secret"},403);let u;try{u=await req.clone().json();}catch{return null;}const cb=u?.callback_query?.data;if(!["prop","prop:hyro","prop:dashboard","prop:positions","prop:risklive","prop:universe","prop:connectlive","prop:pause","prop:resume"].includes(cb))return null;if(u?.callback_query?.id)tg(env,"answerCallbackQuery",{callback_query_id:u.callback_query.id}).catch(()=>{});const chatId=u?.callback_query?.message?.chat?.id??env.TELEGRAM_CHAT_ID;if(cb==="prop:pause"){const c=await setHyroPaused(env,true);await cancelHyroPending(env).catch(()=>{});await send(env,chatId,"⛔ HYRO AUTO ĐÃ DỪNG\n\nChỉ chặn PROP mở lệnh mới. SIGNAL, CÁ NHÂN, monitoring tài khoản và quản lý vị thế hiện có vẫn hoạt động.",propKeyboard(c.manualPaused));return json({ok:true,version:VERSION,manualPaused:true});}if(cb==="prop:resume"){const c=await setHyroPaused(env,false);await send(env,chatId,"▶️ HYRO AUTO ĐÃ CHO PHÉP HOẠT ĐỘNG\n\nChỉ thực sự gửi order nếu API connected + HYRO_AUTO_EXECUTION=true + Risk Firewall PASS.",propKeyboard(c.manualPaused));return json({ok:true,version:VERSION,manualPaused:false});}let x;if(cb==="prop:positions")x=await positionsText(env);else if(cb==="prop:risklive")x=await riskText(env);else if(cb==="prop:universe")x=await universeText(env);else if(cb==="prop:connectlive")x=await connectText(env);else x=await dashboard(env);await send(env,chatId,x.text,x.kb);return json({ok:true,version:VERSION,propDashboard:true});}
async function patchedStatus(req,env){const r=await signalHub.fetch(req,env);let p;try{p=await r.clone().json();}catch{return r;}const cfg=hyroExecutionConfig(env),control=await getHyroControl(env),runtime=await getHyroRuntime(env);return json({...p,version:VERSION,service:SERVICE,architecture:{signal:"INDEPENDENT_TELEGRAM_SIGNAL_ONLY",prop:"INDEPENDENT_HYRO_AUTO_PLUS_ACCOUNT_DASHBOARD",personal:"INDEPENDENT_RESERVED_RUNTIME"},hyro:{...cfg,manualPaused:control.manualPaused,silentTelegram:true,lastRuntime:runtime}},r.status);}
export default {async fetch(req,env,ctx){const u=new URL(req.url),path=u.pathname.replace(/\/$/,"")||"/";if(path==="/status")return patchedStatus(req,env);if(path==="/prop/hyro/telemetry")return json(await getHyroTelemetry(env));if(path==="/prop/hyro/reconcile")return json(await reconcileHyro(env));if(path==="/prop/hyro/runtime")return json({ok:true,version:VERSION,runtime:await getHyroRuntime(env)});if(path==="/telegram/webhook"&&req.method==="POST"){const handled=await handlePropTelegram(req,env);if(handled)return handled;}return signalHub.fetch(req,env,ctx);},async scheduled(controller,env,ctx){const signalPromise=Promise.resolve(signalHub.scheduled?.(controller,env,ctx)).catch(()=>null),hyroPromise=runHyroAutoCycle(env).catch(async e=>{if(env.TRADING_STATE)await env.TRADING_STATE.put("v7718:hyro:runtime",JSON.stringify({ok:false,error:String(e?.message||e),at:Date.now()}));return null;});if(ctx?.waitUntil){ctx.waitUntil(signalPromise);ctx.waitUntil(hyroPromise);return;}await Promise.allSettled([signalPromise,hyroPromise]);}};
