import fs from 'node:fs';
const PAPER='/var/lib/meme-alpha/data/paper/state.json', OUT='/var/lib/meme-alpha/data/paper/validation.json', SAFE='/opt/meme-alpha/app/runtime-status/validation.json';
const s=JSON.parse(fs.readFileSync(PAPER,'utf8')); const trades=s.trades||[], open=s.openPositions||[];
const buys=trades.filter(x=>x.type==='PAPER_BUY_PROBE'), sells=trades.filter(x=>x.type==='PAPER_SELL'); const byId=new Map(); const integrity=[];
for(const b of buys){if(!b.positionId) continue; const r=byId.get(b.positionId)||{positionId:b.positionId,mint:b.mint,symbol:b.symbol,openedAt:b.timestamp,buyEvents:0,sellEvents:0,realizedPnlSol:0,exitReasons:[]}; r.buyEvents++; byId.set(b.positionId,r);}
for(const x of sells){if(!x.positionId) continue; const r=byId.get(x.positionId)||{positionId:x.positionId,mint:x.mint,symbol:x.symbol,buyEvents:0,sellEvents:0,realizedPnlSol:0,exitReasons:[]}; r.sellEvents++; r.realizedPnlSol+=Number(x.pnlSol||0); r.lastSellAt=x.timestamp; if(x.reason) r.exitReasons.push(x.reason); byId.set(x.positionId,r);}
const openIds=new Set(open.map(p=>p.id||p.positionId).filter(Boolean));
const lifecycles=[...byId.values()].map(r=>{const closed=!openIds.has(r.positionId)&&r.buyEvents>0; const opened=Date.parse(r.openedAt||0), ended=Date.parse(r.lastSellAt||0); return {...r,closed,realizedPnlSol:Number(r.realizedPnlSol.toFixed(10)),durationSec:closed&&Number.isFinite(opened)&&Number.isFinite(ended)?Math.max(0,(ended-opened)/1000):null};});
for(const r of lifecycles){if(r.buyEvents===0&&r.sellEvents>0) integrity.push(`ORPHAN_SELL_${r.positionId}`); if(r.buyEvents>1) integrity.push(`DUPLICATE_BUY_${r.positionId}`);}
const completed=lifecycles.filter(x=>x.closed), pnls=completed.map(x=>x.realizedPnlSol), wins=pnls.filter(x=>x>0), losses=pnls.filter(x=>x<0), sum=a=>a.reduce((x,y)=>x+y,0), gp=sum(wins), gl=Math.abs(sum(losses));
const equity=Number(s.equitySol||0), start=Number(s.startingEquitySol||1), high=Number(s.highWaterEquitySol||equity), ret=start>0?(equity/start-1)*100:0, dd=high>0?(1-equity/high)*100:0, expectancy=completed.length?sum(pnls)/completed.length:0, pf=gl>0?gp/gl:(gp>0?Infinity:0);
const criteria={minCompletedLifecycles:completed.length>=20,positiveExpectancy:expectancy>0,profitFactorAtLeast1_10:pf>=1.10,currentDrawdownBelow12Pct:dd<12,dataIntegrityClean:integrity.length===0};
let readinessStatus='ACCUMULATING'; if(completed.length>=20) readinessStatus=Object.values(criteria).every(Boolean)?'PASS':'FAIL';
const result={version:'1.6',timestamp:new Date().toISOString(),readinessStatus,readinessCriteria:criteria,startingEquitySol:start,equitySol:equity,equityReturnPct:Number(ret.toFixed(4)),highWaterEquitySol:high,currentDrawdownPct:Number(dd.toFixed(4)),openPositions:open.length,probeEntries:buys.length,realizedSellEvents:sells.length,lifecycleTrades:lifecycles.length,completedLifecycleTrades:completed.length,winningLifecycleTrades:wins.length,losingLifecycleTrades:losses.length,winRatePct:completed.length?Number((wins.length/completed.length*100).toFixed(2)):0,grossProfitSol:Number(gp.toFixed(8)),grossLossSol:Number(gl.toFixed(8)),profitFactor:Number.isFinite(pf)?Number(pf.toFixed(4)):(pf===Infinity?'INF_NO_LOSS_YET':0),expectancyPerLifecycleSol:Number(expectancy.toFixed(8)),legacyBuyEventsWithoutPositionId:buys.filter(x=>!x.positionId).length,legacySellEventsWithoutPositionId:sells.filter(x=>!x.positionId).length,dataIntegrityErrors:integrity,realizedPnlSol:Number(s.realizedPnlSol||0),unrealizedPnlSol:Number(s.unrealizedPnlSol||0),lifecycles};
for(const p of [OUT,SAFE]){const t=`${p}.tmp`;fs.writeFileSync(t,JSON.stringify(result,null,2));fs.renameSync(t,p);try{fs.chmodSync(p,0o664)}catch{}}
console.log('=== MEME ALPHA VALIDATION v1.6 ==='); console.log(`CompletedLifecycles=${completed.length}`); console.log(`Readiness=${readinessStatus}`); console.log(`ProfitFactor=${result.profitFactor}`); console.log(`Expectancy=${result.expectancyPerLifecycleSol}`); console.log(`IntegrityErrors=${integrity.length}`); console.log('LIVE_EXECUTION=DISABLED'); console.log('VALIDATION_STATUS=PASS');
