import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = path.join(__dirname, 'public');
const PORT = Number(process.env.PORT || 8788);
const NODE_TIMER_MAX_MS = 2_147_483_647;
const CLOCK_SKEW_MS = 30_000;
function boundedMs(raw, fallback, minimum, maximum = NODE_TIMER_MAX_MS) { const n=Number(raw); if(!Number.isFinite(n))return fallback; return Math.min(maximum,Math.max(minimum,n)); }
const STALE_MS=boundedMs(process.env.CONTROL_CENTER_STALE_MS,120000,15000);
const REFRESH_MS=boundedMs(process.env.CONTROL_CENTER_REFRESH_MS,5000,2000,Math.max(2000,Math.min(NODE_TIMER_MAX_MS,STALE_MS)));
const PROVIDERS=['deepseek','codex','claude','qwen','openrouter'];
const SOURCES={
  vps:process.env.CC_VPS_STATUS_URL||'',github:process.env.CC_GITHUB_STATUS_URL||'',cloudflare:process.env.CC_CLOUDFLARE_STATUS_URL||'',telegram:process.env.CC_TELEGRAM_STATUS_URL||'',
  multi_ai:process.env.CC_MULTI_AI_STATUS_URL||'',deepseek:process.env.CC_DEEPSEEK_STATUS_URL||'',codex:process.env.CC_CODEX_STATUS_URL||'',claude:process.env.CC_CLAUDE_STATUS_URL||'',qwen:process.env.CC_QWEN_STATUS_URL||'',openrouter:process.env.CC_OPENROUTER_STATUS_URL||''
};
const SAFE_KEYS=new Set(['state','status','message','last_updated','last_seen','timestamp','task','task_id','issue','pr','sha','run_id','workflow','validation','verdict','consensus','deploy','version','provider','providers','configured','model','role','events','details','stage','url','label','age_ms','pipeline','intake','implementation','codex_review','claude_review','merge','qwen_review','openrouter_review']);
const STALE_SUCCESS_STATES=new Set(['ONLINE','WAITING','RUNNING','REVIEWING','ACCEPT','PASS']);
const nowIso=()=>new Date().toISOString();
function normalizeState(v){const s=String(v||'UNKNOWN').toUpperCase();return new Set(['ONLINE','DEGRADED','OFFLINE','UNKNOWN','WAITING','RUNNING','REVIEWING','ACCEPT','REJECT','BLOCKED','PASS','FAIL','PENDING']).has(s)?s:'UNKNOWN';}
function isPlainObject(v){return Boolean(v)&&typeof v==='object'&&!Array.isArray(v);}
function sanitize(value,depth=0){if(depth>4)return null;if(Array.isArray(value))return value.slice(0,100).map(v=>sanitize(v,depth+1));if(!value||typeof value!=='object')return typeof value==='string'?value.slice(0,2000):value;const out={};for(const [k,v] of Object.entries(value)){if(SAFE_KEYS.has(k))out[k]=sanitize(v,depth+1);}return out;}
function parseTime(obj){for(const key of ['last_updated','last_seen','timestamp']){const raw=obj?.[key];const t=typeof raw==='number'?raw:Date.parse(raw);if(Number.isFinite(t))return t;}return NaN;}
function freshness(obj,now=Date.now()){const t=parseTime(obj);if(!Number.isFinite(t))return {stale:true,age_ms:null,reason:'missing timestamp'};const delta=now-t;if(delta<-CLOCK_SKEW_MS)return {stale:true,age_ms:0,reason:'future-dated timestamp'};const age=Math.max(0,delta);return {stale:age>STALE_MS,age_ms:age,reason:age>STALE_MS?'stale timestamp':null};}
function materializeItem(item,now=Date.now()){const out=isPlainObject(item)?{...item}:{state:'DEGRADED',message:'malformed source payload',last_updated:null};const fresh=freshness(out,now);out.age_ms=fresh.age_ms;out._stale=fresh.stale;const state=normalizeState(out.state||out.status);out.state=state;if(fresh.stale&&STALE_SUCCESS_STATES.has(state)){out.state='DEGRADED';out.message=out.message||fresh.reason||'stale evidence';}return out;}
function materializePipeline(pipeline,parentStale,now=Date.now()){if(!isPlainObject(pipeline))return {};const out={};for(const [stage,raw] of Object.entries(pipeline)){if(isPlainObject(raw)){const stageFresh=freshness(raw,now),state=normalizeState(raw.state||raw.status),stale=parentStale||stageFresh.stale;out[stage]={...raw,age_ms:stageFresh.age_ms,state:stale&&STALE_SUCCESS_STATES.has(state)?'UNKNOWN':state};if(stale&&STALE_SUCCESS_STATES.has(state)&&!out[stage].message)out[stage].message=stageFresh.reason||'stale parent evidence';}else{const state=normalizeState(raw);out[stage]=STALE_SUCCESS_STATES.has(state)?'UNKNOWN':state;}}return out;}
async function fetchJson(url){if(!url)return {state:'UNKNOWN',message:'source not configured',last_updated:null};const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),5000);try{const res=await fetch(url,{headers:{accept:'application/json'},signal:ctl.signal});if(!res.ok)return {state:'DEGRADED',message:`HTTP ${res.status}`,last_updated:nowIso()};const parsed=await res.json();if(!isPlainObject(parsed))return {state:'DEGRADED',message:'malformed source payload: expected JSON object',last_updated:nowIso()};const safe=sanitize(parsed);return isPlainObject(safe)?safe:{state:'DEGRADED',message:'malformed source payload after sanitization',last_updated:nowIso()};}catch(err){return {state:'OFFLINE',message:String(err?.message||err).slice(0,500),last_updated:nowIso()};}finally{clearTimeout(timer);}}
function gatewayProvider(gateway,name){const p=gateway?.providers?.[name];if(!isPlainObject(p))return {state:'UNKNOWN',message:'provider absent from aggregate gateway',last_updated:null};const explicit=normalizeState(p.state||p.status);const gatewayTs=gateway?.timestamp;const t=p.last_updated||p.last_seen||p.timestamp||(explicit!=='UNKNOWN'&&gatewayTs?gatewayTs:null);return {...p,state:explicit,last_updated:t||null,message:p.message||(explicit==='UNKNOWN'?'configured metadata only; no runtime state evidence':undefined)};}
let cache={last_updated:nowIso(),refresh_ms:REFRESH_MS,systems:{},ai:{},pipeline:{},events:[]};let refreshing=false;
async function refresh(){if(refreshing)return cache;refreshing=true;try{const entries=await Promise.all(Object.entries(SOURCES).map(async([name,url])=>{try{return [name,await fetchJson(url)];}catch(err){return [name,{state:'OFFLINE',message:`source isolation: ${String(err?.message||err).slice(0,450)}`,last_updated:nowIso()}];}}));const map=Object.fromEntries(entries),events=[];for(const [name,item] of entries){if(isPlainObject(item)&&Array.isArray(item.events))for(const e of item.events.slice(-25))events.push({source:name,...sanitize(e)});}events.sort((a,b)=>Date.parse(b.timestamp||b.last_updated||0)-Date.parse(a.timestamp||a.last_updated||0));const ai={};for(const p of PROVIDERS){ai[p]=SOURCES[p]?map[p]:gatewayProvider(map.multi_ai,p);}cache={last_updated:nowIso(),refresh_ms:REFRESH_MS,systems:{vps:map.vps,github:map.github,cloudflare:map.cloudflare,telegram:map.telegram},ai,pipeline:map.github?.details?.pipeline||map.github?.pipeline||{},events:events.slice(0,100)};return cache;}finally{refreshing=false;}}
function responseSnapshot(){const now=Date.now(),systems=Object.fromEntries(Object.entries(cache.systems||{}).map(([k,v])=>[k,materializeItem(v,now)])),ai=Object.fromEntries(Object.entries(cache.ai||{}).map(([k,v])=>[k,materializeItem(v,now)]));return {...cache,systems,ai,pipeline:materializePipeline(cache.pipeline,Boolean(systems.github?._stale),now)};}
setInterval(()=>refresh().catch(()=>{}),REFRESH_MS).unref();await refresh();
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};
async function serveFile(req,res){const urlPath=new URL(req.url,'http://localhost').pathname,rel=urlPath==='/'?'index.html':urlPath.replace(/^\/+/,''),file=path.resolve(PUBLIC_DIR,rel),relative=path.relative(PUBLIC_DIR,file);if(relative.startsWith('..')||path.isAbsolute(relative)){res.writeHead(403);res.end('Forbidden');return;}try{const data=await fs.readFile(file);res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(data);}catch{res.writeHead(404);res.end('Not found');}}
http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/healthz'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify({ok:true,service:'trading-multi-ai-control-center',time:nowIso()}));return;}if(u.pathname==='/api/status'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(responseSnapshot()));return;}await serveFile(req,res);}).listen(PORT,'0.0.0.0',()=>console.log(`Control Center listening on :${PORT}`));
