import baseEngine from '../engine-v77168.js';

const MAX_AGE_SEC={crypto:15,forex:65,metal:65,index:65};
const INDEX_TD={NAS100:'NDX',US30:'DJI',US500:'SPX',SPX500:'SPX',DEX:'DAX',GER40:'DAX',JP225:'N225'};
const INDEX_MASSIVE={NAS100:'I:NDX',US30:'I:DJI',US500:'I:SPX',SPX500:'I:SPX',DEX:'I:DAX',GER40:'I:DAX',JP225:'I:N225'};
const norm=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null;};
const nowSec=()=>Math.floor(Date.now()/1000);
const parseTs=v=>{if(v==null)return null;if(typeof v==='number')return v>2e10?Math.floor(v/1000):Math.floor(v);if(/^\d+$/.test(String(v))){const n=Number(v);return n>2e10?Math.floor(n/1000):Math.floor(n);}const d=Date.parse(String(v).replace(' ','T')+(/Z|[+-]\d\d:?\d\d$/.test(String(v))?'':'Z'));return Number.isFinite(d)?Math.floor(d/1000):null;};
const cryptoPair=s=>{const x=norm(s);return /(USDT|USDC|USD)$/.test(x)?x:`${x}USDT`;};
async function fetchJson(url,init={}){const c=new AbortController(),id=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{...init,headers:{accept:'application/json','user-agent':'Mozilla/5.0 Trading-V11-LiveQuote/1.1',...(init.headers||{})},signal:c.signal});const j=await r.json().catch(()=>null);if(!r.ok||!j)throw new Error(`HTTP_${r.status}`);return j;}finally{clearTimeout(id);}}
function out(source,market,symbol,price,ts,extra={}){const age=ts==null?null:Math.max(0,nowSec()-ts),max=MAX_AGE_SEC[market]??65;return {source,market,requestedSymbol:norm(symbol),price:num(price),providerTimestamp:ts,quoteAgeSec:age,fresh:age!==null&&age<=max,...extra};}
function requireFresh(q){if(!(q?.price>0)||q.fresh!==true)throw new Error('STALE_OR_INVALID');return q;}
async function bybitQuote(requested,pair){const j=await fetchJson(`https://api.bybit.com/v5/market/tickers?category=spot&symbol=${encodeURIComponent(pair)}`),r=j?.result?.list?.[0];if(norm(r?.symbol)!==pair)throw new Error('SYMBOL_MISMATCH');return requireFresh(out('Bybit Spot','crypto',requested,r?.lastPrice,Math.floor(Number(j?.time)/1000),{bid:num(r?.bid1Price),ask:num(r?.ask1Price),providerSymbol:pair}));}
async function okxQuote(requested,pair){const id=pair.endsWith('USDT')?`${pair.slice(0,-4)}-USDT`:pair,j=await fetchJson(`https://www.okx.com/api/v5/market/ticker?instId=${encodeURIComponent(id)}`),r=j?.data?.[0];if(norm(r?.instId)!==pair)throw new Error('SYMBOL_MISMATCH');return requireFresh(out('OKX Spot','crypto',requested,r?.last,Math.floor(Number(r?.ts)/1000),{bid:num(r?.bidPx),ask:num(r?.askPx),providerSymbol:id}));}
async function binanceQuote(requested,pair){let last;for(const host of ['https://data-api.binance.vision','https://api.binance.com']){try{const j=await fetchJson(`${host}/api/v3/ticker/24hr?symbol=${encodeURIComponent(pair)}`);if(norm(j?.symbol)!==pair)throw new Error('SYMBOL_MISMATCH');return requireFresh(out('Binance Spot','crypto',requested,j?.lastPrice,Math.floor(Number(j?.closeTime)/1000),{bid:num(j?.bidPrice),ask:num(j?.askPrice),providerSymbol:pair}));}catch(e){last=e;}}throw last||new Error('BINANCE_UNAVAILABLE');}
async function kucoinQuote(requested,pair){if(!pair.endsWith('USDT'))throw new Error('NOT_USDT');const id=`${pair.slice(0,-4)}-USDT`,j=await fetchJson(`https://api.kucoin.com/api/v1/market/orderbook/level1?symbol=${encodeURIComponent(id)}`),r=j?.data;if(j?.code!=='200000'||norm(r?.symbol||id)!==pair)throw new Error('SYMBOL_MISMATCH');const ts=parseTs(r?.time??j?.time);if(ts==null)throw new Error('KUCOIN_TIMESTAMP_MISSING');return requireFresh(out('KuCoin Spot','crypto',requested,r?.price,ts,{bid:num(r?.bestBid),ask:num(r?.bestAsk),providerSymbol:id}));}
function chooseCrypto(quotes){const ok=quotes.filter(q=>q?.price>0&&q?.fresh===true);if(!ok.length)throw new Error('NO_FRESH_CRYPTO_QUOTE');const sorted=ok.map(q=>q.price).sort((a,b)=>a-b),mid=sorted.length>>1,median=sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2;const core=/^(BTC|ETH|SOL|XRP)(USDT|USD|USDC)?$/.test(norm(ok[0]?.requestedSymbol));const tolerance=core?0.0025:0.0045;const inliers=ok.filter(q=>Math.abs(q.price-median)/median<=tolerance);if(!inliers.length)throw new Error('CRYPTO_PRICE_CONSENSUS_FAILED');inliers.sort((a,b)=>Math.abs(a.price-median)-Math.abs(b.price-median)||(a.quoteAgeSec??999)-(b.quoteAgeSec??999));const q=inliers[0],spread=Math.max(...inliers.map(x=>x.price))-Math.min(...inliers.map(x=>x.price));return {...q,crossSourceCount:inliers.length,crossSources:inliers.map(x=>x.source),medianPrice:median,crossSourceSpreadPct:median>0?spread/median*100:null,canonicalMethod:'CLOSEST_TO_CROSS_SOURCE_MEDIAN'};}
async function legacyEngineQuote(symbol,market,env){try{const r=await baseEngine.fetch(new Request(`https://v11.quote/analyze?symbol=${encodeURIComponent(symbol)}`),env),a=await r.json(),q=a?.analysisQuote||a?.quote,price=Number(q?.price),ts=parseTs(q?.providerTimestamp??q?.timestamp??q?.datetime),age=ts==null?Number(q?.quoteAgeSec):Math.max(0,nowSec()-ts),max=MAX_AGE_SEC[market]??65;if(price>0&&Number.isFinite(age)&&age<=max)return {...q,source:`${q.source||'Legacy engine'} • V77 adapter`,market,requestedSymbol:norm(symbol),price,providerTimestamp:ts,quoteAgeSec:age,fresh:true,legacyAdapter:true};}catch{}return null;}
async function cryptoQuote(symbol,env){const requested=norm(symbol),pair=cryptoPair(requested),settled=await Promise.allSettled([bybitQuote(requested,pair),okxQuote(requested,pair),binanceQuote(requested,pair),kucoinQuote(requested,pair)]),quotes=settled.filter(x=>x.status==='fulfilled').map(x=>x.value);if(quotes.length)return chooseCrypto(quotes);const legacy=await legacyEngineQuote(pair,'crypto',env);if(legacy)return {...legacy,requestedSymbol:requested,providerSymbol:legacy.providerSymbol||pair};throw new Error('NO_FRESH_CRYPTO_QUOTE:'+settled.map(x=>x.status==='rejected'?String(x.reason?.message||x.reason):'OK').join('|'));}
async function twelveQuote(symbol,market,env){if(!env.TWELVE_DATA_API_KEY)throw new Error('TWELVE_DATA_API_KEY_MISSING');const s=norm(symbol);if(s.length!==6)throw new Error(`INVALID_${market.toUpperCase()}_SYMBOL`);const ps=`${s.slice(0,3)}/${s.slice(3)}`,u=new URL('https://api.twelvedata.com/quote');u.searchParams.set('symbol',ps);u.searchParams.set('apikey',env.TWELVE_DATA_API_KEY);try{const j=await fetchJson(u.toString()),price=num(j?.close)??num(j?.price),ts=parseTs(j?.last_quote_at??j?.timestamp??j?.datetime),q=out('Twelve Data',market,s,price,ts,{providerSymbol:ps,bid:num(j?.bid),ask:num(j?.ask)});if(q.price>0&&q.fresh)return q;}catch{}const legacy=await legacyEngineQuote(s,market,env);if(legacy)return legacy;throw new Error(`NO_FRESH_${market.toUpperCase()}_QUOTE`);}
async function twelveIndex(symbol,env){if(!env.TWELVE_DATA_API_KEY)throw new Error('TWELVE_DATA_API_KEY_MISSING');const s=norm(symbol),ps=INDEX_TD[s];if(!ps)throw new Error('INDEX_UNSUPPORTED');const u=new URL('https://api.twelvedata.com/time_series');for(const [k,v] of Object.entries({symbol:ps,type:'Index',interval:'1min',outputsize:'2',order:'DESC',timezone:'UTC',apikey:env.TWELVE_DATA_API_KEY}))u.searchParams.set(k,v);const j=await fetchJson(u.toString()),values=Array.isArray(j?.values)?j.values:Array.isArray(j?.data?.values)?j.data.values:[],r=values[0],price=num(r?.close),ts=parseTs(r?.datetime),q=out('Twelve Data Native Index','index',s,price,ts,{providerSymbol:ps,analysisOnly:true});if(!(q.price>0)||!q.fresh)throw new Error('TWELVE_INDEX_STALE');return q;}
async function massiveIndex(symbol,env){if(!env.MASSIVE_API_KEY)throw new Error('MASSIVE_API_KEY_MISSING');const s=norm(symbol),ticker=INDEX_MASSIVE[s];if(!ticker)throw new Error('INDEX_UNSUPPORTED');const u=new URL('https://api.massive.com/v3/snapshot/indices');u.searchParams.set('ticker',ticker);u.searchParams.set('limit','10');u.searchParams.set('apiKey',env.MASSIVE_API_KEY);const j=await fetchJson(u.toString()),r=(j?.results||[]).find(x=>x?.ticker===ticker&&!x?.error),ts=r?.last_updated?Math.floor(Number(r.last_updated)/1e9):null,q=out('Massive Indices Snapshot','index',s,r?.value,ts,{providerSymbol:ticker,analysisOnly:true,marketStatus:r?.market_status||null});if(!(q.price>0)||!q.fresh)throw new Error('MASSIVE_INDEX_STALE');return q;}
export async function getLiveQuote(symbol,market,env){const m=String(market||'').toLowerCase();if(m==='crypto')return cryptoQuote(symbol,env);if(m==='forex'||m==='metal')return twelveQuote(symbol,m,env);if(m==='index'){try{return await twelveIndex(symbol,env);}catch(e){try{return await massiveIndex(symbol,env);}catch(e2){const legacy=await legacyEngineQuote(symbol,'index',env);if(legacy)return legacy;throw new Error(`${e.message}|${e2.message}`);}}}throw new Error('UNKNOWN_MARKET');}
