const MAX_AGE_SEC={crypto:10,forex:65,metal:65,index:65};
const INDEX_TD={NAS100:'NDX',US30:'DJI',US500:'SPX',DEX:'DAX',JP225:'N225'};
const INDEX_MASSIVE={NAS100:'I:NDX',US30:'I:DJI',US500:'I:SPX',DEX:'I:DAX',JP225:'I:N225'};
const norm=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null;};
const nowSec=()=>Math.floor(Date.now()/1000);
const parseTs=v=>{if(v==null)return null;if(typeof v==='number'){return v>2e10?Math.floor(v/1000):Math.floor(v);}if(/^\d+$/.test(String(v))){const n=Number(v);return n>2e10?Math.floor(n/1000):Math.floor(n);}const d=Date.parse(String(v).replace(' ','T')+(/Z|[+-]\d\d:?\d\d$/.test(String(v))?'':'Z'));return Number.isFinite(d)?Math.floor(d/1000):null;};
async function fetchJson(url,init={}){const c=new AbortController(),id=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{...init,signal:c.signal});const j=await r.json().catch(()=>null);if(!r.ok||!j)throw new Error(`HTTP_${r.status}`);return j;}finally{clearTimeout(id);}}
function out(source,market,symbol,price,ts,extra={}){const age=ts==null?null:Math.max(0,nowSec()-ts),max=MAX_AGE_SEC[market]??65;return {source,market,requestedSymbol:norm(symbol),price:num(price),providerTimestamp:ts,quoteAgeSec:age,fresh:age!==null&&age<=max,...extra};}
async function cryptoQuote(symbol){const s=norm(symbol),errors=[];try{const j=await fetchJson(`https://api.bybit.com/v5/market/tickers?category=spot&symbol=${encodeURIComponent(s)}`),r=j?.result?.list?.[0],ts=Math.floor(Number(j?.time)/1000),q=out('Bybit Spot','crypto',s,r?.lastPrice,ts,{bid:num(r?.bid1Price),ask:num(r?.ask1Price),providerSymbol:s});if(q.price>0&&q.fresh)return q;errors.push('BYBIT_STALE');}catch(e){errors.push('BYBIT_'+e.message);}try{const id=s.endsWith('USDT')?`${s.slice(0,-4)}-USDT`:s,j=await fetchJson(`https://www.okx.com/api/v5/market/ticker?instId=${encodeURIComponent(id)}`),r=j?.data?.[0],ts=Math.floor(Number(r?.ts)/1000),q=out('OKX Spot','crypto',s,r?.last,ts,{bid:num(r?.bidPx),ask:num(r?.askPx),providerSymbol:id});if(q.price>0&&q.fresh)return q;errors.push('OKX_STALE');}catch(e){errors.push('OKX_'+e.message);}for(const host of ['https://data-api.binance.vision','https://api.binance.com']){try{const j=await fetchJson(`${host}/api/v3/ticker/24hr?symbol=${encodeURIComponent(s)}`),ts=Math.floor(Number(j?.closeTime)/1000),q=out('Binance Spot','crypto',s,j?.lastPrice,ts,{bid:num(j?.bidPrice),ask:num(j?.askPrice),providerSymbol:s});if(q.price>0&&q.fresh)return q;errors.push('BINANCE_STALE');}catch(e){errors.push('BINANCE_'+e.message);}}throw new Error('NO_FRESH_CRYPTO_QUOTE:'+errors.join('|'));}
async function twelveQuote(symbol,market,env){if(!env.TWELVE_DATA_API_KEY)throw new Error('TWELVE_DATA_API_KEY_MISSING');const s=norm(symbol),ps=`${s.slice(0,3)}/${s.slice(3)}`,u=new URL('https://api.twelvedata.com/quote');u.searchParams.set('symbol',ps);u.searchParams.set('apikey',env.TWELVE_DATA_API_KEY);const j=await fetchJson(u.toString()),price=num(j?.close)??num(j?.price),ts=parseTs(j?.last_quote_at??j?.timestamp??j?.datetime),q=out('Twelve Data',market,s,price,ts,{providerSymbol:ps,bid:num(j?.bid),ask:num(j?.ask)});if(!(q.price>0)||!q.fresh)throw new Error(`NO_FRESH_${market.toUpperCase()}_QUOTE`);return q;}
async function twelveIndex(symbol,env){if(!env.TWELVE_DATA_API_KEY)throw new Error('TWELVE_DATA_API_KEY_MISSING');const s=norm(symbol),ps=INDEX_TD[s];if(!ps)throw new Error('INDEX_UNSUPPORTED');const u=new URL('https://api.twelvedata.com/time_series');for(const [k,v] of Object.entries({symbol:ps,type:'Index',interval:'1min',outputsize:'2',order:'DESC',timezone:'UTC',apikey:env.TWELVE_DATA_API_KEY}))u.searchParams.set(k,v);const j=await fetchJson(u.toString()),values=Array.isArray(j?.values)?j.values:Array.isArray(j?.data?.values)?j.data.values:[],r=values[0],price=num(r?.close),ts=parseTs(r?.datetime);const q=out('Twelve Data Native Index','index',s,price,ts,{providerSymbol:ps,analysisOnly:true});if(!(q.price>0)||!q.fresh)throw new Error('TWELVE_INDEX_STALE');return q;}
async function massiveIndex(symbol,env){if(!env.MASSIVE_API_KEY)throw new Error('MASSIVE_API_KEY_MISSING');const s=norm(symbol),ticker=INDEX_MASSIVE[s];if(!ticker)throw new Error('INDEX_UNSUPPORTED');const u=new URL('https://api.massive.com/v3/snapshot/indices');u.searchParams.set('ticker',ticker);u.searchParams.set('limit','10');u.searchParams.set('apiKey',env.MASSIVE_API_KEY);const j=await fetchJson(u.toString()),r=(j?.results||[]).find(x=>x?.ticker===ticker&&!x?.error),ts=r?.last_updated?Math.floor(Number(r.last_updated)/1e9):null,q=out('Massive Indices Snapshot','index',s,r?.value,ts,{providerSymbol:ticker,analysisOnly:true,marketStatus:r?.market_status||null});if(!(q.price>0)||!q.fresh)throw new Error('MASSIVE_INDEX_STALE');return q;}
export async function getLiveQuote(symbol,market,env){const m=String(market||'').toLowerCase();if(m==='crypto')return cryptoQuote(symbol);if(m==='forex'||m==='metal')return twelveQuote(symbol,m,env);if(m==='index'){try{return await twelveIndex(symbol,env);}catch(e){try{return await massiveIndex(symbol,env);}catch(e2){throw new Error(`${e.message}|${e2.message}`);}}}throw new Error('UNKNOWN_MARKET');}
