import baseEngine from '../engine-v77168.js';
import {telegramApiRequest} from '../providers/telegram-client.js';
import {V11_CONFIG,V11_GROUPS} from './config.js';
import {buildEntryPlan} from './entry-plan.js';
import {evaluateMarketCandidate} from './market-policies.js';
import {recordV11,refreshV11Lifecycle} from './store.js';
import {getLiveQuote} from './live-quote.js';
const SKEY='v11:native:schedule';
const ACTIONABLE=new Set(['MARKET_SIGNAL','MARKET','LIMIT','MARKET_PLAN','LIMIT_PLAN']);
const MARKET_READY=new Set(['MARKET_SIGNAL','MARKET']);
const PROVIDERS=['claude','codex','deepseek','qwen','openrouter'];
const AI_RECHECK_MS=180000;
const ENTRY_DRIFT_MAX_PCT={crypto:.20,forex:.08,metal:.12,index:.12};
async function engine(path,env){const r=await baseEngine.fetch(new Request(`https://v11.internal${path}`),env);try{return await r.json()}catch{return null}}
const finite=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const px=v=>Number.isFinite(Number(v))?Number(v).toPrecision(7):'—';
const pnlPct=(side,entry,price)=>{entry=Number(entry);price=Number(price);if(!(entry>0)||!(price>0))return null;return (String(side).toUpperCase()==='SHORT'?(entry-price):(price-entry))/entry*100;};
async function notify(env,text){if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID)return false;try{await telegramApiRequest(env,'sendMessage',{chat_id:env.TELEGRAM_CHAT_ID,text,disable_web_page_preview:true});return true}catch(e){console.error('V11_TELEGRAM_NOTIFY',e);return false}}
function signalText(x){const c=x.candidate||{},q=c.quote||{},quality=Number(c.qualityScore??c.score),fresh=Number.isFinite(Number(q.quoteAgeSec))?`${Number(q.quoteAgeSec)}s`:'—';return [`🟢 V11 MARKET SIGNAL`,`━━━━━━━━━━━━`,`${String(x.market||'').toUpperCase()} • ${c.side==='LONG'?'BUY':'SELL'} ${x.symbol}`,`📍 Entry ${px(c.entry)}`,`🛑 SL ${px(c.sl)}`,`🎯 TP ${px(c.tp)}`,`⚖️ RR ${Number(c.rr||0).toFixed(2)}`,`⭐ Quality ${Number.isFinite(quality)?quality.toFixed(0)+'/100':'—'}`,`📡 LIVE ${q.source||'verified source'} • age ${fresh}`,`🧭 ${c.setup||'—'}`,``,`WHY NOW`,`• upstream ${c.upstreamStatus||'MARKET_READY'}`,`• canonical fresh quote verified`,`• structure geometry valid`,`• deterministic V11 market gates passed`,``,`⚠️ SIGNAL ONLY • không phải broker fill`].join('\n');}
function lifecycleText(x){const c=x.candidate||{},p=pnlPct(c.side,c.entry,x.closePrice),ps=p==null?'—':`${p>=0?'+':''}${p.toFixed(2)}%`,icon=x.outcome==='WIN'?'✅':x.outcome==='LOSS'?'🛑':x.outcome==='CUT'?'✂️':'⌛';return [`${icon} V11 ${x.lifecycleStatus}`,`━━━━━━━━━━━━`,`${String(x.market||'').toUpperCase()} • ${c.side==='LONG'?'BUY':'SELL'} ${x.symbol}`,`📍 Entry ${px(c.entry)}`,`🏁 Close ${px(x.closePrice)}`,`📊 P/L từ Entry: ${ps}`,`🛑 SL ${px(c.sl)} • 🎯 TP ${px(c.tp)}`,`Kết quả: ${x.outcome}`,x.outcome==='CUT'?`🧠 AI CUT: ${x.cutAiVotes??'—'}/5 • valid ${x.cutAiValid??'—'}/5`:null,x.outcome==='CUT'?`Lý do: ${x.cutReason||'AI_REEVALUATION_FAILED'}`:null].filter(Boolean).join('\n');}
function normalizeCandidate(a,q){const planned=a?.planned||{},canonical=a?.canonical||{},mg=canonical.marketGeometry||{},lg=canonical.limitGeometry||{},m15=canonical.m15Location||{},m5=canonical.m5Trigger||{};const atrCandidates=[a?.atr,a?.atr14,a?.indicators?.atr,a?.indicators?.atr14,a?.M5?.atr14,a?.M15?.atr14,a?.H1?.atr14,a?.timeframes?.M5?.atr14,a?.timeframes?.M15?.atr14,a?.timeframes?.H1?.atr14,planned.atr,planned.atr14,mg.atr,lg.atr].map(finite).filter(x=>x>0);const entry=finite(a?.entry??planned.entry??q?.price);const structureLevels=[a?.swingLow,a?.swingHigh,a?.support,a?.resistance,a?.structureInvalidation,a?.swingInvalidation,m15.level,m5.level,mg.level,lg.level,planned.sl].map(finite).filter(Number.isFinite);const liquidityLevels=[a?.liquidityLow,a?.liquidityHigh,a?.target1,a?.target2,a?.tp,a?.tp1,a?.tp2,planned.tp,planned.tp1,planned.tp2].map(finite).filter(Number.isFinite);return {...a,price:finite(q?.price),entry,quote:q,atr:atrCandidates[0]??null,qualityScore:Number(a?.qualityScore??a?.quality??a?.score??0),structureLevels,liquidityLevels};}
async function freshAnalyze(symbol,market,env){const [a,q]=await Promise.all([engine(`/analyze?symbol=${encodeURIComponent(symbol)}`,env),getLiveQuote(symbol,market,env)]);if(!a)throw new Error('V11_ANALYSIS_UNAVAILABLE');if(!(Number(q?.price)>0)||q?.fresh!==true)throw new Error('V11_QUOTE_NOT_VERIFIED_FRESH');return {analysis:a,quote:{...q,price:Number(q.price),fresh:true}};}
async function resolveFreshAnalysis(raw,market,env){const q=await getLiveQuote(raw.symbol,market,env);return {analysis:raw,quote:q};}
function entryDriftOk(market,entry,live){const e=Number(entry),p=Number(live);if(!(e>0)||!(p>0))return false;return Math.abs(p-e)/e*100<=(ENTRY_DRIFT_MAX_PCT[market]??.12);}
async function bridgeReview(env,evidence){const secret=String(env.V11_AI_BRIDGE_SECRET||'');if(!secret||!env.AI_BRIDGE||typeof env.AI_BRIDGE.fetch!=='function')return {ok:false,error:'AI_BRIDGE_UNAVAILABLE',providers:{}};try{const r=await env.AI_BRIDGE.fetch(new Request('http://127.0.0.1:8789/review',{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+secret},body:JSON.stringify({evidence}),signal:AbortSignal.timeout(125000)}));const j=await r.json().catch(()=>({}));return {ok:r.ok&&j?.ok===true,providers:j?.providers||{},error:r.ok?null:`BRIDGE_HTTP_${r.status}`};}catch(e){return {ok:false,error:'BRIDGE_FETCH_'+String(e?.message||e),providers:{}};}}
function aiVote(item,side){if(item?.status!=='OK'||!item.review)return 'UNAVAILABLE';const r=item.review,d=String(r.direction||'WAIT').toUpperCase(),conf=Number(r.confidence||0),hard=Array.isArray(r.hardRisk)&&r.hardRisk.length>0;if(hard&&conf>=50)return 'CUT';if(d===side&&!hard&&conf>=60)return 'KEEP';if(d!==side&&conf>=55)return 'CUT';return 'NEUTRAL';}
async function aiReevaluate(x,current,deterministic,env){const side=String(x.candidate?.side||'').toUpperCase(),evidence={mode:'V11_LIVE_POSITION_REEVALUATION',instruction:'Re-evaluate this already-open MARKET signal using ONLY supplied fresh evidence. Return the original side only if it is still suitable as an immediate MARKET setup. Return WAIT or the opposite side when the edge is gone or invalidated. Never invent data.',market:x.market,symbol:x.symbol,originalSide:side,entry:Number(x.candidate?.entry),sl:Number(x.candidate?.sl),tp:Number(x.candidate?.tp),currentPrice:Number(current.quote?.price),quote:{source:current.quote?.source,providerTimestamp:current.quote?.providerTimestamp,quoteAgeSec:current.quote?.quoteAgeSec,fresh:current.quote?.fresh},analysis:{status:current.status,qualityScore:current.candidate?.qualityScore,setup:current.plan?.setup,rr:current.plan?.rr},deterministic};const r=await bridgeReview(env,evidence),votes={};let valid=0,cut=0,keep=0;for(const p of PROVIDERS){const v=aiVote(r.providers?.[p],side);votes[p]=v;if(v!=='UNAVAILABLE')valid++;if(v==='CUT')cut++;if(v==='KEEP')keep++;}return {bridgeOk:r.ok,valid,cut,keep,votes,cutConfirmed:valid>=4&&cut>=4,keepConfirmed:valid>=4&&keep>=3};}
export async function scanMarketV11(env,market){const r=await engine(`/run-now?group=${market}`,env);if(!r?.ok||['BUSY','RATE_BUDGET_WAIT'].includes(String(r?.status||'')))return {status:r?.status||'SCAN_FAILED',market,approved:0};let approved=0,watch=0,rejected=0,notified=0,capped=0;for(const raw of r.analyses||[]){if(!ACTIONABLE.has(String(raw?.status||'').toUpperCase())||!raw?.symbol)continue;try{const {analysis,quote}=await resolveFreshAnalysis(raw,market,env),upstreamStatus=String(analysis?.status||raw?.status||'').toUpperCase(),c=normalizeCandidate({...raw,...analysis},quote),plan=buildEntryPlan(market,c);if(!plan.ok||!plan.executable){await recordV11(env,{status:plan.ok?'WATCH':'REJECTED',market,symbol:raw.symbol,plan});plan.ok?watch++:rejected++;continue;}if(!MARKET_READY.has(upstreamStatus)){await recordV11(env,{status:'WATCH',market,symbol:raw.symbol,reason:'UPSTREAM_'+upstreamStatus+'_NOT_MARKET_READY',plan});watch++;continue;}if(!entryDriftOk(market,plan.entry,quote.price)){await recordV11(env,{status:'WATCH',market,symbol:raw.symbol,reason:'LIVE_PRICE_DRIFT_TOO_HIGH',plan});watch++;continue;}const candidate={...c,symbol:plan.symbol,entry:Number(quote.price),sl:plan.sl,tp:plan.tp,rr:plan.rr,setup:plan.setup,upstreamStatus,quote};const gate=evaluateMarketCandidate(market,candidate);if(!gate.pass){await recordV11(env,{status:'REJECTED',market,symbol:plan.symbol,reason:gate.reasons?.join('|')||'MARKET_POLICY_REJECTED',plan,gate});rejected++;continue;}const saved=await recordV11(env,{status:'APPROVED_SIGNAL',version:'V11',market,symbol:plan.symbol,candidate,plan:{...plan,entry:Number(quote.price)},gate,approvedAt:Date.now(),expiresAt:Date.now()+V11_CONFIG.markets[market].horizonMin*60000});approved++;if(saved.storeReason==='MARKET_CAP_REACHED'){capped++;continue;}if(saved.stored&&await notify(env,signalText(saved)))notified++;}catch(e){await recordV11(env,{status:'REJECTED',market,symbol:raw.symbol,plan:{reason:String(e?.message||e)}});rejected++;}}return {status:'SCANNED',market,approved,watch,rejected,notified,capped,maxOpenPerMarket:5,coverage:{requested:r.requested,broadOk:r.broadOk,deepOk:r.deepOk}};}
async function lifecycleQuote(symbol,market,env){return getLiveQuote(symbol,market,env);}
async function revalidateOpenSignal(x,q,env){const {analysis,quote}=await freshAnalyze(x.symbol,x.market,env),status=String(analysis?.status||'').toUpperCase(),c=normalizeCandidate(analysis,quote),plan=buildEntryPlan(x.market,c),originalSide=String(x.candidate?.side||'').toUpperCase(),newSide=String(plan?.side||c?.side||'').toUpperCase();let deterministicKeep=true,reason='STILL_MARKET_READY';if(!MARKET_READY.has(status)){deterministicKeep=false;reason=`UPSTREAM_${status||'UNKNOWN'}_NOT_MARKET_READY`;}else if(!plan.ok||!plan.executable){deterministicKeep=false;reason=`PLAN_${plan.reason||'NO_LONGER_EXECUTABLE'}`;}else if(newSide&&originalSide&&newSide!==originalSide){deterministicKeep=false;reason=`SIDE_CHANGED_${originalSide}_TO_${newSide}`;}let gate={pass:true,reasons:[]};if(deterministicKeep){const candidate={...c,symbol:x.symbol,entry:Number(quote.price),sl:plan.sl,tp:plan.tp,rr:plan.rr,setup:plan.setup,upstreamStatus:status,side:originalSide||newSide,quote};gate=evaluateMarketCandidate(x.market,candidate);if(!gate.pass){deterministicKeep=false;reason=`MARKET_GATE_${(gate.reasons||[]).join('|')||'REJECTED'}`;}}
 const due=Date.now()-Number(x.lastAiReviewAt||0)>=AI_RECHECK_MS;if(!due&&deterministicKeep)return {keep:true,reason:'AI_RECHECK_NOT_DUE',lastAiReviewAt:x.lastAiReviewAt,lastAiVotes:x.lastAiVotes,lastAiValid:x.lastAiValid};const ai=await aiReevaluate(x,{analysis,quote,status,candidate:c,plan},{keep:deterministicKeep,reason,gateReasons:gate.reasons||[]},env);const meta={lastAiReviewAt:Date.now(),lastAiVotes:ai.votes,lastAiValid:ai.valid,lastAiCutVotes:ai.cut,lastAiKeepVotes:ai.keep};if(ai.cutConfirmed)return {keep:false,reason:`AI_4OF5_CUT:${reason}`,cutAiVotes:ai.cut,cutAiValid:ai.valid,...meta};return {keep:true,reason:ai.valid<4?`AI_INSUFFICIENT_EVIDENCE:${reason}`:ai.keepConfirmed?'AI_KEEP_CONFIRMED':`AI_NO_CUT_CONSENSUS:${reason}`,...meta};}
export async function scheduledNativeV11(event,env,ctx){ctx.waitUntil((async()=>{const lifecycle=await refreshV11Lifecycle(env,(s,m)=>lifecycleQuote(s,m,env),(x,q)=>revalidateOpenSignal(x,q,env));for(const x of lifecycle.events||[])await notify(env,lifecycleText(x));const t=Number(event?.scheduledTime||Date.now()),state=await env.TRADING_STATE?.get(SKEY,'json')||{last:{}};let pick=null,over=-Infinity;for(const m of V11_GROUPS){const due=t-Number(state.last?.[m]||0)-V11_CONFIG.scanCadenceSec[m]*1000;if(due>=0&&due>over){pick=m;over=due;}}if(!pick)return;const out=await scanMarketV11(env,pick);if(out.status==='SCANNED'){state.last={...(state.last||{}),[pick]:t};state.updatedAt=Date.now();await env.TRADING_STATE?.put(SKEY,JSON.stringify(state));}})().catch(e=>console.error('V11_NATIVE_CRON',e)));}
