import baseEngine from '../engine-v77168.js';
import {telegramApiRequest} from '../providers/telegram-client.js';
import {V11_CONFIG,V11_GROUPS} from './config.js';
import {buildEntryPlan} from './entry-plan.js';
import {evaluateMarketCandidate} from './market-policies.js';
import {recordV11,refreshV11Lifecycle} from './store.js';
const SKEY='v11:native:schedule';
const ACTIONABLE=new Set(['MARKET_SIGNAL','MARKET','LIMIT','MARKET_PLAN','LIMIT_PLAN']);
const MARKET_READY=new Set(['MARKET_SIGNAL','MARKET']);
async function engine(path,env){const r=await baseEngine.fetch(new Request(`https://v11.internal${path}`),env);try{return await r.json()}catch{return null}}
const finite=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const px=v=>Number.isFinite(Number(v))?Number(v).toPrecision(7):'—';
const pnlPct=(side,entry,price)=>{entry=Number(entry);price=Number(price);if(!(entry>0)||!(price>0))return null;return (String(side).toUpperCase()==='SHORT'?(entry-price):(price-entry))/entry*100;};
async function notify(env,text){if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID)return false;try{await telegramApiRequest(env,'sendMessage',{chat_id:env.TELEGRAM_CHAT_ID,text,disable_web_page_preview:true});return true}catch(e){console.error('V11_TELEGRAM_NOTIFY',e);return false}}
function signalText(x){const c=x.candidate||{},q=c.quote||c.analysisQuote||{},quality=Number(c.qualityScore??c.score),fresh=Number.isFinite(Number(q.quoteAgeSec))?`${Number(q.quoteAgeSec)}s`:q.fresh===true?'YES':'—';return [`🟢 V11 MARKET SIGNAL`,`━━━━━━━━━━━━`,`${String(x.market||'').toUpperCase()} • ${c.side==='LONG'?'BUY':'SELL'} ${x.symbol}`,`📍 Entry ${px(c.entry)}`,`🛑 SL ${px(c.sl)}`,`🎯 TP ${px(c.tp)}`,`⚖️ RR ${Number(c.rr||0).toFixed(2)}`,`⭐ Quality ${Number.isFinite(quality)?quality.toFixed(0)+'/100':'—'}`,`📡 Fresh ${fresh} • ${q.source||c.source||'verified source'}`,`🧭 ${c.setup||'—'}`,``,`WHY NOW`,`• upstream ${c.upstreamStatus||'MARKET_READY'}`,`• structure geometry valid`,`• deterministic V11 market gates passed`,``,`⚠️ SIGNAL ONLY • không phải broker fill`].join('\n');}
function lifecycleText(x){const c=x.candidate||{},p=pnlPct(c.side,c.entry,x.closePrice),ps=p==null?'—':`${p>=0?'+':''}${p.toFixed(2)}%`,icon=x.outcome==='WIN'?'✅':x.outcome==='LOSS'?'🛑':x.outcome==='CUT'?'✂️':'⌛';return [`${icon} V11 ${x.lifecycleStatus}`,`━━━━━━━━━━━━`,`${String(x.market||'').toUpperCase()} • ${c.side==='LONG'?'BUY':'SELL'} ${x.symbol}`,`📍 Entry ${px(c.entry)}`,`🏁 Close ${px(x.closePrice)}`,`📊 P/L từ Entry: ${ps}`,`🛑 SL ${px(c.sl)} • 🎯 TP ${px(c.tp)}`,`Kết quả: ${x.outcome}`,x.outcome==='CUT'?`Lý do CUT: ${x.cutReason||'REEVALUATION_FAILED'}`:null].filter(Boolean).join('\n');}
function normalizeCandidate(a,q){const planned=a.planned||{},canonical=a.canonical||{},mg=canonical.marketGeometry||{},lg=canonical.limitGeometry||{},m15=canonical.m15Location||{},m5=canonical.m5Trigger||{};const atrCandidates=[a.atr,a.atr14,a.indicators?.atr,a.indicators?.atr14,a.M5?.atr14,a.M15?.atr14,a.H1?.atr14,a.timeframes?.M5?.atr14,a.timeframes?.M15?.atr14,a.timeframes?.H1?.atr14,planned.atr,planned.atr14,mg.atr,lg.atr].map(finite).filter(x=>x>0);const entry=finite(a.entry??planned.entry??q.price);const structureLevels=[a.swingLow,a.swingHigh,a.support,a.resistance,a.structureInvalidation,a.swingInvalidation,m15.level,m5.level,mg.level,lg.level,planned.sl].map(finite).filter(Number.isFinite);const liquidityLevels=[a.liquidityLow,a.liquidityHigh,a.target1,a.target2,a.tp,a.tp1,a.tp2,planned.tp,planned.tp1,planned.tp2].map(finite).filter(Number.isFinite);return {...a,price:finite(q.price),entry,quote:q,atr:atrCandidates[0]??null,qualityScore:Number(a.qualityScore??a.quality??a.score??0),structureLevels,liquidityLevels};}
async function freshAnalyze(symbol,env){const a=await engine(`/analyze?symbol=${encodeURIComponent(symbol)}`,env),q=a?.analysisQuote||a?.quote;if(!(Number(q?.price)>0)||q?.fresh!==true)throw new Error('V11_QUOTE_NOT_VERIFIED_FRESH');return {analysis:a,quote:{...q,price:Number(q.price),fresh:true}};}
async function resolveFreshAnalysis(raw,env){const q=raw?.analysisQuote||raw?.quote;if(Number(q?.price)>0&&q?.fresh===true)return {analysis:raw,quote:{...q,price:Number(q.price),fresh:true}};return freshAnalyze(raw.symbol,env);}
export async function scanMarketV11(env,market){const r=await engine(`/run-now?group=${market}`,env);if(!r?.ok||['BUSY','RATE_BUDGET_WAIT'].includes(String(r?.status||'')))return {status:r?.status||'SCAN_FAILED',market,approved:0};let approved=0,watch=0,rejected=0,notified=0,capped=0;for(const raw of r.analyses||[]){if(!ACTIONABLE.has(String(raw?.status||'').toUpperCase())||!raw?.symbol)continue;try{const {analysis,quote}=await resolveFreshAnalysis(raw,env),upstreamStatus=String(analysis?.status||raw?.status||'').toUpperCase(),c=normalizeCandidate({...raw,...analysis},quote),plan=buildEntryPlan(market,c);if(!plan.ok||!plan.executable){await recordV11(env,{status:plan.ok?'WATCH':'REJECTED',market,symbol:raw.symbol,plan});plan.ok?watch++:rejected++;continue;}if(!MARKET_READY.has(upstreamStatus)){await recordV11(env,{status:'WATCH',market,symbol:raw.symbol,reason:'UPSTREAM_'+upstreamStatus+'_NOT_MARKET_READY',plan});watch++;continue;}const candidate={...c,symbol:plan.symbol,entry:plan.entry,sl:plan.sl,tp:plan.tp,rr:plan.rr,setup:plan.setup,upstreamStatus};const gate=evaluateMarketCandidate(market,candidate);if(!gate.pass){await recordV11(env,{status:'REJECTED',market,symbol:plan.symbol,reason:gate.reasons?.join('|')||'MARKET_POLICY_REJECTED',plan,gate});rejected++;continue;}const saved=await recordV11(env,{status:'APPROVED_SIGNAL',version:'V11',market,symbol:plan.symbol,candidate,plan,gate,approvedAt:Date.now(),expiresAt:Date.now()+V11_CONFIG.markets[market].horizonMin*60000});approved++;if(saved.storeReason==='MARKET_CAP_REACHED'){capped++;continue;}if(saved.stored&&await notify(env,signalText(saved)))notified++;}catch(e){await recordV11(env,{status:'REJECTED',market,symbol:raw.symbol,plan:{reason:String(e?.message||e)}});rejected++;}}return {status:'SCANNED',market,approved,watch,rejected,notified,capped,maxOpenPerMarket:5,coverage:{requested:r.requested,broadOk:r.broadOk,deepOk:r.deepOk}};}
async function lifecycleQuote(symbol,market,env){const {quote}=await freshAnalyze(symbol,env);return quote;}
async function revalidateOpenSignal(x,q,env){const {analysis,quote}=await freshAnalyze(x.symbol,env),status=String(analysis?.status||'').toUpperCase();if(!MARKET_READY.has(status))return {keep:false,reason:`UPSTREAM_${status||'UNKNOWN'}_NOT_MARKET_READY`};const c=normalizeCandidate(analysis,quote),plan=buildEntryPlan(x.market,c);if(!plan.ok||!plan.executable)return {keep:false,reason:`PLAN_${plan.reason||'NO_LONGER_EXECUTABLE'}`};const originalSide=String(x.candidate?.side||'').toUpperCase(),newSide=String(plan.side||c.side||'').toUpperCase();if(newSide&&originalSide&&newSide!==originalSide)return {keep:false,reason:`SIDE_CHANGED_${originalSide}_TO_${newSide}`};const candidate={...c,symbol:x.symbol,entry:Number(q?.price)||plan.entry,sl:plan.sl,tp:plan.tp,rr:plan.rr,setup:plan.setup,upstreamStatus:status,side:originalSide||newSide};const gate=evaluateMarketCandidate(x.market,candidate);if(!gate.pass)return {keep:false,reason:`MARKET_GATE_${(gate.reasons||[]).join('|')||'REJECTED'}`};return {keep:true,reason:'STILL_VALID'};}
export async function scheduledNativeV11(event,env,ctx){ctx.waitUntil((async()=>{const lifecycle=await refreshV11Lifecycle(env,(s,m)=>lifecycleQuote(s,m,env),(x,q)=>revalidateOpenSignal(x,q,env));for(const x of lifecycle.events||[])await notify(env,lifecycleText(x));const t=Number(event?.scheduledTime||Date.now()),state=await env.TRADING_STATE?.get(SKEY,'json')||{last:{}};let pick=null,over=-Infinity;for(const m of V11_GROUPS){const due=t-Number(state.last?.[m]||0)-V11_CONFIG.scanCadenceSec[m]*1000;if(due>=0&&due>over){pick=m;over=due;}}if(!pick)return;const out=await scanMarketV11(env,pick);if(out.status==='SCANNED'){state.last={...(state.last||{}),[pick]:t};state.updatedAt=Date.now();await env.TRADING_STATE?.put(SKEY,JSON.stringify(state));}})().catch(e=>console.error('V11_NATIVE_CRON',e)));}
