const K={accepted:'v11:accepted',history:'v11:history',funnel:'v11:funnel'};
const MAX_OPEN_PER_MARKET=5;
async function get(env,k,d=[]){try{return await env.TRADING_STATE?.get(k,'json')??d}catch{return d}}
async function put(env,k,v){if(!env.TRADING_STATE)throw new Error('TRADING_STATE_REQUIRED');await env.TRADING_STATE.put(k,JSON.stringify(v));}
export async function recordV11(env,x){const f=await get(env,K.funnel,[]);const gateReasons=Array.isArray(x.gate?.reasons)?x.gate.reasons:[];const reason=x.reason||(gateReasons.length?gateReasons.join('|'):null)||x.plan?.reason||x.decision?.reason||null;f.unshift({at:Date.now(),status:x.status,market:x.market,symbol:x.symbol,reason,gateReasons:gateReasons.length?gateReasons:null,planReason:x.plan?.reason||null});await put(env,K.funnel,f.slice(0,500));if(x.status!=='APPROVED_SIGNAL')return {...x,stored:false};const a=await get(env,K.accepted,[]),id=`V11:${x.market}:${x.symbol}:${x.candidate.side}:${Math.round(x.approvedAt/60000)}`,duplicateOpen=a.some(y=>y.lifecycleStatus==='OPEN'&&y.market===x.market&&y.symbol===x.symbol&&y.candidate?.side===x.candidate?.side),duplicateId=a.some(y=>y.id===id),openInMarket=a.filter(y=>y.lifecycleStatus==='OPEN'&&y.market===x.market).length,capacityOpen=openInMarket<MAX_OPEN_PER_MARKET,stored=!duplicateOpen&&!duplicateId&&capacityOpen;if(stored)a.unshift({...x,id,lifecycleStatus:'OPEN',lastAiReviewAt:0,lastAiVotes:null,lastAiValid:0,lastAiCutVotes:0,lastAiKeepVotes:0,quoteFailureCount:0});await put(env,K.accepted,a.slice(0,100));return {...x,id,stored,capacityOpen,openInMarket,maxOpenPerMarket:MAX_OPEN_PER_MARKET,storeReason:stored?'STORED':duplicateOpen?'DUPLICATE_OPEN':duplicateId?'DUPLICATE_ID':'MARKET_CAP_REACHED'};}
export async function getV11Accepted(env,market){const a=await get(env,K.accepted,[]);return a.filter(x=>x.lifecycleStatus==='OPEN'&&(!market||x.market===market));}
export async function getV11History(env,market){const h=await get(env,K.history,[]);return h.filter(x=>!market||x.market===market);}
export async function getV11Funnel(env){return get(env,K.funnel,[]);}
export async function refreshV11Lifecycle(env,quoteFn,revalidateFn){const a=await get(env,K.accepted,[]),h=await get(env,K.history,[]),keep=[],events=[],now=Date.now();for(const original of a){if(original.lifecycleStatus!=='OPEN')continue;const x={...original};const upstream=String(x.candidate?.upstreamStatus||x.candidate?.status||'').toUpperCase();if(['LIMIT','LIMIT_PLAN','MARKET_PLAN','WATCH'].includes(upstream)){const closed={...x,lifecycleStatus:'CUT',closedAt:now,outcome:'CUT',cutReason:'LEGACY_NON_MARKET'};h.unshift(closed);events.push(closed);continue;}if(Number(x.expiresAt)>0&&now>=Number(x.expiresAt)){const closed={...x,lifecycleStatus:'EXPIRED',closedAt:now,closePrice:x.currentPrice??null,outcome:'EXPIRED',closeReason:'HORIZON_EXPIRED'};h.unshift(closed);events.push(closed);continue;}let close=null,price=null,q=null;try{q=await quoteFn(x.symbol,x.market);if(q?.fresh!==true||!(Number(q.price)>0))throw new Error('QUOTE_NOT_FRESH');price=Number(q.price);x.currentPrice=price;x.currentQuote={source:q.source||null,providerTimestamp:q.providerTimestamp||null,quoteAgeSec:q.quoteAgeSec??null,fresh:true,crossSourceCount:q.crossSourceCount??null,crossSources:q.crossSources??null};x.lastPriceAt=now;x.quoteFailureCount=0;x.lastQuoteError=null;}catch(e){x.quoteFailureCount=Number(x.quoteFailureCount||0)+1;x.lastQuoteError=String(e?.message||e).slice(0,300);x.lastQuoteFailureAt=now;keep.push(x);continue;}const c=x.candidate,side=String(c.side||'').toUpperCase();if(side==='LONG'){if(price<=c.sl)close='SL';else if(price>=c.tp)close='TP';}else if(side==='SHORT'){if(price>=c.sl)close='SL';else if(price<=c.tp)close='TP';}if(!close&&typeof revalidateFn==='function'){try{const verdict=await revalidateFn(x,q);if(verdict&&typeof verdict==='object'){for(const k of ['lastAiReviewAt','lastAiVotes','lastAiValid','lastAiCutVotes','lastAiKeepVotes'])if(verdict[k]!==undefined)x[k]=verdict[k];x.lastReevaluationReason=verdict.reason||null;if(verdict.keep===false){close='CUT';x.cutReason=String(verdict.reason||'AI_REEVALUATION_FAILED').slice(0,500);x.cutAiVotes=verdict.cutAiVotes??verdict.lastAiCutVotes??null;x.cutAiValid=verdict.cutAiValid??verdict.lastAiValid??null;}}}catch{/* never CUT on evaluator transport failure */}}if(close){const closed={...x,lifecycleStatus:close,closedAt:now,closePrice:price,outcome:close==='TP'?'WIN':close==='SL'?'LOSS':'CUT'};h.unshift(closed);events.push(closed);}else keep.push(x);}await put(env,K.accepted,keep);await put(env,K.history,h.slice(0,1000));return {open:keep.length,history:h.length,events};}
