const fs=require('fs');
const p='cloudflare-worker/index.js';
let s=fs.readFileSync(p,'utf8');
function must(oldv,newv,label){if(!s.includes(oldv))throw new Error('marker missing '+label);s=s.replace(oldv,newv);}
must('version: "V77.16.7",','version: "V77.16.8",','version');
must('service: "Trading V77.16.7 Durable Order Archive Hub",','service: "Trading V77.16.8 Role Navigation Hub",','service');
const oldBase='function baseKeyboard(){return {inline_keyboard:[[{text:"🧭 HUB TOP SETUPS",callback_data:"hub"}],[{text:"💱 FOREX",callback_data:"scan:forex"},{text:"🪙 CRYPTO",callback_data:"scan:crypto"}],[{text:"🥇 METAL",callback_data:"scan:metal"},{text:"📈 FUTURES",callback_data:"scan:future"}],[{text:"🔎 TỪNG SYMBOL",callback_data:"symbols"}],[{text:"📊 STATUS",callback_data:"status"},{text:"📚 LIVE ORDERS",callback_data:"books"}]]};}';
const newBase=`function baseKeyboard(){return {inline_keyboard:[[{text:"📡 SIGNAL",callback_data:"signal"}],[{text:"🏦 PROP",callback_data:"prop"},{text:"👤 CÁ NHÂN",callback_data:"personal"}],[{text:"🔎 SYMBOL",callback_data:"symbols"}],[{text:"📊 STATUS",callback_data:"status"},{text:"📚 LIVE ORDERS",callback_data:"books"}]]};}\nfunction signalKeyboard(){return {inline_keyboard:[[{text:"🧭 QUÉT TẤT CẢ / TOP SETUPS",callback_data:"hub"}],[{text:"💱 FOREX",callback_data:"scan:forex"},{text:"🪙 CRYPTO",callback_data:"scan:crypto"}],[{text:"🥇 METAL",callback_data:"scan:metal"},{text:"📈 FUTURES",callback_data:"scan:future"}],[{text:"⬅️ MENU CHÍNH",callback_data:"menu"}]]};}\nfunction propKeyboard(){return {inline_keyboard:[[{text:"🟣 HYROTRADER",callback_data:"prop:hyro"},{text:"🔵 BREAKOUT",callback_data:"prop:breakout"}],[{text:"📚 LỆNH PROP",callback_data:"prop:orders"},{text:"🛡️ RISK PROP",callback_data:"prop:risk"}],[{text:"⬅️ MENU CHÍNH",callback_data:"menu"}]]};}\nfunction personalKeyboard(){return {inline_keyboard:[[{text:"🖥️ MT5 CÁ NHÂN",callback_data:"personal:mt5"}],[{text:"📚 LỆNH CÁ NHÂN",callback_data:"personal:orders"},{text:"🛡️ RISK CÁ NHÂN",callback_data:"personal:risk"}],[{text:"⬅️ MENU CHÍNH",callback_data:"menu"}]]};}`;
must(oldBase,newBase,'baseKeyboard');
const oldBack='[{text:"⬅️ HUB",callback_data:"hub"}]';
s=s.replace(oldBack,'[{text:"⬅️ MENU CHÍNH",callback_data:"menu"}]');
s=s.replaceAll('{text:"🧭 HUB",callback_data:"hub"}','{text:"📡 SIGNAL",callback_data:"signal"}');
const marker='  if(cb==="hub"||text==="/hub")await sendHub(env,chatId);';
const repl=`  if(cb==="menu"||text==="/start"||text==="/menu")await sendText(env,"🏠 TRADING HUB\\n\\nChọn khu vực:",chatId,baseKeyboard());\n  else if(cb==="signal")await sendText(env,"📡 SIGNAL\\n\\nMỗi lần bấm quét sẽ lấy dữ liệu thị trường mới. Chọn toàn thị trường hoặc từng thị trường:",chatId,signalKeyboard());\n  else if(cb==="prop")await sendText(env,"🏦 PROP\\n\\nTheo dõi các tài khoản quỹ được tích hợp. Kết nối execution sẽ được bật riêng cho từng quỹ sau khi xác nhận API/rule.",chatId,propKeyboard());\n  else if(cb==="prop:hyro")await sendText(env,"🟣 HYROTRADER\\n\\nTrạng thái: CHƯA KẾT NỐI TÀI KHOẢN/API.\\nSignal engine vẫn hoạt động độc lập; chưa tự gửi lệnh vào quỹ.",chatId,propKeyboard());\n  else if(cb==="prop:breakout")await sendText(env,"🔵 BREAKOUT\\n\\nTrạng thái: CHƯA KẾT NỐI TÀI KHOẢN/API.\\nChưa bật auto-execution cho tới khi quyền bot/API được xác nhận.",chatId,propKeyboard());\n  else if(cb==="prop:orders"||cb==="prop:risk")await sendText(env,"🏦 PROP\\n\\nChưa có tài khoản prop được kết nối nên chưa có position/risk telemetry riêng.",chatId,propKeyboard());\n  else if(cb==="personal")await sendText(env,"👤 CÁ NHÂN\\n\\nTheo dõi tài khoản cá nhân đã tích hợp. MT5 Bridge sẽ cung cấp equity, positions, broker bid/ask và execution khi được kết nối.",chatId,personalKeyboard());\n  else if(cb?.startsWith("personal:"))await sendText(env,"👤 MT5 CÁ NHÂN\\n\\nTrạng thái: CHƯA KẾT NỐI MT5 BRIDGE.\\nKhi kết nối, khu vực này sẽ hiển thị Equity • Daily P/L • Live Positions • Pending • Risk.",chatId,personalKeyboard());\n  else if(cb==="hub"||text==="/hub")await sendHub(env,chatId);`;
must(marker,repl,'telegram callbacks');
fs.writeFileSync(p,s);
console.log('V77.16.8 hub navigation migration applied');