const fs=require('fs');
const p='cloudflare-worker/index.js';let s=fs.readFileSync(p,'utf8');
function must(a,b,l){if(!s.includes(a))throw new Error('Missing '+l);s=s.replace(a,b);}
if(!s.includes('version: "V77.16.1"'))throw new Error('Expected V77.16.1');
s=s.replaceAll('V77.16.1','V77.16.2');
s=s.replace('Trading V77.16.2 Plan-Invariant Quality Hub','Trading V77.16.2 Risk-Calibrated Quality Hub');
const old='function planSignal(symbol,type,side,reason,planned,extra={}){const intel=extra?.method||null,q=rrQuality(planned,intel);if(planned&&Number.isFinite(Number(planned.targetRR))&&!q.pass)return watch(symbol,type,side,"RR_QUALITY_REQUIRED",{...extra,rejectedPlan:{entry:planned.entry,sl:planned.sl,tp1:planned.tp1,tp2:planned.tp2,targetRR:planned.targetRR,minQualityRR:q.minRR,entryStyle:planned.entryStyle||null},planned:null});const status=plannedModeLabel(planned);return {ok:true,status,action:status,symbol,market:type,side,reason,canonicalStage:reason,planned:{...planned,minQualityRR:planned?.minQualityRR??q.minRR,rrQualityPass:true,planType:status,executionVerified:false},executionReady:false,engine:CONFIG.version,...extra};}';
const neu='function planSignal(symbol,type,side,reason,planned,extra={}){const intel=extra?.method||null,q=rrQuality(planned,intel);if(planned&&Number.isFinite(Number(planned.targetRR))&&!q.pass)return watch(symbol,type,side,"RR_QUALITY_REQUIRED",{...extra,rejectedPlan:{entry:planned.entry,sl:planned.sl,tp1:planned.tp1,tp2:planned.tp2,targetRR:planned.targetRR,minQualityRR:q.minRR,entryStyle:planned.entryStyle||null},planned:null});if(type==="future"&&["MNQ","MES"].includes(norm(symbol))&&planned){const fs=futureSizing(symbol,planned);if(fs&&!fs.tradable)return watch(symbol,type,side,"FUTURE_RISK_LIMIT_REQUIRED",{...extra,microSizing:fs,rejectedPlan:{entry:planned.entry,sl:planned.sl,tp1:planned.tp1,tp2:planned.tp2,targetRR:planned.targetRR,entryStyle:planned.entryStyle||null,oneContractRiskUsd:fs.oneContractRiskUsd},planned:null});}const status=plannedModeLabel(planned);return {ok:true,status,action:status,symbol,market:type,side,reason,canonicalStage:reason,planned:{...planned,minQualityRR:planned?.minQualityRR??q.minRR,rrQualityPass:true,planType:status,executionVerified:false},executionReady:false,engine:CONFIG.version,...extra};}';
must(old,neu,'future central risk invariant');
fs.writeFileSync(p,s);console.log('Applied V77.16.2 future risk invariant');
