const fs=require('fs');
const path='cloudflare-worker/index.js';
let s=fs.readFileSync(path,'utf8');
function mustReplace(from,to,label){if(!s.includes(from))throw new Error('Missing '+label);s=s.replace(from,to);}
function insertBefore(marker,block,label){const i=s.indexOf(marker);if(i<0)throw new Error('Missing '+label);s=s.slice(0,i)+block+s.slice(i);}
function replaceRange(start,end,repl,label){const a=s.indexOf(start);if(a<0)throw new Error('Missing start '+label);const b=s.indexOf(end,a+start.length);if(b<0)throw new Error('Missing end '+label);s=s.slice(0,a)+repl+s.slice(b);}

mustReplace('import SYMBOL_KNOWLEDGE from "../data/symbol_knowledge_registry.json" with { type: "json" };','import SYMBOL_KNOWLEDGE from "../data/symbol_knowledge_registry.json" with { type: "json" };\nimport FUTURES_KNOWLEDGE from "../data/futures_knowledge.json" with { type: "json" };','futures import');
s=s.replaceAll('V77.13.1','V77.14.0');
s=s.replace('Trading V77.14.0 Calibrated Adaptive Entry Hub','Trading V77.14.0 Futures Actionable Entry Hub');
mustReplace('cryptoQuoteAgeSec: 10,','cryptoQuoteAgeSec: 10,\n  futureQuoteAgeSec: 12,\n  futureAnalysisMaxAgeSec: 900,','future age config');
mustReplace('shadowSetups: "v7713:shadow_setups",','shadowSetups: "v7713:shadow_setups",\n    futureContract: "v7714:future_contract",','future state key');

mustReplace('const METALS = ["XAUUSD","XAGUSD"];\nconst GROUPS = { forex: FOREX, crypto: CRYPTO, metal: METALS };','const METALS = ["XAUUSD","XAGUSD"];\nconst FUTURE_SYMBOLS = ["NQ","MNQ","ES","MES"];\nconst FUTURE_SCAN = ["NQ","ES"];\nconst GROUPS = { forex: FOREX, crypto: CRYPTO, metal: METALS, future: FUTURE_SYMBOLS };','future universe');
mustReplace('function marketType(symbol){const s=norm(symbol);if(FOREX.includes(s))return "forex";if(CRYPTO.includes(s))return "crypto";if(METALS.includes(s))return "metal";return "unknown";}','function marketType(symbol){const s=norm(symbol);if(FOREX.includes(s))return "forex";if(CRYPTO.includes(s))return "crypto";if(METALS.includes(s))return "metal";if(FUTURE_SYMBOLS.includes(s))return "future";return "unknown";}','market type future');

const massiveBlock=[
'async function massiveFetch(pathname,params,env){',
'  if(!env.MASSIVE_API_KEY)throw new Error("MASSIVE_API_KEY missing");',
'  const q=new URLSearchParams(params||{});q.set("apiKey",env.MASSIVE_API_KEY);',
'  const r=await fetchTimeout("https://api.massive.com"+pathname+"?"+q,{},9000),p=await r.json().catch(()=>null);',
'  if(!r.ok||!p||p.status!=="OK")throw new Error(p?.error||p?.message||("Massive HTTP "+r.status));return p;',
'}',
'async function futureContractSuffix(env){',
'  try{const c=await env.TRADING_STATE?.get(CONFIG.keys.futureContract,"json");if(c?.suffix&&Date.now()-Number(c.savedAt)<21600000)return c.suffix;}catch{}',
'  const today=new Date().toISOString().slice(0,10),p=await massiveFetch("/futures/v1/contracts",{product_code:"NQ",active:"true",date:today,limit:"100"},env);',
'  const rows=(p.results||[]).filter(x=>x.active!==false&&String(x.ticker||"").startsWith("NQ")&&Number(x.days_to_maturity)>=0).sort((a,b)=>Number(a.days_to_maturity)-Number(b.days_to_maturity));',
'  const ticker=String(rows[0]?.ticker||"");if(!ticker.startsWith("NQ"))throw new Error("Massive NQ front contract unresolved");const suffix=ticker.slice(2);',
'  try{await env.TRADING_STATE?.put(CONFIG.keys.futureContract,JSON.stringify({suffix,ticker,savedAt:Date.now()}),{expirationTtl:21600});}catch{}return suffix;',
'}',
'function massiveResolutionSec(r){return r==="5min"?300:r==="1hour"?3600:0;}',
'async function massiveAgg(ticker,resolution,limit,env){',
'  const p=await massiveFetch("/futures/v1/aggs/"+encodeURIComponent(ticker),{resolution,limit:String(limit)},env),sec=massiveResolutionSec(resolution),now=nowSec();',
'  return (p.results||[]).map(x=>({timestamp:Math.floor(Number(x.window_start)/1e9),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close),volume:num(x.volume),sessionEndDate:x.session_end_date||null,ticker:x.ticker||ticker})).filter(x=>x.timestamp&&Number.isFinite(x.open)&&Number.isFinite(x.high)&&Number.isFinite(x.low)&&Number.isFinite(x.close)&&(!sec||x.timestamp+sec<=now)).sort((a,b)=>a.timestamp-b.timestamp);',
'}',
'function aggregateFixed(rows,bucketSec){const m=new Map();for(const x of rows||[]){const k=Math.floor(x.timestamp/bucketSec)*bucketSec;let a=m.get(k);if(!a){a={timestamp:k,open:x.open,high:x.high,low:x.low,close:x.close,volume:Number(x.volume)||0};m.set(k,a);}else{a.high=Math.max(a.high,x.high);a.low=Math.min(a.low,x.low);a.close=x.close;a.volume+=(Number(x.volume)||0);}}return [...m.values()].sort((a,b)=>a.timestamp-b.timestamp);}',
'function aggregateSessions(rows){const m=new Map();for(const x of rows||[]){const k=x.sessionEndDate||new Date(x.timestamp*1000).toISOString().slice(0,10);let a=m.get(k);if(!a){a={timestamp:x.timestamp,open:x.open,high:x.high,low:x.low,close:x.close,volume:Number(x.volume)||0,sessionEndDate:k};m.set(k,a);}else{a.timestamp=Math.min(a.timestamp,x.timestamp);a.high=Math.max(a.high,x.high);a.low=Math.min(a.low,x.low);a.close=x.close;a.volume+=(Number(x.volume)||0);}}return [...m.values()].sort((a,b)=>a.timestamp-b.timestamp);}',
'async function futureBundle(symbol,env,suffix=null){',
'  const s=norm(symbol);if(!FUTURE_SYMBOLS.includes(s))throw new Error("Unsupported future symbol");const sf=suffix||await futureContractSuffix(env),ticker=s+sf;',
'  const [m5,h1]=await Promise.all([massiveAgg(ticker,"5min",900,env),massiveAgg(ticker,"1hour",2200,env)]);if(m5.length<80||h1.length<300)throw new Error("Massive futures history insufficient for "+ticker);',
'  const m15=aggregateFixed(m5,900),h4=aggregateFixed(h1,14400),d1=aggregateSessions(h1),last=m5.at(-1),age=last?Math.max(0,nowSec()-last.timestamp-300):null;',
'  return {symbol:s,ticker,suffix:sf,candles:[m5,m15,h1,h4,d1],quote:{source:"Massive Futures closed bars",providerSymbol:ticker,price:last?.close??null,providerTimestamp:last?.timestamp??null,quoteAgeSec:age,fresh:age!==null&&age<=CONFIG.futureAnalysisMaxAgeSec,executionVerified:false,analysisOnly:true},source:"Massive Futures"};',
'}',
'function recentMove(c,n=12){if(!Array.isArray(c)||c.length<n+1)return 0;const a=c.at(-(n+1))?.close,b=c.at(-1)?.close;return a?((b-a)/a)*100:0;}',
'function futurePairContext(nq,es,which){const nqMove=recentMove(nq.candles[2]),esMove=recentMove(es.candles[2]),rel=nqMove-esMove,isNq=which==="NQ"||which==="MNQ",x=isNq?rel:-rel;return {relativeStrength:x,benchmark:isNq?"ES":"NQ",nqMovePct:nqMove,esMovePct:esMove,smtDivergence:Math.sign(nqMove)!==Math.sign(esMove)&&Math.abs(rel)>.12,score:Math.min(10,5+Math.abs(x)*8)};}',
'function mirrorFutureAnalysis(a,target){if(!a)return null;const k=symbolKnowledge(target);return {...a,symbol:target,market:"future",source:(a.source||"Massive Futures")+" • leader mirror",knowledge:k?{canonicalSymbol:k.canonicalSymbol,allowedModes:k.allowedModes,riskATR:k.riskATR,calibration:k.calibration}:a.knowledge,executionLeader:a.symbol,basisReference:true};}',
'async function runFutureSymbol(symbol,env){const s=norm(symbol),suffix=await futureContractSuffix(env),b=await futureBundle(s,env,suffix);return deepAnalyze(s,env,b.candles,b.quote,b.source,{score:6,benchmark:FUTURES_KNOWLEDGE?.symbols?.[s]?.benchmark||null});}',
'async function runFutureGroup(env){',
'  if(!(await acquireLock(env)))return {ok:false,status:"BUSY",group:"future",version:CONFIG.version,scanId:"future-busy-"+Date.now(),scannedAt:new Date().toISOString(),analyses:[]};',
'  const started=Date.now(),scanId="future-"+started+"-"+Math.random().toString(36).slice(2,8),scannedAt=new Date(started).toISOString();try{',
'    if(!env.MASSIVE_API_KEY){const out={ok:true,version:CONFIG.version,status:"DATA_BLOCK",group:"future",scanId,scannedAt,requested:4,broadOk:0,deepRequested:4,deepOk:0,newCount:0,analyses:[],diagnostics:{error:"MASSIVE_API_KEY missing"},elapsedMs:Date.now()-started};await saveScanSnapshot("future",out,env);return out;}',
'    const suffix=await futureContractSuffix(env);let nq=null,es=null,errors=[];const rs=await Promise.allSettled([futureBundle("NQ",env,suffix),futureBundle("ES",env,suffix)]);if(rs[0].status==="fulfilled")nq=rs[0].value;else errors.push({symbol:"NQ",error:String(rs[0].reason?.message||rs[0].reason)});if(rs[1].status==="fulfilled")es=rs[1].value;else errors.push({symbol:"ES",error:String(rs[1].reason?.message||rs[1].reason)});',
'    const analyses=[];if(nq){const a=await deepAnalyze("NQ",env,nq.candles,nq.quote,nq.source,es?futurePairContext(nq,es,"NQ"):{score:5});analyses.push(a,mirrorFutureAnalysis(a,"MNQ"));}if(es){const a=await deepAnalyze("ES",env,es.candles,es.quote,es.source,nq?futurePairContext(nq,es,"ES"):{score:5});analyses.push(a,mirrorFutureAnalysis(a,"MES"));}',
'    const books=await getBooks(env);for(const a of analyses.filter(Boolean))await recordShadowSetup("future",a,scanId,env);const out={ok:true,version:CONFIG.version,group:"future",scanId,scannedAt,requested:4,broadOk:(nq?2:0)+(es?2:0),fresh:analyses.length,deepRequested:4,deepOk:analyses.filter(a=>a&&a.ok!==false).length,newCount:0,analyses:analyses.filter(Boolean),diagnostics:{frontSuffix:suffix,frontContracts:{NQ:nq?.ticker||null,ES:es?.ticker||null,MNQ:nq?"MNQ"+suffix:null,MES:es?"MES"+suffix:null},errors,liveSymbolsSkipped:[...(books.future?.marketActive||[]),...(books.future?.limitActive||[]),...(books.future?.limitPending||[])].map(x=>x.symbol)},elapsedMs:Date.now()-started};await env.TRADING_STATE.put(CONFIG.keys.lastRun,JSON.stringify(out));await saveScanSnapshot("future",out,env);return out;',
'  }finally{await releaseLock(env);}',
'}',
''
].join('\n');
insertBefore('async function bybit(',massiveBlock+'\n','massive functions');

mustReplace('function v73Prior(symbol,type){\n  const e=v73Entry(symbol,type);let key=null;if(type==="forex")key=norm(symbol);if(type==="crypto")key=v73CryptoPriorKey(symbol);','function v73Prior(symbol,type){\n  if(type==="future"){const k=FUTURES_KNOWLEDGE?.symbols?.[norm(symbol)];if(!k)return {applicable:true,available:false,key:norm(symbol)};return {applicable:true,available:true,key:norm(symbol),source:"FUTURES_KNOWLEDGE_V1",timeframe:"MULTI",status:"PRIOR_ONLY_UNCALIBRATED",family:k.profile,families:k.families||[],profile:k.profile,entryMode:"DYNAMIC",rr:null,signalHourUTC:null,riskATR:k.riskATR,newsProfile:{profileDrivers:k.drivers||[]},classification:FUTURES_KNOWLEDGE.classification};}\n  const e=v73Entry(symbol,type);let key=null;if(type==="forex")key=norm(symbol);if(type==="crypto")key=v73CryptoPriorKey(symbol);','future prior');
mustReplace('if(type==="metal"&&Number.isFinite(context.relativeStrength))why.push("metal-relative context");','if(type==="metal"&&Number.isFinite(context.relativeStrength))why.push("metal-relative context");\n  if(type==="future"){if(Number.isFinite(context.relativeStrength))why.push("NQ-ES relative/SMT context");if(context.smtDivergence)fit+=4;}','future method context');
mustReplace('function symbolKnowledge(symbol){const s=canonicalUserSymbol(symbol),k=s.endsWith("USDT")?s.slice(0,-4):s;return SYMBOL_KNOWLEDGE?.symbols?.[s]||SYMBOL_KNOWLEDGE?.symbols?.[k]||null;}','function symbolKnowledge(symbol){const s=canonicalUserSymbol(symbol),k=s.endsWith("USDT")?s.slice(0,-4):s;return FUTURES_KNOWLEDGE?.symbols?.[s]||SYMBOL_KNOWLEDGE?.symbols?.[s]||SYMBOL_KNOWLEDGE?.symbols?.[k]||null;}','knowledge future');

const newsBlock=[
'async function getNewsClearance(symbol,env){',
'  const s=norm(symbol),key=CONFIG.keys.newsPrefix+s;',
'  try{const raw=await env.TRADING_STATE?.get(key,"json");if(raw?.clearedAt&&Date.now()-Number(raw.clearedAt)<=CONFIG.newsClearanceTtlSec*1000)return raw;}catch{}',
'  if(env.NEWS_GATE_URL){try{const u=new URL(env.NEWS_GATE_URL);u.searchParams.set("symbol",s);u.searchParams.set("market",marketType(s));const r=await fetchTimeout(u.toString());const p=await r.json();if(r.ok&&p?.clear===true){const v={clearedAt:Date.now(),source:"NEWS_GATE_URL",detail:p.detail||null,soft:false};await env.TRADING_STATE?.put(key,JSON.stringify(v),{expirationTtl:CONFIG.newsClearanceTtlSec});return v;}return null;}catch{return null;}}',
'  return {clearedAt:Date.now(),source:"SOFT_NO_EXTERNAL_NEWS_FEED",soft:true,detail:"No live news gate configured; technical plan may proceed but Hub labels news as unverified."};',
'}',
''
].join('\n');
replaceRange('async function getNewsClearance(symbol,env){','async function setNewsClearance(symbol,env){',newsBlock+'async function setNewsClearance(symbol,env){','soft news gate');

const geometryBlock=[
'function limitGeometry(side,current,entry,M5,M15,plan){const atr=Number(M15?.atr14)||Number(M5?.atr14)||0;if(!atr||!Number.isFinite(current)||!Number.isFinite(entry))return {pass:false,reason:"NO_ATR"};const dist=Math.abs(current-entry)/atr,correct=side==="LONG"?entry<current:entry>current,notInvalid=side==="LONG"?entry>Number(plan?.sl):entry<Number(plan?.sl);return {pass:correct&&notInvalid&&dist>=.05&&dist<=.90,distanceATR:Number(dist.toFixed(2)),correctSide:correct,notInvalid};}',
'function marketGeometry(side,current,M5,trigPolicy){const atr=Number(M5?.atr14)||0,ref=Number(trigPolicy?.level);if(!atr||!Number.isFinite(current))return {pass:false,chaseATR:null};const chase=Number.isFinite(ref)?Math.abs(current-ref)/atr:0,r=Number(M5?.rsi14??50),notExtreme=side==="LONG"?r<=78:r>=22;return {pass:chase<=.48&&notExtreme,chaseATR:Number(chase.toFixed(2)),rsi:r,notExtreme};}',
'function plannedModeLabel(p){return p?.mode==="MARKET"?"MARKET_PLAN":(p?.mode==="LIMIT"||p?.mode==="INDICATIVE_LIMIT")?"LIMIT_PLAN":"WATCH";}',
''
].join('\n');
insertBefore('async function deepAnalyze(',geometryBlock+'\n','entry geometry');

mustReplace('const news=await getNewsClearance(s,env);if(!news)return watch(s,type,side,"NEWS_CONTEXT_REQUIRED",{...base,score,setupReady:true,planned,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:false}}});\n  score=setupScore({methodFit:intel.methodFit,htf:true,location:true,trigger:!pendingRetest,pending:pendingRetest,plan:true,contextScore:context.score??5,news:true});\n  if(type!=="crypto")return watch(s,type,side,"EXECUTION_QUOTE_REQUIRED",{...base,score,setupReady:true,planned,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:"Twelve Data analysis",canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true}}});','const news=await getNewsClearance(s,env);if(!news)return watch(s,type,side,"NEWS_CONTEXT_REQUIRED",{...base,score,setupReady:true,planned,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:false}}});\n  const newsSoft=!!news.soft;score=setupScore({methodFit:intel.methodFit,htf:true,location:true,trigger:!pendingRetest,pending:pendingRetest,plan:true,contextScore:context.score??5,news:!newsSoft});\n  if(pendingRetest){const lg=limitGeometry(side,M5.close,preview.entry,M5,M15,preview);if(!lg.pass)return watch(s,type,side,"LIMIT_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,geometry:lg},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source},limitGeometry:lg}});}\n  if(type!=="crypto")return watch(s,type,side,"EXECUTION_QUOTE_REQUIRED",{...base,score,setupReady:true,planned:{...planned,planType:plannedModeLabel(planned)},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source}}});','news and noncrypto plan');
mustReplace('const entry=pendingRetest?Number(trigPolicy.level):reference.price,plan=buildTradePlan(side,entry,M5,M15,H1,H4,D1,pendingRetest,prior);if(!plan||plan.invalid)return watch(s,type,side,plan?.invalid||"STRUCTURAL_SL_REQUIRED",{...base,score,setupReady:true,planned,quote:reference});\n  const spread=reference.ask-reference.bid,costR=spread/plan.risk;if(!Number.isFinite(costR)||costR>CONFIG.maxExecutionCostR)return watch(s,type,side,"EXECUTION_COST_TOO_HIGH",{...base,score,setupReady:true,planned,costR,quote:reference});','if(!pendingRetest){const mg=marketGeometry(side,reference.price,M5,trigPolicy);if(!mg.pass)return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,marketGeometry:mg},quote:reference,canonical:{...base.canonical,marketGeometry:mg}});}\n  const entry=pendingRetest?Number(trigPolicy.level):reference.price,plan=buildTradePlan(side,entry,M5,M15,H1,H4,D1,pendingRetest,prior);if(!plan||plan.invalid)return watch(s,type,side,plan?.invalid||"STRUCTURAL_SL_REQUIRED",{...base,score,setupReady:true,planned,quote:reference});\n  if(pendingRetest){const lg=limitGeometry(side,reference.price,entry,M5,M15,plan);if(!lg.pass)return watch(s,type,side,"LIMIT_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,geometry:lg},quote:reference,canonical:{...base.canonical,limitGeometry:lg}});}\n  const spread=reference.ask-reference.bid,costR=spread/plan.risk;if(!Number.isFinite(costR)||costR>CONFIG.maxExecutionCostR)return watch(s,type,side,"EXECUTION_COST_TOO_HIGH",{...base,score,setupReady:true,planned,costR,quote:reference});','final geometry');

mustReplace('async function runGroup(group,env){\n  if(!GROUPS[group])throw new Error("invalid group");if(!(await acquireLock(env)))','async function runGroup(group,env){\n  if(group==="future")return runFutureGroup(env);\n  if(!GROUPS[group])throw new Error("invalid group");if(!(await acquireLock(env)))','future runGroup route');
mustReplace('async function runSymbol(symbol,env){\n  const s=canonicalUserSymbol(symbol),type=marketType(s);if(type==="unknown")return {ok:false,status:"DATA_BLOCK",symbol:s,reason:"UNSUPPORTED_SYMBOL"};\n  if(type==="crypto")','async function runSymbol(symbol,env){\n  const s=canonicalUserSymbol(symbol),type=marketType(s);if(type==="unknown")return {ok:false,status:"DATA_BLOCK",symbol:s,reason:"UNSUPPORTED_SYMBOL"};\n  if(type==="future")return runFutureSymbol(s,env);\n  if(type==="crypto")','future runSymbol route');

const keyboardBlock=[
'function baseKeyboard(){return {inline_keyboard:[[{text:"🧭 HUB TOP SETUPS",callback_data:"hub"}],[{text:"💱 FOREX",callback_data:"scan:forex"},{text:"🪙 CRYPTO",callback_data:"scan:crypto"}],[{text:"🥇 METAL",callback_data:"scan:metal"},{text:"📈 FUTURES",callback_data:"scan:future"}],[{text:"🔎 TỪNG SYMBOL",callback_data:"symbols"}],[{text:"📊 STATUS",callback_data:"status"},{text:"📚 LIVE ORDERS",callback_data:"books"}]]};}',
'function symbolMarketKeyboard(){return {inline_keyboard:[[{text:"💱 Forex",callback_data:"symmarket:forex"},{text:"🪙 Crypto",callback_data:"symmarket:crypto"}],[{text:"🥇 Metal",callback_data:"symmarket:metal"},{text:"📈 Futures",callback_data:"symmarket:future"}],[{text:"⬅️ HUB",callback_data:"hub"}]]};}',
'function symbolListFor(group){return group==="future"?FUTURE_SYMBOLS:(GROUPS[group]||[]);}',
'function symbolPageKeyboard(group,page=0){const all=symbolListFor(group),size=12,pages=Math.max(1,Math.ceil(all.length/size)),p=Math.max(0,Math.min(pages-1,Number(page)||0)),slice=all.slice(p*size,p*size+size),rows=[];for(let i=0;i<slice.length;i+=2)rows.push(slice.slice(i,i+2).map(sym=>({text:sym,callback_data:"sym:"+group+":"+sym})));const nav=[];if(p>0)nav.push({text:"⬅️",callback_data:"sympage:"+group+":"+(p-1)});nav.push({text:(p+1)+"/"+pages,callback_data:"noop"});if(p<pages-1)nav.push({text:"➡️",callback_data:"sympage:"+group+":"+(p+1)});rows.push(nav);rows.push([{text:"↩️ Chọn thị trường",callback_data:"symbols"},{text:"🧭 HUB",callback_data:"hub"}]);return {inline_keyboard:rows};}',
''
].join('\n');
replaceRange('function baseKeyboard(){','function groupKeyboard(',keyboardBlock+'function groupKeyboard(','nested symbol menus');

mustReplace('function groupTitle(g){return g==="forex"?"💱 FOREX":g==="crypto"?"🪙 CRYPTO":"🥇 METAL";}','function groupTitle(g){return g==="forex"?"💱 FOREX":g==="crypto"?"🪙 CRYPTO":g==="future"?"📈 FUTURES":"🥇 METAL";}','future group title');
mustReplace('function reasonText(r){return ({HTF_METHOD_ALIGNMENT_REQUIRED:"Chờ phương pháp riêng + HTF đồng thuận",HTF_ALIGNMENT_REQUIRED:"Chờ D1/H4/H1 đồng thuận",M15_LOCATION_REQUIRED:"Chờ giá vào vùng M15 đẹp",M5_MSS_DISPLACEMENT_RETEST_REQUIRED:"Chờ trigger M5 phù hợp profile",STRUCTURAL_SL_REQUIRED:"Chưa có SL cấu trúc",CLEAN_TARGET_REQUIRED:"Chưa có mục tiêu thanh khoản đủ tốt",NEWS_CONTEXT_REQUIRED:"Chờ tin/context",EXECUTION_QUOTE_REQUIRED:"Chờ bid/ask thực",FINAL_QUOTE_REQUIRED:"Chờ giá execution",FINAL_QUOTE_STALE:"Giá execution cũ",EXECUTION_COST_TOO_HIGH:"Spread/chi phí cao",RR_QUALITY_REQUIRED:"RR cấu trúc chưa đủ tốt",TIMEFRAME_DATA_REQUIRED:"Thiếu timeframe",ANALYSIS_DATA_UNAVAILABLE:"Thiếu dữ liệu"})[r]||"Chờ thêm xác nhận";}','function reasonText(r){return ({HTF_METHOD_ALIGNMENT_REQUIRED:"Chờ phương pháp riêng + HTF đồng thuận",HTF_ALIGNMENT_REQUIRED:"Chờ D1/H4/H1 đồng thuận",M15_LOCATION_REQUIRED:"Chờ giá vào vùng M15 đẹp",M5_MSS_DISPLACEMENT_RETEST_REQUIRED:"Chờ trigger M5 phù hợp profile",STRUCTURAL_SL_REQUIRED:"Chưa có SL cấu trúc",CLEAN_TARGET_REQUIRED:"Chưa có mục tiêu thanh khoản đủ tốt",NEWS_CONTEXT_REQUIRED:"Chờ tin/context",EXECUTION_QUOTE_REQUIRED:"Kế hoạch đạt cấu trúc; chờ giá execution thật",FINAL_QUOTE_REQUIRED:"Chờ giá execution",FINAL_QUOTE_STALE:"Giá execution cũ",EXECUTION_COST_TOO_HIGH:"Spread/chi phí cao",RR_QUALITY_REQUIRED:"RR cấu trúc chưa đủ tốt",LIMIT_GEOMETRY_REQUIRED:"Vùng LIMIT chưa đúng khoảng cách/retest",MARKET_GEOMETRY_REQUIRED:"Giá MARKET đã chạy xa trigger",TIMEFRAME_DATA_REQUIRED:"Thiếu timeframe",ANALYSIS_DATA_UNAVAILABLE:"Thiếu dữ liệu"})[r]||"Chờ thêm xác nhận";}','reason labels');
mustReplace('function stageText(a){if(a.status==="MARKET")return "🟢 MARKET";if(a.status==="LIMIT")return "🟡 LIMIT";if(a.reason==="NEWS_CONTEXT_REQUIRED")return "🟠 ARMED";if(a.reason==="EXECUTION_QUOTE_REQUIRED"||a.reason==="FINAL_QUOTE_REQUIRED")return "🔵 READY";if(a.reason==="M5_MSS_DISPLACEMENT_RETEST_REQUIRED")return "🟣 SETUP";return "⚪ WATCH";}','function stageText(a){if(a.status==="MARKET")return "🟢 MARKET EXEC";if(a.status==="LIMIT")return "🟡 LIMIT EXEC";if(a.planned?.mode==="MARKET")return "🟢 MARKET PLAN";if(a.planned?.mode==="LIMIT"||a.planned?.mode==="INDICATIVE_LIMIT")return "🟡 LIMIT PLAN";if(a.reason==="NEWS_CONTEXT_REQUIRED")return "🟠 ARMED";if(a.reason==="EXECUTION_QUOTE_REQUIRED"||a.reason==="FINAL_QUOTE_REQUIRED")return "🔵 READY";if(a.reason==="M5_MSS_DISPLACEMENT_RETEST_REQUIRED")return "🟣 SETUP";return "⚪ WATCH";}','plan stage labels');

const summaryStart='function summary(group,books,run=null){';
const summaryEnd='async function sendGroup(group,env,chatId)';
const summaryBlock=[
'function freshPlanFromRun(run,kind){return (run?.analyses||[]).filter(a=>a?.status==="WATCH"&&a.planned&&(kind==="market"?a.planned.mode==="MARKET":(a.planned.mode==="LIMIT"||a.planned.mode==="INDICATIVE_LIMIT"))).sort((a,b)=>(Number(b.score)||0)-(Number(a.score)||0));}',
'function summary(group,books,run=null){',
'  const b=books[group],marketPlans=freshPlanFromRun(run,"market"),limitPlans=freshPlanFromRun(run,"limit"),watch=(run?.analyses||[]).filter(a=>a?.status==="WATCH"&&!a.planned).sort((a,b)=>(Number(b.score)||0)-(Number(a.score)||0)).slice(0,CONFIG.maxWatch),L=[groupTitle(group)];',
'  if(run?.scannedAt)L.push("🕒 Quét mới: "+run.scannedAt);',
'  L.push("","🟢 MARKET ĐANG CHẠY "+b.marketActive.length+"/"+CONFIG.maxMarketActive);if(b.marketActive.length)b.marketActive.forEach((p,i)=>L.push((i+1)+". "+posLine(p)));else L.push("Trống");',
'  L.push("","🎯 MARKET PLAN "+marketPlans.length);if(marketPlans.length)marketPlans.slice(0,3).forEach((a,i)=>L.push((i+1)+". "+watchLine(a)));else L.push("Trống");',
'  L.push("","📐 LIMIT PLAN "+limitPlans.length);if(limitPlans.length)limitPlans.slice(0,3).forEach((a,i)=>L.push((i+1)+". "+watchLine(a)));else L.push("Trống");',
'  L.push("","🟡 LIMIT ĐANG CHỜ "+b.limitPending.length+"/"+CONFIG.maxPendingLimit);if(b.limitPending.length)b.limitPending.forEach((p,i)=>L.push((i+1)+". "+posLine(p)));else L.push("Trống");',
'  L.push("","👀 WATCH THUẦN "+watch.length);if(watch.length)watch.forEach((a,i)=>L.push((i+1)+". "+watchLine(a)));else L.push("Trống");',
'  if(run?.status==="RATE_BUDGET_WAIT"){L.push("⏱ Không dùng setup cũ. Chờ quota ~"+(run.retryAfterSec??60)+"s.");return L.join("\\n");}',
'  if(run?.status==="BUSY"){L.push("⏳ Một lượt quét khác đang chạy. Không hiển thị setup cũ.");return L.join("\\n");}',
'  if(run)L.push("🔍 Coverage "+run.broadOk+"/"+run.requested+" • Deep "+run.deepOk+"/"+run.deepRequested+" • Lệnh executable mới "+run.newCount,"🆔 Scan "+run.scanId);return L.join("\\n");',
'}',
''
].join('\n');
replaceRange(summaryStart,summaryEnd,summaryBlock+summaryEnd,'actionable summary');

mustReplace('async function runHub(env){const t=Date.now(),runs={};for(const g of ["crypto","forex","metal"])runs[g]=await runGroup(g,env);','async function runHub(env){const t=Date.now(),runs={};for(const g of ["crypto","forex","metal","future"])runs[g]=await runGroup(g,env);','hub includes futures');
mustReplace('for(const g of ["forex","crypto","metal"]){const r=h.runs[g];','for(const g of ["forex","crypto","metal","future"]){const r=h.runs[g];','hub summary futures');
mustReplace('async function sendHub(env,chatId){await sendText(env,"⏳ HUB đang QUÉT MỚI Crypto + Forex + Metal...",chatId);','async function sendHub(env,chatId){await sendText(env,"⏳ HUB đang QUÉT MỚI Crypto + Forex + Metal + Futures...",chatId);','hub message futures');
mustReplace('for(const g of ["forex","crypto","metal"]){const b=books[g];','for(const g of ["forex","crypto","metal","future"]){const b=books[g];','books summary futures');

const tgNeedle='if(cb==="hub"||text==="/hub")await sendHub(env,chatId);\n  else if(cb?.startsWith("scan:"))await sendGroup(cb.split(":")[1],env,chatId);';
const tgReplace='if(cb==="hub"||text==="/hub")await sendHub(env,chatId);\n  else if(cb==="symbols")await sendText(env,"🔎 Chọn thị trường để tìm từng symbol:",chatId,symbolMarketKeyboard());\n  else if(cb?.startsWith("symmarket:")){const g=cb.split(":")[1];await sendText(env,"🔎 "+groupTitle(g)+" • chọn symbol",chatId,symbolPageKeyboard(g,0));}\n  else if(cb?.startsWith("sympage:")){const [,g,p]=cb.split(":");await sendText(env,"🔎 "+groupTitle(g)+" • chọn symbol",chatId,symbolPageKeyboard(g,Number(p)));}\n  else if(cb?.startsWith("sym:")){const [,g,raw]=cb.split(":");let symbol=canonicalUserSymbol(raw);await sendText(env,"⏳ Quét MỚI "+symbol+"...",chatId);const a=await runSymbol(symbol,env);await sendText(env,singleAnalysisText(a),chatId,symbolPageKeyboard(g,Math.floor(Math.max(0,symbolListFor(g).indexOf(symbol))/12)));}\n  else if(cb==="noop"){}\n  else if(cb?.startsWith("scan:"))await sendGroup(cb.split(":")[1],env,chatId);';
mustReplace(tgNeedle,tgReplace,'telegram symbol callbacks');
mustReplace('const cm=text.trim().match(/^\\/(?:coin|analyze)\\s+([A-Za-z0-9]+)$/i);','const cm=text.trim().match(/^\\/(?:coin|analyze|forex|metal|future)\\s+([A-Za-z0-9]+)$/i);','direct symbol commands');
mustReplace('let symbol=canonicalUserSymbol(cm[1]);if(!symbol.endsWith("USDT")&&CRYPTO_BASE.includes(symbol))symbol=symbol+"USDT";','let symbol=canonicalUserSymbol(cm[1]);if(!symbol.endsWith("USDT")&&CRYPTO_BASE.includes(symbol))symbol=symbol+"USDT";','direct normalize keep');
mustReplace('else if(cb==="status"||text==="/status")await sendText(env,`⚙️ SYSTEM STATUS\\nVersion: ${CONFIG.version}\\nKV: ${env.TRADING_STATE?"ONLINE":"MISSING"}\\nTwelve Data: ${env.TWELVE_DATA_API_KEY?"CONFIGURED":"MISSING"}\\nTelegram: CONNECTED\\nHub: ADAPTIVE\\nCrypto: 61 symbol • exact 5TF + bid/ask • TON→GRAM canonical\\nLệnh: chỉ executable khi đủ gate\\nGõ /coin BTC hoặc /analyze KAITOUSDT để phân tích riêng\\nNews gate: STRICT\\nV73: FROZEN PRIOR`,chatId,baseKeyboard());','else if(cb==="status"||text==="/status")await sendText(env,`⚙️ SYSTEM STATUS\\nVersion: ${CONFIG.version}\\nKV: ${env.TRADING_STATE?"ONLINE":"MISSING"}\\nTwelve Data: ${env.TWELVE_DATA_API_KEY?"CONFIGURED":"MISSING"}\\nMassive Futures: ${env.MASSIVE_API_KEY?"CONFIGURED":"MISSING"}\\nTelegram: CONNECTED\\nHub: ADAPTIVE + FRESH SCAN\\nCrypto: 61 symbol\\nForex: 28 pairs\\nMetal: XAU/XAG\\nFutures: NQ/MNQ/ES/MES\\nMARKET/LIMIT EXEC chỉ khi execution authority thật; MARKET PLAN/LIMIT PLAN luôn tách rõ.\\nNews gate: ${env.NEWS_GATE_URL?"EXTERNAL STRICT":"SOFT UNVERIFIED"}`,chatId,baseKeyboard());','status text');

mustReplace('if(p==="/status")return json({ok:true,version:CONFIG.version,service:CONFIG.service,kv:!!env.TRADING_STATE,twelveData:!!env.TWELVE_DATA_API_KEY,telegram:!!env.TELEGRAM_BOT_TOKEN,v73:{version:V73_CONFIG.version,classification:V73_CONFIG.classification},providers:{forex:"Twelve Data batch analysis; broker execution quote required",crypto:"Exact exchange-native 5TF analysis + Bybit/OKX/Binance execution",metal:"Twelve Data batch analysis; broker execution quote required"},newsGate:{mode:"STRICT",clearanceTtlSec:CONFIG.newsClearanceTtlSec,externalUrlConfigured:!!env.NEWS_GATE_URL},hub:{enabled:true,order:["crypto","forex","metal"]}});','if(p==="/status")return json({ok:true,version:CONFIG.version,service:CONFIG.service,kv:!!env.TRADING_STATE,twelveData:!!env.TWELVE_DATA_API_KEY,massive:!!env.MASSIVE_API_KEY,telegram:!!env.TELEGRAM_BOT_TOKEN,v73:{version:V73_CONFIG.version,classification:V73_CONFIG.classification},providers:{forex:"Twelve Data analysis; MT5 broker quote required for execution",crypto:"Exchange-native analysis + exact canonical bid/ask execution",metal:"Twelve Data analysis; MT5 broker quote required for execution",future:"Massive Futures NQ/ES analysis; delayed/basic data remains analysis-only"},newsGate:{mode:env.NEWS_GATE_URL?"EXTERNAL_STRICT":"SOFT_UNVERIFIED",clearanceTtlSec:CONFIG.newsClearanceTtlSec,externalUrlConfigured:!!env.NEWS_GATE_URL},hub:{enabled:true,freshScan:true,order:["crypto","forex","metal","future"]}});','status endpoint');
mustReplace('if(p==="/telegram/menu"){await sendText(env,`🤖 TRADING HUB ${CONFIG.version}\\nChọn HUB/thị trường hoặc gõ /coin BTC:`,env.TELEGRAM_CHAT_ID,baseKeyboard());return json({ok:true});}','if(p==="/telegram/menu"){await sendText(env,`🤖 TRADING HUB ${CONFIG.version}\\nMỗi lần bấm = quét mới. Chọn HUB/thị trường hoặc 🔎 TỪNG SYMBOL.`,env.TELEGRAM_CHAT_ID,baseKeyboard());return json({ok:true});}','telegram menu text');
mustReplace('return json({ok:true,version:CONFIG.version,endpoints:["/status","/hub","/run-now?group=forex|crypto|metal","/analyze?symbol=BTCUSDT","/telegram/setup-webhook","/telegram/webhook-info","/telegram/menu","/books"]});','return json({ok:true,version:CONFIG.version,endpoints:["/status","/hub","/run-now?group=forex|crypto|metal|future","/analyze?symbol=BTCUSDT|EURUSD|XAUUSD|NQ|MNQ|ES|MES","/knowledge?symbol=NQ","/telegram/menu","/books"]});','endpoint list');

fs.writeFileSync(path,s);
console.log('Applied V77.14.0 Futures Actionable Entry Hub migration');
