const fs=require('fs');
const p='cloudflare-worker/index.js';let s=fs.readFileSync(p,'utf8');
function must(a,b,l){if(!s.includes(a))throw new Error('Missing '+l);s=s.replace(a,b);}
s=s.replaceAll('V77.15.2','V77.15.3');s=s.replace('Trading V77.15.3 Actionable Plan Metrics Hub','Trading V77.15.3 Structural Limit Rescue Hub');
must(
'  if(!locPolicy.pass){const planned=indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);if(planned)return planSignal(s,type,planned.side||side,"M15_LOCATION_REQUIRED",planned,{...base,score:Math.max(base.score,44),entryPolicy:{profile:profileMode(intel),location:locPolicy},canonical:{...base.canonical,m15Location:loc}});return watch(s,type,side,"M15_LOCATION_REQUIRED",{...base,entryPolicy:{profile:profileMode(intel),location:locPolicy},canonical:{...base.canonical,m15Location:loc}});}',
'  if(!locPolicy.pass){const planned=indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||refinedLimitPlan(side,M15.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,{})||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);if(planned)return planSignal(s,type,planned.side||side,"M15_LOCATION_REQUIRED",planned,{...base,score:Math.max(base.score,44),entryPolicy:{profile:profileMode(intel),location:locPolicy},canonical:{...base.canonical,m15Location:loc}});return watch(s,type,side,"M15_LOCATION_REQUIRED",{...base,entryPolicy:{profile:profileMode(intel),location:locPolicy},canonical:{...base.canonical,m15Location:loc}});}',
'location limit rescue');
must(
'  if(!trigPolicy.pass){const planned=indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);if(planned)return planSignal(s,type,planned.side||side,"M5_MSS_DISPLACEMENT_RETEST_REQUIRED",planned,{...base,score:Math.max(base.score,48),entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig}});return watch(s,type,side,"M5_MSS_DISPLACEMENT_RETEST_REQUIRED",{...base,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig}});}',
'  if(!trigPolicy.pass){const planned=indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||refinedLimitPlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy)||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);if(planned)return planSignal(s,type,planned.side||side,"M5_MSS_DISPLACEMENT_RETEST_REQUIRED",planned,{...base,score:Math.max(base.score,48),entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig}});return watch(s,type,side,"M5_MSS_DISPLACEMENT_RETEST_REQUIRED",{...base,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig}});}',
'trigger limit rescue');
must(
'  const previewEntry=pendingRetest?Number(trigPolicy.level):M5.close,preview=buildTradePlan(side,previewEntry,M5,M15,H1,H4,D1,pendingRetest,prior);if(!preview)return watch(s,type,side,"STRUCTURAL_SL_REQUIRED",base);if(preview.invalid)return watch(s,type,side,preview.invalid,{...base,roomR:preview.roomR});',
'  const previewEntry=pendingRetest?Number(trigPolicy.level):M5.close,preview=buildTradePlan(side,previewEntry,M5,M15,H1,H4,D1,pendingRetest,prior);if(!preview)return watch(s,type,side,"STRUCTURAL_SL_REQUIRED",base);if(preview.invalid){const alt=refinedLimitPlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)return planSignal(s,type,side,preview.invalid,alt,{...base,score:Math.max(base.score,50),setupReady:true});return watch(s,type,side,preview.invalid,{...base,roomR:preview.roomR});}',
'clean target limit rescue');
must(
'  if(!quality.pass)return watch(s,type,side,"RR_QUALITY_REQUIRED",{...base,score,setupReady:true,planned,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,rrQuality:quality}});',
'  if(!quality.pass){const alt=refinedLimitPlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)return planSignal(s,type,side,"RR_QUALITY_REQUIRED",alt,{...base,score:Math.max(score,52),setupReady:true,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,rrQuality:quality,limitGeometry:alt.geometry}});return watch(s,type,side,"RR_QUALITY_REQUIRED",{...base,score,setupReady:true,planned,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,rrQuality:quality}});}',
'rr limit rescue');
fs.writeFileSync(p,s);console.log('Applied V77.15.3 structural limit rescue');
