const fs=require('fs');
const p='cloudflare-worker/index.js';let s=fs.readFileSync(p,'utf8');
function must(a,b,label){if(!s.includes(a))throw new Error('Missing '+label);s=s.replace(a,b);}
if(!s.includes('version: "V77.16.6"'))throw new Error('Expected V77.16.6');
s=s.replaceAll('V77.16.6','V77.16.7');
s=s.replace('Trading V77.16.7 Legacy-Preserved Live Order Hub','Trading V77.16.7 Durable Order Archive Hub');
const old=`function normalizeBooks(v){const b=emptyBooks();if(!v||typeof v!=="object")return b;for(const g of Object.keys(GROUPS)){const src=v?.[g]||{};b[g].marketActive=Array.isArray(src.marketActive)?src.marketActive.filter(p=>validExecutablePosition(p,g)).map(p=>preserveLegacyOrder(p,"ACTIVE")).slice(0,CONFIG.maxMarketActive):[];b[g].limitActive=Array.isArray(src.limitActive)?src.limitActive.filter(p=>validExecutablePosition(p,g)).map(p=>preserveLegacyOrder(p,"ACTIVE")).slice(0,CONFIG.maxLimitActive):[];b[g].limitPending=Array.isArray(src.limitPending)?src.limitPending.filter(p=>validExecutablePosition(p,g)).map(p=>preserveLegacyOrder(p,"PENDING")).slice(0,CONFIG.maxPendingLimit):[];b[g].watch=[];}b.updatedAt=v.updatedAt||Date.now();return b;}\nasync function getBooks(env){try{return normalizeBooks(await env.TRADING_STATE.get(CONFIG.keys.books,"json"));}catch{return emptyBooks();}}`;
const neu=`function normalizeBooks(v){const b=emptyBooks();if(!v||typeof v!=="object")return b;for(const g of Object.keys(GROUPS)){const src=v?.[g]||{};b[g].marketActive=Array.isArray(src.marketActive)?src.marketActive.filter(p=>validExecutablePosition(p,g)).map(p=>preserveLegacyOrder(p,"ACTIVE")):[];b[g].limitActive=Array.isArray(src.limitActive)?src.limitActive.filter(p=>validExecutablePosition(p,g)).map(p=>preserveLegacyOrder(p,"ACTIVE")):[];b[g].limitPending=Array.isArray(src.limitPending)?src.limitPending.filter(p=>validExecutablePosition(p,g)).map(p=>preserveLegacyOrder(p,"PENDING")):[];b[g].watch=[];}b.updatedAt=v.updatedAt||Date.now();return b;}\nasync function archiveLiveOrders(env,books){try{const old=await env.TRADING_STATE.get(CONFIG.keys.orderHistory,"json"),rows=Array.isArray(old?.rows)?old.rows:[],seen=new Set(rows.map(x=>String(x?.position?.id||"")+":"+String(x?.event||"")));let changed=false;for(const g of Object.keys(GROUPS)){const b=books[g]||{};for(const p of [...(b.marketActive||[]),...(b.limitActive||[]),...(b.limitPending||[])]){const k=String(p.id||"")+":LIVE_STATE_PRESERVED";if(!p.id||seen.has(k))continue;rows.push({event:"LIVE_STATE_PRESERVED",group:g,position:p,recordedAt:Date.now(),engine:CONFIG.version});seen.add(k);changed=true;}}if(changed)await env.TRADING_STATE.put(CONFIG.keys.orderHistory,JSON.stringify({rows:rows.slice(-1000),updatedAt:Date.now()}));}catch{}}\nasync function getBooks(env){try{const b=normalizeBooks(await env.TRADING_STATE.get(CONFIG.keys.books,"json"));await archiveLiveOrders(env,b);return b;}catch{return emptyBooks();}}`;
must(old,neu,'unbounded legacy preservation and archive');
const oldHist='async function getShadowSetups(env,symbol=null){try{const v=await env.TRADING_STATE.get(CONFIG.keys.shadowSetups,"json");const rows=Array.isArray(v?.rows)?v.rows:[];return symbol?rows.filter(x=>x.symbol===canonicalUserSymbol(symbol)):rows;}catch{return [];}}';
const newHist=oldHist+'\nasync function getOrderHistory(env){try{const v=await env.TRADING_STATE.get(CONFIG.keys.orderHistory,"json");return {rows:Array.isArray(v?.rows)?v.rows:[],updatedAt:v?.updatedAt||null};}catch{return {rows:[],updatedAt:null};}}';
must(oldHist,newHist,'history reader');
must('if(p==="/books"||p==="/orders")return json(await getBooks(env));','if(p==="/books"||p==="/orders")return json(await getBooks(env));\n      if(p==="/order-history"||p==="/history")return json(await getOrderHistory(env));','history endpoint');
s=s.replace('"/telegram/menu","/books"]','"/telegram/menu","/books","/order-history"]');
fs.writeFileSync(p,s);console.log('Applied V77.16.7 durable order archive');
