const fs=require('fs');
const path='cloudflare-worker/index.js';
let s=fs.readFileSync(path,'utf8');
function mustReplace(from,to,label){if(!s.includes(from))throw new Error('Missing '+label);s=s.replace(from,to);}
function insertAfter(marker,text,label){const i=s.indexOf(marker);if(i<0)throw new Error('Missing '+label);const p=i+marker.length;s=s.slice(0,p)+text+s.slice(p);}

s=s.replaceAll('V77.14.2','V77.15.0');
s=s.replaceAll('Trading V77.15.0 Actionable Geometry Hub','Trading V77.15.0 Actionable Multi-Market Entry Hub');

mustReplace('  maxCandidates: 3,\n  deepShortlist: 12,','  maxCandidates: 3,\n  deepNonCryptoCandidates: 5,\n  deepShortlist: 12,','deep candidate config');
mustReplace('  pendingLimitExpiryMinutes: 90,','  pendingLimitExpiryMinutes: 90,\n  actionablePlanMaxAtr: 1.15,','actionable plan config');
mustReplace('function tdPlannedCost(group){return group==="forex"?40:group==="metal"?10:0;}','function tdPlannedCost(group){return group==="forex"?48:group==="metal"?10:0;}','forex quota plan');
mustReplace('  if(!a||a.status!=="WATCH"||!a.planned||!["LONG","SHORT"].includes(a.side))return;','  if(!a||!["WATCH","MARKET_PLAN","LIMIT_PLAN"].includes(a.status)||!a.planned||!["LONG","SHORT"].includes(a.side))return;','shadow plan status');

const marker='function plannedModeLabel(p){return p?.mode==="MARKET"?"MARKET_PLAN":(p?.mode==="LIMIT"||p?.mode==="INDICATIVE_LIMIT")?"LIMIT_PLAN":"WATCH";}';
const helper=`\nfunction planSignal(symbol,type,side,reason,planned,extra={}){const status=plannedModeLabel(planned);return {ok:true,status,action:status,symbol,market:type,side,reason,canonicalStage:reason,planned:{...planned,planType:status,executionVerified:false},executionReady:false,engine:CONFIG.version,...extra};}\nfunction refinedLimitPlan(side,current,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy){\n  if(!Number.isFinite(current)||!Number.isFinite(M15?.atr14)||M15.atr14<=0)return null;const atr=M15.atr14,raw=[trigPolicy?.level,locPolicy?.level,M15.ema20,M5.ema20,side==="LONG"?M15.liquidityLow20:M15.liquidityHigh20].filter(Number.isFinite),cand=[...new Set(raw)].filter(e=>side==="LONG"?e<current:e>current).filter(e=>Math.abs(current-e)/atr<=CONFIG.actionablePlanMaxAtr);let best=null;\n  for(const e of cand){const p=buildTradePlan(side,e,M5,M15,H1,H4,D1,true,prior);if(!p||p.invalid)continue;const q=rrQuality(p,intel),g=limitGeometry(side,current,e,M5,M15,p);if(!q.pass||!g.pass)continue;const conf=raw.filter(x=>Math.abs(x-e)<=atr*.12).length,score=conf*25+Math.min(40,p.targetRR*12)-Math.abs(g.distanceATR-.30)*12;if(!best||score>best._score)best={...p,mode:"LIMIT",indicative:true,entryStyle:"STRUCTURE_RETEST_LIMIT",minQualityRR:q.minRR,rrQualityPass:true,geometry:g,confluence:conf,_score:score};}\n  if(best)delete best._score;return best;\n}\nfunction planOrWatch(symbol,type,side,reason,planned,extra={}){if(planned){const q=rrQuality(planned,extra.method||extra?.base?.method||{});if(planned.rrQualityPass===true||q.pass)return planSignal(symbol,type,side,reason,{...planned,minQualityRR:planned.minQualityRR??q.minRR,rrQualityPass:true},extra);}return watch(symbol,type,side,reason,{...extra,planned:planned||null});}\n`;
insertAfter(marker,helper,'plan helpers');

mustReplace('  if(side==="NEUTRAL"||!htf){const cp=conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);return watch(s,type,cp?.side||side,"HTF_METHOD_ALIGNMENT_REQUIRED",{...base,planned:cp,entryPolicy:cp?{profile:profileMode(intel),conditional:true}:undefined});}','  if(side==="NEUTRAL"||!htf){const cp=conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);if(cp)return planSignal(s,type,cp.side,"HTF_METHOD_ALIGNMENT_REQUIRED",cp,{...base,score:Math.max(base.score,40),entryPolicy:{profile:profileMode(intel),conditional:true}});return watch(s,type,side,"HTF_METHOD_ALIGNMENT_REQUIRED",base);}','htf conditional plan');
mustReplace('  if(!locPolicy.pass){const planned=indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior);return watch(s,type,side,"M15_LOCATION_REQUIRED",{...base,planned,entryPolicy:{profile:profileMode(intel),location:locPolicy},canonical:{...base.canonical,m15Location:loc}});}','  if(!locPolicy.pass){const planned=indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);if(planned)return planSignal(s,type,planned.side||side,"M15_LOCATION_REQUIRED",planned,{...base,score:Math.max(base.score,44),entryPolicy:{profile:profileMode(intel),location:locPolicy},canonical:{...base.canonical,m15Location:loc}});return watch(s,type,side,"M15_LOCATION_REQUIRED",{...base,entryPolicy:{profile:profileMode(intel),location:locPolicy},canonical:{...base.canonical,m15Location:loc}});}','location plan');
mustReplace('  if(!trigPolicy.pass){const planned=indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior);return watch(s,type,side,"M5_MSS_DISPLACEMENT_RETEST_REQUIRED",{...base,planned,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig}});}','  if(!trigPolicy.pass){const planned=indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);if(planned)return planSignal(s,type,planned.side||side,"M5_MSS_DISPLACEMENT_RETEST_REQUIRED",planned,{...base,score:Math.max(base.score,48),entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig}});return watch(s,type,side,"M5_MSS_DISPLACEMENT_RETEST_REQUIRED",{...base,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig}});}','trigger plan');

mustReplace('  if(pendingRetest){const lg=limitGeometry(side,M5.close,preview.entry,M5,M15,preview);if(!lg.pass)return watch(s,type,side,"LIMIT_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,geometry:lg},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source},limitGeometry:lg}});}','  if(pendingRetest){const lg=limitGeometry(side,M5.close,preview.entry,M5,M15,preview);if(!lg.pass){const alt=refinedLimitPlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)return planSignal(s,type,side,"LIMIT_GEOMETRY_REQUIRED",alt,{...base,score,setupReady:true,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,limitGeometry:alt.geometry}});return watch(s,type,side,"LIMIT_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,geometry:lg},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,limitGeometry:lg}});}}','pre-exec limit refinement');

mustReplace('  if(type!=="crypto"){if(!pendingRetest){const mg=marketGeometry(side,M5.close,M5,trigPolicy);if(!mg.pass)return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,marketGeometry:mg,planType:"MARKET_PLAN"},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source},marketGeometry:mg}});planned.marketGeometry=mg;}return watch(s,type,side,"EXECUTION_QUOTE_REQUIRED",{...base,score,setupReady:true,planned:{...planned,planType:plannedModeLabel(planned)},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source}}});}','  if(type!=="crypto"){let p=planned;if(!pendingRetest){const mg=marketGeometry(side,M5.close,M5,trigPolicy);if(!mg.pass){const alt=refinedLimitPlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)p=alt;else return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,marketGeometry:mg},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,marketGeometry:mg}});}else p={...p,marketGeometry:mg};}return planSignal(s,type,side,"EXECUTION_QUOTE_REQUIRED",p,{...base,score,setupReady:true,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source}}});}','noncrypto explicit plan status');

mustReplace('  try{if(!reference||reference.analysisOnly)reference=await cryptoExecutionQuote(s);}catch(e){return watch(s,type,side,"FINAL_QUOTE_REQUIRED",{...base,score,setupReady:true,planned,error:e?.message||String(e)});}if(!reference.fresh)return watch(s,type,side,"FINAL_QUOTE_STALE",{...base,score,setupReady:true,planned,quote:reference});if(!reference.executionVerified)return watch(s,type,side,"EXECUTION_QUOTE_REQUIRED",{...base,score,setupReady:true,planned,quote:reference});','  try{if(!reference||reference.analysisOnly)reference=await cryptoExecutionQuote(s);}catch(e){return planSignal(s,type,side,"FINAL_QUOTE_REQUIRED",planned,{...base,score,setupReady:true,error:e?.message||String(e)});}if(!reference.fresh)return planSignal(s,type,side,"FINAL_QUOTE_STALE",planned,{...base,score,setupReady:true,quote:reference});if(!reference.executionVerified)return planSignal(s,type,side,"EXECUTION_QUOTE_REQUIRED",planned,{...base,score,setupReady:true,quote:reference});','crypto plan when execution missing');
mustReplace('  if(!pendingRetest){const mg=marketGeometry(side,reference.price,M5,trigPolicy);if(!mg.pass)return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,marketGeometry:mg},quote:reference,canonical:{...base.canonical,marketGeometry:mg}});}','  if(!pendingRetest){const mg=marketGeometry(side,reference.price,M5,trigPolicy);if(!mg.pass){const alt=refinedLimitPlan(side,reference.price,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)return planSignal(s,type,side,"MARKET_GEOMETRY_REQUIRED",alt,{...base,score,setupReady:true,quote:reference,canonical:{...base.canonical,marketGeometry:mg,limitGeometry:alt.geometry}});return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,marketGeometry:mg},quote:reference,canonical:{...base.canonical,marketGeometry:mg}});}}','market-chase conversion');
mustReplace('  if(pendingRetest){const lg=limitGeometry(side,reference.price,entry,M5,M15,plan);if(!lg.pass)return watch(s,type,side,"LIMIT_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,geometry:lg},quote:reference,canonical:{...base.canonical,limitGeometry:lg}});}','  if(pendingRetest){const lg=limitGeometry(side,reference.price,entry,M5,M15,plan);if(!lg.pass){const alt=refinedLimitPlan(side,reference.price,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)return planSignal(s,type,side,"LIMIT_GEOMETRY_REQUIRED",alt,{...base,score,setupReady:true,quote:reference,canonical:{...base.canonical,limitGeometry:alt.geometry}});return watch(s,type,side,"LIMIT_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,geometry:lg},quote:reference,canonical:{...base.canonical,limitGeometry:lg}});}}','final limit refinement');

mustReplace('function actionableRank(a){let x=Number(a?.score)||0;if(a?.status==="MARKET")x+=1000;else if(a?.status==="LIMIT")x+=900;else if(a?.planned?.mode==="MARKET")x+=500;else if(a?.planned?.mode==="LIMIT"||a?.planned?.mode==="INDICATIVE_LIMIT")x+=420;else if(a?.setupReady)x+=150;return x;}','function actionableRank(a){let x=Number(a?.score)||0;if(a?.status==="MARKET")x+=1000;else if(a?.status==="LIMIT")x+=900;else if(a?.status==="MARKET_PLAN")x+=700;else if(a?.status==="LIMIT_PLAN")x+=650;else if(a?.planned?.mode==="MARKET")x+=500;else if(a?.planned?.mode==="LIMIT"||a?.planned?.mode==="INDICATIVE_LIMIT")x+=420;else if(a?.setupReady)x+=150;return x;}','actionable status ranking');
mustReplace('      valid.sort((a,b)=>actionableRank(b)-actionableRank(a));analyses.push(...valid.slice(0,CONFIG.maxCandidates));','      valid.sort((a,b)=>actionableRank(b)-actionableRank(a));analyses.push(...valid.slice(0,CONFIG.maxCandidates));','crypto rank marker');

mustReplace('      const candidates=entryRows.slice(0,CONFIG.maxCandidates);let prepared=new Map();try{prepared=await prepareNonCryptoDeep(candidates.map(c=>c.symbol),broad.h1Map,env);}catch{}\n      for(const c of candidates){if(Date.now()-started>CONFIG.scanDeadlineMs)break;deepAttempted++;const pc=prepared.get(c.symbol);if(!pc)analyses.push({ok:false,status:"DATA_BLOCK",symbol:c.symbol,reason:"ANALYSIS_DATA_UNAVAILABLE"});else analyses.push(await deepAnalyze(c.symbol,env,pc,null,"Twelve Data",c.context||{}));}','      const deepLimit=group==="forex"?CONFIG.deepNonCryptoCandidates:CONFIG.maxCandidates,candidates=entryRows.slice(0,deepLimit),tmp=[];let prepared=new Map();try{prepared=await prepareNonCryptoDeep(candidates.map(c=>c.symbol),broad.h1Map,env);}catch{}\n      for(const c of candidates){if(Date.now()-started>CONFIG.scanDeadlineMs)break;deepAttempted++;const pc=prepared.get(c.symbol);if(!pc)tmp.push({ok:false,status:"DATA_BLOCK",symbol:c.symbol,reason:"ANALYSIS_DATA_UNAVAILABLE"});else tmp.push(await deepAnalyze(c.symbol,env,pc,null,"Twelve Data",c.context||{}));}\n      tmp.sort((a,b)=>actionableRank(b)-actionableRank(a));analyses.push(...tmp.slice(0,CONFIG.maxCandidates));','deeper forex candidate routing');

mustReplace('function freshPlanFromRun(run,kind){return (run?.analyses||[]).filter(a=>a?.status==="WATCH"&&a.planned&&(kind==="market"?a.planned.mode==="MARKET":(a.planned.mode==="LIMIT"||a.planned.mode==="INDICATIVE_LIMIT"))).sort((a,b)=>(Number(b.score)||0)-(Number(a.score)||0));}','function freshPlanFromRun(run,kind){return (run?.analyses||[]).filter(a=>a?.planned&&(kind==="market"?(a.status==="MARKET_PLAN"||a.planned.mode==="MARKET"):(a.status==="LIMIT_PLAN"||a.planned.mode==="LIMIT"||a.planned.mode==="INDICATIVE_LIMIT"))).sort((a,b)=>actionableRank(b)-actionableRank(a));}','plan grouping');
mustReplace('function stageText(a){if(a.status==="MARKET")return "🟢 MARKET EXEC";if(a.status==="LIMIT")return "🟡 LIMIT EXEC";if(a.planned?.mode==="MARKET")return "🟢 MARKET PLAN";if(a.planned?.mode==="LIMIT"||a.planned?.mode==="INDICATIVE_LIMIT")return "🟡 LIMIT PLAN";if(a.reason==="NEWS_CONTEXT_REQUIRED")return "🟠 ARMED";if(a.reason==="EXECUTION_QUOTE_REQUIRED"||a.reason==="FINAL_QUOTE_REQUIRED")return "🔵 READY";if(a.reason==="M5_MSS_DISPLACEMENT_RETEST_REQUIRED")return "🟣 SETUP";return "⚪ WATCH";}','function stageText(a){if(a.status==="MARKET")return "🟢 MARKET EXEC";if(a.status==="LIMIT")return "🟡 LIMIT EXEC";if(a.status==="MARKET_PLAN"||a.planned?.mode==="MARKET")return "🟢 MARKET PLAN";if(a.status==="LIMIT_PLAN"||a.planned?.mode==="LIMIT"||a.planned?.mode==="INDICATIVE_LIMIT")return "🟡 LIMIT PLAN";if(a.reason==="NEWS_CONTEXT_REQUIRED")return "🟠 ARMED";if(a.reason==="EXECUTION_QUOTE_REQUIRED"||a.reason==="FINAL_QUOTE_REQUIRED")return "🔵 READY";if(a.reason==="M5_MSS_DISPLACEMENT_RETEST_REQUIRED")return "🟣 SETUP";return "⚪ WATCH";}','stage plan status');
mustReplace('function hubRank(a){const base=Number(a.score)||0;if(a.status==="MARKET")return 200+base;if(a.status==="LIMIT")return 190+base;if(a.reason==="EXECUTION_QUOTE_REQUIRED"||a.reason==="FINAL_QUOTE_REQUIRED")return 170+base;if(a.reason==="NEWS_CONTEXT_REQUIRED")return 160+base;if(a.reason==="M5_MSS_DISPLACEMENT_RETEST_REQUIRED")return 120+base;if(a.reason==="M15_LOCATION_REQUIRED")return 90+base;return base;}','function hubRank(a){return actionableRank(a);}','hub rank');
mustReplace('line+="\\n   ↳ "+(a.status==="WATCH"?reasonText(a.reason):"Đủ gate execution");','line+="\\n   ↳ "+(a.status==="MARKET"||a.status==="LIMIT"?"Đủ gate execution":a.status==="MARKET_PLAN"||a.status==="LIMIT_PLAN"?"Kế hoạch kỹ thuật hợp lệ — chờ execution authority":reasonText(a.reason));','hub plan truth label');

mustReplace('    const books=await getBooks(env);for(const a of analyses.filter(Boolean))await recordShadowSetup("future",a,scanId,env);const out={ok:true,version:CONFIG.version,group:"future",scanId,scannedAt,requested:4,broadOk:(nq?2:0)+(es?2:0),fresh:analyses.length,deepRequested:4,deepOk:analyses.filter(a=>a&&a.ok!==false).length,newCount:0,analyses:analyses.filter(Boolean),diagnostics:{frontSuffix:suffix,frontContracts:{NQ:nq?.ticker||null,ES:es?.ticker||null,MNQ:nq?"MNQ"+suffix:null,MES:es?"MES"+suffix:null},errors,liveSymbolsSkipped:[...(books.future?.marketActive||[]),...(books.future?.limitActive||[]),...(books.future?.limitPending||[])].map(x=>x.symbol)},elapsedMs:Date.now()-started};','    const books=await getBooks(env),liveSet=new Set([...(books.future?.marketActive||[]),...(books.future?.limitActive||[]),...(books.future?.limitPending||[])].map(x=>canonicalUserSymbol(x.symbol))),usable=analyses.filter(Boolean).filter(a=>!liveSet.has(canonicalUserSymbol(a.symbol))).sort((a,b)=>actionableRank(b)-actionableRank(a));for(const a of usable)await recordShadowSetup("future",a,scanId,env);const out={ok:true,version:CONFIG.version,group:"future",scanId,scannedAt,requested:4,broadOk:(nq?2:0)+(es?2:0),fresh:usable.length,deepRequested:Math.max(0,4-liveSet.size),deepOk:usable.filter(a=>a&&a.ok!==false).length,newCount:0,analyses:usable,diagnostics:{frontSuffix:suffix,frontContracts:{NQ:nq?.ticker||null,ES:es?.ticker||null,MNQ:nq?"MNQ"+suffix:null,MES:es?"MES"+suffix:null},errors,liveSymbolsSkipped:[...liveSet]},elapsedMs:Date.now()-started};','future live skip');

fs.writeFileSync(path,s);
console.log('Applied V77.15.0 actionable multi-market hub');
