const fs=require('fs');
const p='cloudflare-worker/index.js';let s=fs.readFileSync(p,'utf8');
function must(a,b,label){if(!s.includes(a))throw new Error('Missing '+label);s=s.replace(a,b);}
if(!s.includes('version: "V77.16.4"'))throw new Error('Expected V77.16.4');
s=s.replaceAll('V77.16.4','V77.16.5');
s=s.replace('Trading V77.16.5 Context-Cached Stable Quality Hub','Trading V77.16.5 Live-Order Reconciled Hub');
must('  cryptoDeepCooldownMs: 220,','  cryptoDeepCooldownMs: 220,\n  autoCryptoScanMinutes: 5,','auto scan config');

const oldPos=`function sideText(x){return x==="LONG"?"BUY":x==="SHORT"?"SELL":"NEUTRAL";}\nfunction duplicate(book,sym){return [...book.marketActive,...book.limitActive,...book.limitPending].some(x=>x.symbol===sym);}\nfunction toPos(sig){return {id:sig.symbol+"-"+Date.now(),symbol:sig.symbol,side:sig.side,entry:sig.entry,sl:sig.sl,tp:sig.targetRR===2?sig.tp2:sig.tp1,tp1:sig.tp1,tp2:sig.tp2,targetRR:sig.targetRR,origin:sig.action,status:"ACTIVE",openedAt:Date.now(),engineOpened:sig.engine,engine:sig.engine,source:sig.quote?.source,executionVerified:true,executionAuthority:sig.quote?.source||"CANONICAL_CRYPTO"};}\nfunction fillBooks(group,books,analyses){const b=books[group],newItems=[];for(const a of analyses){if(group!=="crypto")continue;if(a.status==="MARKET"&&!duplicate(b,a.symbol)&&b.marketActive.length<CONFIG.maxMarketActive){const p=toPos(a);b.marketActive.push(p);newItems.push(p);}if(a.status==="LIMIT"&&!duplicate(b,a.symbol)&&b.limitPending.length<CONFIG.maxPendingLimit&&(b.limitActive.length+b.limitPending.length)<CONFIG.maxLimitActive){const p={...toPos(a),status:"PENDING",expiresAt:Date.now()+CONFIG.pendingLimitExpiryMinutes*60000};b.limitPending.push(p);newItems.push(p);}}b.watch=[];return newItems;}`;
const newPos=`function sideText(x){return x==="LONG"?"BUY":x==="SHORT"?"SELL":"NEUTRAL";}\nfunction orderSourceText(x){return x==="AUTO_CRON"?"AUTO SCAN":x==="HUB_MANUAL"?"HUB MANUAL":x==="GROUP_MANUAL"?"NÚT THỊ TRƯỜNG":x==="SYMBOL_MANUAL"?"SYMBOL MANUAL":x==="COMMAND_MANUAL"?"LỆNH CHAT":x==="NEWS_MANUAL"?"NEWS CONFIRM":x==="API_RUN_NOW"?"API RUN-NOW":x==="API_HUB"?"API HUB":String(x||"SCAN");}\nfunction duplicate(book,sym){return [...book.marketActive,...book.limitActive,...book.limitPending].some(x=>x.symbol===sym);}\nfunction toPos(sig,discoveredBy="SCAN"){const tp=Number.isFinite(Number(sig.tp2))?sig.tp2:sig.tp1;return {id:sig.symbol+"-"+Date.now(),symbol:sig.symbol,side:sig.side,entry:sig.entry,sl:sig.sl,tp,tp1:sig.tp1,tp2:sig.tp2,targetRR:sig.targetRR,origin:sig.action,discoveredBy,status:"ACTIVE",openedAt:Date.now(),createdAt:Date.now(),engineOpened:sig.engine,engine:sig.engine,source:sig.quote?.source,executionVerified:true,executionAuthority:sig.quote?.source||"CANONICAL_CRYPTO"};}\nfunction fillBooks(group,books,analyses,trigger="SCAN"){const b=books[group],newItems=[];for(const a of analyses){if(group!=="crypto")continue;if(a.status==="MARKET"&&!duplicate(b,a.symbol)&&b.marketActive.length<CONFIG.maxMarketActive){const p=toPos(a,trigger);b.marketActive.push(p);newItems.push(p);}if(a.status==="LIMIT"&&!duplicate(b,a.symbol)&&b.limitPending.length<CONFIG.maxPendingLimit&&(b.limitActive.length+b.limitPending.length)<CONFIG.maxLimitActive){const p={...toPos(a,trigger),status:"PENDING",expiresAt:Date.now()+CONFIG.pendingLimitExpiryMinutes*60000};b.limitPending.push(p);newItems.push(p);}}b.watch=[];return newItems;}\nfunction livePositionLine(p){const kind=p.status==="PENDING"?"LIMIT CHỜ":p.origin==="LIMIT"?"LIMIT KHỚP":"MARKET";return kind+" • "+posLine(p)+" • nguồn "+orderSourceText(p.discoveredBy);}\nfunction allLivePositions(books){const out=[];for(const g of ["crypto","forex","metal","future"]){const b=books?.[g];if(!b)continue;for(const p of b.marketActive||[])out.push({group:g,...p});for(const p of b.limitActive||[])out.push({group:g,...p});}return out;}`;
must(oldPos,newPos,'position helpers');

must('async function runGroup(group,env){','async function runGroup(group,env,trigger="API_RUN_NOW"){','runGroup signature');
must('const books=existingBooks,newItems=fillBooks(group,books,analyses);await saveBooks(env,books);','const books=existingBooks,newItems=fillBooks(group,books,analyses,trigger);await saveBooks(env,books);','fillBooks trigger');
must('newCount:newItems.length,analyses,diagnostics:', 'newCount:newItems.length,newItems,scanTrigger:trigger,analyses,diagnostics:','run output source');

const oldSummary=`  L.push("","🟢 MARKET ĐANG CHẠY "+b.marketActive.length+"/"+CONFIG.maxMarketActive);if(b.marketActive.length)b.marketActive.forEach((p,i)=>L.push((i+1)+". "+posLine(p)));else L.push("Trống");\n  L.push("","🎯 MARKET PLAN "+marketPlans.length);`;
const newSummary=`  L.push("","🟢 MARKET ĐANG CHẠY "+b.marketActive.length+"/"+CONFIG.maxMarketActive);if(b.marketActive.length)b.marketActive.forEach((p,i)=>L.push((i+1)+". "+livePositionLine(p)));else L.push("Trống");\n  L.push("","🔵 LIMIT ĐÃ KHỚP / ĐANG CHẠY "+b.limitActive.length+"/"+CONFIG.maxLimitActive);if(b.limitActive.length)b.limitActive.forEach((p,i)=>L.push((i+1)+". "+livePositionLine(p)));else L.push("Trống");\n  L.push("","🎯 MARKET PLAN "+marketPlans.length);`;
must(oldSummary,newSummary,'group live limit display');
must('if(b.limitPending.length)b.limitPending.forEach((p,i)=>L.push((i+1)+". "+posLine(p)));','if(b.limitPending.length)b.limitPending.forEach((p,i)=>L.push((i+1)+". "+livePositionLine(p)));','pending source');

must('async function sendGroup(group,env,chatId){await sendText(env,"⏳ Đang quét MỚI "+group.toUpperCase()+"...",chatId);const run=await runGroup(group,env),books=await getBooks(env);return sendText(env,summary(group,books,run),chatId,groupKeyboard(group,run));}',
'async function sendGroup(group,env,chatId){await sendText(env,"⏳ Đang quét MỚI "+group.toUpperCase()+"...",chatId);const run=await runGroup(group,env,"GROUP_MANUAL"),books=await getBooks(env);return sendText(env,summary(group,books,run),chatId,groupKeyboard(group,run));}','manual group source');

must('async function runHub(env){const t=Date.now(),runs={};for(const g of ["crypto","forex","metal","future"])runs[g]=await runGroup(g,env);const top=',
'async function runHub(env,trigger="API_HUB"){const t=Date.now(),runs={};for(const g of ["crypto","forex","metal","future"])runs[g]=await runGroup(g,env,trigger);const top=','hub trigger');
must('return {ok:true,version:CONFIG.version,hubScanId:', 'const books=await getBooks(env);return {ok:true,version:CONFIG.version,books,hubScanId:','hub books');

const hubStart='function hubSummary(h){const L=["🧭 TRADING HUB "+CONFIG.version,"🕒 QUÉT MỚI: "+h.scannedAt,"🆔 "+h.hubScanId,"","🔥 TOP SETUPS CỦA LẦN QUÉT NÀY"];';
const hubNew='function hubSummary(h){const live=allLivePositions(h.books),L=["🧭 TRADING HUB "+CONFIG.version,"🕒 QUÉT MỚI: "+h.scannedAt,"🆔 "+h.hubScanId,"","📚 LIVE POSITIONS "+live.length];if(live.length)live.forEach((p,i)=>L.push((i+1)+". "+groupTitle(p.group)+" • "+livePositionLine(p)));else L.push("Trống");L.push("","🔥 TOP SETUPS MỚI CỦA LẦN QUÉT NÀY");';
must(hubStart,hubNew,'hub live positions');
must('async function sendHub(env,chatId){await sendText(env,"⏳ HUB đang QUÉT MỚI Crypto + Forex + Metal + Futures...",chatId);const h=await runHub(env);return sendText(env,hubSummary(h),chatId,hubKeyboard(h));}',
'async function sendHub(env,chatId){await sendText(env,"⏳ HUB đang QUÉT MỚI Crypto + Forex + Metal + Futures...",chatId);const h=await runHub(env,"HUB_MANUAL");return sendText(env,hubSummary(h),chatId,hubKeyboard(h));}','manual hub source');

must('function booksSummary(books){const L=["📚 LIVE ORDERS — LƯU BỀN QUA UPDATE BOT"];for(const g of ["forex","crypto","metal","future"]){const b=books[g];L.push(groupTitle(g)+" • MARKET "+b.marketActive.length+" • LIMIT ACTIVE "+b.limitActive.length+" • LIMIT CHỜ "+b.limitPending.length);}L.push("WATCH/SETUP không nằm trong Books; mỗi lần bấm Hub sẽ quét mới.");return L.join("\\n");}',
'function booksSummary(books){const L=["📚 LIVE ORDERS — LƯU BỀN QUA UPDATE BOT"];for(const g of ["forex","crypto","metal","future"]){const b=books[g];L.push("",groupTitle(g)+" • MARKET "+b.marketActive.length+" • LIMIT ACTIVE "+b.limitActive.length+" • LIMIT CHỜ "+b.limitPending.length);for(const p of b.marketActive)L.push("• "+livePositionLine(p));for(const p of b.limitActive)L.push("• "+livePositionLine(p));for(const p of b.limitPending)L.push("• "+livePositionLine(p));}L.push("","WATCH/SETUP không nằm trong Books; Hub quét setup mới nhưng LIVE positions luôn được hiển thị riêng.");return L.join("\\n");}','books details');

must('await sendText(env,"🔵 LIMIT ĐÃ KHỚP\\n"+p.symbol+" "+sideText(p.side)+"\\nEntry: "+p.entry).catch(()=>{});',
'await sendText(env,"🔵 LIMIT ĐÃ KHỚP — ĐANG CHẠY\\n"+p.symbol+" "+sideText(p.side)+"\\nEntry: "+p.entry+" • SL: "+p.sl+" • TP: "+p.tp+"\\nNguồn lệnh: "+orderSourceText(p.discoveredBy)+"\\nLệnh đã chuyển LIMIT CHỜ → LIMIT ACTIVE và sẽ tiếp tục xuất hiện trong HUB/Crypto.").catch(()=>{});','fill notification');
must('await sendText(env,(hitTP?"✅ TAKE PROFIT":"❌ STOP LOSS")+"\\n"+p.symbol+" "+sideText(p.side)+"\\n"+(hitTP?"TP":"SL")+": "+px).catch(()=>{});',
'await sendText(env,(hitTP?"✅ TAKE PROFIT":"❌ STOP LOSS")+"\\n"+p.symbol+" "+sideText(p.side)+"\\n"+(hitTP?"TP":"SL")+": "+px+"\\nNguồn lệnh: "+orderSourceText(p.discoveredBy)).catch(()=>{});','close notification');

const lifecycleEnd='  if(changed)await saveBooks(env,books);\n}\nasync function setupWebhook';
const lifecycleNew=`  if(changed)await saveBooks(env,books);\n}\nasync function notifyNewCryptoOrders(run,env){for(const p of run?.newItems||[]){const pending=p.status==="PENDING",title=pending?"🟡 AUTO SCAN • LIMIT MỚI ĐANG CHỜ":"🟢 AUTO SCAN • MARKET MỚI ĐANG CHẠY";await sendText(env,title+"\\n"+p.symbol+" "+sideText(p.side)+"\\nEntry: "+p.entry+" • SL: "+p.sl+" • TP: "+p.tp+"\\nNguồn: "+orderSourceText(p.discoveredBy)+"\\nLệnh đã lưu vào LIVE ORDERS.").catch(()=>{});}}\nasync function autoScanCrypto(env){const run=await runGroup("crypto",env,"AUTO_CRON");await notifyNewCryptoOrders(run,env);return run;}\nasync function setupWebhook`;
must(lifecycleEnd,lifecycleNew,'auto scanner helper');

must('else if(cb?.startsWith("sym:")){const [,g,raw]=cb.split(":");let symbol=canonicalUserSymbol(raw);await sendText(env,"⏳ Quét MỚI "+symbol+"...",chatId);const a=await runSymbol(symbol,env);await sendText(env,singleAnalysisText(a),chatId,symbolPageKeyboard(g,Math.floor(Math.max(0,symbolListFor(g).indexOf(symbol))/12)));}',
'else if(cb?.startsWith("sym:")){const [,g,raw]=cb.split(":");let symbol=canonicalUserSymbol(raw);await sendText(env,"⏳ Quét MỚI "+symbol+"...",chatId);const a=await runSymbol(symbol,env),books=await getBooks(env),added=fillBooks(g,books,[a],"SYMBOL_MANUAL");if(added.length)await saveBooks(env,books);let msg=singleAnalysisText(a);if(added.length)msg+="\\n\\n✅ Đã ghi lệnh vào LIVE ORDERS • nguồn SYMBOL MANUAL";await sendText(env,msg,chatId,symbolPageKeyboard(g,Math.floor(Math.max(0,symbolListFor(g).indexOf(symbol))/12)));}','symbol button source');
must('const books=await getBooks(env);fillBooks(group,books,[a]);await saveBooks(env,books);',
'const books=await getBooks(env);fillBooks(group,books,[a],"NEWS_MANUAL");await saveBooks(env,books);','news source');
must('const books=await getBooks(env);const added=fillBooks(type,books,[a]);if(added.length||a.status==="WATCH")await saveBooks(env,books);',
'const books=await getBooks(env);const added=fillBooks(type,books,[a],"COMMAND_MANUAL");if(added.length||a.status==="WATCH")await saveBooks(env,books);','command source');

must('if(p==="/run-now"){const g=u.searchParams.get("group");return json(await runGroup(g,env));}',
'if(p==="/run-now"){const g=u.searchParams.get("group");return json(await runGroup(g,env,"API_RUN_NOW"));}','api run source');
must('if(p==="/hub")return json(await runHub(env));','if(p==="/hub")return json(await runHub(env,"API_HUB"));','api hub source');
must('  async scheduled(_controller,env,ctx){ctx.waitUntil(lifecycle(env).catch(e=>console.error("CRON",e)));}',
'  async scheduled(_controller,env,ctx){ctx.waitUntil((async()=>{await lifecycle(env);const minute=Math.floor(Number(_controller?.scheduledTime||Date.now())/60000);if(minute%CONFIG.autoCryptoScanMinutes===0)await autoScanCrypto(env);})().catch(e=>console.error("CRON",e)));}','scheduled auto scan');

fs.writeFileSync(p,s);console.log('Applied V77.16.5 live-order visibility and notification routing');
