const fs=require('fs');
const p='cloudflare-worker/index.js';let s=fs.readFileSync(p,'utf8');
function must(a,b,l){if(!s.includes(a))throw new Error('Missing '+l);s=s.replace(a,b);}
s=s.replaceAll('V77.14.2','V77.14.3');s=s.replace('Trading V77.14.3 Actionable Geometry Hub','Trading V77.14.3 Context-Parity Actionable Hub');
must('async function runFutureSymbol(symbol,env){const s=norm(symbol),suffix=await futureContractSuffix(env),b=await futureBundle(s,env,suffix);return deepAnalyze(s,env,b.candles,b.quote,b.source,{score:6,benchmark:FUTURES_KNOWLEDGE?.symbols?.[s]?.benchmark||null});}','async function runFutureSymbol(symbol,env){const s=norm(symbol),suffix=await futureContractSuffix(env),peer=s==="NQ"?"ES":s==="ES"?"NQ":s==="MNQ"?"MES":"MNQ";const rs=await Promise.allSettled([futureBundle(s,env,suffix),futureBundle(peer,env,suffix)]);if(rs[0].status!=="fulfilled")throw rs[0].reason;const b=rs[0].value,other=rs[1].status==="fulfilled"?rs[1].value:null;let context={score:6,benchmark:peer};if(other){const n=(s==="NQ"||s==="MNQ")?b:other,e=(s==="ES"||s==="MES")?b:other;context=futurePairContext(n,e,s);}return deepAnalyze(s,env,b.candles,b.quote,b.source,context);}','future direct pair context');
const old='  const maps=await Promise.all(INTERVALS.map(i=>tdBatchCandles([s],i,env,CONFIG.candleOutputSize)));const candles=maps.map(m=>m.get(s)||[]);return deepAnalyze(s,env,candles,null,"Twelve Data",{score:5});';
const neu='  if(type==="forex"){const h1=await tdBatchCandles(FOREX,"1h",env,60),fx=forexStrengthMap(h1),base=s.slice(0,3),quote=s.slice(3),d=(fx[base]||0)-(fx[quote]||0),context={baseStrength:fx[base]||0,quoteStrength:fx[quote]||0,strengthDiff:d,score:Math.min(10,5+Math.abs(d)*4)},extra=await Promise.all(["5min","15min","4h","1day"].map(i=>tdBatchCandles([s],i,env,CONFIG.candleOutputSize))),candles=[extra[0].get(s)||[],extra[1].get(s)||[],h1.get(s)||[],extra[2].get(s)||[],extra[3].get(s)||[]];let q=null;try{q=await tdQuote(s,env);}catch{}const a=await deepAnalyze(s,env,candles,q,"Twelve Data direct + 28-pair strength",context);if(q)a.analysisQuote=q;return a;}\n  if(type==="metal"){const h1=await tdBatchCandles(METALS,"1h",env,60),moves={};for(const x of METALS)moves[x]=changeFromCandles(h1.get(x)||[]);const other=s==="XAUUSD"?"XAGUSD":"XAUUSD",rel=(moves[s]||0)-(moves[other]||0),context={relativeStrength:rel,benchmark:other,score:Math.min(10,5+Math.abs(rel)*3)},extra=await Promise.all(["5min","15min","4h","1day"].map(i=>tdBatchCandles([s],i,env,CONFIG.candleOutputSize))),candles=[extra[0].get(s)||[],extra[1].get(s)||[],h1.get(s)||[],extra[2].get(s)||[],extra[3].get(s)||[]];let q=null;try{q=await tdQuote(s,env);}catch{}const a=await deepAnalyze(s,env,candles,q,"Twelve Data direct + metal relative",context);if(q)a.analysisQuote=q;return a;}\n  const maps=await Promise.all(INTERVALS.map(i=>tdBatchCandles([s],i,env,CONFIG.candleOutputSize)));const candles=maps.map(m=>m.get(s)||[]);return deepAnalyze(s,env,candles,null,"Twelve Data",{score:5});';
must(old,neu,'direct forex metal context');
must('if(a.source)L.push(`Data: ${a.source}`);','if(a.source)L.push(`Data: ${a.source}`);const q=a.quote||a.analysisQuote;if(q?.price)L.push(`Giá nguồn: ${fmtPx(q.price)}${Number.isFinite(q.quoteAgeSec)?" • age "+q.quoteAgeSec+"s":""}${q.executionVerified?" • execution verified":" • analysis only"}`);if(a.context?.benchmark)L.push(`Context: đối chiếu ${a.context.benchmark}${a.context.smtSignal&&a.context.smtSignal!=="NONE"?" • SMT "+a.context.smtSignal:""}`);','single analysis context display');
fs.writeFileSync(p,s);console.log('Applied V77.14.3 direct-symbol context parity');
