const fs=require('fs');
const p='cloudflare-worker/index.js';let s=fs.readFileSync(p,'utf8');
function must(a,b,l){if(!s.includes(a))throw new Error('Missing '+l);s=s.replace(a,b);}
s=s.replaceAll('V77.15.1','V77.15.2');s=s.replace('Trading V77.15.2 Consolidated Actionable Multi-Market Hub','Trading V77.15.2 Actionable Plan Metrics Hub');
must('return {entry:p.entry,sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,mode:"INDICATIVE_LIMIT",targetSource:p.targetSource,indicative:true,geometry:g,entryStyle:"STRUCTURAL_PULLBACK_ZONE"};','return {entry:p.entry,sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,mode:"INDICATIVE_LIMIT",targetSource:p.targetSource,indicative:true,currentPrice:M15.close,geometry:g,entryStyle:"STRUCTURAL_PULLBACK_ZONE"};','indicative current price');
must('return {side,entry:p.entry,sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,mode:"INDICATIVE_LIMIT",targetSource:p.targetSource,indicative:true,conditional:true,entryStyle:"CONDITIONAL_HTF_PULLBACK",minQualityRR:q.minRR,rrQualityPass:true,geometry:g};','return {side,entry:p.entry,sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,mode:"INDICATIVE_LIMIT",targetSource:p.targetSource,indicative:true,conditional:true,currentPrice:M15.close,entryStyle:"CONDITIONAL_HTF_PULLBACK",minQualityRR:q.minRR,rrQualityPass:true,geometry:g};','conditional current price');
must('best={...p,mode:"LIMIT",indicative:true,entryStyle:"STRUCTURE_RETEST_LIMIT",minQualityRR:q.minRR,rrQualityPass:true,geometry:g,confluence:conf,_score:score};','best={...p,mode:"LIMIT",indicative:true,currentPrice:current,entryStyle:"STRUCTURE_RETEST_LIMIT",minQualityRR:q.minRR,rrQualityPass:true,geometry:g,confluence:conf,_score:score};','refined current price');
must('const quality=rrQuality(preview,intel),planned={entry:preview.entry,sl:preview.sl,tp1:preview.tp1,tp2:preview.tp2,targetRR:preview.targetRR,tp1RR:preview.tp1RR,tp2RR:preview.tp2RR,roomR:preview.roomR,mode:preview.mode,targetSource:preview.targetSource,targetTier:preview.targetTier,entryStyle:trigPolicy.mode,adaptive:!!(locPolicy.soft||trigPolicy.soft),minQualityRR:quality.minRR,rrQualityPass:quality.pass};','const quality=rrQuality(preview,intel),planned={entry:preview.entry,sl:preview.sl,tp1:preview.tp1,tp2:preview.tp2,targetRR:preview.targetRR,tp1RR:preview.tp1RR,tp2RR:preview.tp2RR,roomR:preview.roomR,mode:preview.mode,currentPrice:M5.close,targetSource:preview.targetSource,targetTier:preview.targetTier,entryStyle:trigPolicy.mode,adaptive:!!(locPolicy.soft||trigPolicy.soft),minQualityRR:quality.minRR,rrQualityPass:quality.pass};','preview current price');
const helper='function futureSizing(symbol,plan){const k=FUTURES_KNOWLEDGE?.symbols?.[norm(symbol)];if(!k||!plan||!["MNQ","MES"].includes(norm(symbol)))return null;const pv=Number(k.pointValue),riskPts=Math.abs(Number(plan.entry)-Number(plan.sl)),tpPts=Math.abs(Number(plan.tp2??plan.tp1)-Number(plan.entry));if(!pv||!riskPts)return null;const qty=Math.floor(500/(riskPts*pv));if(qty<1)return {tradable:false,contracts:0,riskPoints:riskPts,oneContractRiskUsd:riskPts*pv,maxRiskUsd:500};return {tradable:true,contracts:qty,riskPoints:riskPts,riskUsd:qty*riskPts*pv,tpPoints:tpPts,tpUsd:qty*tpPts*pv,maxRiskUsd:500,pointValue:pv};}\nfunction planMetricText(symbol,p){if(!p)return null;const cur=Number(p.currentPrice),entry=Number(p.entry),dist=Number.isFinite(cur)&&Number.isFinite(entry)?Math.abs(cur-entry):null,g=p.geometry||p.marketGeometry||{};let x=[];if(Number.isFinite(dist))x.push("Δ "+fmtPx(dist)+(marketType(symbol)==="future"?" pts":""));if(Number.isFinite(g.distanceATR))x.push(g.distanceATR+" ATR");if(Number.isFinite(g.chaseATR))x.push("chase "+g.chaseATR+" ATR");if(Number.isFinite(p.confluence))x.push("confluence "+p.confluence);return x.length?x.join(" • "):null;}\n';
must('function watchLine(w){let x=',helper+'function watchLine(w){let x=','plan metrics helpers');
must('if(w.planned.entryStyle)x+=`\n   ↳ Entry style: ${w.planned.entryStyle}`;}if(w.method?.profile)x+=','if(w.planned.entryStyle)x+=`\n   ↳ Entry style: ${w.planned.entryStyle}`;const mt=planMetricText(w.symbol,w.planned);if(mt)x+=`\n   ↳ Geometry: ${mt}`;const fs=futureSizing(w.symbol,w.planned);if(fs){if(fs.tradable)x+=`\n   ↳ Micro sizing: ${fs.contracts} contract • risk ~$${fs.riskUsd.toFixed(0)} • TP2 ~$${fs.tpUsd.toFixed(0)}`;else x+=`\n   ↳ Micro sizing: 1 contract risk ~$${fs.oneContractRiskUsd.toFixed(0)} > $500, chưa phù hợp`;}}if(w.method?.profile)x+=','watch metrics');
must('if(a.planned.entryStyle)L.push(`Style: ${a.planned.entryStyle}`);}','if(a.planned.entryStyle)L.push(`Style: ${a.planned.entryStyle}`);const mt=planMetricText(a.symbol,a.planned);if(mt)L.push(`Geometry: ${mt}`);const fs=futureSizing(a.symbol,a.planned);if(fs){if(fs.tradable)L.push(`Micro sizing: ${fs.contracts} contract • Risk ~$${fs.riskUsd.toFixed(0)} • TP2 ~$${fs.tpUsd.toFixed(0)}`);else L.push(`Micro sizing: 1 contract risk ~$${fs.oneContractRiskUsd.toFixed(0)} > $500`);}if(a.basisReference)L.push(`⚠️ Giá plan dùng leader ${a.executionLeader}; phải refresh ${a.symbol} trước execution.`);}','single plan metrics');
fs.writeFileSync(p,s);console.log('Applied V77.15.2 plan metrics and Futures sizing');
