const fs=require('fs');
const p='cloudflare-worker/index.js';let s=fs.readFileSync(p,'utf8');
function must(a,b,l){if(!s.includes(a))throw new Error('Missing '+l);s=s.replace(a,b);}
if(!s.includes('version: "V77.15.4"'))throw new Error('Expected V77.15.4');
s=s.replaceAll('V77.15.4','V77.15.5');
s=s.replace('Trading V77.15.5 Diversified Actionable Hub','Trading V77.15.5 Action-First Entry Hub');
const marker='function planOrWatch(symbol,type,side,reason,planned,extra={}){if(planned){const q=rrQuality(planned,extra.method||extra?.base?.method||{});if(planned.rrQualityPass===true||q.pass)return planSignal(symbol,type,side,reason,{...planned,minQualityRR:planned.minQualityRR??q.minRR,rrQualityPass:true},extra);}return watch(symbol,type,side,reason,{...extra,planned:planned||null});}';
const helper=`\nfunction routeRescueSide(intel){const r=intel?.route||{};for(const x of [intel?.side,r.trendSide,r.ctxSide])if(["LONG","SHORT"].includes(x))return x;return "NEUTRAL";}\nfunction structuralFallbackLimit(side,current,M5,M15,H1,H4,D1,prior,intel){\n  if(!["LONG","SHORT"].includes(side)||!M5?.ready||!M15?.ready||!Number.isFinite(current)||!Number.isFinite(M15.atr14)||M15.atr14<=0)return null;\n  if(Number(intel?.methodFit||0)<48)return null;const atr=Number(M15.atr14),mid=(Number.isFinite(M15.liquidityHigh20)&&Number.isFinite(M15.liquidityLow20))?(M15.liquidityHigh20+M15.liquidityLow20)/2:null;\n  const raw=[M5.ema20,M15.ema20,H1?.ema20,mid,side==="LONG"?M5.liquidityLow20:M5.liquidityHigh20,side==="LONG"?M15.liquidityLow20:M15.liquidityHigh20,side==="LONG"?H1?.liquidityLow20:H1?.liquidityHigh20].filter(Number.isFinite);\n  const cand=[...new Set(raw)].filter(e=>side==="LONG"?e<current:e>current).filter(e=>{const d=Math.abs(current-e)/atr;return d>=.05&&d<=.90;});let best=null;\n  for(const e of cand){const plan=buildTradePlan(side,e,M5,M15,H1,H4,D1,true,prior);if(!plan||plan.invalid)continue;const q=rrQuality(plan,intel),g=limitGeometry(side,current,e,M5,M15,plan);if(!q.pass||!g.pass)continue;const conf=raw.filter(x=>Math.abs(x-e)<=atr*.12).length,rr=Number(plan.targetRR)||0,score=conf*28+Math.min(45,rr*13)-Math.abs(g.distanceATR-.35)*10;if(!best||score>best._score)best={...plan,mode:"LIMIT",indicative:true,conditional:true,currentPrice:current,entryStyle:"STRUCTURAL_FALLBACK_LIMIT",minQualityRR:q.minRR,rrQualityPass:true,geometry:g,confluence:conf,_score:score};}\n  if(best)delete best._score;return best;\n}\nfunction rescuePlan(side,current,M5,M15,H1,H4,D1,prior,intel,locPolicy={},trigPolicy={}){return refinedLimitPlan(side,current,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy)||structuralFallbackLimit(side,current,M5,M15,H1,H4,D1,prior,intel);}\n`;
must(marker,marker+helper,'plan helper marker');
must('if(side==="NEUTRAL"||!htf){const cp=conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);if(cp)return planSignal(s,type,cp.side,"HTF_METHOD_ALIGNMENT_REQUIRED",cp,{...base,score:Math.max(base.score,40),entryPolicy:{profile:profileMode(intel),conditional:true}});return watch(s,type,side,"HTF_METHOD_ALIGNMENT_REQUIRED",base);}',
'if(side==="NEUTRAL"||!htf){const rs=routeRescueSide(intel),cp=conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior)||rescuePlan(rs,M15.close,M5,M15,H1,H4,D1,prior,intel,{},{});if(cp)return planSignal(s,type,cp.side||rs,"HTF_METHOD_ALIGNMENT_REQUIRED",cp,{...base,score:Math.max(base.score,40),entryPolicy:{profile:profileMode(intel),conditional:true,rescue:true}});return watch(s,type,side,"HTF_METHOD_ALIGNMENT_REQUIRED",base);}','htf rescue');
s=s.replace('indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||refinedLimitPlan(side,M15.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,{})||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior)','indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||rescuePlan(side,M15.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,{})||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior)');
s=s.replace('indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||refinedLimitPlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy)||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior)','indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior)||rescuePlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy)||conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior)');
s=s.replaceAll('const alt=refinedLimitPlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);','const alt=rescuePlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);');
s=s.replaceAll('const alt=refinedLimitPlan(side,reference.price,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);','const alt=rescuePlan(side,reference.price,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);');
must('const news=await getNewsClearance(s,env);if(!news)return watch(s,type,side,"NEWS_CONTEXT_REQUIRED",{...base,score,setupReady:true,planned,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:false}}});',
'const news=await getNewsClearance(s,env);if(!news)return planSignal(s,type,side,"NEWS_CONTEXT_REQUIRED",planned,{...base,score,setupReady:true,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:false}}});','news plan not watch');
must('const entry=pendingRetest?Number(trigPolicy.level):reference.price,plan=buildTradePlan(side,entry,M5,M15,H1,H4,D1,pendingRetest,prior);if(!plan||plan.invalid)return watch(s,type,side,plan?.invalid||"STRUCTURAL_SL_REQUIRED",{...base,score,setupReady:true,planned,quote:reference});',
'const entry=pendingRetest?Number(trigPolicy.level):reference.price,plan=buildTradePlan(side,entry,M5,M15,H1,H4,D1,pendingRetest,prior);if(!plan||plan.invalid){const alt=rescuePlan(side,reference.price,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)return planSignal(s,type,side,plan?.invalid||"STRUCTURAL_SL_REQUIRED",alt,{...base,score,setupReady:true,quote:reference});return watch(s,type,side,plan?.invalid||"STRUCTURAL_SL_REQUIRED",{...base,score,setupReady:true,planned,quote:reference});}','final plan rescue');
must('const spread=reference.ask-reference.bid,costR=spread/plan.risk;if(!Number.isFinite(costR)||costR>CONFIG.maxExecutionCostR)return watch(s,type,side,"EXECUTION_COST_TOO_HIGH",{...base,score,setupReady:true,planned,costR,quote:reference});',
'const spread=reference.ask-reference.bid,costR=spread/plan.risk;if(!Number.isFinite(costR)||costR>CONFIG.maxExecutionCostR){const alt=rescuePlan(side,reference.price,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)return planSignal(s,type,side,"EXECUTION_COST_TOO_HIGH",alt,{...base,score,setupReady:true,costR,quote:reference});return watch(s,type,side,"EXECUTION_COST_TOO_HIGH",{...base,score,setupReady:true,planned,costR,quote:reference});}','cost rescue');
fs.writeFileSync(p,s);console.log('Applied V77.15.5 action-first entry routing');
