const fs=require('fs');
const p='cloudflare-worker/index.js';let s=fs.readFileSync(p,'utf8');
function must(a,b,l){if(!s.includes(a))throw new Error('Missing '+l);s=s.replace(a,b);}
function insertBefore(marker,block,label){const i=s.indexOf(marker);if(i<0)throw new Error('Missing '+label);s=s.slice(0,i)+block+s.slice(i);}
s=s.replaceAll('V77.14.1','V77.14.2');s=s.replace('Trading V77.14.2 Futures Actionable Entry Hub','Trading V77.14.2 Actionable Geometry Hub');

const oldIndic='function indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior){\n  if(!M5?.ready||!M15?.ready)return null;let e=Number(locPolicy?.level);if(!Number.isFinite(e))e=Number(M15.ema20);\n  if(!Number.isFinite(e)||!Number.isFinite(M15.atr14)||Math.abs(e-M15.close)>M15.atr14*1.35)return null;\n  const p=buildTradePlan(side,e,M5,M15,H1,H4,D1,true,prior);if(!p||p.invalid)return null;\n  return {entry:p.entry,sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,mode:"INDICATIVE_LIMIT",targetSource:p.targetSource,indicative:true};\n}';
const newIndic='function indicativePlan(side,M5,M15,H1,H4,D1,locPolicy,prior){\n  if(!M5?.ready||!M15?.ready||!["LONG","SHORT"].includes(side))return null;let e=Number(locPolicy?.level);if(!Number.isFinite(e))e=Number(M15.ema20);\n  const atr=Number(M15.atr14);if(!Number.isFinite(e)||!Number.isFinite(atr)||atr<=0)return null;const dist=Math.abs(e-M15.close)/atr,correct=side==="LONG"?e<M15.close:e>M15.close;if(!correct||dist<.05||dist>.90)return null;\n  const p=buildTradePlan(side,e,M5,M15,H1,H4,D1,true,prior);if(!p||p.invalid)return null;const g=limitGeometry(side,M15.close,e,M5,M15,p);if(!g.pass)return null;\n  return {entry:p.entry,sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,mode:"INDICATIVE_LIMIT",targetSource:p.targetSource,indicative:true,geometry:g,entryStyle:"STRUCTURAL_PULLBACK_ZONE"};\n}';
must(oldIndic,newIndic,'indicative geometry');

const condBlock=[
'function conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior){',
'  if(!M5?.ready||!M15?.ready)return null;const route=intel?.route||{},side=["LONG","SHORT"].includes(intel?.side)?intel.side:(["LONG","SHORT"].includes(route.trendSide)?route.trendSide:(["LONG","SHORT"].includes(route.ctxSide)?route.ctxSide:"NEUTRAL"));',
'  if(side==="NEUTRAL"||Number(intel?.methodFit||0)<55)return null;const e=Number(M15.ema20);if(!Number.isFinite(e)||!Number.isFinite(M15.atr14)||M15.atr14<=0)return null;',
'  const dist=Math.abs(e-M15.close)/M15.atr14,correct=side==="LONG"?e<M15.close:e>M15.close;if(!correct||dist<.08||dist>.85)return null;',
'  const p=buildTradePlan(side,e,M5,M15,H1,H4,D1,true,prior);if(!p||p.invalid)return null;const q=rrQuality(p,intel),g=limitGeometry(side,M15.close,e,M5,M15,p);if(!q.pass||!g.pass)return null;',
'  return {side,entry:p.entry,sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,mode:"INDICATIVE_LIMIT",targetSource:p.targetSource,indicative:true,conditional:true,entryStyle:"CONDITIONAL_HTF_PULLBACK",minQualityRR:q.minRR,rrQualityPass:true,geometry:g};',
'}',
'function actionableRank(a){let x=Number(a?.score)||0;if(a?.status==="MARKET")x+=1000;else if(a?.status==="LIMIT")x+=900;else if(a?.planned?.mode==="MARKET")x+=500;else if(a?.planned?.mode==="LIMIT"||a?.planned?.mode==="INDICATIVE_LIMIT")x+=420;else if(a?.setupReady)x+=150;return x;}',
''
].join('\n');
insertBefore('function watch(symbol,type,side,reason,extra={})',condBlock+'\n','conditional actionability');

must('if(side==="NEUTRAL"||!htf)return watch(s,type,side,"HTF_METHOD_ALIGNMENT_REQUIRED",base);','if(side==="NEUTRAL"||!htf){const cp=conditionalPlanFromRoute(intel,M5,M15,H1,H4,D1,prior);return watch(s,type,cp?.side||side,"HTF_METHOD_ALIGNMENT_REQUIRED",{...base,planned:cp,entryPolicy:cp?{profile:profileMode(intel),conditional:true}:undefined});}','conditional HTF plan');

must('if(type!=="crypto")return watch(s,type,side,"EXECUTION_QUOTE_REQUIRED",{...base,score,setupReady:true,planned:{...planned,planType:plannedModeLabel(planned)},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source}}});','if(type!=="crypto"){if(!pendingRetest){const mg=marketGeometry(side,M5.close,M5,trigPolicy);if(!mg.pass)return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,marketGeometry:mg,planType:"MARKET_PLAN"},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source},marketGeometry:mg}});planned.marketGeometry=mg;}return watch(s,type,side,"EXECUTION_QUOTE_REQUIRED",{...base,score,setupReady:true,planned:{...planned,planType:plannedModeLabel(planned)},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source}}});}','noncrypto market geometry');

must('valid.sort((a,b)=>(Number(b.score)||0)-(Number(a.score)||0));analyses.push(...valid.slice(0,CONFIG.maxCandidates));','valid.sort((a,b)=>actionableRank(b)-actionableRank(a));analyses.push(...valid.slice(0,CONFIG.maxCandidates));','crypto actionable ranking');

must('for(const sym of symbols){const T=tf(h1Map.get(sym)||[]);if(!T.ready){errors.push({symbol:sym,reason:"H1_UNAVAILABLE"});continue;}let context={score:5};if(group==="forex"){const base=sym.slice(0,3),quote=sym.slice(3),d=(fx[base]||0)-(fx[quote]||0);context={baseStrength:fx[base]||0,quoteStrength:fx[quote]||0,strengthDiff:d,score:Math.min(10,5+Math.abs(d)*4)};}else{const other=sym==="XAUUSD"?"XAGUSD":"XAUUSD",rel=(metalMoves[sym]||0)-(metalMoves[other]||0);context={relativeStrength:rel,benchmark:other,score:Math.min(10,5+Math.abs(rel)*3)};}rows.push({symbol:sym,quote:{source:"Twelve Data H1",price:T.close,fresh:true},strength:Math.abs((T.close-(T.ema20??T.close))/(T.atr14||1)),context});}rows.sort((a,b)=>b.strength-a.strength);return {requested:symbols.length,rows,errors,h1Map};','for(const sym of symbols){const T=tf(h1Map.get(sym)||[]);if(!T.ready){errors.push({symbol:sym,reason:"H1_UNAVAILABLE"});continue;}let context={score:5};if(group==="forex"){const base=sym.slice(0,3),quote=sym.slice(3),d=(fx[base]||0)-(fx[quote]||0);context={baseStrength:fx[base]||0,quoteStrength:fx[quote]||0,strengthDiff:d,score:Math.min(10,5+Math.abs(d)*4)};}else{const other=sym==="XAUUSD"?"XAGUSD":"XAUUSD",rel=(metalMoves[sym]||0)-(metalMoves[other]||0);context={relativeStrength:rel,benchmark:other,score:Math.min(10,5+Math.abs(rel)*3)};}const raw=Math.abs((T.close-(T.ema20??T.close))/(T.atr14||1)),prior=v73Prior(sym,group),discoveryScore=raw*2+Number(context.score||5)*.35+sessionFit(prior)*.5;rows.push({symbol:sym,quote:{source:"Twelve Data H1",price:T.close,fresh:true},strength:discoveryScore,rawStrength:raw,context});}rows.sort((a,b)=>b.strength-a.strength);return {requested:symbols.length,rows,errors,h1Map};','noncrypto discovery quality');

fs.writeFileSync(p,s);console.log('Applied V77.14.2 actionable plan geometry');
