const fs=require('fs');
const v73=JSON.parse(fs.readFileSync('data/nocut_intraday_allpass_v73.json','utf8'));

function uniq(a){return [...new Set(a.filter(Boolean))];}
function modeFromFamily(f){const x=String(f||'').toUpperCase();if(/MEANREV|REVERT|CONTRA|FADE|SLOW|SESSION/.test(x))return 'MEAN_REVERSION';if(/BREADTH|RELATIVE|BTCALIGN|HYBRID|L2/.test(x))return 'RELATIVE';if(/TREND|MOM|MOMENTUM|FAST|H1TREND|H4TREND|D1TREND|BTC_CORE|\bH1\b|\bH4\b|\bD1\b/.test(x))return 'TREND';return null;}
function one(assetClass,key,e){const m=e.method||{},st=m.style||{},actions=Array.isArray(m.actions)?m.actions:[];const families=uniq([st.family,m.profile,...actions.map(a=>a.family)]);const riskATR=st.riskATR??actions.map(a=>a.riskATR).find(Number.isFinite)??null;const allowedModes=uniq(families.map(modeFromFamily));const canonical=assetClass==='crypto'&&key==='TON'?'GRAMUSDT':assetClass==='crypto'?key+'USDT':key;const aliases=assetClass==='crypto'&&key==='TON'?['TON','TONUSDT','GRAM','GRAMUSDT']:[canonical];return {canonicalSymbol:canonical,legacyPriorKey:key,aliases,assetClass,source:e.source||null,timeframe:e.timeframe||null,priorClassification:v73.classification,priorStatus:m.status||null,families,allowedModes:allowedModes.length?allowedModes:['GENERIC'],entryMode:st.entryMode||(m.router?'ROUTER':null),signalHourUTC:st.signalHourUTC??m.decisionHourUTC??null,riskATR,priorRR:st.rr??null,newsProfile:e.newsProfile||null,calibration:{status:'PRIOR_ONLY_UNCALIBRATED',reason:'V73 is exposed development prior, not untouched OOS proof',sampleSize:m.development?.trades??null,developmentWinRatePct:m.development?.wrAllTrades??null,developmentMeanR:m.development?.meanRAllTrades??null},productionPolicy:{hubScoreIsWinProbability:false,executionRequiresFreshAuthority:true,slPolicy:'STRUCTURE_LIQUIDITY_INVALIDATION_WITH_VOLATILITY_FLOOR',tpPolicy:'FORWARD_STRUCTURE_LIQUIDITY',indicativePlanMayBeWatch:true}};}
const registry={version:'SYMBOL_KNOWLEDGE_V1',generatedAt:new Date().toISOString(),sourceV73:v73.version,classification:v73.classification,policy:{noGuaranteedWinRate:true,optimize:'robust_expectancy_after_costs',requireWalkForwardBeforeCalibration:true},symbols:{}};
for(const [k,e] of Object.entries(v73.forex?.symbols||{}))registry.symbols[k]=one('forex',k,e);
for(const [k,e] of Object.entries(v73.crypto?.symbols||{})){const o=one('crypto',k,e);registry.symbols[o.canonicalSymbol]=o;}
for(const m of ['XAUUSD','XAGUSD'])registry.symbols[m]={canonicalSymbol:m,legacyPriorKey:null,aliases:[m],assetClass:'metal',source:'RUNTIME_ADAPTIVE',timeframe:'MULTI_TF',priorClassification:'NO_V73_SYMBOL_PRIOR',priorStatus:null,families:['METAL_STRUCTURE','RELATIVE_METAL'],allowedModes:['TREND','MEAN_REVERSION','RELATIVE'],entryMode:'DYNAMIC_ROUTER',signalHourUTC:null,riskATR:null,priorRR:null,newsProfile:null,calibration:{status:'UNCALIBRATED',reason:'Requires dedicated metal walk-forward/OOS calibration'},productionPolicy:{hubScoreIsWinProbability:false,executionRequiresFreshAuthority:true,slPolicy:'STRUCTURE_LIQUIDITY_INVALIDATION_WITH_VOLATILITY_FLOOR',tpPolicy:'FORWARD_STRUCTURE_LIQUIDITY',indicativePlanMayBeWatch:true}};
fs.writeFileSync('data/symbol_knowledge_registry.json',JSON.stringify(registry,null,2)+'\n');
console.log(`Wrote ${Object.keys(registry.symbols).length} symbol knowledge records`);
