import fs from 'node:fs';
const ep='cloudflare-worker/engine-v77168.js', hp='cloudflare-worker/hub-v77171.js', ip='cloudflare-worker/index.js', dp='cloudflare-worker/dual-ai-intervention.js';
let e=fs.readFileSync(ep,'utf8'),h=fs.readFileSync(hp,'utf8'),i=fs.readFileSync(ip,'utf8'),d=fs.readFileSync(dp,'utf8');
const must=(s,x,label)=>{if(!s.includes(x))throw new Error('missing '+label);};
const rep=(s,a,b,label)=>{must(s,a,label);return s.replace(a,b);};

e=rep(e,'version: "V77.16.19",\n  service: "Trading V77.16.19 Signal Live Sync R6",','version: "V77.16.20",\n  service: "Trading V77.16.20 Signal Integrity R7",','engine version');
e=rep(e,'async function tdIndexQuote(symbol,env){const s=norm(symbol),ps=INDEX_PROVIDER[s]||s,p=await tdFetch("time_series",{symbol:ps,type:"Index",interval:"1min",outputsize:"2",order:"DESC",timezone:"UTC"},env),node=tdIndexNode(p);assertTdIndexIdentity(s,node);const c=tdCandlesFromNode(node,"1min"),last=c?.at(-1),price=num(last?.close);if(!(price>0)||!validIndexPrice(s,price))throw new Error(`Twelve Data invalid native index value ${s}/${ps}: ${price}`);return {source:"Twelve Data Native Index",requestedSymbol:s,providerSymbol:ps,price,providerTimestamp:last?.timestamp||null,quoteAgeSec:last?.timestamp?Math.max(0,nowSec()-last.timestamp-60):null,fresh:true,bid:null,ask:null,executionVerified:false,analysisOnly:true,assetType:node?.meta?.type||"Index"};}','async function tdIndexQuote(symbol,env){const s=norm(symbol),ps=INDEX_PROVIDER[s]||s,p=await tdFetch("time_series",{symbol:ps,type:"Index",interval:"1min",outputsize:"2",order:"DESC",timezone:"UTC"},env),node=tdIndexNode(p);assertTdIndexIdentity(s,node);const c=tdCandlesFromNode(node,"1min"),last=c?.at(-1),price=num(last?.close);if(!(price>0)||!validIndexPrice(s,price))throw new Error(`Twelve Data invalid native index value ${s}/${ps}: ${price}`);const age=last?.timestamp?Math.max(0,nowSec()-last.timestamp-60):null;return {source:"Twelve Data Native Index",requestedSymbol:s,providerSymbol:ps,price,providerTimestamp:last?.timestamp||null,quoteAgeSec:age,fresh:age!==null&&age<=900,bid:null,ask:null,executionVerified:false,analysisOnly:true,assetType:node?.meta?.type||"Index"};}','index freshness');
e=rep(e,'function validSignalPosition(p,group){if(!p||typeof p!=="object"||!GROUPS[group]?.includes(canonicalUserSymbol(p.symbol)))return false;if(!["LONG","SHORT"].includes(p.side))return false;if(![p.entry,p.sl,p.tp].every(v=>Number.isFinite(Number(v))&&Number(v)>0))return false;if(p.expiresAt&&Date.now()>Number(p.expiresAt))return false;return p.signalOnly===true||p.executionAuthority==="SIGNAL_ONLY";}','function validSignalPosition(p,group){if(!p||typeof p!=="object"||!GROUPS[group]?.includes(canonicalUserSymbol(p.symbol)))return false;if(!["LONG","SHORT"].includes(p.side))return false;if(![p.entry,p.sl,p.tp].every(v=>Number.isFinite(Number(v))&&Number(v)>0))return false;return p.signalOnly===true||p.executionAuthority==="SIGNAL_ONLY";}','signal normalization');
e=rep(e,'function enrichBookPosition(g,p,q){const o={...p},px=Number(q?.price),e=Number(p.entry),dir=p.side==="SHORT"?-1:1;if(!(px>0&&e>0))return o;o.currentPrice=px;o.liveAt=Date.now();o.liveSource=q?.source||null;o.pnlPct=(px-e)/e*100*dir;if(p.status!=="PENDING"){const z=bookQty(p);if(z.qty){o.pnlUsd=(px-e)*dir*z.qty;o.pnlUsdEstimated=z.estimated||g!=="crypto";}}return o;}','function enrichBookPosition(g,p,q){const o={...p},px=Number(q?.price),e=Number(p.entry),dir=p.side==="SHORT"?-1:1;o.liveSource=q?.source||null;o.liveQuoteAgeSec=Number.isFinite(Number(q?.quoteAgeSec))?Number(q.quoteAgeSec):null;if(q?.fresh===false){o.liveStale=true;return o;}if(!(px>0&&e>0))return o;o.currentPrice=px;o.liveAt=Date.now();o.liveStale=false;o.pnlPct=(px-e)/e*100*dir;if(p.status!=="PENDING"){const z=bookQty(p);if(z.qty){o.pnlUsd=(px-e)*dir*z.qty;o.pnlUsdEstimated=z.estimated||g!=="crypto";}}return o;}','live stale guard');
e=rep(e,'function toSignalPos(sig,discoveredBy="SCAN",group="forex"){const tp=Number.isFinite(Number(sig.tp2))?Number(sig.tp2):Number(sig.tp1),ttl=group==="forex"?12:8;return {id:`signal-${sig.symbol}-${Date.now()}`,symbol:sig.symbol,side:sig.side,entry:Number(sig.entry??sig.planned?.entry),sl:Number(sig.sl??sig.planned?.sl),tp,tp1:Number(sig.tp1??sig.planned?.tp1),tp2:Number(sig.tp2??sig.planned?.tp2),targetRR:Number(sig.targetRR??sig.planned?.targetRR),origin:"MARKET_SIGNAL",discoveredBy,status:"ACTIVE",openedAt:Date.now(),createdAt:Date.now(),expiresAt:Date.now()+ttl*3600000,engineOpened:sig.engine,engine:sig.engine,source:sig.analysisQuote?.source||sig.quote?.source||sig.source,executionVerified:false,executionAuthority:"SIGNAL_ONLY",signalOnly:true,riskUsd:CONFIG.defaultRiskUsd};}','function toSignalPos(sig,discoveredBy="SCAN",group="forex"){const tp1=Number(sig.tp1??sig.planned?.tp1),tp2=Number(sig.tp2??sig.planned?.tp2),tp=Number.isFinite(tp2)&&tp2>0?tp2:tp1,ttl=group==="forex"?12:8;return {id:`signal-${sig.symbol}-${Date.now()}`,symbol:sig.symbol,side:sig.side,entry:Number(sig.entry??sig.planned?.entry),sl:Number(sig.sl??sig.planned?.sl),tp,tp1,tp2:Number.isFinite(tp2)&&tp2>0?tp2:tp1,targetRR:Number(sig.targetRR??sig.planned?.targetRR),origin:"MARKET_SIGNAL",discoveredBy,status:"ACTIVE",openedAt:Date.now(),createdAt:Date.now(),expiresAt:Date.now()+ttl*3600000,engineOpened:sig.engine,engine:sig.engine,source:sig.analysisQuote?.source||sig.quote?.source||sig.source,executionVerified:false,executionAuthority:"SIGNAL_ONLY",signalOnly:true,riskUsd:CONFIG.defaultRiskUsd};}','signal TP fallback');
e=rep(e,'function stageText(a){if(a.status==="MARKET")return "🟢 MARKET EXEC";','function stageText(a){if(a.status==="MARKET_SIGNAL")return "⚡ MARKET SIGNAL";if(a.status==="MARKET")return "🟢 MARKET EXEC";','stage market signal');
e=e.replace('if(run)L.push("🔍 Coverage "+run.broadOk+"/"+run.requested+" • Deep "+run.deepOk+"/"+run.deepRequested+" • Lệnh executable mới "+run.newCount','if(run)L.push("🔍 Coverage "+run.broadOk+"/"+run.requested+" • Deep "+run.deepOk+"/"+run.deepRequested+" • Record Live mới "+run.newCount');
e=e.replace('deepRequested:Math.min(CONFIG.maxCandidates,broad.rows.length)','deepRequested:deepAttempted');
e=e.replace('async function sendHub(env,chatId){await sendText(env,"⏳ HUB đang QUÉT MỚI Crypto + Forex + Metal + Futures..."','async function sendHub(env,chatId){await sendText(env,"⏳ HUB đang QUÉT MỚI Crypto + Forex + Metal + Index Cash..."');
e=e.replace('line+="\\n   ↳ "+(a.status==="MARKET"||a.status==="LIMIT"?"Đủ gate execution":a.status==="MARKET_PLAN"||a.status==="LIMIT_PLAN"?"Kế hoạch kỹ thuật hợp lệ — chờ execution authority":reasonText(a.reason));','line+="\\n   ↳ "+(a.status==="MARKET_SIGNAL"?"Signal advisory fresh — SIGNAL-ONLY":a.status==="MARKET"||a.status==="LIMIT"?"Đủ gate execution":a.status==="MARKET_PLAN"||a.status==="LIMIT_PLAN"?"Kế hoạch kỹ thuật hợp lệ — chờ execution authority":reasonText(a.reason));');
const oldLife='async function lifecycle(env){\n  const books=await getBooks(env),b=books.crypto;let changed=false,pending=[];';
const newLife='async function lifecycleSignalGroups(env,books){let changed=false;for(const group of ["forex","metal","index"]){const b=books[group],keep=[];for(const p of b.signalActive||[]){if(p.expiresAt&&Date.now()>Number(p.expiresAt)){changed=true;await appendOrderHistory(env,{event:"SIGNAL_EXPIRED",group,position:p});continue;}try{const q=await liveBookQuote(group,p,env);if(!q||q.fresh===false){keep.push(p);continue;}const px=Number(q.price),hitTP=p.side==="LONG"?px>=Number(p.tp):px<=Number(p.tp),hitSL=p.side==="LONG"?px<=Number(p.sl):px>=Number(p.sl);if(hitTP||hitSL){changed=true;await appendOrderHistory(env,{event:hitTP?"SIGNAL_TP":"SIGNAL_SL",group,position:p,closePrice:px,source:q.source});await sendText(env,signalEventText(hitTP?"TP":"SL",p,{group,closePrice:px}),undefined,signalNotifyKeyboard(group,p.symbol)).catch(()=>{});}else keep.push(p);}catch{keep.push(p);}}b.signalActive=keep;}return changed;}\nasync function lifecycle(env){\n  const books=await getBooks(env),b=books.crypto;let changed=await lifecycleSignalGroups(env,books),pending=[];';
e=rep(e,oldLife,newLife,'signal lifecycle');
e=e.replace('newCount:["MARKET","LIMIT"].includes(a.status)?1:0','newCount:["MARKET","LIMIT","MARKET_SIGNAL"].includes(a.status)?1:0');
e=e.replace('groupKeyboard(group,books))','groupKeyboard(group,{analyses:[a]}))');
fs.writeFileSync(ep,e);

h=rep(h,'const VERSION="V77.18.41",UI_REV="HUB-R9-SIGNAL-LIVE-SYNC",SERVICE="Trading V77.18.41 • Signal Live Sync";','const VERSION="V77.18.42",UI_REV="HUB-R10-SIGNAL-INTEGRITY",SERVICE="Trading V77.18.42 • Signal Integrity";','hub version');
h=h.replace('${p.pnlUsdEstimated||p.signalOnly?"~":""}${usd>=0?"+":""}${usd.toFixed(2)}','${p.pnlUsdEstimated||p.signalOnly?"~":""}${usd>=0?"+":""}$${usd.toFixed(2)}');
h=h.replace('pending?"⏳ Chưa khớp • chưa tính P/L":`💵 ${p.signalOnly?"Theo dõi":"P/L"}','pending?"⏳ Chưa khớp • chưa tính P/L":p.liveStale?`⚠️ Quote stale${Number.isFinite(p.liveQuoteAgeSec)?` • ${Math.round(p.liveQuoteAgeSec)}s`:""} • chưa cập nhật P/L`:`💵 ${p.signalOnly?"Theo dõi":"P/L"}');
fs.writeFileSync(hp,h);

i=rep(i,'const VERSION="V77.18.38",SERVICE="Trading V77.18.38 Repair + Deploy Sync";\nconst RELEASE_NAME="Repair + Deploy Sync";','const VERSION="V77.18.42",SERVICE="Trading V77.18.42 Signal Integrity + Claude Audit";\nconst RELEASE_NAME="Signal Integrity + Claude Audit";','index version');
fs.writeFileSync(ip,i);

d=rep(d,'const REVIEW_REV="MARKET_BALANCE_R5_BUDGET";','const REVIEW_REV="SIGNAL_LIVE_INTEGRITY_R1";','Claude review revision');
d=rep(d,'const cut=(s,n=1600)=>String(s||"").slice(0,n);','const cut=(s,n=1600)=>String(s||"").slice(0,n);\nfunction focus(src,needles,radius=900){const s=String(src||""),chunks=[];for(const needle of needles){const at=s.indexOf(needle);if(at<0)continue;chunks.push(s.slice(Math.max(0,at-radius),Math.min(s.length,at+needle.length+radius)));}return cut([...new Set(chunks)].join("\\n---FOCUS---\\n"),9000);}');
d=rep(d,'async function snapshot(env){const files=[];for(const path of FILES){try{files.push({path,content:cut(await ft(`https://raw.githubusercontent.com/${REPO}/main/${path}`),1900)});}catch(e){files.push({path,error:String(e?.message||e)});}}const [health,runtime,books,tuning,hubUx]=await Promise.all([kvGet(env,"v771817:health:last",null),kvGet(env,"v7718:hyro:runtime",null),kvGet(env,"v775:books",null),getAdaptiveTuningState(env),getHubUxState(env)]);return {files,health:health?{ok:health.ok,errors:health.errors,warnings:health.warnings,signature:health.signature,issues:(health.issues||[]).slice(0,10)}:null,runtime:runtime?{reason:runtime.reason,executed:runtime.executed,scanSummary:runtime.scanSummary,preview:(runtime.preview||[]).slice(0,5),dynamicRisk:runtime.dynamicRisk}:null,books:books?{groups:Object.keys(books),updatedAt:books.updatedAt}:null,tuning,hubUx};}','async function snapshot(env){const files=[];for(const path of FILES){try{const raw=await ft(`https://raw.githubusercontent.com/${REPO}/main/${path}`),needles=path.endsWith("engine-v77168.js")?["MARKET_SIGNAL","toSignalPos","fillBooks","getBooksLive","lifecycleSignalGroups","notifySignalPlans","signalNotifyKeyboard"]:path.endsWith("hub-v77171.js")?["booksText","MARKET SIGNAL","live:","signal:scan:"]:path.endsWith("index.js")?["dual-ai/status","scheduled(event","ensureDualAiIntervention"]:[];files.push({path,content:needles.length?focus(raw,needles):cut(raw,1900)});}catch(e){files.push({path,error:String(e?.message||e)});}}const [health,runtime,books,tuning,hubUx]=await Promise.all([kvGet(env,"v771817:health:last",null),kvGet(env,"v7718:hyro:runtime",null),kvGet(env,"v775:books",null),getAdaptiveTuningState(env),getHubUxState(env)]);const bookSummary=books?Object.fromEntries(Object.entries(books).filter(([k])=>["forex","crypto","metal","index"].includes(k)).map(([g,b])=>[g,{marketActive:(b?.marketActive||[]).length,signalActive:(b?.signalActive||[]).length,limitActive:(b?.limitActive||[]).length,limitPending:(b?.limitPending||[]).length,signals:(b?.signalActive||[]).slice(0,3).map(p=>({symbol:p.symbol,side:p.side,entry:p.entry,sl:p.sl,tp:p.tp,expiresAt:p.expiresAt,source:p.source}))}])):null;return {files,health:health?{ok:health.ok,errors:health.errors,warnings:health.warnings,signature:health.signature,issues:(health.issues||[]).slice(0,10)}:null,runtime:runtime?{reason:runtime.reason,executed:runtime.executed,scanSummary:runtime.scanSummary,preview:(runtime.preview||[]).slice(0,5),dynamicRisk:runtime.dynamicRisk}:null,books:bookSummary?{groups:bookSummary,updatedAt:books.updatedAt}:null,tuning,hubUx};}','Claude snapshot focus');
d=d.replace('FOREX ENTRY QUALITY AND MARKET-ISOLATED HUB ARE THE FIRST PRIORITY FOR THIS REVIEW.','SIGNAL LIVE INTEGRITY IS THE FIRST PRIORITY FOR THIS REVIEW. Audit the complete MARKET_SIGNAL lifecycle: analysis object schema, planned/top-level entry-SL-TP fallback, fillBooks persistence, normalizeBooks preservation, duplicate suppression, scoped Live refresh, fresh-vs-stale quotes, TP/SL/expiry removal, order history, Telegram notification dedupe and callback routing. A Telegram MARKET_SIGNAL must appear in the matching market Live immediately and remain there until explicit TP, SL or expiry. Never silently drop a valid signal. Verify signal-only P/L is clearly theoretical and never called a broker fill.\n\nFOREX ENTRY QUALITY AND MARKET-ISOLATED HUB ARE THE NEXT PRIORITY FOR THIS REVIEW.');
d=d.replace('Perform MARKET_BALANCE_R5_BUDGET first.','Perform SIGNAL_LIVE_INTEGRITY_R1 first.');
d=d.replace('lastAction:"MARKET_BALANCE_R5_BUDGET"','lastAction:"SIGNAL_LIVE_INTEGRITY_R1"');
fs.writeFileSync(dp,d);

for(const [p,s] of [[ep,e],[hp,h],[ip,i],[dp,d]]){if(!s.includes('SIGNAL'))throw new Error('sanity failed '+p);}
console.log('Signal Integrity R7 migration complete');
