from pathlib import Path

# ENGINE
p=Path('cloudflare-worker/engine-v77168.js'); s=p.read_text()
s=s.replace('version: "V77.16.16",','version: "V77.16.17",').replace('service: "Trading V77.16.16 Verified Index Pricing",','service: "Trading V77.16.17 Market Isolation + Forex R4",')
s=s.replace('const rel=Number(context.relativeStrength??context.strengthDiff),ctxMag=Number.isFinite(rel)?Math.min(1,Math.abs(rel)/2):0,ctxSide=Number.isFinite(rel)&&Math.abs(rel)>.05?(rel>0?"LONG":"SHORT"):"NEUTRAL";', 'const rel=Number(context.strengthNormalizedSigned??context.relativeStrength??context.strengthDiff),ctxMag=Number.isFinite(rel)?Math.min(1,Math.abs(rel)/2):0,ctxSide=Number.isFinite(rel)&&Math.abs(rel)>.05?(rel>0?"LONG":"SHORT"):"NEUTRAL";')
old='context={baseStrength:fx[base]||0,quoteStrength:fx[quote]||0,strengthDiff:d,session:sess.label,sessionScore:sess.score,score:Math.min(10,4.6+Math.abs(d)*4.4+sess.score*.7)};'
new='context={baseStrength:fx[base]||0,quoteStrength:fx[quote]||0,strengthDiff:d,strengthNormalizedSigned:Math.max(-1,Math.min(1,d/.60)),session:sess.label,sessionScore:sess.score,score:Math.min(10,4.7+Math.abs(d)*4.2+sess.score*.75)};'
if old not in s: raise SystemExit('broad forex context missing')
s=s.replace(old,new)
old='''function adaptiveLocationPolicy(intel,M15,loc,side,context={}){
  const mode=profileMode(intel);if(loc?.valid)return {pass:true,mode:"STRUCTURAL_LOCATION",soft:false,level:loc.level};
  if(!M15?.ready||!Number.isFinite(M15.atr14)||M15.atr14<=0)return {pass:false,mode,soft:false};
  const strong=Number(intel?.methodFit||0)>=80&&Number(context.score||0)>=7,nearEma=Number.isFinite(M15.ema20)&&Math.abs(M15.close-M15.ema20)<=M15.atr14*(strong?1.0:.80);
  const continuation=side==="LONG"?(M15.bullishBreak||M15.bullishReclaim||sideTrendMatch(M15,side)):(M15.bearishBreak||M15.bearishReclaim||sideTrendMatch(M15,side));'''
new='''function adaptiveLocationPolicy(intel,M15,loc,side,context={}){
  const mode=profileMode(intel);if(loc?.valid)return {pass:true,mode:"STRUCTURAL_LOCATION",soft:false,level:loc.level};
  if(!M15?.ready||!Number.isFinite(M15.atr14)||M15.atr14<=0)return {pass:false,mode,soft:false};
  const isFx=intel?.type==="forex",strong=Number(intel?.methodFit||0)>=80&&Number(context.score||0)>=7,nearMult=isFx?(strong?1.20:1.00):(strong?1.0:.80),nearEma=Number.isFinite(M15.ema20)&&Math.abs(M15.close-M15.ema20)<=M15.atr14*nearMult;
  const continuation=side==="LONG"?(M15.bullishBreak||M15.bullishReclaim||sideTrendMatch(M15,side)):(M15.bearishBreak||M15.bearishReclaim||sideTrendMatch(M15,side));
  if(isFx&&["TREND","RELATIVE"].includes(mode)&&Number(intel.methodFit||0)>=46&&Number(context.score||0)>=5.2&&nearEma&&continuation)return {pass:true,mode:"FX_SESSION_CONTINUATION_ZONE",soft:true,level:M15.ema20};'''
if old not in s: raise SystemExit('location block missing')
s=s.replace(old,new)
old='''  const structuralImpulse=side==="LONG"?(M5.bullishBreak||M5.bullishReclaim):(M5.bearishBreak||M5.bearishReclaim);
  if(mode==="MEAN_REVERSION")return {pass:false,pending:false,mode};'''
new='''  const structuralImpulse=side==="LONG"?(M5.bullishBreak||M5.bullishReclaim):(M5.bearishBreak||M5.bearishReclaim),isFx=intel?.type==="forex";
  const fxImpulse=side==="LONG"?trend&&r>=48&&r<=74&&M5.close>=M5.ema20:trend&&r<=52&&r>=26&&M5.close<=M5.ema20;
  if(isFx&&["TREND","RELATIVE"].includes(mode)&&Number(intel.methodFit||0)>=47&&Number(context.score||0)>=5.2&&fxImpulse&&(structuralImpulse||Math.abs(r-50)>=3||Number(intel.methodFit||0)>=72))return {pass:true,pending:false,mode:"FX_M5_SESSION_CONTINUATION",level:M5.close,soft:true};
  if(mode==="MEAN_REVERSION")return {pass:false,pending:false,mode};'''
if old not in s: raise SystemExit('trigger block missing')
s=s.replace(old,new)
# runSymbol forex: add session and normalized strength
old='context={baseStrength:fx[base]||0,quoteStrength:fx[quote]||0,strengthDiff:d,score:Math.min(10,5+Math.abs(d)*4),contextCached:!!cached}'
new='context={baseStrength:fx[base]||0,quoteStrength:fx[quote]||0,strengthDiff:d,strengthNormalizedSigned:Math.max(-1,Math.min(1,d/.60)),session:forexSessionBias(s).label,sessionScore:forexSessionBias(s).score,score:Math.min(10,4.7+Math.abs(d)*4.2+forexSessionBias(s).score*.75),contextCached:!!cached}'
if old not in s: raise SystemExit('runSymbol forex context missing')
s=s.replace(old,new)
# Attach explicit quote to crypto result
old='return deepAnalyze(s,env,b.candles,b.quote,b.source,context);}'
new='const a=await deepAnalyze(s,env,b.candles,b.quote,b.source,context);if(b.quote)a.analysisQuote=b.quote;return a;}'
s=s.replace(old,new,1)
# Replace generic index runSymbol tail with native quote/context
old='''  const maps=await Promise.all(INTERVALS.map(i=>tdBatchCandles([s],i,env,CONFIG.candleOutputSize)));const candles=maps.map(m=>m.get(s)||[]);return deepAnalyze(s,env,candles,null,"Twelve Data",{score:5});
}'''
new='''  const maps=await Promise.all(INTERVALS.map(i=>tdBatchCandles([s],i,env,CONFIG.candleOutputSize))),candles=maps.map(m=>m.get(s)||[]);let q=null;try{q=await tdQuote(s,env);}catch{}const sess=indexSessionBias(s),context={session:sess.label,sessionScore:sess.score,score:Math.min(10,5+sess.score*.8)};const a=await deepAnalyze(s,env,candles,q,q?.source||"Verified native Index",context);if(q)a.analysisQuote=q;return a;
}'''
if old not in s: raise SystemExit('index runSymbol tail missing')
s=s.replace(old,new)
# Non-crypto MARKET SIGNAL must use a fresh explicit quote and revalidate plan at that price.
old='''  if(type!=="crypto"){let p=planned,mg=null;if(!pendingRetest){mg=marketGeometry(side,M5.close,M5,trigPolicy);if(!mg.pass){const alt=rescuePlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)p=alt;else return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,marketGeometry:mg},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="index"?"Twelve Data Index":"Twelve Data analysis"),canonical:{...base.canonical,marketGeometry:mg}});}else p={...p,marketGeometry:mg};}
    const advisoryFit=type==="forex"?50:type==="metal"?52:type==="index"?52:999,advisoryContext=type==="forex"?5.4:type==="metal"?5.5:5.4;
    const marketAdvisory=["forex","metal","index"].includes(type)&&!pendingRetest&&mg?.pass&&Number(intel.methodFit||0)>=advisoryFit&&Number(context.score||0)>=advisoryContext&&Number.isFinite(Number(M15.close))&&quality.pass;
    if(marketAdvisory)return {ok:true,status:"MARKET_SIGNAL",action:"MARKET_SIGNAL",symbol:s,market:type,side,score:Math.max(score,55),method:intel,context,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},entry:Number(M15.close),currentPrice:Number(M15.close),sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,planned:{...p,mode:"MARKET",signalOnly:true,analysisQuote:true},executionReady:false,executionAuthority:"SIGNAL_ONLY",quote:{source:type==="index"?"Twelve Data Index":"Twelve Data analysis",price:Number(M15.close),fresh:true,analysisOnly:true,executionVerified:false},source:type==="index"?"Twelve Data Index":"Twelve Data analysis",canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source},marketGeometry:mg},engine:CONFIG.version};
    return planSignal(s,type,side,"EXECUTION_QUOTE_REQUIRED",p,{...base,score,setupReady:true,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="index"?"Twelve Data Index":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source}}});}'''
new='''  if(type!=="crypto"){let signalQuote=reference;try{if(!signalQuote?.price||signalQuote.fresh===false)signalQuote=await tdQuote(s,env);}catch{}const livePrice=Number(signalQuote?.price),hasFresh=Number.isFinite(livePrice)&&livePrice>0&&signalQuote?.fresh!==false;let p=planned,mg=null,liveQuality=quality;if(!pendingRetest&&hasFresh){mg=marketGeometry(side,livePrice,M5,trigPolicy);const rebuilt=buildTradePlan(side,livePrice,M5,M15,H1,H4,D1,false,prior);if(rebuilt&&!rebuilt.invalid){const q2=rrQuality(rebuilt,intel);if(q2.pass){p={...rebuilt,marketGeometry:mg,minQualityRR:q2.minRR,rrQualityPass:true};liveQuality=q2;}}if(!mg.pass){const alt=rescuePlan(side,livePrice,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)p=alt;else return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,analysisQuote:signalQuote,planned:{...planned,marketGeometry:mg},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:signalQuote?.source||source,canonical:{...base.canonical,marketGeometry:mg}});}}
    const advisoryFit=type==="forex"?48:type==="metal"?52:type==="index"?52:999,advisoryContext=type==="forex"?5.2:type==="metal"?5.5:5.4;
    const marketAdvisory=["forex","metal","index"].includes(type)&&!pendingRetest&&hasFresh&&mg?.pass&&Number(intel.methodFit||0)>=advisoryFit&&Number(context.score||0)>=advisoryContext&&liveQuality.pass;
    if(marketAdvisory)return {ok:true,status:"MARKET_SIGNAL",action:"MARKET_SIGNAL",symbol:s,market:type,side,score:Math.max(score,55),method:intel,context,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},entry:livePrice,currentPrice:livePrice,sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,analysisQuote:signalQuote,planned:{...p,mode:"MARKET",signalOnly:true,analysisQuote:true},executionReady:false,executionAuthority:"SIGNAL_ONLY",quote:{...signalQuote,analysisOnly:true,executionVerified:false},source:signalQuote?.source||source||"analysis quote",canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source},marketGeometry:mg},engine:CONFIG.version};
    return planSignal(s,type,side,hasFresh?"EXECUTION_QUOTE_REQUIRED":"FINAL_QUOTE_REQUIRED",p,{...base,score,setupReady:true,analysisQuote:signalQuote||null,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:signalQuote?.source||source,canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source}}});}'''
if old not in s: raise SystemExit('noncrypto market block missing')
s=s.replace(old,new)
# Expose market-scoped symbol lists.
s=s.replace('if(p==="/analyze"){const symbol=u.searchParams.get("symbol");return json(await runSymbol(symbol,env));}', 'if(p==="/analyze"){const symbol=u.searchParams.get("symbol");return json(await runSymbol(symbol,env));}\n      if(p==="/symbols"){const g=u.searchParams.get("group");if(!GROUPS[g])return json({ok:false,error:"invalid group"},400);return json({ok:true,group:g,symbols:GROUPS[g]});}')
s=s.replace('"/analyze?symbol=BTCUSDT|EURUSD|XAUUSD|NAS100|US30|US500|DEX|JP225"', '"/analyze?symbol=BTCUSDT|EURUSD|XAUUSD|NAS100|US30|US500|DEX|JP225","/symbols?group=forex|crypto|metal|index"')
p.write_text(s)

# HUB
p=Path('cloudflare-worker/hub-v77171.js'); s=p.read_text()
s=s.replace('const VERSION="V77.18.35",UI_REV="HUB-R6-SPLIT-LIVE",SERVICE="Trading V77.18.35 • Verified Index Pricing";', 'const VERSION="V77.18.36",UI_REV="HUB-R7-MARKET-ISOLATED",SERVICE="Trading V77.18.36 • Market Isolated UX";')
start=s.index('function mainKeyboard(style={})')
end=s.index('function propKeyboard',start)
newkeys='''function mainKeyboard(style={}){return {inline_keyboard:[[{text:"📡 Signal",callback_data:"signal"},{text:"🏦 Hyro",callback_data:"prop"}],[{text:"💱 Forex",callback_data:"market:forex"},{text:"🪙 Crypto",callback_data:"market:crypto"}],[{text:"🥇 Metal",callback_data:"market:metal"},{text:"📊 Index",callback_data:"market:index"}],[{text:"••• Thêm",callback_data:"hub:more"}]]};}\nconst moreKeyboard=()=>({inline_keyboard:[[{text:"🩺 Hệ thống",callback_data:"status"},{text:"🧠 AI Co-engineer",callback_data:"claude:status"}],[{text:"⬅️ Hub",callback_data:"menu"}]]});\nconst signalKeyboard=()=>({inline_keyboard:[[{text:"💱 Forex",callback_data:"market:forex"},{text:"🪙 Crypto",callback_data:"market:crypto"}],[{text:"🥇 Metal",callback_data:"market:metal"},{text:"📊 Index Cash",callback_data:"market:index"}],[{text:"⬅️ Hub",callback_data:"menu"}]]});\nconst marketKeyboard=g=>({inline_keyboard:[[{text:"🔍 Quét "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`signal:scan:${g}`},{text:"📚 Live "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`live:${g}`}],[{text:"🎯 Từng Symbol",callback_data:`symbols:${g}:0`}],[{text:"⬅️ Signal",callback_data:"signal"},{text:"🏠 Hub",callback_data:"menu"}]]});\nconst scanKeyboard=g=>({inline_keyboard:[[{text:"🔄 Quét lại "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`signal:scan:${g}`},{text:"📚 Live "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`live:${g}`}],[{text:"🎯 Symbol "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`symbols:${g}:0`}],[{text:"⬅️ "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`market:${g}`},{text:"🏠 Hub",callback_data:"menu"}]]});\nconst liveGroupKeyboard=g=>({inline_keyboard:[[{text:"🔄 Refresh "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`live:${g}`},{text:"📡 Quét "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`signal:scan:${g}`}],[{text:"🎯 Symbol "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`symbols:${g}:0`}],[{text:"⬅️ "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`market:${g}`},{text:"🏠 Hub",callback_data:"menu"}]]});\n'''
s=s[:start]+newkeys+s[end:]
# add symbol helpers before setupCard
needle='function setupCard(a,i=0)'
helpers='''function symbolResultText(g,a){const q=a?.analysisQuote||a?.quote||{},price=Number(q?.price??a?.currentPrice??a?.entry),age=Number(q?.quoteAgeSec),src=q?.source||a?.source||"—",fresh=q?.fresh===false?"🔴 STALE":"🟢 FRESH",L=[`${groupName(g)} • ${a?.symbol||"—"}`,"━━━━━━━━━━━━",`💵 Giá: ${fmt(price)}`,`📡 ${src} • ${fresh}${Number.isFinite(age)?` • ${Math.round(age)}s`:""}`,""];L.push(setupCard(a)||`⚪ ${a?.reason||"Chưa có setup"}`);return L.join("\\n");}\nfunction symbolPageKeyboard(g,symbols,page=0){const per=12,total=Math.max(1,Math.ceil(symbols.length/per)),pg=Math.max(0,Math.min(total-1,Number(page)||0)),slice=symbols.slice(pg*per,(pg+1)*per),rows=[];for(let i=0;i<slice.length;i+=2)rows.push(slice.slice(i,i+2).map(x=>({text:x,callback_data:`symbol:${g}:${x}`})));const nav=[];if(pg>0)nav.push({text:"◀️",callback_data:`symbols:${g}:${pg-1}`});nav.push({text:`${pg+1}/${total}`,callback_data:`symbols:${g}:${pg}`});if(pg<total-1)nav.push({text:"▶️",callback_data:`symbols:${g}:${pg+1}`});rows.push(nav,[{text:"⬅️ "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`market:${g}`},{text:"🏠 Hub",callback_data:"menu"}]);return {inline_keyboard:rows};}\n'''
if needle not in s: raise SystemExit('setupCard hub missing')
s=s.replace(needle,helpers+needle)
# handled callbacks
old='handled=["prop","prop:setup","prop:hyro","prop:orders","prop:risk","prop:connect","menu","hub:more","signal","signal:top","symbols","books","live","status"].includes(cb)||cb?.startsWith("prop:wiz:")||cb?.startsWith("signal:scan:")||cb?.startsWith("live:")||text==="/start"||text==="/menu"'
new='handled=["prop","prop:setup","prop:hyro","prop:orders","prop:risk","prop:connect","menu","hub:more","signal","status"].includes(cb)||cb?.startsWith("prop:wiz:")||cb?.startsWith("market:")||cb?.startsWith("signal:scan:")||cb?.startsWith("live:")||cb?.startsWith("symbols:")||cb?.startsWith("symbol:")||text==="/start"||text==="/menu"'
if old not in s: raise SystemExit('handled block missing')
s=s.replace(old,new)
# replace signal/top/live/symbol global handler segment
old='''if(cb==="menu"||text==="/start"||text==="/menu"){const x=await hubText(env);await sendText(env,x.text,chatId,x.kb);return json({ok:true,version:VERSION,ui:UI_REV});}if(cb==="hub:more"){await sendText(env,"••• TIỆN ÍCH\\n━━━━━━━━━━━━\\nCác công cụ ít dùng hơn:",chatId,moreKeyboard());return json({ok:true});}if(cb==="signal"){await sendText(env,"📡 SIGNAL CENTER\\n━━━━━━━━━━━━\\n⚡ Quét dữ liệu mới theo từng thị trường\\n🔥 Top Setup = cơ hội nổi bật nhất\\n🔎 Symbol = kiểm tra riêng một mã\\n\\nChọn tác vụ:",chatId,signalKeyboard());return json({ok:true,ui:UI_REV});}if(cb==="signal:top"){await sendText(env,"⏳ Đang quét 4 thị trường để xếp Top Setup…",chatId);const h=await engineJson("/hub",req,env);await sendText(env,topText(h),chatId,signalKeyboard());return json({ok:true});}if(cb?.startsWith("signal:scan:")){const g=cb.split(":").at(-1);await sendText(env,`⏳ ${groupName(g)} • đang lấy dữ liệu mới…`,chatId);const r=await engineJson(`/run-now?group=${g}`,req,env);await sendText(env,scanText(g,r),chatId,scanKeyboard(g));return json({ok:true,group:g});}if(cb==="live"||cb==="books"){await sendText(env,"📚 LIVE CENTER\\n━━━━━━━━━━━━\\nChọn đúng thị trường cần xem. Mỗi nút chỉ refresh P/L của thị trường đó, không gọi các market khác.",chatId,liveMarketKeyboard());return json({ok:true});}if(cb?.startsWith("live:")){const g=cb.split(":").at(-1);await sendText(env,`⏳ ${groupName(g)} • refresh P/L riêng…`,chatId);const b=await engineJson(`/books?group=${g}`,req,env);await sendText(env,booksText(b,g),chatId,liveGroupKeyboard(g));return json({ok:true,group:g});}if(cb==="symbols"){await sendText(env,"🔎 SYMBOL SCANNER\\n━━━━━━━━━━━━\\nChọn thị trường, sau đó chọn đúng mã cần phân tích:",chatId,symbolMarketKeyboard());return json({ok:true});}'''
new='''if(cb==="menu"||text==="/start"||text==="/menu"){const x=await hubText(env);await sendText(env,x.text,chatId,x.kb);return json({ok:true,version:VERSION,ui:UI_REV});}if(cb==="hub:more"){await sendText(env,"••• TIỆN ÍCH\\n━━━━━━━━━━━━\\nKhông còn nút quét/Live dùng chung nhiều thị trường.",chatId,moreKeyboard());return json({ok:true});}if(cb==="signal"){await sendText(env,"📡 SIGNAL CENTER\\n━━━━━━━━━━━━\\nMỗi thị trường có Quét • Live • Symbol riêng.\\nKhông có quét chung hoặc Live chung.",chatId,signalKeyboard());return json({ok:true,ui:UI_REV});}if(cb?.startsWith("market:")){const g=cb.split(":").at(-1);await sendText(env,`${groupName(g)} • TRUNG TÂM\\n━━━━━━━━━━━━\\nChỉ thao tác dữ liệu của ${groupName(g).replace(/^[^ ]+ /,"")}.`,chatId,marketKeyboard(g));return json({ok:true,group:g});}if(cb?.startsWith("signal:scan:")){const g=cb.split(":").at(-1);await sendText(env,`⏳ ${groupName(g)} • chỉ quét thị trường này…`,chatId);const r=await engineJson(`/run-now?group=${g}`,req,env);await sendText(env,scanText(g,r),chatId,scanKeyboard(g));return json({ok:true,group:g});}if(cb?.startsWith("live:")){const g=cb.split(":").at(-1);await sendText(env,`⏳ ${groupName(g)} • chỉ refresh Live thị trường này…`,chatId);const b=await engineJson(`/books?group=${g}`,req,env);await sendText(env,booksText(b,g),chatId,liveGroupKeyboard(g));return json({ok:true,group:g});}if(cb?.startsWith("symbols:")){const parts=cb.split(":"),g=parts[1],page=Number(parts[2]||0),d=await engineJson(`/symbols?group=${g}`,req,env),symbols=Array.isArray(d?.symbols)?d.symbols:[];await sendText(env,`🎯 ${groupName(g)} • SYMBOL\\n━━━━━━━━━━━━\\nChọn một mã. Mỗi mã sẽ lấy giá cụ thể trước khi phân tích.`,chatId,symbolPageKeyboard(g,symbols,page));return json({ok:true,group:g,page});}if(cb?.startsWith("symbol:")){const parts=cb.split(":"),g=parts[1],sym=parts[2];await sendText(env,`⏳ ${sym} • đang lấy giá mới + phân tích riêng…`,chatId);const a=await engineJson(`/analyze?symbol=${encodeURIComponent(sym)}`,req,env);await sendText(env,symbolResultText(g,a),chatId,{inline_keyboard:[[{text:"🔄 Quét lại "+sym,callback_data:`symbol:${g}:${sym}`},{text:"📚 Live "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`live:${g}`}],[{text:"⬅️ Symbol",callback_data:`symbols:${g}:0`},{text:"🏠 Hub",callback_data:"menu"}]]});return json({ok:true,group:g,symbol:sym});}'''
if old not in s: raise SystemExit('hub handler segment missing')
s=s.replace(old,new)
# status must not expose global Live button
s=s.replace('{inline_keyboard:[[{text:"📡 Signal",callback_data:"signal"},{text:"📚 Live",callback_data:"live"}],[{text:"🏠 Hub",callback_data:"menu"}]]}', '{inline_keyboard:[[{text:"💱 Forex",callback_data:"market:forex"},{text:"🪙 Crypto",callback_data:"market:crypto"}],[{text:"🥇 Metal",callback_data:"market:metal"},{text:"📊 Index",callback_data:"market:index"}],[{text:"🏠 Hub",callback_data:"menu"}]]}')
p.write_text(s)

# DUAL AI: focus Claude on Forex + isolated Hub/source review.
p=Path('cloudflare-worker/dual-ai-intervention.js'); s=p.read_text()
s=s.replace('const REVIEW_REV="METAL_INDEX_CASH_R1";','const REVIEW_REV="FOREX_MARKET_ISOLATION_R4";')
s=s.replace('METAL + INDEX CASH QUALITY IS THE FIRST PRIORITY FOR THIS REVIEW.', 'FOREX ENTRY QUALITY AND MARKET-ISOLATED HUB ARE THE FIRST PRIORITY FOR THIS REVIEW. Audit why Forex produces too few MARKET_SIGNAL recommendations. Inspect normalized currency strength, London/New York session routing, HTF pass, M15 location, M5 trigger, fresh quote usage, structural RR and duplicated gates. A valid Forex MARKET_SIGNAL must use a fresh explicit analysis quote, never a stale closed M15 bar. Do not weaken hard news/freshness/structural SL.\n\nMETAL + INDEX CASH QUALITY REMAINS IMPORTANT.')
s=s.replace('Perform METAL_INDEX_CASH_R1 first, then Forex and compact Hub UX sanity review.', 'Perform FOREX_MARKET_ISOLATION_R4 first. Review the new per-market Hub callbacks and Forex R4 thresholds, then Metal/Index/Crypto isolation sanity.')
s=s.replace('lastAction:"METAL_INDEX_CASH_R1_AND_SYSTEM"','lastAction:"FOREX_MARKET_ISOLATION_R4"')
p.write_text(s)

# RELEASE
p=Path('cloudflare-worker/index.js'); s=p.read_text().replace('const VERSION="V77.18.35",SERVICE="Trading V77.18.35 Verified Index Pricing";','const VERSION="V77.18.36",SERVICE="Trading V77.18.36 Market Isolation + Forex R4";').replace('const RELEASE_NAME="Verified Index Pricing";','const RELEASE_NAME="Market Isolation + Forex R4";'); p.write_text(s)
print('V771836_PATCH_OK')
