from pathlib import Path
import re

# V77.18.29 — comprehensive live P/L patch. Incremental only; no KV reset.

# ---------- PROP / Hyro ----------
p=Path('cloudflare-worker/index.js'); s=p.read_text()
s=s.replace('const VERSION="V77.18.25",SERVICE="Trading V77.18.25 Hyro Method + Hub UX";','const VERSION="V77.18.29",SERVICE="Trading V77.18.29 Live PnL + Unified UX";')
s=s.replace('const RELEASE_NAME="Hyro Method + Hub UX";','const RELEASE_NAME="Live PnL + Unified UX";')
old='function posLine(p,i){const side=p.side==="Buy"?"BUY":"SELL";return `${i+1}. ${p.symbol} ${side} | P/L ${money(p.unrealisedPnl)}\\nEntry ${p.avgPrice} | SL ${p.stopLoss||"—"} | TP ${p.takeProfit||"—"}`;}'
new='function posPnlMovePct(p){const e=Number(p?.avgPrice||0),m=Number(p?.markPrice||0);if(!(e>0&&m>0))return 0;const raw=(m-e)/e*100;return p?.side==="Sell"?-raw:raw;}\nfunction posLine(p,i,equity=0){const sd=p.side==="Buy"?"BUY":"SELL",pnl=Number(p.unrealisedPnl||0),move=posPnlMovePct(p),eqPct=Number(equity)>0?pnl/Number(equity)*100:0,icon=pnl>0?"🟢":pnl<0?"🔴":"⚪";return `${i+1}. ${icon} ${p.symbol} ${sd}\\n💵 P/L ${money(pnl)} • ${eqPct>=0?"+":""}${eqPct.toFixed(2)}% vốn\\n📍 Entry ${p.avgPrice} → Mark ${p.markPrice||"—"} • Move ${move>=0?"+":""}${move.toFixed(2)}%\\n🛑 SL ${p.stopLoss||"—"} • 🏁 TP ${p.takeProfit||"—"}`;}'
if old not in s: raise SystemExit('index posLine target missing')
s=s.replace(old,new)
old='async function positionsText(env){env=await propEnv(env);const c=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env),kb=propKeyboard(c.manualPaused,cfg.mode);return {text:t.connected?`📈 HYRO • VỊ THẾ\\n${t.positions.length?t.positions.map(posLine).join("\\n\\n"):"Không có vị thế."}`:`📈 Hyro • Telemetry ${t.reason||"OFF"}`,kb};}'
new='async function positionsText(env){env=await propEnv(env);const c=await getHyroControl(env),cfg=hyroExecutionConfig(env),t=await getHyroTelemetry(env),kb=propKeyboard(c.manualPaused,cfg.mode);if(!t.connected)return {text:`📈 HYRO • TELEMETRY ${t.reason||"OFF"}`,kb};const total=Number(t.totalUnrealised||0),equity=Number(t.equity||0),pct=equity>0?total/equity*100:0,icon=total>0?"🟢":total<0?"🔴":"⚪";return {text:["📈 HYRO • VỊ THẾ LIVE","━━━━━━━━━━━━",`${icon} Tổng P/L mở ${money(total)} • ${pct>=0?"+":""}${pct.toFixed(2)}% vốn`,`💰 Equity ${cash(equity)} • Vị thế ${t.positions.length}`,"",t.positions.length?t.positions.map((p,i)=>posLine(p,i,equity)).join("\\n\\n"):"⚪ Không có vị thế đang chạy.","","🔄 Bấm Vị thế để refresh giá/P&L mới nhất."].join("\\n"),kb};}'
if old not in s: raise SystemExit('index positionsText target missing')
s=s.replace(old,new)
p.write_text(s)

# ---------- Signal engine live books ----------
p=Path('cloudflare-worker/engine-v77168.js'); s=p.read_text()
old='function toPos(sig,discoveredBy="SCAN"){const tp=Number.isFinite(Number(sig.tp2))?sig.tp2:sig.tp1;return {id:sig.symbol+"-"+Date.now(),symbol:sig.symbol,side:sig.side,entry:sig.entry,sl:sig.sl,tp,tp1:sig.tp1,tp2:sig.tp2,targetRR:sig.targetRR,origin:sig.action,discoveredBy,status:"ACTIVE",openedAt:Date.now(),createdAt:Date.now(),engineOpened:sig.engine,engine:sig.engine,source:sig.quote?.source,executionVerified:true,executionAuthority:sig.quote?.source||"CANONICAL_CRYPTO"};}'
new='function toPos(sig,discoveredBy="SCAN"){const tp=Number.isFinite(Number(sig.tp2))?sig.tp2:sig.tp1;return {id:sig.symbol+"-"+Date.now(),symbol:sig.symbol,side:sig.side,entry:sig.entry,sl:sig.sl,tp,tp1:sig.tp1,tp2:sig.tp2,targetRR:sig.targetRR,origin:sig.action,discoveredBy,status:"ACTIVE",openedAt:Date.now(),createdAt:Date.now(),engineOpened:sig.engine,engine:sig.engine,source:sig.quote?.source,executionVerified:true,executionAuthority:sig.quote?.source||"CANONICAL_CRYPTO",quantity:Number(sig.risk?.quantity)||null,riskUsd:Number(sig.risk?.riskUsd)||CONFIG.defaultRiskUsd};}'
if old not in s: raise SystemExit('engine toPos target missing')
s=s.replace(old,new)
marker='async function saveBooks(env,b){b.updatedAt=Date.now();for(const g of Object.keys(GROUPS))b[g].watch=[];await env.TRADING_STATE.put(CONFIG.keys.books,JSON.stringify(b));}'
helper='''async function saveBooks(env,b){b.updatedAt=Date.now();for(const g of Object.keys(GROUPS))b[g].watch=[];await env.TRADING_STATE.put(CONFIG.keys.books,JSON.stringify(b));}\nfunction bookQty(p){const q=Number(p?.quantity??p?.qty);if(Number.isFinite(q)&&q>0)return {qty:q,estimated:false};const e=Number(p?.entry),sl=Number(p?.sl),risk=Number(p?.riskUsd??CONFIG.defaultRiskUsd),d=Math.abs(e-sl);return e>0&&sl>0&&risk>0&&d>0?{qty:risk/d,estimated:true}:{qty:null,estimated:true};}\nasync function liveBookQuote(g,p,env){try{if(g==="crypto")return await cryptoExecutionQuote(p.symbol);if(g==="forex"||g==="metal")return await tdQuote(p.symbol,env);if(g==="future"){const a=await recentFutureScanAnalysis(p.symbol,env),q=a?.quote||a?.analysisQuote,price=Number(a?.currentPrice??q?.price);return price>0?{price,source:q?.source||a?.source||"Massive recent"}:null;}}catch{}return null;}\nfunction enrichBookPosition(g,p,q){const o={...p},px=Number(q?.price),e=Number(p.entry),dir=p.side==="SHORT"?-1:1;if(!(px>0&&e>0))return o;o.currentPrice=px;o.liveAt=Date.now();o.liveSource=q?.source||null;o.pnlPct=(px-e)/e*100*dir;if(p.status!=="PENDING"){const z=bookQty(p);if(z.qty){o.pnlUsd=(px-e)*dir*z.qty;o.pnlUsdEstimated=z.estimated||g!=="crypto";}}return o;}\nasync function getBooksLive(env){const b=await getBooks(env),o=JSON.parse(JSON.stringify(b)),jobs=[];for(const g of Object.keys(GROUPS))for(const k of ["marketActive","limitActive","limitPending"])for(let i=0;i<(o[g]?.[k]||[]).length;i++)jobs.push((async()=>{const p=o[g][k][i],q=await liveBookQuote(g,p,env);o[g][k][i]=enrichBookPosition(g,p,q);})());await Promise.all(jobs);o.liveRefreshedAt=Date.now();return o;}'''
if marker not in s: raise SystemExit('engine saveBooks marker missing')
s=s.replace(marker,helper)
old='function livePositionLine(p){const kind=p.status==="PENDING"?"LIMIT CHỜ":p.origin==="LIMIT"?"LIMIT KHỚP":"MARKET";return kind+" • "+posLine(p)+" • nguồn "+orderSourceText(p.discoveredBy);}'
new='function livePositionLine(p){const kind=p.status==="PENDING"?"LIMIT CHỜ":p.origin==="LIMIT"?"LIMIT KHỚP":"MARKET",pct=Number(p.pnlPct),usd=Number(p.pnlUsd),live=Number.isFinite(pct)?`${pct>=0?"🟢":"🔴"} ${pct>=0?"+":""}${pct.toFixed(2)}%${Number.isFinite(usd)?` • ${p.pnlUsdEstimated?"~":""}${usd>=0?"+":""}$${usd.toFixed(2)}`:""}`:p.status==="PENDING"?"🟡 chưa khớp":"⚪ chờ refresh";return `${kind} • ${p.symbol} ${sideText(p.side)} • ${live} • E ${fmtPx(p.entry)}${p.currentPrice?` → ${fmtPx(p.currentPrice)}`:""} • SL ${fmtPx(p.sl)} • TP ${fmtPx(p.tp)}`;}'
if old not in s: raise SystemExit('engine livePositionLine target missing')
s=s.replace(old,new)
s=s.replace('const run=await runGroup(group,env,"GROUP_MANUAL"),books=await getBooks(env);return sendText(env,summary(group,books,run),chatId,groupKeyboard(group,run));','const run=await runGroup(group,env,"GROUP_MANUAL"),books=await getBooksLive(env);return sendText(env,summary(group,books,run),chatId,groupKeyboard(group,run));')
s=s.replace('else if(cb==="books")await sendText(env,booksSummary(await getBooks(env)),chatId,baseKeyboard());','else if(cb==="books")await sendText(env,booksSummary(await getBooksLive(env)),chatId,{inline_keyboard:[[{text:"🔄 Refresh P/L",callback_data:"books"},{text:"📡 Signal",callback_data:"signal"}],[{text:"🏦 Hyro",callback_data:"prop"},{text:"🏠 Hub",callback_data:"menu"}]]});')
s=s.replace('if(p==="/books"||p==="/orders")return json(await getBooks(env));','if(p==="/books"||p==="/orders")return json(await getBooksLive(env));')
old='function signalEventText(kind,p,extra={}){const group=extra.group||"crypto",side=sideText(p?.side),entry=fmtPx(p?.entry),sl=fmtPx(p?.sl),tp1=fmtPx(p?.tp1),tp2=fmtPx(p?.tp2||p?.tp),rr=Number(p?.targetRR);const head=kind==="LIMIT_FILLED"?"🔵 LIMIT KHỚP • ACTIVE":kind==="TP"?"✅ TP DONE":kind==="SL"?"🛑 SL HIT":kind==="LIMIT_NEW"?"🟡 LIMIT MỚI • ĐANG CHỜ":"🟢 MARKET MỚI • ACTIVE";const L=[head,groupTitle(group)+" • "+(p?.symbol||"—")+" • "+side,"━━━━━━━━━━━━━━"];if(kind==="TP"||kind==="SL"){L.push("📍 Entry "+entry,"🏁 Close "+fmtPx(extra.closePrice));}else{L.push("🎯 Entry "+entry,"🛡 SL "+sl,"💰 TP1 "+tp1+" • TP2 "+tp2+(Number.isFinite(rr)?" • RR "+rr.toFixed(2):""));}if(p?.discoveredBy)L.push("⚙️ "+orderSourceText(p.discoveredBy));return L.join("\\n");}'
new='function signalEventText(kind,p,extra={}){const group=extra.group||"crypto",side=sideText(p?.side),entry=fmtPx(p?.entry),sl=fmtPx(p?.sl),tp1=fmtPx(p?.tp1),tp2=fmtPx(p?.tp2||p?.tp),rr=Number(p?.targetRR);const head=kind==="LIMIT_FILLED"?"🔵 LIMIT KHỚP • LIVE":kind==="TP"?"✅ TP DONE":kind==="SL"?"🛑 SL HIT":kind==="LIMIT_NEW"?"🟡 LIMIT MỚI • ĐANG CHỜ":"🟢 MARKET • LIVE";const L=[head,groupTitle(group)+" • "+(p?.symbol||"—")+" • "+side,"━━━━━━━━━━━━━━"];if(kind==="TP"||kind==="SL"){const mv=Number(extra.closePrice)>0&&Number(p?.entry)>0?(Number(extra.closePrice)-Number(p.entry))/Number(p.entry)*100*(p.side==="SHORT"?-1:1):null;L.push("📍 Entry "+entry,"🏁 Close "+fmtPx(extra.closePrice)+(Number.isFinite(mv)?` • ${mv>=0?"+":""}${mv.toFixed(2)}%`:""));}else{L.push("🎯 Entry "+entry,"🛡 SL "+sl,"💰 TP1 "+tp1+" • TP2 "+tp2+(Number.isFinite(rr)?" • RR "+rr.toFixed(2):""));if(kind!=="LIMIT_NEW")L.push("🔄 Mở 📚 Live Orders để refresh P/L % + USD");}if(p?.discoveredBy)L.push("⚙️ "+orderSourceText(p.discoveredBy));return L.join("\\n");}'
if old not in s: raise SystemExit('engine signalEventText target missing')
s=s.replace(old,new)
p.write_text(s)

# ---------- Hub visual ----------
p=Path('cloudflare-worker/hub-v77171.js'); s=p.read_text()
s=s.replace('const VERSION="V77.18.27",UI_REV="HUB-R3-SIGNAL",SERVICE="Trading V77.18.27 • Signal UX R3";','const VERSION="V77.18.29",UI_REV="HUB-R4-LIVE-PNL",SERVICE="Trading V77.18.29 • Unified Live PnL UX";')
old='function booksText(b){const L=["📚 LIVE ORDERS","━━━━━━━━━━━━"];let n=0;for(const g of ["crypto","forex","metal","future"]){const x=b?.[g]||{},rows=[...(x.marketActive||[]),...(x.limitActive||[]),...(x.limitPending||[])];if(!rows.length)continue;L.push("",groupName(g));for(const p of rows){n++;L.push(`${p.status==="PENDING"?"🟡":"🟢"} ${p.symbol} • ${side(p.side)}`,`   E ${fmt(p.entry)} • SL ${fmt(p.sl)} • TP ${fmt(p.tp)}`);}}if(!n)L.push("","⚪ Hiện chưa có lệnh live.");L.push("","━━━━━━━━━━━━",`Tổng: ${n} lệnh`);return L.join("\\n");}'
new='function booksText(b){const L=["📚 LIVE ORDERS • REALTIME P/L","━━━━━━━━━━━━"];let n=0,a=0,w=0;for(const g of ["crypto","forex","metal","future"]){const x=b?.[g]||{},rows=[...(x.marketActive||[]),...(x.limitActive||[]),...(x.limitPending||[])];if(!rows.length)continue;L.push("",groupName(g));for(const p of rows){n++;const pending=p.status==="PENDING",pct=Number(p.pnlPct),usd=Number(p.pnlUsd),icon=pending?"🟡":Number.isFinite(pct)&&pct>0?"🟢":Number.isFinite(pct)&&pct<0?"🔴":"⚪",kind=pending?"LIMIT CHỜ":p.origin==="LIMIT"?"LIMIT KHỚP":"MARKET";pending?w++:a++;L.push(`${icon} ${p.symbol} • ${side(p.side)} • ${kind}`,`   📍 ${fmt(p.entry)}${p.currentPrice?` → ${fmt(p.currentPrice)}`:""}`,pending?"   ⏳ Chưa khớp • chưa tính P/L":`   💵 P/L ${Number.isFinite(pct)?(pct>=0?"+":"")+pct.toFixed(2)+"%":"—"}${Number.isFinite(usd)?` • ${p.pnlUsdEstimated?"~":""}${usd>=0?"+":""}$${usd.toFixed(2)}`:""}`,`   🛑 SL ${fmt(p.sl)} • 🏁 TP ${fmt(p.tp)}`);}}if(!n)L.push("","⚪ Hiện chưa có lệnh live.");L.push("","━━━━━━━━━━━━",`Active ${a} • Pending ${w} • Tổng ${n}`,`🕒 ${b?.liveRefreshedAt?new Date(b.liveRefreshedAt).toISOString():"chưa refresh"}`,"ℹ️ ~USD = ước tính khi broker size không có.");return L.join("\\n");}'
if old not in s: raise SystemExit('hub booksText target missing')
s=s.replace(old,new)
p.write_text(s)

print('PATCH_V771829_OK')
