from pathlib import Path
p=Path('cloudflare-worker/engine-v77168.js')
s=p.read_text()
s=s.replace('version: "V77.16.14",','version: "V77.16.15",').replace('service: "Trading V77.16.14 Split Market Live",','service: "Trading V77.16.15 Native Index Failover",')
# Index scans must not be blocked before Massive is tried.
s=s.replace('async function ensureTdBudget(group,env){\n  const required=tdPlannedCost(group);','async function ensureTdBudget(group,env){\n  if(group==="index"&&env.MASSIVE_API_KEY)return {ok:true,required:0,left:memory.tdCreditsLeft,primary:"MASSIVE"};\n  const required=tdPlannedCost(group);')
old='''async function tdBatchCandles(symbols,interval,env,outputsize=CONFIG.candleOutputSize){\n  const requested=[...new Set(symbols.map(norm))];if(requested.length&&requested.every(x=>marketType(x)==="index")&&env.MASSIVE_API_KEY){const m=await massiveIndexBatchCandles(requested,interval,env,outputsize);if(m.size)return m;}const provider=requested.map(tdSymbol),out=new Map();if(!requested.length)return out;\n  const p=await tdFetch("time_series",{symbol:provider.join(","),interval,outputsize:String(outputsize),order:"ASC",timezone:"UTC"},env);\n  if(Array.isArray(p?.values)){const c=tdCandlesFromNode(p,interval);if(c)out.set(requested[0],c);return out;}\n  const lookup=new Map(provider.map((x,i)=>[norm(x),requested[i]]));\n  for(const [key,raw] of Object.entries(p||{})){\n    const node=raw?.data?.values?raw.data:raw,c=tdCandlesFromNode(raw,interval);if(!c)continue;\n    const canonical=lookup.get(norm(node?.meta?.symbol||key));if(canonical)out.set(canonical,c);\n  }\n  return out;\n}'''
new='''async function tdSingleIndexCandles(symbol,interval,env,outputsize=CONFIG.candleOutputSize){\n  const s=norm(symbol),ps=INDEX_PROVIDER[s]||s,p=await tdFetch("time_series",{symbol:ps,interval,outputsize:String(outputsize),order:"ASC",timezone:"UTC"},env),c=tdCandlesFromNode(p,interval);\n  if(!c?.length)throw new Error(`Twelve Data index candles unavailable ${s}/${ps}`);return c;\n}\nasync function tdBatchCandles(symbols,interval,env,outputsize=CONFIG.candleOutputSize){\n  const requested=[...new Set(symbols.map(norm))],out=new Map();if(!requested.length)return out;\n  if(requested.every(x=>marketType(x)==="index")){\n    if(env.MASSIVE_API_KEY){const m=await massiveIndexBatchCandles(requested,interval,env,outputsize);for(const [k,v] of m)if(v?.length)out.set(k,v);}\n    const missing=requested.filter(s=>!out.has(s));\n    if(missing.length&&env.TWELVE_DATA_API_KEY){await Promise.all(missing.map(async s=>{try{const c=await tdSingleIndexCandles(s,interval,env,outputsize);if(c.length)out.set(s,c);}catch{}}));}\n    return out;\n  }\n  const provider=requested.map(tdSymbol),p=await tdFetch("time_series",{symbol:provider.join(","),interval,outputsize:String(outputsize),order:"ASC",timezone:"UTC"},env);\n  if(Array.isArray(p?.values)){const c=tdCandlesFromNode(p,interval);if(c)out.set(requested[0],c);return out;}\n  const lookup=new Map(provider.map((x,i)=>[norm(x),requested[i]]));for(const [key,raw] of Object.entries(p||{})){const node=raw?.data?.values?raw.data:raw,c=tdCandlesFromNode(raw,interval);if(!c)continue;const canonical=lookup.get(norm(node?.meta?.symbol||key));if(canonical)out.set(canonical,c);}return out;\n}'''
if old not in s: raise SystemExit('tdBatchCandles block not found')
s=s.replace(old,new)
old='''async function massiveIndexQuote(symbol,env){const s=norm(symbol),ticker=MASSIVE_INDEX_PROVIDER[s];if(!ticker)throw new Error("Unsupported Massive index");const c=await massiveIndexCandles(s,"5min",env,30),last=c.at(-1);if(!last)throw new Error("Massive index quote unavailable");const age=Math.max(0,nowSec()-last.timestamp-300);return {source:"Massive Indices",requestedSymbol:s,providerSymbol:ticker,price:last.close,providerTimestamp:last.timestamp,quoteAgeSec:age,fresh:age<=900,bid:null,ask:null,executionVerified:false,analysisOnly:true};}\nasync function tdQuote(symbol,env){\n  if(marketType(symbol)==="index"&&env.MASSIVE_API_KEY){try{return await massiveIndexQuote(symbol,env);}catch{}}\n  const ps=tdSymbol(symbol),p=await tdFetch("quote",{symbol:ps},env),price=num(p.close)??num(p.price);'''
new='''async function massiveIndexQuote(symbol,env){const s=norm(symbol),ticker=MASSIVE_INDEX_PROVIDER[s];if(!ticker)throw new Error("Unsupported Massive index");const j=await massiveIndexFetch("/v3/snapshot/indices",{ticker,limit:"10"},env),r=(j.results||[]).find(x=>x?.ticker===ticker&&!x?.error),price=num(r?.value);if(!(price>0))throw new Error(r?.message||r?.error||"Massive index snapshot unavailable");const ts=r?.last_updated?Math.floor(Number(r.last_updated)/1e9):null,age=ts?Math.max(0,nowSec()-ts):null;return {source:"Massive Indices Snapshot",requestedSymbol:s,providerSymbol:ticker,price,providerTimestamp:ts,quoteAgeSec:age,timeframe:r?.timeframe||null,marketStatus:r?.market_status||null,fresh:age==null?false:age<=900,bid:null,ask:null,executionVerified:false,analysisOnly:true};}\nasync function tdIndexQuote(symbol,env){const s=norm(symbol),ps=INDEX_PROVIDER[s]||s;try{const p=await tdFetch("price",{symbol:ps},env),price=num(p?.price);if(price>0)return {source:"Twelve Data Index Price",requestedSymbol:s,providerSymbol:ps,price,providerTimestamp:null,quoteAgeSec:null,fresh:true,bid:null,ask:null,executionVerified:false,analysisOnly:true};}catch{}const p=await tdFetch("quote",{symbol:ps},env),price=num(p.close)??num(p.price);if(!(price>0))throw new Error("TD index price invalid");const ts=parseTs(p.last_quote_at??p.timestamp??p.datetime),age=ts==null?null:Math.max(0,nowSec()-ts);return {source:"Twelve Data Index Quote",requestedSymbol:s,providerSymbol:ps,price,providerTimestamp:ts,quoteAgeSec:age,fresh:age==null?true:age<=900,bid:null,ask:null,executionVerified:false,analysisOnly:true};}\nasync function tdQuote(symbol,env){\n  if(marketType(symbol)==="index"){if(env.MASSIVE_API_KEY){try{return await massiveIndexQuote(symbol,env);}catch{}}if(env.TWELVE_DATA_API_KEY)return tdIndexQuote(symbol,env);throw new Error("No native index provider configured");}\n  const ps=tdSymbol(symbol),p=await tdFetch("quote",{symbol:ps},env),price=num(p.close)??num(p.price);'''
if old not in s: raise SystemExit('massiveIndexQuote block not found')
s=s.replace(old,new)
# Expose diagnostics for the 5 native index providers.
s=s.replace('providers:{forex:"Twelve Data analysis; MT5 broker quote required for execution",crypto:"Exchange-native analysis + exact canonical bid/ask execution",metal:"Twelve Data analysis; MT5 broker quote required for execution",index:"Twelve Data Index analysis; signal-only until broker execution authority exists"}', 'providers:{forex:"Twelve Data analysis; MT5 broker quote required for execution",crypto:"Exchange-native analysis + exact canonical bid/ask execution",metal:"Twelve Data analysis; MT5 broker quote required for execution",index:"Massive native index snapshot/OHLC primary + Twelve Data native index per-symbol fallback"}')
p.write_text(s)

p=Path('cloudflare-worker/index.js');s=p.read_text();s=s.replace('const VERSION="V77.18.33",SERVICE="Trading V77.18.33 Split Market Live";','const VERSION="V77.18.34",SERVICE="Trading V77.18.34 Native Index Failover";').replace('const RELEASE_NAME="Split Market Live UX";','const RELEASE_NAME="Native Index Failover";');p.write_text(s)
p=Path('cloudflare-worker/hub-v77171.js');s=p.read_text();s=s.replace('const VERSION="V77.18.33",UI_REV="HUB-R6-SPLIT-LIVE",SERVICE="Trading V77.18.33 • Split Market Live UX";','const VERSION="V77.18.34",UI_REV="HUB-R6-SPLIT-LIVE",SERVICE="Trading V77.18.34 • Native Index Failover";');p.write_text(s)
print('V771834_PATCH_OK')