from pathlib import Path

p=Path('cloudflare-worker/hub-v77171.js')
s=p.read_text()
s=s.replace('const VERSION="V77.18.31",UI_REV="HUB-R5-INDEX-CASH",SERVICE="Trading V77.18.31 • Metal + Index Cash UX";','const VERSION="V77.18.33",UI_REV="HUB-R6-SPLIT-LIVE",SERVICE="Trading V77.18.33 • Split Market Live UX";')
s=s.replace('{text:"📚 Lệnh",callback_data:"books"}', '{text:"📚 Live",callback_data:"live"}')
s=s.replace('[{text:"🔎 Từng Symbol",callback_data:"symbols"},{text:"📚 Lệnh Live",callback_data:"books"}]','[{text:"📚 Live theo thị trường",callback_data:"live"}],[{text:"🔎 Từng Symbol",callback_data:"symbols"}]')
s=s.replace('const scanKeyboard=g=>({inline_keyboard:[[{text:"🔄 Quét lại",callback_data:`signal:scan:${g}`},{text:"🔥 Top Setup",callback_data:"signal:top"}],[{text:"🔎 Symbol",callback_data:"symbols"},{text:"📚 Lệnh Live",callback_data:"books"}],[{text:"⬅️ Signal",callback_data:"signal"},{text:"🏠 Hub",callback_data:"menu"}]]});', 'const scanKeyboard=g=>({inline_keyboard:[[{text:"🔄 Quét lại",callback_data:`signal:scan:${g}`},{text:"📚 Live",callback_data:`live:${g}`}],[{text:"🔎 Symbol",callback_data:"symbols"},{text:"🔥 Top Setup",callback_data:"signal:top"}],[{text:"⬅️ Signal",callback_data:"signal"},{text:"🏠 Hub",callback_data:"menu"}]]});\nconst liveMarketKeyboard=()=>({inline_keyboard:[[{text:"💱 Forex Live",callback_data:"live:forex"},{text:"🪙 Crypto Live",callback_data:"live:crypto"}],[{text:"🥇 Metal Live",callback_data:"live:metal"},{text:"📊 Index Live",callback_data:"live:index"}],[{text:"⬅️ Signal",callback_data:"signal"},{text:"🏠 Hub",callback_data:"menu"}]]});\nconst liveGroupKeyboard=g=>({inline_keyboard:[[{text:"🔄 Refresh P/L",callback_data:`live:${g}`},{text:"📡 Quét "+groupName(g).replace(/^[^ ]+ /,""),callback_data:`signal:scan:${g}`}],[{text:"🔎 Symbol",callback_data:"symbols"},{text:"⬅️ Live",callback_data:"live"}],[{text:"🏠 Hub",callback_data:"menu"}]]});')
old='function booksText(b){const L=["📚 LIVE ORDERS • REALTIME P/L","━━━━━━━━━━━━"];let n=0,a=0,w=0;for(const g of ["crypto","forex","metal","index"]){const x=b?.[g]||{},rows=[...(x.marketActive||[]),...(x.limitActive||[]),...(x.limitPending||[])];if(!rows.length)continue;L.push("",groupName(g));for(const p of rows){n++;const pending=p.status==="PENDING",pct=Number(p.pnlPct),usd=Number(p.pnlUsd),icon=pending?"🟡":Number.isFinite(pct)&&pct>0?"🟢":Number.isFinite(pct)&&pct<0?"🔴":"⚪",kind=pending?"LIMIT CHỜ":p.origin==="LIMIT"?"LIMIT KHỚP":"MARKET";pending?w++:a++;L.push(`${icon} ${p.symbol} • ${side(p.side)} • ${kind}`,`   📍 ${fmt(p.entry)}${p.currentPrice?` → ${fmt(p.currentPrice)}`:""}`,pending?"   ⏳ Chưa khớp • chưa tính P/L":`   💵 P/L ${Number.isFinite(pct)?(pct>=0?"+":"")+pct.toFixed(2)+"%":"—"}${Number.isFinite(usd)?` • ${p.pnlUsdEstimated?"~":""}${usd>=0?"+":""}$${usd.toFixed(2)}`:""}`,`   🛑 SL ${fmt(p.sl)} • 🏁 TP ${fmt(p.tp)}`);}}if(!n)L.push("","⚪ Hiện chưa có lệnh live.");L.push("","━━━━━━━━━━━━",`Active ${a} • Pending ${w} • Tổng ${n}`,`🕒 ${b?.liveRefreshedAt?new Date(b.liveRefreshedAt).toISOString():"chưa refresh"}`,"ℹ️ ~USD = ước tính khi broker size không có.");return L.join("\\n");}'
new='function booksText(b,g){const L=[`📚 ${groupName(g)} • LIVE P/L`,`━━━━━━━━━━━━`],x=b?.[g]||{},rows=[...(x.marketActive||[]),...(x.limitActive||[]),...(x.limitPending||[])];let n=0,a=0,w=0;for(const p of rows){n++;const pending=p.status==="PENDING",pct=Number(p.pnlPct),usd=Number(p.pnlUsd),icon=pending?"🟡":Number.isFinite(pct)&&pct>0?"🟢":Number.isFinite(pct)&&pct<0?"🔴":"⚪",kind=pending?"LIMIT CHỜ":p.origin==="LIMIT"?"LIMIT KHỚP":"MARKET";pending?w++:a++;L.push("",`${icon} ${p.symbol} • ${side(p.side)} • ${kind}`,`📍 ${fmt(p.entry)}${p.currentPrice?` → ${fmt(p.currentPrice)}`:""}`,pending?"⏳ Chưa khớp • chưa tính P/L":`💵 P/L ${Number.isFinite(pct)?(pct>=0?"+":"")+pct.toFixed(2)+"%":"—"}${Number.isFinite(usd)?` • ${p.pnlUsdEstimated?"~":""}${usd>=0?"+":""}$${usd.toFixed(2)}`:""}`,`🛑 SL ${fmt(p.sl)} • 🏁 TP ${fmt(p.tp)}`);}if(!n)L.push("","⚪ Thị trường này hiện chưa có lệnh live.");L.push("","━━━━━━━━━━━━",`Active ${a} • Pending ${w} • Tổng ${n}`,`🕒 ${b?.liveRefreshedAt?new Date(b.liveRefreshedAt).toISOString():"chưa refresh"}`,"ℹ️ Chỉ refresh đúng thị trường này.");return L.join("\\n");}'
if old not in s: raise SystemExit('booksText old not found')
s=s.replace(old,new)
s=s.replace('["prop","prop:setup","prop:hyro","prop:orders","prop:risk","prop:connect","menu","hub:more","signal","signal:top","symbols","books","status"].includes(cb)', '["prop","prop:setup","prop:hyro","prop:orders","prop:risk","prop:connect","menu","hub:more","signal","signal:top","symbols","books","live","status"].includes(cb)')
s=s.replace('||cb?.startsWith("signal:scan:")', '||cb?.startsWith("signal:scan:")||cb?.startsWith("live:")')
s=s.replace('if(cb==="symbols"){await sendText(env,"🔎 SYMBOL SCANNER', 'if(cb==="live"||cb==="books"){await sendText(env,"📚 LIVE CENTER\\n━━━━━━━━━━━━\\nChọn đúng thị trường cần xem. Mỗi nút chỉ refresh P/L của thị trường đó, không gọi các market khác.",chatId,liveMarketKeyboard());return json({ok:true});}if(cb?.startsWith("live:")){const g=cb.split(":").at(-1);await sendText(env,`⏳ ${groupName(g)} • refresh P/L riêng…`,chatId);const b=await engineJson(`/books?group=${g}`,req,env);await sendText(env,booksText(b,g),chatId,liveGroupKeyboard(g));return json({ok:true,group:g});}if(cb==="symbols"){await sendText(env,"🔎 SYMBOL SCANNER')
oldbooks='if(cb==="books"){const b=await engineJson("/books",req,env);await sendText(env,booksText(b),chatId,{inline_keyboard:[[{text:"🔄 Làm mới",callback_data:"books"},{text:"📡 Signal",callback_data:"signal"}],[{text:"🏠 Hub",callback_data:"menu"}]]});return json({ok:true});}'
s=s.replace(oldbooks,'')
s=s.replace('{text:"📚 Lệnh",callback_data:"books"}', '{text:"📚 Live",callback_data:"live"}')
p.write_text(s)

p=Path('cloudflare-worker/engine-v77168.js')
s=p.read_text()
s=s.replace('version: "V77.16.13",','version: "V77.16.14",').replace('service: "Trading V77.16.13 Index Provider R2",','service: "Trading V77.16.14 Split Market Live",')
s=s.replace('function emptyBooks(){return {forex:emptyGroup(),crypto:emptyGroup(),metal:emptyGroup(),future:emptyGroup(),updatedAt:Date.now()};}','function emptyBooks(){return {forex:emptyGroup(),crypto:emptyGroup(),metal:emptyGroup(),index:emptyGroup(),updatedAt:Date.now()};}')
old='async function getBooksLive(env){const b=await getBooks(env),o=JSON.parse(JSON.stringify(b)),jobs=[];for(const g of Object.keys(GROUPS))for(const k of ["marketActive","limitActive","limitPending"])for(let i=0;i<(o[g]?.[k]||[]).length;i++)jobs.push((async()=>{const p=o[g][k][i],q=await liveBookQuote(g,p,env);o[g][k][i]=enrichBookPosition(g,p,q);})());await Promise.all(jobs);o.liveRefreshedAt=Date.now();return o;}'
new='async function getBooksLive(env,onlyGroup=null){const b=await getBooks(env),o=JSON.parse(JSON.stringify(b)),groups=onlyGroup&&GROUPS[onlyGroup]?[onlyGroup]:Object.keys(GROUPS),jobs=[];for(const g of groups)for(const k of ["marketActive","limitActive","limitPending"])for(let i=0;i<(o[g]?.[k]||[]).length;i++)jobs.push((async()=>{const p=o[g][k][i],q=await liveBookQuote(g,p,env);o[g][k][i]=enrichBookPosition(g,p,q);})());await Promise.all(jobs);o.liveRefreshedAt=Date.now();o.liveRefreshedGroup=onlyGroup||"all";return o;}'
if old not in s: raise SystemExit('getBooksLive old not found')
s=s.replace(old,new)
s=s.replace('if(p==="/books"||p==="/orders")return json(await getBooksLive(env));','if(p==="/books"||p==="/orders"){const g=u.searchParams.get("group");if(g&&!GROUPS[g])return json({ok:false,error:"invalid group"},400);return json(await getBooksLive(env,g||null));}')
s=s.replace('callback_data:"scan:future"','callback_data:"scan:index"')
s=s.replace('callback_data:"books"','callback_data:"live"')
s=s.replace('else if(cb==="books")await sendText(env,booksSummary(await getBooksLive(env)),chatId,{inline_keyboard:[[{text:"🔄 Refresh P/L",callback_data:"live"},{text:"📡 Signal",callback_data:"signal"}],[{text:"🏦 Hyro",callback_data:"prop"},{text:"🏠 Hub",callback_data:"menu"}]]});','else if(cb==="books"||cb==="live")await sendText(env,"📚 LIVE CENTER\\n\\nLive đã tách riêng theo từng thị trường trong Hub mới.",chatId,baseKeyboard());')
s=s.replace('/run-now?group=forex|crypto|metal|future','/run-now?group=forex|crypto|metal|index').replace('/analyze?symbol=BTCUSDT|EURUSD|XAUUSD|NQ|MNQ|ES|MES','/analyze?symbol=BTCUSDT|EURUSD|XAUUSD|NAS100|US30|US500|DEX|JP225').replace('/knowledge?symbol=NQ','/knowledge?symbol=NAS100')
p.write_text(s)

p=Path('cloudflare-worker/index.js'); s=p.read_text(); s=s.replace('const VERSION="V77.18.31",SERVICE="Trading V77.18.31 Metal + Index Cash Migration";','const VERSION="V77.18.33",SERVICE="Trading V77.18.33 Split Market Live";').replace('const RELEASE_NAME="Metal + Index Cash Migration";','const RELEASE_NAME="Split Market Live UX";'); p.write_text(s)

p=Path('.github/workflows/validate-cloudflare-v77.yml'); s=p.read_text(); s=s.replace("'V77.16.13'","'V77.16.14'").replace("'V77.18.31'","'V77.18.33'").replace("'Metal + Index Cash Migration'","'Split Market Live'").replace("'HUB-R5-INDEX-CASH'","'HUB-R6-SPLIT-LIVE'")
s=s.replace("console.log('V77.18.32 Index Provider R2 validation PASS');","for(const x of ['liveMarketKeyboard','liveGroupKeyboard','liveRefreshedGroup','/books?group='])if(!(hub+engine).includes(x))throw new Error('Split Live lock missing: '+x);\n          console.log('V77.18.33 Split Market Live validation PASS');")
p.write_text(s)
print('V771833_PATCH_OK')