from pathlib import Path

P=Path('signalhub-android/app/src/main/java/com/hanlinh/signalhub/SignalHubActivity.java')
G=Path('signalhub-android/app/build.gradle')
s=P.read_text()


def block(start,end,new):
    global s
    a=s.index(start)
    b=s.index(end,a)
    s=s[:a]+new+s[b:]

s=s.replace('private static final String APP_VERSION="3.16.0";','private static final String APP_VERSION="3.17.0";')
s=s.replace('private static final int BG=Color.rgb(2,6,10),PANEL=Color.rgb(7,14,21),PANEL2=Color.rgb(12,23,33),BORDER=Color.rgb(28,52,70);\n    private static final int TEXT=Color.rgb(242,248,252),MUTED=Color.rgb(123,148,166),GREEN=Color.rgb(48,232,159),RED=Color.rgb(255,76,102),YELLOW=Color.rgb(255,201,67),BLUE=Color.rgb(78,154,255),CYAN=Color.rgb(59,224,238);',
'''private static final int BG=Color.rgb(5,9,14),PANEL=Color.rgb(11,18,26),PANEL2=Color.rgb(16,27,38),BORDER=Color.rgb(31,48,63);\n    private static final int TEXT=Color.rgb(246,249,252),MUTED=Color.rgb(139,160,177),GREEN=Color.rgb(57,217,138),RED=Color.rgb(255,91,110),YELLOW=Color.rgb(246,200,95),BLUE=Color.rgb(110,168,254),CYAN=Color.rgb(75,215,230);''')

s=s.replace('private LinearLayout card(){LinearLayout c=column();c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackground(shape(PANEL,15,BORDER));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));c.setLayoutParams(p);return c;}',
'''private LinearLayout card(){LinearLayout c=column();c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(shape(PANEL,18,BORDER));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(p);return c;}''')
s=s.replace('private TextView chip(String s,int color){TextView v=tv(s,9,color,true);v.setPadding(dp(8),dp(5),dp(8),dp(5));v.setGravity(Gravity.CENTER);v.setBackground(shape(Color.argb(28,Color.red(color),Color.green(color),Color.blue(color)),9,color));return v;}',
'''private TextView chip(String s,int color){TextView v=tv(s,9,color,true);v.setPadding(dp(9),dp(5),dp(9),dp(5));v.setGravity(Gravity.CENTER);v.setBackground(shape(Color.argb(24,Color.red(color),Color.green(color),Color.blue(color)),10,Color.argb(150,Color.red(color),Color.green(color),Color.blue(color))));return v;}''')
s=s.replace('private Button button(String s,boolean selected,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(10);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(selected?BG:TEXT);b.setPadding(dp(8),0,dp(8),0);b.setMinHeight(0);b.setMinimumHeight(0);b.setStateListAnimator(null);b.setBackground(shape(selected?GREEN:PANEL2,11,selected?GREEN:BORDER));b.setOnClickListener(l);pressFeedback(b);return b;}',
'''private Button button(String s,boolean selected,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(11);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(selected?BG:TEXT);b.setPadding(dp(10),0,dp(10),0);b.setMinHeight(0);b.setMinimumHeight(0);b.setStateListAnimator(null);b.setBackground(shape(selected?CYAN:PANEL2,14,selected?CYAN:BORDER));b.setOnClickListener(l);pressFeedback(b);return b;}''')
s=s.replace('private void setBtn(Button b,boolean on){b.setTextColor(on?BG:TEXT);b.setBackground(shape(on?GREEN:PANEL2,11,on?GREEN:BORDER));}',
'''private void setBtn(Button b,boolean on){b.setTextColor(on?BG:TEXT);b.setBackground(shape(on?CYAN:PANEL2,14,on?CYAN:BORDER));}''')

insert='''    private View sectionHeader(String title,String sub,int color){LinearLayout c=column();c.setPadding(0,dp(8),0,dp(3));TextView t=tv(title,15,TEXT,true);c.addView(t);if(sub!=null&&!sub.isEmpty())c.addView(tv(sub,9,color,false));return c;}\n    private View levelBox(String label,String value,int color){LinearLayout c=column();c.setPadding(dp(10),dp(9),dp(10),dp(9));c.setBackground(shape(PANEL2,12,Color.TRANSPARENT));c.addView(tv(label,8,MUTED,true));TextView v=tv(value,12,color,true);v.setPadding(0,dp(2),0,0);c.addView(v);return c;}\n    private View miniStat(String label,String value,String sub,int color){LinearLayout c=column();c.setPadding(dp(13),dp(12),dp(13),dp(12));c.setBackground(shape(PANEL,16,BORDER));c.addView(tv(label,9,MUTED,true));c.addView(tv(value,22,TEXT,true));c.addView(tv(sub,9,color,false));return c;}\n    private View navItem(String key,String label,int icon){boolean on=screen.equals(key);LinearLayout c=column();c.setGravity(Gravity.CENTER);c.setPadding(dp(3),dp(5),dp(3),dp(4));c.setBackground(shape(on?PANEL2:PANEL,14,on?BORDER:Color.TRANSPARENT));ImageView im=new ImageView(this);im.setImageResource(icon);im.setColorFilter(on?CYAN:MUTED);im.setContentDescription(label);c.addView(im,new LinearLayout.LayoutParams(dp(21),dp(21)));TextView t=tv(label,9,on?TEXT:MUTED,on);t.setGravity(Gravity.CENTER);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(20));lp.setMargins(0,dp(3),0,0);c.addView(t,lp);c.setClickable(true);c.setOnClickListener(v->selectScreen(key));pressFeedback(c);return c;}\n    private void openSignalDetail(JSONObject s){style=s.optString("style",style).toUpperCase(Locale.US);screen="SIGNALS";detail=true;selectedSignal=s;signalControls.setVisibility(View.VISIBLE);paintControls();drawBottom();renderDetail(s,true);}\n    private View homeSignalRow(JSONObject s){LinearLayout c=card();String sym=s.optString("symbol","—"),st=s.optString("style","SCALP"),side=sideVi(s.optString("side",""));double e=s.optDouble("entry",0),px=priceFor(s,e);int col=side.equals("BUY")?GREEN:RED;LinearLayout h=row();LinearLayout names=column();names.addView(tv(sym,16,TEXT,true));names.addView(tv(st+" • "+orderDisplay(s,px),9,MUTED,true));h.addView(names,new LinearLayout.LayoutParams(0,-2,1f));h.addView(chip(side,col));c.addView(h);LinearLayout q=row();q.setPadding(0,dp(9),0,0);LinearLayout left=column();left.addView(tv("GIÁ HIỆN TẠI",8,MUTED,true));left.addView(tv(fmt(px),16,TEXT,true));q.addView(left,new LinearLayout.LayoutParams(0,-2,1f));LinearLayout right=column();right.setGravity(Gravity.END);right.addView(tv("ENTRY",8,MUTED,true));TextView ev=tv(fmt(e),12,orderColor(s,px),true);ev.setGravity(Gravity.END);right.addView(ev);q.addView(right,new LinearLayout.LayoutParams(0,-2,1f));c.addView(q);TextView state=tv(tradeStatusText(s,px),9,tradeStatusColor(s,px),true);state.setPadding(0,dp(7),0,0);c.addView(state);c.setClickable(true);c.setOnClickListener(v->openSignalDetail(s));pressFeedback(c);return c;}\n'''
s=s.replace('    private void buildUi(){',insert+'\n    private void buildUi(){',1)

block('    private void buildUi(){','    private void setStyle(String s){',r'''    private void buildUi(){
        LinearLayout root=column();root.setBackgroundColor(BG);
        LinearLayout head=column();head.setPadding(dp(16),dp(12),dp(16),dp(8));
        LinearLayout top=row();ImageView brand=new ImageView(this);brand.setImageResource(R.drawable.ic_signalhub);brand.setColorFilter(CYAN);brand.setContentDescription("SignalHub");LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(32),dp(32));bp.setMargins(0,0,dp(10),0);top.addView(brand,bp);
        LinearLayout titles=column();TextView logo=tv("SignalHub",20,TEXT,true);subtitle=tv("CRYPTO • 2 SCALP + 2 SWING",9,MUTED,false);titles.addView(logo);titles.addView(subtitle);top.addView(titles,new LinearLayout.LayoutParams(0,-2,1f));cryptoLive=chip("ĐANG KẾT NỐI",YELLOW);top.addView(cryptoLive);head.addView(top);
        signalControls=column();LinearLayout segment=row();segment.setPadding(dp(4),dp(4),dp(4),dp(4));segment.setBackground(shape(PANEL,16,BORDER));scalpBtn=button("SCALP",true,v->setStyle("SCALP"));swingBtn=button("SWING",false,v->setStyle("SWING"));LinearLayout.LayoutParams s1=new LinearLayout.LayoutParams(0,dp(40),1f);s1.setMargins(0,0,dp(3),0);LinearLayout.LayoutParams s2=new LinearLayout.LayoutParams(0,dp(40),1f);s2.setMargins(dp(3),0,0,0);segment.addView(scalpBtn,s1);segment.addView(swingBtn,s2);LinearLayout.LayoutParams sg=new LinearLayout.LayoutParams(-1,-2);sg.setMargins(0,dp(10),0,0);signalControls.addView(segment,sg);head.addView(signalControls);root.addView(head);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setVerticalScrollBarEnabled(false);content=column();content.setPadding(dp(16),dp(3),dp(16),dp(24));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));bottom=row();bottom.setPadding(dp(7),dp(6),dp(7),dp(8));bottom.setBackgroundColor(PANEL);root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(66)));setContentView(root);drawBottom();signalControls.setVisibility(screen.equals("SIGNALS")?View.VISIBLE:View.GONE);
    }

''')

block('    private void drawBottom(){','    private void swap(Runnable r){',r'''    private void drawBottom(){
        bottom.removeAllViews();String[] keys={"HOME","SIGNALS","WATCH","STATS","SETTINGS"},names={"Trang chủ","Tín hiệu","Theo dõi","Thống kê","Cài đặt"};int[] icons={R.drawable.ic_home,R.drawable.ic_signal,R.drawable.ic_watchlist,R.drawable.ic_stats,R.drawable.ic_settings};
        for(int i=0;i<keys.length;i++){View v=navItem(keys[i],names[i],icons[i]);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(52),1f);p.setMargins(dp(2),0,dp(2),0);bottom.addView(v,p);}
    }
''')

block('    private String performanceSummary(){','    private View simpleLevel(',r'''    private String performanceSummary(){JSONObject p=perfCache.get("CRYPTO:"+style);if(p==null)return "Chưa đủ dữ liệu đóng lệnh";int n=p.optInt("resolved",0);return n==0?"Chưa có lệnh đóng":("WR "+p.optString("winRateLabel","—")+" • "+n+" mẫu • Net "+String.format(Locale.US,"%+.2fR",p.optDouble("netRResolved",0)));}
    private View signalCard(JSONObject s){
        LinearLayout c=card();String sym=s.optString("symbol","—"),side=sideVi(s.optString("side","—")),signalStyle=s.optString("style",style),id=s.optString("signalId",s.optString("id",sym+":"+signalStyle));int col=side.equals("BUY")?GREEN:RED;double e=s.optDouble("entry",0),sl=s.optDouble("sl",0),tp3=s.optDouble("tp3",s.optDouble("tp",0)),px=priceFor(s,e);
        LinearLayout h=row();ImageView coin=new ImageView(this);coin.setImageResource(R.drawable.ic_crypto_coin);coin.setColorFilter(CYAN);coin.setContentDescription(sym);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(28),dp(28));cp.setMargins(0,0,dp(10),0);h.addView(coin,cp);LinearLayout names=column();names.addView(tv(sym,18,TEXT,true));names.addView(tv(signalStyle+" • "+s.optString("executionPriceAuthority",s.optString("provider","CRYPTO")),9,MUTED,false));h.addView(names,new LinearLayout.LayoutParams(0,-2,1f));h.addView(chip(side,col));LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-2,-2);op.setMargins(dp(6),0,0,0);h.addView(chip(orderDisplay(s,px),orderColor(s,px)),op);c.addView(h);
        LinearLayout priceRow=row();priceRow.setPadding(0,dp(10),0,0);LinearLayout priceCol=column();priceCol.addView(tv("GIÁ HIỆN TẠI",8,MUTED,true));TextView pv=tv(fmt(px),22,TEXT,true);priceCol.addView(pv);priceRow.addView(priceCol,new LinearLayout.LayoutParams(0,-2,1f));TextView pnl=tv(tradeStatusText(s,px),10,tradeStatusColor(s,px),true);pnl.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);priceRow.addView(pnl,new LinearLayout.LayoutParams(0,-2,1f));c.addView(priceRow);priceViews.put(id,pv);viewMarkets.put(id,"CRYPTO");pnlViews.put(id,pnl);
        if(isDisplayLive(s,px)){TradeGauge g=new TradeGauge();g.setData(currentR(s,px),targetR(s));LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(55));gp.setMargins(0,dp(5),0,0);c.addView(g,gp);gaugeViews.put(id,g);}else{EntryGauge g=new EntryGauge();g.setData(s,px);LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(59));gp.setMargins(0,dp(5),0,0);c.addView(g,gp);entryGaugeViews.put(id,g);}
        LinearLayout lv=row();LinearLayout.LayoutParams a=new LinearLayout.LayoutParams(0,-2,1f);a.setMargins(0,dp(6),dp(3),0);LinearLayout.LayoutParams b=new LinearLayout.LayoutParams(0,-2,1f);b.setMargins(dp(3),dp(6),dp(3),0);LinearLayout.LayoutParams d=new LinearLayout.LayoutParams(0,-2,1f);d.setMargins(dp(3),dp(6),0,0);lv.addView(levelBox("ENTRY",fmt(e),TEXT),a);lv.addView(levelBox("SL",fmt(sl),RED),b);lv.addView(levelBox("TP3",fmt(tp3),GREEN),d);c.addView(lv);
        TextView foot=tv(shortReason(s)+"  •  Chạm để xem phân tích",9,MUTED,false);foot.setPadding(0,dp(9),0,0);c.addView(foot);pressFeedback(c);c.setClickable(true);c.setOnClickListener(v->openSignalDetail(s));return c;
    }
''')

block('    private void renderSignals(boolean animate){','    private void addCryptoSignalGroup(',r'''    private void renderSignals(boolean animate){
        if(detail&&selectedSignal!=null){renderDetail(selectedSignal,animate);return;}Runnable body=()->{content.removeAllViews();priceViews.clear();sourceViews.clear();viewMarkets.clear();gaugeViews.clear();entryGaugeViews.clear();pnlViews.clear();subtitle.setText(style+" • CRYPTO REALTIME");
            List<JSONObject> rows=collectSignals(),liveRows=new ArrayList<>(),waitRows=new ArrayList<>();for(JSONObject x:rows){double px=priceFor(x,x.optDouble("entry",0));if(isDisplayLive(x,px))liveRows.add(x);else waitRows.add(x);}
            LinearLayout top=row();LinearLayout title=column();title.addView(tv(style,20,TEXT,true));title.addView(tv(style.equals("SCALP")?"Giao dịch ngắn • 5m / 15m / 1h":"Giữ theo cấu trúc • 1h / 4h / 1D",9,MUTED,false));top.addView(title,new LinearLayout.LayoutParams(0,-2,1f));top.addView(chip(cryptoState,stateColor(cryptoState)));content.addView(top);
            LinearLayout stats=row();View live=miniStat("LIVE",String.valueOf(liveRows.size()),"đã khớp",GREEN),wait=miniStat("CHỜ ENTRY",String.valueOf(waitRows.size()),"limit / stop",YELLOW);LinearLayout.LayoutParams p1=new LinearLayout.LayoutParams(0,-2,1f);p1.setMargins(0,dp(8),dp(4),dp(7));LinearLayout.LayoutParams p2=new LinearLayout.LayoutParams(0,-2,1f);p2.setMargins(dp(4),dp(8),0,dp(7));stats.addView(live,p1);stats.addView(wait,p2);content.addView(stats);content.addView(tv(performanceSummary(),9,MUTED,false));
            addCryptoSignalGroup("ĐANG CHẠY",liveRows,GREEN);addCryptoSignalGroup("CHỜ KHỚP ENTRY",waitRows,YELLOW);
        };if(animate)swap(body);else body.run();updateAllPriceViews();
    }
''')

block('    private void renderDetail(JSONObject s,boolean animate){','    private void loadDashboardData(){',r'''    private void renderDetail(JSONObject s,boolean animate){Runnable body=()->{content.removeAllViews();priceViews.clear();sourceViews.clear();viewMarkets.clear();gaugeViews.clear();entryGaugeViews.clear();pnlViews.clear();subtitle.setText("CHI TIẾT TÍN HIỆU");
        Button back=button("‹  Quay lại tín hiệu",false,v->{detail=false;selectedSignal=null;renderSignals(true);});content.addView(back,new LinearLayout.LayoutParams(-1,dp(44)));
        String market=s.optString("market","CRYPTO"),signalStyle=s.optString("style",style),side=sideVi(s.optString("side","—")),id=s.optString("signalId",s.optString("id","detail"));int col=side.equals("BUY")?GREEN:RED;double px=priceFor(s,s.optDouble("entry",0));
        LinearLayout trade=card();LinearLayout h=row();LinearLayout names=column();names.addView(tv(s.optString("symbol","—"),24,TEXT,true));names.addView(tv(signalStyle+" • "+orderDisplay(s,px)+" • "+lifecycleVi(s),10,orderColor(s,px),true));h.addView(names,new LinearLayout.LayoutParams(0,-2,1f));h.addView(chip(side,col));trade.addView(h);
        TextView pv=tv(fmt(px),30,TEXT,true);pv.setPadding(0,dp(12),0,0);trade.addView(pv);priceViews.put(id,pv);viewMarkets.put(id,market);TextView sv=tv(sourceText(market),9,stateColor(cryptoState),true);trade.addView(sv);sourceViews.put(id,sv);TextView pnl=tv(tradeStatusText(s,px),13,tradeStatusColor(s,px),true);pnl.setPadding(0,dp(10),0,dp(2));trade.addView(pnl);pnlViews.put(id,pnl);
        if(isDisplayLive(s,px)){TradeGauge gauge=new TradeGauge();gauge.setData(currentR(s,px),targetR(s));trade.addView(gauge,new LinearLayout.LayoutParams(-1,dp(70)));gaugeViews.put(id,gauge);}else{EntryGauge eg=new EntryGauge();eg.setData(s,px);trade.addView(eg,new LinearLayout.LayoutParams(-1,dp(72)));entryGaugeViews.put(id,eg);}
        LinearLayout l1=row();LinearLayout.LayoutParams x1=new LinearLayout.LayoutParams(0,-2,1f);x1.setMargins(0,dp(5),dp(3),0);LinearLayout.LayoutParams x2=new LinearLayout.LayoutParams(0,-2,1f);x2.setMargins(dp(3),dp(5),dp(3),0);LinearLayout.LayoutParams x3=new LinearLayout.LayoutParams(0,-2,1f);x3.setMargins(dp(3),dp(5),0,0);l1.addView(levelBox("ENTRY",fmt(s.optDouble("entry",0)),TEXT),x1);l1.addView(levelBox("SL",fmt(s.optDouble("sl",0)),RED),x2);l1.addView(levelBox("TP3",fmt(s.optDouble("tp3",s.optDouble("tp",0))),GREEN),x3);trade.addView(l1);LinearLayout l2=row();LinearLayout.LayoutParams y1=new LinearLayout.LayoutParams(0,-2,1f);y1.setMargins(0,dp(6),dp(3),0);LinearLayout.LayoutParams y2=new LinearLayout.LayoutParams(0,-2,1f);y2.setMargins(dp(3),dp(6),dp(3),0);LinearLayout.LayoutParams y3=new LinearLayout.LayoutParams(0,-2,1f);y3.setMargins(dp(3),dp(6),0,0);l2.addView(levelBox("TP1",fmt(s.optDouble("tp1",0)),GREEN),y1);l2.addView(levelBox("TP2",fmt(s.optDouble("tp2",0)),GREEN),y2);l2.addView(levelBox("RR","1 : "+String.format(Locale.US,"%.2f",targetR(s)),CYAN),y3);trade.addView(l2);content.addView(trade);
        content.addView(sectionHeader("Phân tích thị trường","Cấu trúc và logic của chính setup này",CYAN));LinearLayout analysis=card();analysis.addView(line("REGIME",s.optString("marketRegime","MARKET READ").replace('_',' '),BLUE));analysis.addView(line("STYLE",s.optString("styleExecutionModel",signalStyle.equals("SCALP")?"SCALP MICROSTRUCTURE":"SWING HTF STRUCTURE").replace('_',' '),CYAN));analysis.addView(line("ENTRY",s.optString("entryModel","BOT MARKET JUDGMENT").replace('_',' '),YELLOW));analysis.addView(line("STOP",s.optString("slModel","STRUCTURE INVALIDATION").replace('_',' '),RED));analysis.addView(line("TARGET",s.optString("tpModel","STRUCTURE TARGETS").replace('_',' '),GREEN));content.addView(analysis);
        JSONArray why=s.optJSONArray("rationale");if(why!=null&&why.length()>0){content.addView(sectionHeader("Vì sao có tín hiệu","Các điều kiện chính đã được engine xác nhận",MUTED));LinearLayout reasons=card();for(int i=0;i<why.length();i++){TextView r=tv("• "+why.optString(i),10,MUTED,false);r.setPadding(0,dp(3),0,dp(3));reasons.addView(r);}content.addView(reasons);}
        LinearLayout meta=card();meta.addView(tv("WR chỉ dựa trên lệnh đã đóng • không phải xác suất thắng dự đoán.",9,YELLOW,false));meta.addView(tv("Phát "+time(s.optString("issuedAt",""))+" • "+historicalWr(market,signalStyle),9,MUTED,false));content.addView(meta);
    };if(animate)swap(body);else body.run();updateAllPriceViews();}

''')

block('    private View statTile(','    private void renderAlerts(',r'''    private View statTile(String icon,String title,String value,String sub,int color){return miniStat(title,value,sub,color);}

    private void renderHome(boolean animate){Runnable body=()->{content.removeAllViews();priceViews.clear();sourceViews.clear();viewMarkets.clear();gaugeViews.clear();entryGaugeViews.clear();pnlViews.clear();subtitle.setText("CRYPTO • 2 SCALP + 2 SWING");
        LinearLayout hero=card();LinearLayout h=row();LinearLayout left=column();left.addView(tv("SIGNALHUB CRYPTO",10,CYAN,true));left.addView(tv(systemState.equals("RUNNING")?"Sẵn sàng theo dõi":"Đang kết nối lại",22,TEXT,true));left.addView(tv(cryptoProvider+" • "+cryptoState,9,stateColor(cryptoState),true));h.addView(left,new LinearLayout.LayoutParams(0,-2,1f));ImageView mark=new ImageView(this);mark.setImageResource(R.drawable.ic_signalhub);mark.setColorFilter(CYAN);mark.setContentDescription("SignalHub");h.addView(mark,new LinearLayout.LayoutParams(dp(42),dp(42)));hero.addView(h);TextView promise=tv("Bảng tham khảo luôn ưu tiên 2 SCALP + 2 SWING. Watchlist phân tích riêng coin bạn chọn.",9,MUTED,false);promise.setPadding(0,dp(10),0,0);hero.addView(promise);content.addView(hero);
        LinearLayout counts=row();View sc=miniStat("SCALP",String.valueOf(countStyle("SCALP")),"mục tiêu 2 active",CYAN),sw=miniStat("SWING",String.valueOf(countStyle("SWING")),"mục tiêu 2 active",BLUE);LinearLayout.LayoutParams p1=new LinearLayout.LayoutParams(0,-2,1f);p1.setMargins(0,0,dp(4),0);LinearLayout.LayoutParams p2=new LinearLayout.LayoutParams(0,-2,1f);p2.setMargins(dp(4),0,0,0);counts.addView(sc,p1);counts.addView(sw,p2);content.addView(counts);
        JSONObject ps=perfCache.get("CRYPTO:SCALP"),pw=perfCache.get("CRYPTO:SWING");content.addView(sectionHeader("Hiệu suất đã đóng","Không dùng WR dự đoán",MUTED));LinearLayout evidence=card();evidence.addView(evidenceLine("SCALP",ps));evidence.addView(evidenceLine("SWING",pw));content.addView(evidence);
        List<JSONObject> rows=allSignals();content.addView(sectionHeader("4 tín hiệu tham khảo","Chạm vào từng coin để xem Entry / SL / TP và phân tích",MUTED));if(rows.isEmpty()){LinearLayout z=card();z.addView(tv("Đang đồng bộ tín hiệu từ server…",10,MUTED,false));content.addView(z);}else{for(int i=0;i<Math.min(4,rows.size());i++)content.addView(homeSignalRow(rows.get(i)));}
    };if(animate)swap(body);else body.run();updateAllPriceViews();}
    private int countStyle(String st){int n=0;for(JSONObject s:allSignals())if(st.equals(s.optString("style","")))n++;return n;}
    private View evidenceLine(String st,JSONObject p){LinearLayout r=row();r.setPadding(0,dp(7),0,dp(7));r.addView(tv(st,11,st.equals("SCALP")?CYAN:BLUE,true),new LinearLayout.LayoutParams(0,-2,1f));if(p==null){r.addView(tv("đang tải",9,MUTED,false));return r;}int n=p.optInt("resolved",0);String x=n==0?"chưa có mẫu":p.optString("winRateLabel","—")+" • "+n+" mẫu • "+String.format(Locale.US,"%+.1fR",p.optDouble("netRResolved",0));r.addView(tv(x,10,n>=30?TEXT:YELLOW,true));return r;}

''')

block('    private View watchStyleBlock(','    private void loadAllPerformance(){',r'''    private View watchStyleBlock(String styleName,JSONObject x){LinearLayout c=column();c.setPadding(0,dp(9),0,dp(4));String state=x==null?"LOADING":x.optString("state","NO_TRADE"),side=sideVi(x==null?"":x.optString("side","")),order=x==null?"":x.optString("orderType","");LinearLayout h=row();h.addView(tv(styleName,11,TEXT,true),new LinearLayout.LayoutParams(0,-2,1f));h.addView(chip(watchStateVi(state),watchStateColor(state)));c.addView(h);if(x==null){TextView z=tv("Đang đọc cấu trúc…",9,MUTED,false);z.setPadding(0,dp(5),0,0);c.addView(z);return c;}String regime=x.optString("marketRegime","");if(!side.isEmpty()&&!order.isEmpty()){TextView d=tv(side+" • "+order+(regime.isEmpty()?"":" • "+regime),10,side.equals("BUY")?GREEN:RED,true);d.setPadding(0,dp(5),0,0);c.addView(d);}else if(!regime.isEmpty()){TextView d=tv(regime,9,MUTED,true);d.setPadding(0,dp(5),0,0);c.addView(d);}double e=x.optDouble("entry",0),sl=x.optDouble("sl",0),tp=x.optDouble("tp3",0);if(e>0&&sl>0&&tp>0)c.addView(tv("Entry "+fmt(e)+"  •  SL "+fmt(sl)+"  •  TP3 "+fmt(tp),9,TEXT,true));String story=x.optString("marketStory","");if(!story.isEmpty()&&(state.equals("TRADEABLE_NOW")||state.equals("ACTIVE_SIGNAL")||state.equals("CONDITIONAL_WAIT")))c.addView(tv(story,9,MUTED,false));JSONArray failed=x.optJSONArray("failedChecks");if(state.equals("NO_TRADE")&&failed!=null&&failed.length()>0)c.addView(tv("Chưa đạt: "+failed.optString(0),8,YELLOW,false));return c;}
    private void renderWatchlist(boolean animate){Runnable body=()->{content.removeAllViews();subtitle.setText("WATCHLIST • PHÂN TÍCH RIÊNG");content.addView(tv("Theo dõi coin",20,TEXT,true));content.addView(tv("Không chiếm 4 slot tín hiệu chính",9,MUTED,false));LinearLayout add=row();EditText input=new EditText(this);input.setHint("Nhập BTC, ETH, XRP…");input.setHintTextColor(MUTED);input.setTextColor(TEXT);input.setTextSize(12);input.setSingleLine(true);input.setPadding(dp(13),0,dp(13),0);input.setBackground(shape(PANEL2,14,BORDER));Button addBtn=button("Thêm",true,v->{String x=input.getText().toString();input.setText("");addWatch(x);});LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(0,dp(46),1f);ip.setMargins(0,dp(12),dp(5),dp(8));add.addView(input,ip);LinearLayout.LayoutParams ab=new LinearLayout.LayoutParams(dp(78),dp(46));ab.setMargins(dp(5),dp(12),0,dp(8));add.addView(addBtn,ab);content.addView(add);List<String> symbols=watchSymbols();if(symbols.isEmpty()){LinearLayout z=card();z.addView(tv("Chưa có coin nào trong Watchlist.",11,TEXT,true));z.addView(tv("Nhập mã phía trên để xem phân tích SCALP và SWING riêng.",9,MUTED,false));content.addView(z);return;}for(String sym:symbols){JSONObject root=watchCache.get(sym),ticker=root==null?null:root.optJSONObject("ticker"),live=cryptoPrices.get(sym);double px=live!=null?live.optDouble("lastPrice",0):(ticker==null?0:ticker.optDouble("lastPrice",0));LinearLayout c=card();LinearLayout h=row();LinearLayout n=column();n.addView(tv(sym.replace("USDT"," / USDT"),16,TEXT,true));String provider=live!=null?cryptoProvider:(ticker==null?"—":ticker.optString("provider","—"));n.addView(tv(provider+" • "+cryptoState,8,stateColor(cryptoState),false));h.addView(n,new LinearLayout.LayoutParams(0,-2,1f));TextView price=tv(fmt(px),15,CYAN,true);h.addView(price);Button rm=button("×",false,v->removeWatch(sym));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(dp(40),dp(36));rp.setMargins(dp(8),0,0,0);h.addView(rm,rp);c.addView(h);JSONObject styles=root==null?null:root.optJSONObject("styles");c.addView(watchStyleBlock("SCALP  •  5m / 15m / 1h",styles==null?null:styles.optJSONObject("SCALP")));c.addView(watchStyleBlock("SWING  •  1h / 4h / 1D",styles==null?null:styles.optJSONObject("SWING")));Button refresh=button(Boolean.TRUE.equals(watchLoading.get(sym))?"Đang phân tích…":"Phân tích lại",false,v->refreshWatchSymbol(sym,true));LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(42));fp.setMargins(0,dp(7),0,0);c.addView(refresh,fp);content.addView(c);} };if(animate)swap(body);else body.run();}

''')

block('    private void renderStats(boolean animate){','    private void renderSources(',r'''    private void renderStats(boolean animate){Runnable body=()->{content.removeAllViews();subtitle.setText("THỐNG KÊ • CHỈ LỆNH ĐÃ ĐÓNG");content.addView(tv("Hiệu suất",20,TEXT,true));content.addView(tv("Win rate chỉ là kết quả lịch sử, không phải xác suất thắng của lệnh kế tiếp.",9,MUTED,false));for(String st:new String[]{"SCALP","SWING"})content.addView(perfCard("CRYPTO",st));};if(animate)swap(body);else body.run();}
    private View perfCard(String m,String st){LinearLayout c=card(),h=row();LinearLayout names=column();names.addView(tv(st,16,TEXT,true));names.addView(tv(st.equals("SCALP")?"5m / 15m / 1h":"1h / 4h / 1D",9,MUTED,false));h.addView(names,new LinearLayout.LayoutParams(0,-2,1f));h.addView(chip(st,st.equals("SCALP")?CYAN:BLUE));c.addView(h);JSONObject p=perfCache.get(m+":"+st);if(p==null){c.addView(tv("Đang đồng bộ lịch sử…",10,MUTED,false));return c;}int tp=p.optInt("tp",0),sl=p.optInt("sl",0),n=p.optInt("resolved",tp+sl);LinearLayout big=row();big.setPadding(0,dp(12),0,dp(5));LinearLayout wr=column();wr.addView(tv("WIN RATE",8,MUTED,true));wr.addView(tv(p.optString("winRateLabel","—"),26,TEXT,true));big.addView(wr,new LinearLayout.LayoutParams(0,-2,1f));LinearLayout nr=column();nr.setGravity(Gravity.END);nr.addView(tv("NET R",8,MUTED,true));TextView rv=tv(String.format(Locale.US,"%+.2fR",p.optDouble("netRResolved",0)),18,p.optDouble("netRResolved",0)>=0?GREEN:RED,true);rv.setGravity(Gravity.END);nr.addView(rv);big.addView(nr,new LinearLayout.LayoutParams(0,-2,1f));c.addView(big);c.addView(line("MẪU",String.valueOf(n),TEXT));c.addView(line("TP / SL",tp+" / "+sl,TEXT));c.addView(tv(n>=30?"Sample ≥30 • đáng tham khảo hơn":"Sample <30 • dữ liệu còn sơ bộ",9,n>=30?MUTED:YELLOW,false));return c;}

''')

block('    private void renderSettings(boolean animate){','    private double pxForOrder(',r'''    private void renderSettings(boolean animate){Runnable body=()->{content.removeAllViews();subtitle.setText("CÀI ĐẶT • CRYPTO ONLY");content.addView(tv("Cài đặt",20,TEXT,true));content.addView(tv("Chỉ giữ các trạng thái quan trọng để dễ kiểm tra.",9,MUTED,false));
        LinearLayout notify=card();notify.addView(tv("Thông báo & nền",13,TEXT,true));notify.addView(statusRow("Theo dõi nền",monitorStarted?"RUNNING":"OFFLINE"));notify.addView(statusRow("Quyền thông báo",notifyPermission()?"ONLINE":"OFFLINE"));if(!monitorStarted){Button b=button("Bật theo dõi",true,v->ensureMonitor(true));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(44));bp.setMargins(0,dp(7),0,0);notify.addView(b,bp);}content.addView(notify);
        LinearLayout data=card();data.addView(tv("Dữ liệu thị trường",13,TEXT,true));data.addView(statusRow(cryptoProvider,cryptoState));data.addView(line("Pending","Server theo dõi liên tục",GREEN));data.addView(line("Execution","Đúng provider của signal",CYAN));content.addView(data);
        LinearLayout engine=card();engine.addView(tv("Signal engine",13,TEXT,true));engine.addView(line("SCALP","5m • 15m • 1h",CYAN));engine.addView(line("SWING","1h • 4h • 1D",BLUE));engine.addView(line("Danh mục","2 SCALP + 2 SWING",GREEN));engine.addView(line("App",APP_VERSION,TEXT));if(systemStatus!=null)engine.addView(line("Backend",systemStatus.optString("version","—"),MUTED));content.addView(engine);
    };if(animate)swap(body);else body.run();}

''')

P.write_text(s)
g=G.read_text().replace('versionCode 21','versionCode 22').replace("versionName '3.16.0'","versionName '3.17.0'")
G.write_text(g)
print('patched SignalHub V3.17 UX polish')
