from pathlib import Path

def rep(s,a,b,label):
    if a not in s: raise SystemExit(f'MISSING:{label}')
    return s.replace(a,b,1)

p=Path('cloudflare-worker/engine-v77168.js'); s=p.read_text()
s=rep(s,'version: "V77.16.10",\n  service: "Trading V77.16.10 Balanced Discovery Signal Engine",','version: "V77.16.11",\n  service: "Trading V77.16.11 Forex Opportunity Routing R3",','engine version')

old='function forexStrengthMap(h1Map){const sum={},cnt={};for(const [sym,c] of h1Map.entries()){if(!Array.isArray(c)||c.length<2)continue;const ch=changeFromCandles(c),base=sym.slice(0,3),quote=sym.slice(3);sum[base]=(sum[base]||0)+ch;cnt[base]=(cnt[base]||0)+1;sum[quote]=(sum[quote]||0)-ch;cnt[quote]=(cnt[quote]||0)+1;}const out={};for(const k of Object.keys(sum))out[k]=sum[k]/Math.max(1,cnt[k]);return out;}'
new='function weightedFxMove(c){if(!Array.isArray(c)||c.length<7)return changeFromCandles(c);const last=Number(c.at(-1)?.close||0);if(!(last>0))return 0;const move=n=>{const a=Number(c.at(-(n+1))?.close||0);return a>0?(last-a)/a*100:0;};return move(1)*.50+move(3)*.30+move(6)*.20;}\nfunction forexStrengthMap(h1Map){const sum={},cnt={};for(const [sym,c] of h1Map.entries()){if(!Array.isArray(c)||c.length<2)continue;const ch=weightedFxMove(c),base=sym.slice(0,3),quote=sym.slice(3);sum[base]=(sum[base]||0)+ch;cnt[base]=(cnt[base]||0)+1;sum[quote]=(sum[quote]||0)-ch;cnt[quote]=(cnt[quote]||0)+1;}const out={};for(const k of Object.keys(sum))out[k]=sum[k]/Math.max(1,cnt[k]);return out;}\nfunction forexSessionBias(symbol){const s=norm(symbol),h=new Date().getUTCHours(),cc=[s.slice(0,3),s.slice(3)],asia=cc.some(x=>["JPY","AUD","NZD"].includes(x)),europe=cc.some(x=>["EUR","GBP","CHF"].includes(x)),america=cc.some(x=>["USD","CAD"].includes(x));let score=.35,label="OFF_PEAK";if(h>=0&&h<8&&asia){score=1;label="ASIA_ACTIVE";}if(h>=6&&h<13&&europe){score=Math.max(score,1);label="LONDON_ACTIVE";}if(h>=12&&h<17&&(europe||america)){score=1.15;label="LONDON_NY_OVERLAP";}if(h>=13&&h<21&&america){score=Math.max(score,.9);label=label==="LONDON_NY_OVERLAP"?label:"NEW_YORK_ACTIVE";}return {score,label};}'
s=rep(s,old,new,'fx strength')

old='if(group==="forex"){const base=sym.slice(0,3),quote=sym.slice(3),d=(fx[base]||0)-(fx[quote]||0);context={baseStrength:fx[base]||0,quoteStrength:fx[quote]||0,strengthDiff:d,score:Math.min(10,5+Math.abs(d)*4)};}'
new='if(group==="forex"){const base=sym.slice(0,3),quote=sym.slice(3),d=(fx[base]||0)-(fx[quote]||0),sess=forexSessionBias(sym);context={baseStrength:fx[base]||0,quoteStrength:fx[quote]||0,strengthDiff:d,session:sess.label,sessionScore:sess.score,score:Math.min(10,4.6+Math.abs(d)*4.4+sess.score*.7)};}'
s=rep(s,old,new,'fx context')

old='const raw=Math.abs((T.close-(T.ema20??T.close))/(T.atr14||1)),prior=v73Prior(sym,group),sweet=Math.max(0,1-Math.abs(raw-.45)/.90),discoveryScore=sweet*2.4+Number(context.score||5)*.45+sessionFit(prior)*.55+Math.min(raw,1.2)*.10;'
new='const raw=Math.abs((T.close-(T.ema20??T.close))/(T.atr14||1)),prior=v73Prior(sym,group),sweet=Math.max(0,1-Math.abs(raw-.35)/.85),sessionBoost=group==="forex"?Number(context.sessionScore||.35):sessionFit(prior),directionBoost=group==="forex"?Math.min(1.4,Math.abs(Number(context.strengthDiff||0))*3.2):0,discoveryScore=sweet*2.2+Number(context.score||5)*.48+sessionBoost*.75+directionBoost*.35+Math.min(raw,1.2)*.08;'
s=rep(s,old,new,'discovery score')

old='function selectForexDiverse(rows,limit){const pool=[...(rows||[])],picked=[],used=new Set();while(pool.length&&picked.length<limit){let idx=-1;for(let i=0;i<pool.length;i++){const s=norm(pool[i].symbol),b=s.slice(0,3),q=s.slice(3),overlap=(used.has(b)?1:0)+(used.has(q)?1:0);if(overlap===0){idx=i;break;}if(idx<0&&overlap===1)idx=i;}if(idx<0)idx=0;const r=pool.splice(idx,1)[0],s=norm(r.symbol);picked.push(r);used.add(s.slice(0,3));used.add(s.slice(3));}return picked;}'
new='function selectForexDiverse(rows,limit){const ranked=[...(rows||[])].sort((a,b)=>(Number(b.strength)||0)-(Number(a.strength)||0)),picked=[],seen=new Set();const core=Math.min(3,limit);for(const r of ranked.slice(0,core)){picked.push(r);seen.add(r.symbol);}const used=new Set(picked.flatMap(r=>[norm(r.symbol).slice(0,3),norm(r.symbol).slice(3)]));for(const r of ranked){if(picked.length>=limit)break;if(seen.has(r.symbol))continue;const s=norm(r.symbol),b=s.slice(0,3),q=s.slice(3),overlap=(used.has(b)?1:0)+(used.has(q)?1:0);if(overlap<=1||picked.length>=limit-1){picked.push(r);seen.add(r.symbol);used.add(b);used.add(q);}}for(const r of ranked){if(picked.length>=limit)break;if(!seen.has(r.symbol)){picked.push(r);seen.add(r.symbol);}}return picked;}'
s=rep(s,old,new,'fx shortlist')

old='if(type!=="crypto"){let p=planned;if(!pendingRetest){const mg=marketGeometry(side,M5.close,M5,trigPolicy);if(!mg.pass){const alt=rescuePlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)p=alt;else return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,marketGeometry:mg},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,marketGeometry:mg}});}else p={...p,marketGeometry:mg};}return planSignal(s,type,side,"EXECUTION_QUOTE_REQUIRED",p,{...base,score,setupReady:true,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source}}});}'
new='if(type!=="crypto"){let p=planned,mg=null;if(!pendingRetest){mg=marketGeometry(side,M5.close,M5,trigPolicy);if(!mg.pass){const alt=rescuePlan(side,M5.close,M5,M15,H1,H4,D1,prior,intel,locPolicy,trigPolicy);if(alt)p=alt;else return watch(s,type,side,"MARKET_GEOMETRY_REQUIRED",{...base,score,setupReady:true,planned:{...planned,marketGeometry:mg},entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,marketGeometry:mg}});}else p={...p,marketGeometry:mg};}\n    const forexAdvisory=type==="forex"&&!pendingRetest&&mg?.pass&&Number(intel.methodFit||0)>=50&&Number(context.score||0)>=5.4&&Number.isFinite(Number(M15.close))&&quality.pass;\n    if(forexAdvisory)return {ok:true,status:"MARKET_SIGNAL",action:"MARKET_SIGNAL",symbol:s,market:type,side,score:Math.max(score,55),method:intel,context,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},entry:Number(M15.close),currentPrice:Number(M15.close),sl:p.sl,tp1:p.tp1,tp2:p.tp2,targetRR:p.targetRR,tp1RR:p.tp1RR,tp2RR:p.tp2RR,roomR:p.roomR,planned:{...p,mode:"MARKET",signalOnly:true,analysisQuote:true},executionReady:false,executionAuthority:"SIGNAL_ONLY",quote:{source:"Twelve Data analysis",price:Number(M15.close),fresh:true,analysisOnly:true,executionVerified:false},source:"Twelve Data analysis",canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source},marketGeometry:mg},engine:CONFIG.version};\n    return planSignal(s,type,side,"EXECUTION_QUOTE_REQUIRED",p,{...base,score,setupReady:true,entryPolicy:{profile:profileMode(intel),location:locPolicy,trigger:trigPolicy},source:source||(type==="future"?"Massive Futures analysis":"Twelve Data analysis"),canonical:{...base.canonical,m15Location:loc,m5Trigger:trig,news:{cleared:true,soft:newsSoft,source:news.source}}});}'
s=rep(s,old,new,'forex market signal')

s=s.replace('if(a.status==="MARKET"||a.status==="LIMIT"){L.push("",`✅ LỆNH EXECUTABLE ${a.status}`','if(a.status==="MARKET"||a.status==="LIMIT"){L.push("",`✅ LỆNH EXECUTABLE ${a.status}`')
s=s.replace('else if(a.planned){const tag=a.planned.indicative?"📐 ENTRY THAM KHẢO — chưa phải lệnh":"🎯 KẾ HOẠCH ENTRY";','else if(a.status==="MARKET_SIGNAL"){L.push("",`⚡ MARKET SIGNAL • SIGNAL-ONLY`,`Entry ${fmtPx(a.entry)} • SL ${fmtPx(a.sl)}`,`TP1 ${fmtPx(a.tp1)} • TP2 ${fmtPx(a.tp2)} • RR ${Number(a.targetRR||0).toFixed(2)}`,`Session ${a.context?.session||"—"} • không phải broker fill`);}\n  else if(a.planned){const tag=a.planned.indicative?"📐 ENTRY THAM KHẢO — chưa phải lệnh":"🎯 KẾ HOẠCH ENTRY";')
s=s.replace('function freshPlanFromRun(run,kind){return (run?.analyses||[]).filter(a=>a?.planned&&(kind==="market"?(a.status==="MARKET_PLAN"||a.planned.mode==="MARKET")','function freshPlanFromRun(run,kind){return (run?.analyses||[]).filter(a=>a?.planned&&(kind==="market"?(a.status==="MARKET_SIGNAL"||a.status==="MARKET_PLAN"||a.planned.mode==="MARKET")')
s=s.replace('const plans=(run?.analyses||[]).filter(a=>a?.planned&&["MARKET_PLAN","LIMIT_PLAN"].includes(a.status))','const plans=(run?.analyses||[]).filter(a=>a?.planned&&["MARKET_SIGNAL","MARKET_PLAN","LIMIT_PLAN"].includes(a.status))')
s=s.replace('const mode=a.status==="MARKET_PLAN"?"MARKET":"LIMIT"','const mode=a.status==="MARKET_SIGNAL"||a.status==="MARKET_PLAN"?"MARKET":"LIMIT"')
s=s.replace('const rr=Number(a.planned?.targetRR||0).toFixed(2),txt=["📡 SIGNAL PLAN • "+groupTitle(group),','const rr=Number(a.planned?.targetRR||0).toFixed(2),marketNow=a.status==="MARKET_SIGNAL",txt=[marketNow?"⚡ MARKET SIGNAL • "+groupTitle(group):"📡 SIGNAL PLAN • "+groupTitle(group),')
s=s.replace('"ℹ️ Plan kỹ thuật • chờ execution authority thật"].join("\\n");','marketNow?"ℹ️ SIGNAL-ONLY • giá phân tích fresh • không phải broker fill":"ℹ️ Plan kỹ thuật • chờ execution authority thật"].join("\\n");')
p.write_text(s)

p=Path('cloudflare-worker/dual-ai-intervention.js'); s=p.read_text()
s=s.replace('const REVIEW_REV="HUB_UX_R2";','const REVIEW_REV="FOREX_ENTRY_R3";')
s=s.replace('HUB UX IS THE FIRST PRIORITY FOR THIS REVIEW.','FOREX ENTRY QUALITY IS THE FIRST PRIORITY FOR THIS REVIEW. Audit why Forex can go 24h+ without a MARKET recommendation. The current architecture intentionally lacks broker execution authority for Forex, so distinguish a high-quality MARKET SIGNAL (advisory, fresh analysis price, no broker fill claim) from an executable broker order. Review shortlist selection, session routing, currency-strength calculation, HTF/location/trigger/RR gates, and duplicated gates that can suppress valid setups. Never loosen hard news/freshness/structural-SL safeguards merely to manufacture trades.\n\nHUB UX IS SECONDARY FOR THIS REVIEW.')
s=s.replace('Perform HUB_UX_R2 first, then strategy review.','Perform FOREX_ENTRY_R3 first, then a compact Hub UX sanity review.')
s=s.replace('lastAction:"HUB_UX_R2_AND_STRATEGY"','lastAction:"FOREX_ENTRY_R3_AND_SYSTEM"')
p.write_text(s)

p=Path('cloudflare-worker/index.js'); s=p.read_text()
s=s.replace('const VERSION="V77.18.29",SERVICE="Trading V77.18.29 Live PnL + Unified UX";\nconst RELEASE_NAME="Live PnL + Unified UX";','const VERSION="V77.18.30",SERVICE="Trading V77.18.30 Forex Opportunity Routing R3";\nconst RELEASE_NAME="Forex Opportunity Routing R3";')
s=s.replace('ensureDualAiIntervention(env,{version:"V77.18.25"','ensureDualAiIntervention(env,{version:"V77.18.30"')
p.write_text(s)

p=Path('.github/workflows/validate-cloudflare-v77.yml'); s=p.read_text()
s=s.replace("'V77.16.10'","'V77.16.11'")
s=s.replace("['V77.18.29','Live PnL + Unified UX'","['V77.18.30','Forex Opportunity Routing R3'")
s=s.replace("'HUB-R4-LIVE-PNL'","'HUB-R4-LIVE-PNL'")
s=s.replace("console.log('V77.18.29 Live PnL + Unified UX validation PASS');","console.log('V77.18.30 Forex Opportunity Routing R3 validation PASS');")
p.write_text(s)
print('PATCH_V771830_OK')
