from pathlib import Path
p=Path('cloudflare-worker/engine-v77168.js')
s=p.read_text()
s=s.replace('version: "V77.16.12",\n  service: "Trading V77.16.12 Metal + Index Cash Routing R1",','version: "V77.16.13",\n  service: "Trading V77.16.13 Index Provider R2",')
s=s.replace('const INDEX_PROVIDER = {NAS100:"NDX",US30:"DJI",US500:"SPX",DEX:"DAX",JP225:"N225"};','const INDEX_PROVIDER = {NAS100:"NDX",US30:"DJI",US500:"SPX",DEX:"DAX",JP225:"N225"};\nconst MASSIVE_INDEX_PROVIDER = {NAS100:"I:NDX",US30:"I:DJI",US500:"I:SPX",DEX:"I:DAX",JP225:"I:N225"};')
needle='async function tdQuote(symbol,env){\n  const ps=tdSymbol(symbol),p=await tdFetch("quote",{symbol:ps},env),price=num(p.close)??num(p.price);\n  if(!price||price<=0)throw new Error("TD price invalid");\n  const ts=parseTs(p.last_quote_at??p.timestamp??p.datetime),age=ts==null?null:Math.max(0,nowSec()-ts);\n  return {source:"Twelve Data",requestedSymbol:norm(symbol),providerSymbol:ps,price,providerTimestamp:ts,quoteAgeSec:age,fresh:age!==null&&age<=CONFIG.maxQuoteAgeSec,bid:null,ask:null,executionVerified:false,analysisOnly:true};\n}\n'
insert='''async function massiveIndexFetch(path,params,env){if(!env.MASSIVE_API_KEY)throw new Error("MASSIVE_API_KEY missing");const q=new URLSearchParams(params||{});q.set("apiKey",env.MASSIVE_API_KEY);const r=await fetchTimeout(`https://api.massive.com${path}?${q}`);const j=await r.json().catch(()=>null);if(!r.ok||!j||j.status==="ERROR")throw new Error(j?.error||j?.message||`Massive HTTP ${r.status}`);return j;}\nfunction massiveIndexRange(interval){const now=Date.now(),d={"5min":7,"15min":14,"1h":45,"4h":180,"1day":500}[interval]||45,m={"5min":[5,"minute"],"15min":[15,"minute"],"1h":[1,"hour"],"4h":[4,"hour"],"1day":[1,"day"]}[interval]||[1,"hour"];return {from:new Date(now-d*86400000).toISOString().slice(0,10),to:new Date(now).toISOString().slice(0,10),mult:m[0],span:m[1]};}\nasync function massiveIndexCandles(symbol,interval,env,limit=CONFIG.candleOutputSize){const s=norm(symbol),ticker=MASSIVE_INDEX_PROVIDER[s];if(!ticker)throw new Error("Unsupported Massive index");const r=massiveIndexRange(interval),j=await massiveIndexFetch(`/v2/aggs/ticker/${encodeURIComponent(ticker)}/range/${r.mult}/${r.span}/${r.from}/${r.to}`,{adjusted:"true",sort:"asc",limit:String(Math.max(limit,120))},env);return normalizeCandles((j.results||[]).map(x=>({timestamp:Math.floor(Number(x.t)/1000),open:x.o,high:x.h,low:x.l,close:x.c,volume:null})),candleSec(interval));}\nasync function massiveIndexBatchCandles(symbols,interval,env,outputsize=CONFIG.candleOutputSize){const out=new Map();await Promise.all(symbols.map(async sym=>{try{const c=await massiveIndexCandles(sym,interval,env,outputsize);if(c.length)out.set(norm(sym),c);}catch{}}));return out;}\nasync function massiveIndexQuote(symbol,env){const s=norm(symbol),ticker=MASSIVE_INDEX_PROVIDER[s];if(!ticker)throw new Error("Unsupported Massive index");const c=await massiveIndexCandles(s,"5min",env,30),last=c.at(-1);if(!last)throw new Error("Massive index quote unavailable");const age=Math.max(0,nowSec()-last.timestamp-300);return {source:"Massive Indices",requestedSymbol:s,providerSymbol:ticker,price:last.close,providerTimestamp:last.timestamp,quoteAgeSec:age,fresh:age<=900,bid:null,ask:null,executionVerified:false,analysisOnly:true};}\n'''
if needle not in s: raise SystemExit('tdQuote needle missing')
s=s.replace(needle,insert+needle.replace('async function tdQuote(symbol,env){','async function tdQuote(symbol,env){\n  if(marketType(symbol)==="index"&&env.MASSIVE_API_KEY){try{return await massiveIndexQuote(symbol,env);}catch{}}'),1)
old='async function tdBatchCandles(symbols,interval,env,outputsize=CONFIG.candleOutputSize){\n  const requested=[...new Set(symbols.map(norm))],provider=requested.map(tdSymbol),out=new Map();if(!requested.length)return out;'
new='async function tdBatchCandles(symbols,interval,env,outputsize=CONFIG.candleOutputSize){\n  const requested=[...new Set(symbols.map(norm))];if(requested.length&&requested.every(x=>marketType(x)==="index")&&env.MASSIVE_API_KEY){const m=await massiveIndexBatchCandles(requested,interval,env,outputsize);if(m.size)return m;}const provider=requested.map(tdSymbol),out=new Map();if(!requested.length)return out;'
if old not in s: raise SystemExit('tdBatch needle missing')
s=s.replace(old,new,1)
p.write_text(s)
print('PATCH_V771832_OK')