from pathlib import Path
p=Path('.github/workflows/validate-cloudflare-v77.yml')
s=p.read_text()
s=s.replace("'V77.16.15','Native Index Failover'","'V77.16.16','Verified Index Pricing'")
s=s.replace("'Twelve Data Index Price'","'Twelve Data Native Index'")
s=s.replace("'V77.18.34','Native Index Failover'","'V77.18.35','Verified Index Pricing'")
s=s.replace("locks(hub,['V77.18.34'","locks(hub,['V77.18.35'")
s=s.replace("console.log('V77.18.34 Native Index Failover validation PASS');","locks(engine,['INDEX_SANITY','validIndexPrice','type:\"Index\"','assertTdIndexIdentity','implausible index price'],'Index sanity');\n          console.log('V77.18.35 Verified Index Pricing validation PASS');")
p.write_text(s)
print('VALIDATOR_PATCH_OK')
