from pathlib import Path

p=Path('cloudflare-worker/engine-v77168.js')
s=p.read_text()
old_func='''async function yahooUs30CashVisibilityQuote(){const s="US30",ps="^DJI",u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(ps)}?interval=1m&range=1d`,r=await fetchTimeout(u,{headers:{"user-agent":"Mozilla/5.0"}}),j=await r.json().catch(()=>null),x=j?.chart?.result?.[0],m=x?.meta||{},price=num(m.regularMarketPrice),ts=num(m.regularMarketTime);if(!r.ok||j?.chart?.error||m.symbol!==ps||String(m.instrumentType||"").toUpperCase()!=="INDEX"||!validIndexPrice(s,price))throw new Error(j?.chart?.error?.description||`Yahoo invalid cash index ${s}/${ps}: ${price}`);const age=ts?Math.max(0,nowSec()-ts):null;return {source:"Yahoo Finance Cash Index Fallback",requestedSymbol:s,providerSymbol:ps,price,providerTimestamp:ts||null,quoteAgeSec:age,fresh:false,bid:null,ask:null,executionVerified:false,analysisOnly:true,fallback:true,fallbackInterval:"quote",assetType:"Index",instrumentIdentity:"CASH_INDEX"};}'''
new_func='''const YAHOO_INDEX_CASH_PROVIDER={NAS100:"^NDX",US30:"^DJI",US500:"^GSPC",DEX:"^GDAXI",JP225:"^N225"};\nasync function yahooIndexCashVisibilityQuote(symbol){const s=norm(symbol),ps=YAHOO_INDEX_CASH_PROVIDER[s];if(!ps)throw new Error(`Yahoo unsupported cash index ${s}`);const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(ps)}?interval=1m&range=1d`,r=await fetchTimeout(u,{headers:{"user-agent":"Mozilla/5.0"}}),j=await r.json().catch(()=>null),x=j?.chart?.result?.[0],m=x?.meta||{},price=num(m.regularMarketPrice),ts=num(m.regularMarketTime);if(!r.ok||j?.chart?.error||m.symbol!==ps||String(m.instrumentType||"").toUpperCase()!=="INDEX"||!validIndexPrice(s,price))throw new Error(j?.chart?.error?.description||`Yahoo invalid cash index ${s}/${ps}: ${price}`);const age=ts?Math.max(0,nowSec()-ts):null;return {source:"Yahoo Finance Cash Index Fallback",requestedSymbol:s,providerSymbol:ps,price,providerTimestamp:ts||null,quoteAgeSec:age,fresh:false,bid:null,ask:null,executionVerified:false,analysisOnly:true,fallback:true,fallbackInterval:"quote",assetType:"Index",instrumentIdentity:"CASH_INDEX"};}\nasync function yahooUs30CashVisibilityQuote(){return yahooIndexCashVisibilityQuote("US30");}'''
old_branch='''  if(marketType(symbol)==="index"){const s=norm(symbol);if(env.MASSIVE_API_KEY){try{return await massiveIndexQuote(s,env);}catch{}}if(env.TWELVE_DATA_API_KEY){try{return await tdIndexQuote(s,env);}catch{}try{return await tdIndexQuoteVisibilityFallback(s,env);}catch{}}if(s==="US30"){try{return await yahooUs30CashVisibilityQuote();}catch{}}throw new Error("No native index quote available");}'''
new_branch='''  if(marketType(symbol)==="index"){const s=norm(symbol);if(env.MASSIVE_API_KEY){try{return await massiveIndexQuote(s,env);}catch{}}if(env.TWELVE_DATA_API_KEY){try{return await tdIndexQuote(s,env);}catch{}try{return await tdIndexQuoteVisibilityFallback(s,env);}catch{}}try{return await yahooIndexCashVisibilityQuote(s);}catch{}throw new Error("No native index quote available");}'''
if s.count('function yahooIndexCashVisibilityQuote')==1:
    print('V78-028 Yahoo all-index CASH fallback already present')
else:
    if s.count(old_func)!=1: raise SystemExit(f'function guard mismatch: {s.count(old_func)}')
    if s.count(old_branch)!=1: raise SystemExit(f'branch guard mismatch: {s.count(old_branch)}')
    s=s.replace(old_func,new_func,1).replace(old_branch,new_branch,1)
    p.write_text(s)
    print('V78-028 Yahoo all-index CASH fallback applied')
